### ISSUE TITLE
[TabLayout] tabBackground with drawable crash in pre-lollipop

### ISSUE THREAD

**Issue by amlwin** [material-components/material-components-android#2502] opened 2021-12-20 06:00 UTC
**Description:**  I implement page dot indicator by using `TabLayout` .It is perfectly work in lollipop. But in pre-lolllipop devices it fail with these logs

```
android.view.InflateException: Binary XML file line #27: Error inflating class com.google.android.material.tabs.TabLayout
at android.view.LayoutInflater.createView(LayoutInflater.java:621)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
```

```
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/indicator_selector.xml from drawable resource ID #0x7f080083
at android.content.res.Resources.loadDrawable(Resources.java:2101)
at android.content.res.Resources.getDrawable(Resources.java:700) 
```
I use `app:tabBackground` to put circle drawable. 
```
<com.google.android.material.tabs.TabLayout
            android:id="@+id/indicatorTabLayout"
            android:layout_width="0dp"
            android:layout_height="16dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:tabBackground="@drawable/indicator_selector"
            app:tabGravity="center"
            app:tabIndicatorHeight="0dp" />
```
in `indicator_selector.xml`
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/indicator_selected" android:state_selected="true" />
    <item android:drawable="@drawable/indicator_normal" />
</selector>
```
I'm did to support backward compatibility for vector drawable in `build.gradle`
```
defaultConfig {
vectorDrawables.useSupportLibrary = true}
```

**Expected behavior:** 
dot indicator with drawable lolipop and beyond is work perfectly fine
![image](https://user-images.githubusercontent.com/9652656/146718843-3d117c11-cf48-4da0-867a-c080926e1783.png)

**Android API version:** 16

**Material Library version:** 1.4.0

**Device:**  Emulator Nexus 5

**Comment by drchen** [comment] 2022-01-04 21:53
Couldn't find the issue from the library end. 

Can you double check if your indicator_selector.xml is put under the right folder?

A small sample app that can reproduce the crash will be helpful.

**Comment by drchen** [comment] 2022-02-04 18:13
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-04 18:13 UTC
Labels: bug, Need more info, Widget: Tab
