### ISSUE TITLE
[Catalog] Context menu doesn't match the theme

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#2682] opened 2022-05-03 17:21 UTC
https://user-images.githubusercontent.com/82187521/166505139-ff76e63e-9032-4d98-b01f-0f3fcde48aad.mp4

**Comment by drchen** [comment] 2023-02-15 16:34
I think this is fixed? I don't see it in the latest Catalog. Let me close this for now. Feel free to reopen it if this is still reproducible.

**Comment by drchen** [comment] 2023-02-15 18:57
Can you provide more details like in which part you think the theme is not applied?

**Comment by pubiqq** [comment] 2023-02-15 19:35
`ListPopupWindow` and context menu have different background colors.

**Closed** 2023-02-23 11:45 UTC
Labels: bug, Issue: Catalog

**Comment by pubiqq** [comment] 2023-02-23 14:47
Unfortunately, even after the fix, the popups still have different colors.

**Comment by drchen** [comment] 2023-02-23 15:58
Can you elaborate?

**Comment by pubiqq** [comment] 2023-02-23 16:12
Well, the fix seems to be correct, but for some reason it doesn't apply to the demo fragment:

<table>
   <tr>
    <th>PopupMenu</th>
    <th>Context menu</th>
   </tr> 
   <tr>
    <td><img src="https://user-images.githubusercontent.com/82187521/220964353-3e41eac1-f1e0-4d55-ae17-96349929c582.png" width="270px"></td>
    <td><img src="https://user-images.githubusercontent.com/82187521/220964399-65596ed8-a946-4a50-abcf-e245eef251e2.png" width="270px"></td>
      </tr>
</table>

**Comment by drchen** [comment] 2023-02-23 16:32
Interesting. I cannot reproduce it on my end. What API level are you using?

**Comment by drchen** [comment] 2023-02-23 16:34
It looks like dynamic color application problem....  which is kind of related but not the same problem.... (and harder to fix because of the intrication of decor view creation order of framework...)

**Comment by pubiqq** [comment] 2023-02-23 20:04
API 33 (see updated description)

I think a video is worth a thousand words:

https://user-images.githubusercontent.com/82187521/221015595-fbc559a6-0099-4abc-8992-2df76e3afdd2.webm

**Comment by drchen** [comment] 2023-02-23 20:12
Yeah I think it's a known problem on API 33 regarding how dynamic colors work. I'll raise this to the team and check if it's even possible for us to fix this.
