### ISSUE TITLE
[MaterialTheme][SplashScreen] IllegalStateException after update from material 1.8.0 to 1.9.0

### ISSUE THREAD

**Issue by Ufkoku** [material-components/material-components-android#3393] opened 2023-05-11 12:44 UTC
Application crashes at splash screen after updating material dependency from `1.8.0` to `1.9.0`. 
Related dependencies:
- Splash screen `androidx.core:core-splashscreen:1.0.1`
-  AppCompat version is `1.6.1` 
- ActivityKtx version is `1.7.1`

I have tried playing around with splash screen, but i have not figured out what changes after switching dependency to 1.9.0

```
FATAL EXCEPTION: main
Process: -, PID: 18630
java.lang.RuntimeException: Unable to start activity ComponentInfo{MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
		at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(SourceFile:926)
		at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(SourceFile:889)
		at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:772)
		at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:197)
		at MainActivity.onCreate(SourceFile:76)
		at android.app.Activity.performCreate(Activity.java:8305)
		at android.app.Activity.performCreate(Activity.java:8284)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
		at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
		at android.os.Handler.dispatchMessage(Handler.java:106) 
		at android.os.Looper.loopOnce(Looper.java:201) 
		at android.os.Looper.loop(Looper.java:288) 
		at android.app.ActivityThread.main(ActivityThread.java:7872) 
		at java.lang.reflect.Method.invoke(Native Method) 
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

```
class MainActivity : AppCompatActivity(R.layout.activity_main) {

override fun onCreate(savedInstanceState: Bundle?) {
        installSplashScreen().setKeepOnScreenCondition { //crash here
            /*Condition on view model state*/
        }

        super.onCreate(savedInstanceState)     
}
```

```
<application       
        android:theme="@style/Theme.App.Dark.Splash">

        <activity
            android:name="MainActivity"
            android:exported="true"
            android:launchMode="singleInstance">
```

```
<style name="Theme.App.Dark.Splash" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/uikit_foundation500</item>
        <item name="windowSplashScreenAnimatedIcon">@drawable/ic_launcher_foreground</item>

        <item name="postSplashScreenTheme">@style/Theme.App.Dark</item>
    </style>

<style name="Theme.App.Dark" parent="Theme.MaterialComponents.NoActionBar">
```

**UPD1.**
Crashes only with isShrinkResources on.

**Comment by Ufkoku** [comment] 2023-05-11 18:45
Hey @imhappi 

>The exception java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity. indicates that you need to use an AppCompat theme with the AppCompat activity; from your themes, it looks like you are using Theme.MaterialComponents.NoActionBar which should be an AppCompat theme.

I know it is strange. But it is how it works. I also cannot spot a dependency at the moment between splash screen and material. 

Project is pretty old and came through multiple dependencies update. AndroidX SplashScreen is integrated for year now since 1.0.0-alpha. And worked fine. 

Today I started updating dependencies one by one. At the moment I have a build which works fine with material 1.8.0, but crashes after switching to 1.9.0. Also it works with 1.9.0 without resource shrinking, but fails when it is on. I tried multiple times with resetting cache and switching this only dependency version forward and back.

I spotted that after calling of `installSplashScreen()` `postSplashScreenTheme` attribute is not resolved, and activity theme is not changed from splash theme to app theme. And as I said before it happens only with resource shrinking on. My project currently uses gradle 8.0, AGP 8.0.0, R8 mode is full on. I'm currently digging into this direction.

**Comment by imhappi** [comment] 2023-05-11 20:27
Ah I guess the exception is caused by the activity theme not being changed to the app theme.

Since it is only happening with resource shrinking, my guess is that `postSplashScreenTheme` isn't resolving maybe because there's a resource attribute that's being cleaned up? But it's not something that can be controlled by the material library; I'm not sure why it's happening only in 1.9 and not 1.8 though of the material library.

The Gradle plugin team may be able to better help debug any issues with resource shrinking; I would advise filing this bug at 
https://issuetracker.google.com/issues?q=componentid:192709

Closing this bug now since I don't think there's anything the Material team can do on our side to help with this particular issue, but please free to comment on any findings that we may be able to help with

**Closed by imhappi** 2023-05-11 20:27 UTC
Labels: bug, Need more info
