### ISSUE TITLE
[Catalog][Slider] slider label is not moved with slider

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3664] opened 2023-11-06 10:43 UTC
**Description:** The slider label (app:labelBehavior="visible") is not moved with the slider (#2869).
![Screenshot_20231106_175528](https://github.com/material-components/material-components-android/assets/71050561/4f7eb124-cb79-41cb-9687-7b154fb8df63)

**Expected behavior:** The slider label is moved with the slider.
![Screenshot_20231106_175601](https://github.com/material-components/material-components-android/assets/71050561/42bdeb1e-8887-4984-bd5b-f6e7dca04dd1)

**Minimal sample app repro:** Catalog app (SliderLabelBehaviorDemoFragment)

**Android API version:** 34

**Material Library version:** 1.11.0-beta01

**Device:** Emulator 32.1.15 (API 32)

**Comment by imhappi** [comment] 2023-11-06 19:17
Duplicate of https://github.com/material-components/material-components-android/issues/2869

**Closed by imhappi** 2023-11-06 19:17 UTC
Labels: bug

**Comment by manabu-nakamura** [comment] 2023-11-07 05:22
To be precise, this is not a duplicate of #2869. The purpose of this issue is (temporary) improvement to the Catalog app (https://github.com/material-components/material-components-android/pull/3665).
