### ISSUE TITLE
[Slider] Add Support to change the thumb drawable/Image

### ISSUE THREAD

**Issue by Mayank1904** [material-components/material-components-android#1590] opened 2020-08-08 05:04 UTC
AppSeekBar have the ability to change the thumb drawable to make it custom thumb for seekbar 

Would love to see the ability to change the thumb drawable in next release which users make the custom slider 

Also Have the functionality to see sliderInfo permanently while scrolled to a particular location

**Comment by matpag** [comment] 2020-08-08 08:29
This is already tracked https://github.com/material-components/material-components-android/issues/1522

**Comment by gabrielemariotti** [comment] 2020-08-13 07:08
Duplicate of #1522

**Closed** 2020-08-13 15:41 UTC
Labels: feature request

**Comment by kamilj** [comment] 2021-02-23 20:14
> Duplicate of #1522

It's not the same

**Comment by AZKZero** [comment] 2024-04-18 11:38
@gabrielemariotti that feature only handle colors, we need to be able to change the thumb drawable itself
