### ISSUE TITLE
Navigation Drawer Layout Not working with Theme.MaterialComponents.DayNight.NoActionBar

### ISSUE THREAD

**Issue by imandaliya** [material-components/material-components-android#1510] opened 2020-07-24 07:25 UTC
Hello,

While setting dark mode of MaterialComponents there is unexpected bug founds in material design library.
Recently i change `Theme.MaterialComponents.Light.NoActionBar` to `Theme.MaterialComponents.DayNight.NoActionBar`

Suddenly com.google.android.material.navigation.NavigationView not working. 

Please check this is major issue. My many of the app are design with this style and working fine without any issue.

Thanks.

**Comment by dsn5ft** [comment] 2020-07-24 13:07
@androidapkr Please attach a screenshot, as well as a minimal sample app that reproduces the issue.

**Comment by kimcy929** [comment] 2020-07-26 15:23
Maybe, I had the similar bug. When **textColor** was incorrect when I changed from a light theme to the dark theme or from dark to light when using **android:textAppearance in TextView**. I always need to remove the app from the recent task then reopen to see a correctly theme.
Repoduct:

```goovy
'appcompat' : '1.3.0-alpha01',
'activity' : '1.2.0-alpha07',
'fragment' : '1.3.0-alpha07',
'material_design' : '1.3.0-alpha02'
```
```xml

<style name="App.Theme" parent ="Theme.MaterialComponents.DayNight.NoActionBar">
  .....
</style>

<style name="TitleTextStyle">
    ....
    <item name="android:textAppearance">@style/TextAppearance.AppCompat.Button</item>
</style>

<TextView
    .....
   style="@style/TitleTextStyle" 
/>
```

```kotlin
class MyApplication : Application() {
     override fun onCreate() {
        super.onCreate()

        setNightMode()
     }

    fun setNightMode() {
        val nightMode = when (AppSettings.instance.nightMode) {
            0 -> AppCompatDelegate.MODE_NIGHT_NO

            1 -> AppCompatDelegate.MODE_NIGHT_YES

            else -> AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM
        }

        AppCompatDelegate.setDefaultNightMode(nightMode)
    }
}
```

```kotlin
class SettingsActivity : AppCompatActivity() {
    ....
   private fun changeAppTheme() {
     (applicationContext as MyApplication).setNightMode()
     val intent = Intent(applicationContext, MainActivity::class.java)
                     .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
      startActivity(intent)
   }
}
```

**Before**
![image](https://user-images.githubusercontent.com/4311848/88482200-fd939c00-cf89-11ea-9e5d-8a36cbfb87d6.png)

**After**

![image](https://user-images.githubusercontent.com/4311848/88482206-0ab08b00-cf8a-11ea-93ff-14d9248527d4.png)

**Comment by drchen** [comment] 2022-02-18 19:47
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-18 19:47 UTC
Labels: bug
