### ISSUE TITLE
[Search][Catalog] SearchBar overlaps with the status bar when scrolling

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3103] opened 2022-11-23 16:54 UTC
**Screenshot:**

<img src="https://user-images.githubusercontent.com/82187521/203598362-57c8bb9e-3395-4ca8-a6e9-45a03230c2f3.png" width="270px" />

**Material Library version:** 1.8.0-alpha03

**Comment by drchen** [comment] 2022-11-23 18:41
Raaj, can you take a look and confirm if it's only a catalog setup issue so we can move it from P1 to P2?

**Comment by raajkumars** [comment] 2023-05-09 14:25
I could not reproduce this issue using the latest build of Catalog demo.

**Comment by afohrman** [comment] 2023-05-23 19:14
I was able to reproduce this on API level 27. It was not reproducible on 28.

![search_overlap_27](https://github.com/material-components/material-components-android/assets/13263374/9f5a9da2-756e-4018-8fac-3a439b3a6da3)

@raajkumars, could you please look into this bug?

**Comment by pubiqq** [comment] 2023-05-23 20:17
It is worth noting that this issue is API-unspecific, it's reproducible on all devices with a large enough status bar (see [screenshot](https://github.com/material-components/material-components-android/issues/3103#issue-1462094872)).

**Comment by dsn5ft** [comment] 2023-06-01 14:06
Moving to a P1 since I think it's mainly a Catalog / client-side issue - we need to look into setting `app:statusBarForeground` on the AppBarLayout to something like `colorSurface` so that there's some "protection" for the status bar content on scroll, even though we're edge-to-edge. @pubiqq feel free to try that if you're interested.

**Comment by tipa** [comment] 2023-10-11 17:37
The catalog app really needs an example on how to provide a "fixed mode" search bar. I am struggling to get one working...

**Comment by dsn5ft** [comment] 2023-10-11 21:10
Hi @tipa, sorry for the lack of clarity on that. What the doc means is to use `SearchBar` without an `AppBarLayout` or `app:layout_behavior="@string/appbar_scrolling_view_behavior"`.

For example, in this Catalog demo you can just remove the `AppBarLayout` here to see how the `SearchBar` will stay fixed in place when the content is scrolled:

https://github.com/material-components/material-components-android/blob/cbb380df61f8eb66273043b437582c8058df7088/catalog/java/io/material/catalog/search/res/layout/cat_search_fragment.xml#L39

However, to preserve the edge-to-edge paddings it does look better to change that `AppBarLayout` to a `FrameLayout`, which will still result in the `SearchBar` staying fixed in place.

We will consider updating the docs/catalog to be more clear on this.

**Closed** 2023-12-14 18:21 UTC
Labels: bug, Issue: Catalog, Widget: Search
