### ISSUE TITLE
[TabLayout] TabLayout doesnt scroll to selected tab without ViewPager

### ISSUE THREAD

**Issue by spartanmarty** [material-components/material-components-android#2113] opened 2021-03-08 09:19 UTC
When I have TabLayout with tabMode scrollable, then selecting a tab doesnt cause view to scroll to selected tab, like it happens after i manually click on tab. The selected tab indicator moves fine. There is a possible workaround - use it with view pager and selecting item in ViewPager does the job. But if i dont need ViewPager, then I dont like doing workarounds to make it fine.

**Comment by drchen** [comment] 2021-11-02 20:28
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:28 UTC
Labels: bug, Need more info
