### ISSUE TITLE
Slider: value label is overlapping other views in ScrollView when labelBehavior=visible

### ISSUE THREAD

**Issue by abed-roid** [material-components/material-components-android#3055] opened 2022-10-31 22:17 UTC
The value label in the Slider is always visible and overlaps other views when the Slider is in ScrollView and out of view.

![Screenshot_20221101_000332](https://user-images.githubusercontent.com/82813615/199119208-05e87ce0-66bd-4d1c-9476-83fdc6c8c5ae.png)

Sample repository link: https://filetransfer.io/data-package/1OjUdBee#link

**Android API version:** 32

**Material Library version:** 1.8.0-alpha02

**Comment by pekingme** [comment] 2022-10-31 22:23
Have you tried different options of this?
https://github.com/material-components/material-components-android/blob/d0ca6ba28aff6bc7d9ec6eba133a58d543722fa9/lib/java/com/google/android/material/slider/res/values/attrs.xml#L29-L39

**Comment by pekingme** [comment] 2022-10-31 22:24
Could you share your sample as a git repo?

**Comment by abed-roid** [comment] 2022-11-01 17:57
The issue is only when labelBehavior is set to visible.

Sample repository: https://github.com/abed-roid/Slider-Sample

**Comment by pekingme** [comment] 2022-11-01 18:45
Thanks. In your screenshot, the slider's track is actually clipped by the text field. In your repo, I noticed that you put them in a ConstraintLayout with a very large bottom padding. I think that's the cause. Try to reduce the bottom padding or put them in a LinearLayout. Closing this for now. Feel free to reopen, if it doesn't fix.

**Closed by pekingme** 2022-11-01 18:45 UTC
Labels: bug, Widget: Slider

**Comment by abed-roid** [comment] 2022-11-01 18:55
I deliberately extended the bottom padding to replicate the bug and mimic the slider's behavior when it's in a long scrollview and a scroll to the bottom happens, the slider is out of sync with value label as shown below:

![Screenshot_20221101_205105 - Copy](https://user-images.githubusercontent.com/82813615/199314750-f58d89d2-3648-4ccc-9ecd-dbd73a2d4ae2.png)

Also, the value label overlaps other views:
![Screenshot_20221101_205513](https://user-images.githubusercontent.com/82813615/199315275-365a06ee-de37-4411-837e-251011b5e2e7.png)

**Comment by abed-roid** [comment] 2022-11-01 19:16
I can't reopen the issue as I am not a collaborator.
