### ISSUE TITLE
Adding Theme.Material3.DayNight.NoActionBar gives you a throwable in you activity or app

### ISSUE THREAD

**Issue by black141312** [material-components/material-components-android#2495] opened 2021-12-05 08:47 UTC
**Description:**I have added the Theme.Material3.DayNight.NoActionBar theme to our app. A Weird Exception is being thrown detailed below.
This throwable comes at every screen i go to. i have enable dyanamic colors too.

 update {(0,103)(1080x2237) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged} ty=APPLICATION_PANEL fmt=TRANSLUCENT wanim=0x10302f5 surfaceInsets=Rect(0, 0 - 0, 0) (manual)
      fl=NOT_FOCUSABLE SPLIT_TOUCH FLAG_LAYOUT_ATTACHED_IN_DECOR
      pfl=WILL_NOT_REPLACE_ON_RELAUNCH LAYOUT_CHILD_WINDOW_IN_PARENT_FRAME
      bhv=DEFAULT
      fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setView
    java.lang.Throwable
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1060)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:431)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1576)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1423)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1379)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1358)
        at com.mine.widget.tooltip.ToolTipView.show(ToolTipView.java:131)
        at com.mine.widget.tooltip.ToolTipBuilderHelper.showToolTipView(ToolTipBuilderHelper.kt:28)
        at com.mine.api.ToolTipBuilder.showToolTipView(ToolTipBuilder.java:59)
        at com.mine.ui.component.TooltipActivity$onCreate$6.onClick(TooltipActivity.kt:69)
        at android.view.View.performClick(View.java:7458)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7435)
        at android.view.View.access$3700(View.java:838)
        at android.view.View$PerformClick.run(View.java:28766)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:329)
        at android.app.ActivityThread.main(ActivityThread.java:8035)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**Expected behavior:** I have made custom tooltip earlier it was supposed to be hinged to anchorview ,now it just goes to top of screen.

**Source code:** Every App which implements gets this error.

**Android API version:** 12

**Material Library version:**1.6.0-alpha01'

**Device:** Any android S device

**Comment by drchen** [comment] 2021-12-06 21:05
Can't tell what the crash has to do with the Material library from the stack trace.

Can you confirm that if you switch Theme.Material3.DayNight.NoActionBar back to Theme.MaterialComponent.DayNight.NoActionBar, the crash goes away? 

It will be nice if you can provide a minimal reproducible sample app for us to debug. : )

**Comment by drchen** [comment] 2021-12-29 17:39
I'll close the issue for now due to no further info available. Feel free to reopen it with more details. Thank you!

**Closed by drchen** 2021-12-29 17:39 UTC
Labels: bug, Need more info
