### ISSUE TITLE
[Button] How MaterialButton set color gradient?

### ISSUE THREAD

**Issue by magic0908** [material-components/material-components-android#2010] opened 2021-01-27 09:56 UTC
like this
![image](https://user-images.githubusercontent.com/23170601/105973364-9df88380-60c7-11eb-811a-c5a899d95131.png)
MaterialButton set horizontal or vertical direction color gradient?
**I hope use custom attr label** 
`<declare-styleable name="">
<attr name="horizontal_color_start"/>
<attr name="horizontal_color_end"/>
...
</declare-styleable>
`

and then  activity_main.xml

 `<com.google.android.material.button.MaterialButton
        app:horizontal_color_start="@color/colorPrimary"
        app:horizontal_color_end="@color/colorAccent"
        ...
        />
`

**Comment by pekingme** [comment] 2021-01-28 17:21
Duplicate of #1167

**Closed by pekingme** 2021-01-28 17:21 UTC
Labels: feature request
