### ISSUE TITLE
[TextInputLayout] + fitsystemWindows + notch = bug

### ISSUE THREAD

**Issue by andrzejbogacz** [material-components/material-components-android#1500] opened 2020-07-22 06:12 UTC
**Description:** TextInputLayout + windowLayoutInDisplayCutoutMode (drawing on both sides of notch)
results in behaviour below

![fitSystemWindowsTrueFalse](https://user-images.githubusercontent.com/30546097/88140991-accb1e80-cbea-11ea-8955-b85f2c86b63c.png)

First screen is fitSystemWindows set to false
Second screen is fitSystemWindows set to true
Third screen is what it looks as xml Layout which is perfectly what first screen is achieving.

**Source code:** I have created sample project which contains only the code necessary to reproduce the bug:
https://github.com/andrzejbogacz/material_design_bug

**Android API version:** Min api 27

**Material Library version:** any stable + beta + alpha (all)

**Device:** any with notch, tested with both emulators and real device

**Comment by drchen** [comment] 2022-04-15 20:43
I don't feel this is a Material library issue since TextInputLayout actually knows nothing about the phone window settings. If with the same settings, but replacing TextInputLayout with a plain LinearLayout and adding some views programmatically into it, will it work correctly? It looks more like caused by a strange combination of ConstraintLayout settings + Notch + System window settings.

I'll close the issue as infeasible.

**Closed by drchen** 2022-04-15 20:43 UTC
Labels: bug, Widget: TextField
