### ISSUE TITLE
[TextInputLayout.OutlinedBox] boxStrokeColor doesn't work with ColorStateLists for the disabled state

### ISSUE THREAD

**Issue by hiworld75018** [material-components/material-components-android#2115] opened 2021-03-08 13:16 UTC
Hello,

I use an **OutlinedBox** with the following style:

```
<style name="My.TextLayout" parent="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox">
  <item name="boxStrokeColor">@color/my_stroke_color</item>
</style>
```

With `my_stroke_color` defined as a **ColorStateList**:
```
<selector>
  <item android:state_focused="true"  android:color="[color1]"/>
  <item android:state_enabled="false" android:color="[color2]"/>
  <item android:color="[color3]"/>
</selector>
```

**Expected behavior:** Description of expected behavior

material v 1.3.0 does handle the `[focused=true] && [enabled=true]` state (color1) and the `[focused=false] && [enabled=true]` state (color3), but NOT the `[enabled=false]` state (color2). It should be noted that v 1.3.0-rc01 did handle the 3 states.

**Android API version:** Android 11 (2021-03-05)

**Material Library version:** 1.3.0

**Device:** Google Pixel 3XL

**Comment by drchen** [comment] 2021-07-02 15:52
Can you provide some screenshots? A small reproducible example will be even better.

We are also using CSLs in default stroke color and it works fine.

**Comment by drchen** [comment] 2021-10-04 19:48
I'll close the issue due to no further info available. Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2021-10-04 19:48 UTC
Labels: bug, Good First Issue
