### ISSUE TITLE
[MaterialButtonToggleGroup] SelectionRequired attribute doesn't enforce checkedButtonId to be a valid id (returns -1)

### ISSUE THREAD

**Issue by riggaroo** [material-components/material-components-android#956] opened 2020-01-29 08:16 UTC
**Description:** The `MaterialButtonToggleGroup`, `selectionRequired` attribute doesn't reflect the selected button when accessing `toggleGroup.checkedButtonId`.

When the button is pressed for the first time, `checkedButtonId` returns the correct value, when the same button is selected for the second time, `checkedButtonId` returns `-1` instead of the selected button. 

The current workaround that I've implemented based upon this StackOverflow answer (https://stackoverflow.com/questions/56164004/required-single-selection-on-materialbuttontogglegroup):
```
materialButtonToggleGroup.addOnButtonCheckedListener { group, checkedId, isChecked ->
    if (group.checkedButtonId == -1) group.check(checkedId)
}
```
After calling `group.check(checkedId)`, the method `MaterialButtonToggleGroup#checkedButtonId` returns the correct button id.

It is worth noting that the `checkedId` that is returned from the above listener returns the correct value when selecting a button twice, it is only when accessing the state (  `MaterialButtonToggleGroup#checkedButtonId`) that -1 is returned.

I have set the `singleSelection` and `selectionRequired` to be true for this component.

**Expected behavior:** The method `MaterialButtonToggleGroup#checkedButtonId` should return the correctly selected button and not -1.

**Android API version:** 29

**Material Library version:** 1.2.0-alpha04

**Device:** Pixel 3

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ymarian** [comment] 2020-01-30 14:42
A fix for this is coming. 

If you're blocked I think the property checkedButtonIds will have the right thing

**Closed** 2020-01-31 16:11 UTC
Labels: bug

**Comment by raman-nbg** [comment] 2020-05-06 20:53
Is this fix already included in 1.2.0-alpha06? If yes, it seems like that this is not fixed. I am still getting `-1` on first selection.

**Comment by raman-nbg** [comment] 2020-05-10 09:46
@ymarian is this fix already available in `1.2.0-alpha06`?

**Comment by wcshi** [comment] 2020-05-11 21:16
No, it'll be in the next release.

**Comment by wcshi** [comment] 2020-05-11 21:44
@raman-nbg 
e56b141  is part of 1.2.0-alpha05.
As stated in the documentation, #checkedButtonId returns -1 when singleSelection == false, use checkedButtonIds instead.

**Comment by raman-nbg** [comment] 2020-05-12 18:48
@wcshi I have set singleSelection == true and I'm still getting `-1`.

The unit test in https://github.com/material-components/material-components-android/commit/e56b141dd5e63c4dcba2ed7ad06d30d3ee5c59cd only checks if `checkedButtonId` returns the correct ID after double tap, but not after the first tap.

```xml
        <com.google.android.material.button.MaterialButtonToggleGroup
            android:id="@+id/trainingWeightButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="8dp"
            app:singleSelection="true"
            app:selectionRequired="true"
            app:layout_constraintBottom_toTopOf="@id/trainingFormLabel"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent">

            <Button
                android:id="@+id/trainingWeightButtonYes"
                style="?attr/materialButtonOutlinedStyle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/yes" />

            <Button
                android:id="@+id/trainingWeightButtonNo"
                style="?attr/materialButtonOutlinedStyle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/no" />
        </com.google.android.material.button.MaterialButtonToggleGroup>
```
```kotlin
        val trainingWeightButtonYesId: Int = R.id.trainingWeightButtonYes
        val trainingWeightButtonNoId: Int = R.id.trainingWeightButtonNo
        val trainingWeightButtonGroup =
            view.findViewById<MaterialButtonToggleGroup>(R.id.trainingWeightButton)
        trainingWeightButtonGroup
            .buttonCheckedChanges()
            .onEach {
                // Workaround: On first click on button, the checkedButtonId is -1
                // https://github.com/material-components/material-components-android/issues/956
                when (trainingWeightButtonGroup.checkedButtonId) {
                    -1 -> trainingWeightButtonGroup.check(it.checkedId)
                    trainingWeightButtonYesId -> viewModel?.isTrainingWeightValid = true
                    trainingWeightButtonNoId -> viewModel?.isTrainingWeightValid = false
                }
            }
            .onEach { refreshFinishValidationButtonState() }
            .launchIn(lifecycleScope)
```

```groovy
implementation "com.google.android.material:material:1.2.0-alpha06"
```

**Comment by wcshi** [comment] 2020-05-12 23:51
@raman-nbg 
I added an OnButtonCheckedListener in the MaterialButtonToggleGroupDemofragment, manually tested it and cannot reproduce your bug. Please provide a small sample app that reproduces the bug you are reporting
