### ISSUE TITLE
Bug BottomAppBar

### ISSUE THREAD

**Issue by Arashvscode** [material-components/material-components-android#2758] opened 2022-06-14 16:38 UTC
![Screenshot_20220614-210526_PT](https://user-images.githubusercontent.com/101287880/173630329-006d0364-4980-43ca-9747-fdedfbad80fa.jpg)

Not work

**Comment by drchen** [comment] 2022-06-14 16:47
Can you provide more details? Like what is not working? How do you set up the bottom app bar?

**Comment by Arashvscode** [comment] 2022-06-14 17:04
> 

Yes, I follow the instructions, but the same bug is still displayed. Do you want me to send the code?

**Comment by drchen** [comment] 2022-06-14 17:28
Can you explain what's the bug you are mentioning? Like what's the expected behavior and what's the actual behavior?

**Comment by Arashvscode** [comment] 2022-06-14 17:30
> 

fab does not come in the middle and the color does not turn completely black, as you can see in the photo, some places are white

**Comment by drchen** [comment] 2022-06-14 17:38
Thanks for the info. I'll check if someone can help take a look. : )

**Comment by afohrman** [comment] 2022-06-14 17:45
Could you please provide the `"AppThemeMaterial"` theme overlay source code?

**Comment by afohrman** [comment] 2022-06-14 17:53
What does the style resource at `android:theme="@style/AppThemeMaterial"` point to? It should be something like `<style name="AppThemeMaterial" parent="?">` with a bunch of XML tags in it.

**Comment by Arashvscode** [comment] 2022-06-14 17:58
/storage/emulated/0/.sketchware/mysc/975/app/src/main/res/layout/files.xml:59: error: attribute fabAttached (aka org.ppsspp.ppsspp:fabAttached) not found.
/storage/emulated/0/.sketchware/mysc/975/app/src/main/res/layout/files.xml:59: error: resource style/AppThemeMaterial (aka org.ppsspp.ppsspp:style/AppThemeMaterial) not found.
error: failed linking file resources.

**Comment by Arashvscode** [comment] 2022-06-14 18:40
> 



> Seems like there's a resource issue on your end, I can help you debug if you provide more info.
> 
> As for the original issue, can you see what happens if you remove the theme overlay entirely? Just remove the line with `"android:theme="@style/AppThemeMaterial"` in the BottomAppBar XML definition.

I deleted it and my program ran well and as you can see in the picture, the fab does not come in the middle and the background does not turn completely black.

**Comment by drchen** [comment] 2022-06-14 20:12
How do you set your app/activity theme?

**Comment by afohrman** [comment] 2022-06-14 22:35
When you delete the theme overlay, do you see any difference in the BottomAppBar, or is it the same as in the original screenshot?

One other thing I noticed is that `android:layout_gravity="bottom"` should be set instead of `android:gravity="bottom"`. `Android:gravity` is responsible for setting the positioning of its children, while `android:layout_gravity` changes the position of the view, itself.

**Comment by Arashvscode** [comment] 2022-06-15 06:14
> When you delete the theme overlay, do you see any difference in the BottomAppBar, or is it the same as in the original screenshot?
> 
> One other thing I noticed is that `android:layout_gravity="bottom"` should be set instead of `android:gravity="bottom"`. `Android:gravity` is responsible for setting the positioning of a View's children, while `android:layout_gravity` changes the position of the View, itself.

![Screenshot_20220615-104148_test](https://user-images.githubusercontent.com/101287880/173755209-710ebb1f-8f9b-4f9c-9026-109bfc82f816.jpg)

Ok, I did what you said, but you still don't get the fab in the middle. Can you send me a code so I can connect the fab to the middle?

I suggest you create a group in Telegram to solve problems like this, maybe it can be solved in the same group

**Comment by afohrman** [comment] 2022-06-15 20:07
Can you send an update of what your code looks like now? Are you still using a theme overlay? I also noticed that you're using an app:menu attribute on your BottomAppBar, and that isn't a supported attribute for that component. If you'd like, the BottomNavigationView component is a bottom based component that does support the menu attribute.

You can reference the [catalog demo](https://github.com/material-components/material-components-android/blob/3fdfb6e230767138849edf858c13da1bf1d3f90b/catalog/java/io/material/catalog/bottomappbar/res/layout/cat_bottomappbar_fragment.xml#L28) for an example of a working BottomAppBar.

**Comment by drchen** [comment] 2022-07-25 20:02
I'll close this issue for now due to no further info available. Please feel free to reopen it if you still need help.

**Closed by drchen** 2022-07-25 20:02 UTC
Labels: bug, Help wanted, Need more info, Widget: BottomAppBar
