### ISSUE TITLE
[TextInputLayout] How to change the  background color of the ExposedDropdownMenu.

### ISSUE THREAD

**Issue by snpmyn** [material-components/material-components-android#1963] opened 2021-01-05 04:42 UTC
**Is your feature request related to a problem? Please describe.**
How to change the  background color of the ExposedDropdownMenu.

**Describe the solution you'd like**
How to change the  background color of the ExposedDropdownMenu.

**Describe alternatives you've considered**
How to change the  background color of the ExposedDropdownMenu.

**Additional context**
How to change the  background color of the ExposedDropdownMenu.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment] 2022-02-18 22:11
Close this as a duplicate of #1477

**Closed by drchen** 2022-02-18 22:11 UTC
Labels: feature request
