### ISSUE TITLE
[Snackbar] Fade animation is flickering

### ISSUE THREAD

**Issue by vkislicins** [material-components/material-components-android#648] opened 2019-10-03 00:18 UTC
**Description:** When using Snackbar with the default ANIMATION_MODE_FADE, it looks like it's flickering when animating.  
![snackbar](https://user-images.githubusercontent.com/6248215/66090475-64961f00-e538-11e9-8194-1657b1722d9a.gif)

**Expected behavior:** Animation should be smooth

**Source code:** 
`Snackbar.make(view, message, Snackbar.LENGTH_SHORT).show()`

**Android API version:** API level 26

**Material Library version:** 1.1.0-alpha10

**Device:** HTC U11 life

**Comment by KunaalKumar** [comment] 2020-02-02 06:51
I had a similar bug and fixed it by removing the following from the parent layout
`android:animateLayoutChanges="true"`

**Comment by drchen** [comment] 2022-04-15 14:15
Hi it looks like this is caused by the framework's behavior and not something we can control or fix. I'm going to close this issue as infeasible. : )

**Closed by drchen** 2022-04-15 14:15 UTC
Labels: bug, Widget: Snackbar

**Comment by Slion** [comment] 2023-03-11 10:39
> Hi it looks like this is caused by the framework's behavior and not something we can control or fix. I'm going to close this issue as infeasible. : )

Could we get actual facts and proper technical analysis of what is causing this and what was tried to actually fix it. The auto transition framework seems to work just fine in most cases. If it is really an issue with the framework itself then surely to proper thing to do is to report it and have it fixed.

**Comment by Slion** [comment] 2023-03-11 21:09
Seems to me that it could be fixed by having an option to disable snackbar built-in animations.
