### ISSUE TITLE
[Checkbox] Error on checked display in specific condition

### ISSUE THREAD

**Issue by mateuyabar** [material-components/material-components-android#1783] opened 2020-10-07 12:09 UTC
**Description:** When a checkbox is checked inside a ViewPager2 in some specific circumstances, the checkbos is not displayed checked

**Screenshot of error:** 
![device-2020-10-07-135609](https://user-images.githubusercontent.com/1798264/95327927-17fcc680-08a5-11eb-976f-7d65a29f69de.png)

**Expected behavior:** 
The first two checkbox should be displayed checked

**Source code:** 
https://github.com/mateuyabar/bug-on-mateirla-checkbox-sample

**Material Library version:**
- Version 1.2.1 and 1.3.0.alpha3 fails

**Comment by hunterstich** [comment] 2020-10-13 14:23
Hey @mateuyabar,

Thanks for including a sample project! 

Can you describe some of the scenarios in which the checkboxes aren't being checked properly? I downloaded your repo and can't seem to reproduce the issue

**Comment by drchen** [comment] 2022-02-18 21:28
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-18 21:28 UTC
Labels: bug
