### ISSUE TITLE
[FloatingActionButton] Behavior change in 1.2.0 - different behavior and strange animation when toggling isEnabled attribute

### ISSUE THREAD

**Issue by mateuszkwiecinski** [material-components/material-components-android#1618] opened 2020-08-15 12:28 UTC
**Description:** 
After bumping library version the `FloatingActionButton` changes behavior when setting `isEnabled=false`. In 1.2.0 it:
a) loses background color
b) shows strange octogonal shape
![image](https://user-images.githubusercontent.com/36954793/90312266-4abcbb00-df03-11ea-8e56-7e770bd2ab1b.png)

**Expected behavior:** 
Behavior doesn't change after library update (or at least it is clearly metioned in the release notes)
|1.1.0|1.2.0|
|-|-|
|![1_1_0](https://user-images.githubusercontent.com/36954793/90312211-c9fdbf00-df02-11ea-9d86-532f972b0fc4.gif)|![1_2_0](https://user-images.githubusercontent.com/36954793/90312214-cb2eec00-df02-11ea-8f5b-3a9c68557a43.gif)|

**Source code:** https://github.com/mateuszkwiecinski/fab_animation_issue 
just downgrade the library version to 1.1.0

**Android API version:** 29

**Material Library version:** 1.2.0

**Device:** Multiple

**Comment by gabrielemariotti** [comment] 2020-08-15 17:40
About the background color it is not a bug.
The version `1.2.0` [changed](https://github.com/material-components/material-components-android/commit/94cd734a5100b4a693d3bf88a6019f4d810089d2#diff-2b09bd518e204efd7f5f214c3981c2fe) the background color and icon tint to support for enabled/disabled state in the `FloatingActionButton`.

From:
```
    <item name="backgroundTint">?attr/colorSecondary</item>
    <item name="tint">?attr/colorOnSecondary</item>
```
To:
```
    <item name="backgroundTint">@color/mtrl_fab_bg_color_selector</item>
    <item name="tint">@color/mtrl_fab_icon_text_color_selector</item>
```

You can check the [selector](https://github.com/material-components/material-components-android/blob/1.2.0/lib/java/com/google/android/material/floatingactionbutton/res/color/mtrl_fab_bg_color_selector.xml):
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:color="?attr/colorSecondary" android:state_enabled="true"/>
  <item android:alpha="0.12" android:color="?attr/colorOnSurface"/>
</selector>
```
The disabled state is based on `colorOnSurface`.
In your case you are using the default value (`#000000` with alpha=`0.12`)

I've submitted a PR to add the info about the states in the doc (#1619).

**Comment by mateuszkwiecinski** [comment] 2020-08-17 17:49
Thanks for explanation. Is there any place where I can go through all behavior changes? 

I looked at [release notes](https://github.com/material-components/material-components-android/releases/tag/1.2.0) but they just say _"Improvements  to the following components"_ and there is an unclickable `more` at the end. 
I also went through [the diff](https://github.com/material-components/material-components-android/compare/1.1.0...1.2.0), but it shows almost 700 commits and even github has issues displaying it. 

Initially I assumed the library follows semantic versioning so I was surprised that minor version bump caused a behavior change. It would be great to have full changelog to test related parts of an app

**Comment by leticiarossi** [comment] 2020-08-18 15:35
Hi @mateuszkwiecinski

**Comment by leticiarossi** [comment] 2020-08-18 15:45
Hi @mateuszkwiecinski I found this diff mentioned in the [1.2.0-alpha04 release notes](https://github.com/material-components/material-components-android/releases/tag/1.2.0-alpha04). The stable release notes is more general since each alpha/beta/etc notes are more detailed with what changed from each version (not sure why GitHub doesn't show all the commits :/). The "more..." is not supposed to be a link, apologies for the confusion, I deleted it! 

Will close this issue and merge in the PR with the doc update

**Closed by leticiarossi** 2020-08-18 15:45 UTC
Labels: bug

**Comment by mateuszkwiecinski** [comment] 2020-08-18 19:27
@leticiarossi thanks for the reply! The release notes are much clearer now 👍 

How about the octagonal shape I reported here too? Is that also an intended change?
i couldn't find any attribute responsible for the shape here.

![image](https://user-images.githubusercontent.com/36954793/90556206-cc794680-e198-11ea-8841-010f2b3e0f61.png)

**Comment by leticiarossi** [comment] 2020-08-19 15:51
This happens due to a framework behavior when a view with a shadow has a translucent background (like the fab).
I guess you're seeing that because you're setting the fab to be disabled when it's clicked?

**Comment by mateuszkwiecinski** [comment] 2020-08-20 11:16
>I guess you're seeing that because you're setting the fab to be disabled when it's clicked?

That is correct: [sample code](https://github.com/mateuszkwiecinski/fab_animation_issue/blob/master/app/src/main/java/com/example/myapplication/MainActivity.kt#L22). I don't think that's an uncommon scenario though 🤔  

>view with a shadow has a translucent background

So the workaround would be to set solid color, withouth alpha parameter as a background color for disabled state 👍 
Shouldn't that be a default setting? I mean seeing the octagonal shape by default seems to be really unexpected - is that intended design?

**Comment by dawidmosk** [comment] 2022-09-24 00:12
But what to do with transparent button? It's occur.
