### ISSUE TITLE
Material 1.6.1 endIconTint ignored

### ISSUE THREAD

**Issue by rmirabelle** [material-components/material-components-android#2753] opened 2022-06-12 06:26 UTC
After updating `com.google.android.material:material:1.5.0` to `com.google.android.material:material:1.6.1`,

usages of `endIconTint` (specifically, in a style, applied to a `TextInput`, but likely for other inputs as well) are now summarily ignored.

Setting `endIconTint` to any color no longer has any effect. Instead, the end icon appears to automatically tint itself to match the color of the text and to completely disregard `endIconTint`.

Anyone else experiencing? Any known workaround?

**Comment by drchen** [comment] 2022-06-13 15:35
Are you setting it in XML or via the setter programmatically?

**Comment by rmirabelle** [comment] 2022-06-13 16:43
Set in XAML - tried both via style and directly on input. Here's the expected output (accurately shown in Android Studio):

![expected](https://user-images.githubusercontent.com/87966/173400061-ff6f7a29-031b-4382-aa19-f366688f3943.png)

Here's the actual output (with incorrect output shown in the emulator):

![actual](https://user-images.githubusercontent.com/87966/173400118-5067fadf-9222-40e8-a20a-039a0ad94714.png)

Notice the end icon is red, summarily ignoring both the style and the `endIconTint` attributes

Interestingly, the correct behavior is restored if I set a different style instead:

`<item name="errorIconTint">@color/frame</item>`

This seems to imply that Material now differentiates between `endIcon` and `errorIcon`. It did not previously do this in 1.5. Setting `endIconTint` worked for both end icon and error icon.

I'm unable to find any documentation that describes the difference between `endIcon` and `errorIcon`, but apparently, this difference is now significant.

There may be some additional confusion caused by the fact that I'm forced to set `endIconMode="custom"` or attempting to store a reference to the drawable with `val origEndIcon = endIconDrawable!!` fails with a null pointer exception. I need to store a reference to the end icon so I can programmatically show and hide it as needed.

**Comment by drchen** [comment] 2022-06-13 17:23
Hi I think `endIconTint` and `errorIconTint` are always working independently. I'm not sure why it "worked" in your case in 1.5.0, and I'm wondering if it could be caused by a bug we fixed in 1.6. 

No matter what, as I said, `endIconTint` and `errorIconTint` are supposed to work independently. So if you want to override the tint in the error state, please override `errorIconTint` instead.

**Closed by drchen** 2022-06-13 17:23 UTC
Labels: bug, Need more info

**Comment by drchen** [comment] 2022-06-13 18:42
Re: Does the end icon magically transform itself into an error icon (a different object) when the input has an error? - yes it's how it works.

I agree it's not being stated very clearly in our dev doc. The best reference we have is probably the javadoc of the `TextInputLayout` class: https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/TextInputLayout.java#L111

**Comment by rmirabelle** [comment] 2022-06-13 20:49
Thanks again. I think it would be useful for the Android docs (not javadoc) to reflect the difference between `endIcon` and `errorIcon`. I find it a bit bewildering that setting `endIconTint` fails if the field is in error.  Even in an error state, the `endIcon` is still an `endIcon`, isn't it?  Feels like the attribute should have been called `endIconValidTint` to clue the user in that setting the tint this way only works in the absence of an error.  Similarly, it seems `errorIconTint` should have been called something like `endIconErrorTint`, so that it doesn't seem like you're dealing with a whole different object other than `endIcon` when there's an error.

**Comment by drchen** [comment] 2022-06-13 21:28
yeah I totally agree we can probably have better API naming here.

I'll raise this to our team for our future reference. Thanks for providing these valuable thoughts!!
