### ISSUE TITLE
java.lang.VerifyError after upgrading from 1.1.0-alpha06 to 1.1.0-alpha07

### ISSUE THREAD

**Issue by yccheok** [material-components/material-components-android#397] opened 2019-06-14 17:36 UTC
After upgrading from `com.google.android.material:material:1.1.0-alpha06` to `com.google.android.material:material:1.1.0-alpha07`, we are getting the following error. It happens in Android 4.3 and Android 4.4 so far.

```
java.lang.VerifyError: 
  at com.google.android.material.tabs.TabLayout.createTabFromPool (TabLayout.java:862)
  at com.google.android.material.tabs.TabLayout.newTab (TabLayout.java:852)
  at com.google.android.material.tabs.TabLayout.populateFromPagerAdapter (TabLayout.java:1474)
  at com.google.android.material.tabs.TabLayout.setPagerAdapter (TabLayout.java:1465)
  at com.google.android.material.tabs.TabLayout.setupWithViewPager (TabLayout.java:1378)
  at com.google.android.material.tabs.TabLayout.setupWithViewPager (TabLayout.java:1339)
  at com.google.android.material.tabs.TabLayout.setupWithViewPager (TabLayout.java:1319)
  at com.yocto.wenote.note.NoteFragment.initTabs (NoteFragment.java:343)
  at com.yocto.wenote.note.NoteFragment.lambda$onCreateView$1 (NoteFragment.java:199)
```

This is the code being called just before entering `com.google.android.material.tabs.TabLayout`

`tabLayout.setupWithViewPager(viewPager);`

It happens in line 862. (Left side is alpha07, right side is alpha06)

<img width="960" alt="2019-06-15 01_31_14- app_build gradle  - File Compare" src="https://user-images.githubusercontent.com/308276/59527355-f4727780-8f0d-11e9-8e72-e220646a2276.png">

Any idea why such incident happens?

**Comment by yccheok** [comment] 2019-06-14 20:28
We somehow workaround this problem by adding the following for R8

```
# VerifyError in Android 4
# https://github.com/material-components/material-components-android/issues/397
-keep class com.google.android.material.tabs.TabLayout$Tab {
*;
}
```

No crash so far. But, why this is required?

**Comment by cristh18** [comment] 2019-06-30 17:03
> We somehow workaround this problem by adding the following for R8

Hi @yccheok how are you? I have this issue on my app but I have not could reproduce it.

<img width="1363" alt="Screen Shot 2019-06-30 at 12 58 42 PM" src="https://user-images.githubusercontent.com/1972427/60399712-ebe98600-9b36-11e9-8628-cf65f4266d54.png">

I think that is the same issue that you had. Would you think that your solution work for me?

**Comment by yccheok** [comment] 2019-06-30 17:32
Yes. I can easily reproduce the problem using Android 4. I believe you can "workaround" the problem, with the method I mentioned above.

**Comment by cristh18** [comment] 2019-06-30 17:41
@yccheok Thank you so much... I'll do tests with your solution. I'll hope that works.

**Comment by yccheok** [comment] 2019-06-30 17:48
Your crash analysis looks interesting. May I know is that a paid service?

**Comment by cristh18** [comment] 2019-06-30 18:01
@yccheok I use https://fabric.io/home and is free

**Comment by ItzNotABug** [comment] 2019-07-08 09:03
facing the same issue..
I also tried @yccheok's solution, still getting crashes on 4.x devices

**Comment by HaydenCampbell** [comment] 2019-07-11 08:48
Also receiving this error on Android 4.4, 4.1, 4.2, 4.3 and 5.01. Will try the workaround.

**Comment by xDragonZ** [comment] 2019-08-06 09:12
this error occur on API 18 and 19 with alpha07, alpha08 and alpha09

fixed by adding, `TabLayout$Tab` to proguard

**Comment by drchen** [comment] 2021-07-15 20:42
I'm going to close this issue since it seems something beyond our control and we have a known workaround.

**Closed by drchen** 2021-07-15 20:42 UTC
