### ISSUE TITLE
[MaterialAlertDialogBuilder] MaterialAlertDialogBuilder crashes because of Theme

### ISSUE THREAD

**Issue by shaikfaizal** [material-components/material-components-android#1229] opened 2020-04-21 07:34 UTC
**Description:**     java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).

**Expected behavior:** shouldn't crash

**Source code:** MaterialAlertDialogBuilder(activity)
                            .setTitle(R.string.logout_title)
                            .setMessage(R.string.logout_message)
                            .setPositiveButton(R.string.logout_positive_btn_label, null)
                            .setNegativeButton(R.string.logout_negative_btn_label, null)
                            .create()

**Theme:**<style name="Theme.MyApp" parent="Base.Theme.MyApp" />
 <item name="materialAlertDialogTheme">@style/ThemeOverlay.App.MaterialAlertDialog</item>

**Android API version:** 29

**Material Library version:** com.google.android.material:material:1.2.0-alpha06

**Device:** Nokia 6.1 plus

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by dsn5ft** [comment] 2020-04-21 19:13
Hi @shaikfaizal, can you make sure your base app theme inherits from a Theme.MaterialComponents theme?

**Comment by masqueNada** [comment] 2020-04-22 17:43
@dsn5ft I'm having the same issue and my app theme inherits from Theme.MaterialComponents

**Comment by shaikfaizal** [comment] 2020-04-23 09:08
@dsn5ft  yah, which is inherited from the base app theme, but one thing, I can use an alert builder without any issues.

**Comment by dsn5ft** [comment] 2020-04-23 17:58
Can you attach a minimal sample app that reproduces the issue?

**Comment by shaikfaizal** [comment] 2020-04-30 05:49
**Top level theme**   <style name="Theme.MyApp" parent="Base.Theme.MyApp" />
**Manifest** <application
        android:name=".BaseApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:supportsRtl="true"
        android:theme="@style/Theme.MyApp"
        android:usesCleartextTraffic="true">

**HomeActivity** <activity
            android:name=".HomeActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.MyApp.FullScreen.Launcher">

**Dialog theme**
    <style name="ThemeOverlay.App.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="colorPrimary">?attr/colorPrimary</item>
        <item name="colorSecondary">?attr/colorSecondary</item>
        <item name="colorSurface">?attr/colorSurface</item>
        <item name="colorOnSurface">?attr/colorOnSurface</item>
        <item name="alertDialogStyle">@style/MaterialAlertDialog.App</item>
        <item name="materialAlertDialogTitleTextStyle">@style/MaterialAlertDialog.App.Title.Text
        </item>
        <item name="buttonBarPositiveButtonStyle">@style/Widget.App.ButtonBase</item>
        <item name="buttonBarNeutralButtonStyle">@style/Widget.App.ButtonBase</item>
    </style>

**Theme added on base theme**
<item name="materialAlertDialogTheme">@style/ThemeOverlay.App.MaterialAlertDialog</item>

**Comment by shaikfaizal** [comment] 2020-05-10 10:35
@dsn5ft any update on this?

**Comment by dsn5ft** [comment] 2020-05-11 16:19
Hi @shaikfaizal, thanks for providing the code snippets. However, it would be best if you could create a GitHub repo with a minimal app that reproduces the issue. In order for us to help it's important for us to see how everything is hooked up.

**Comment by kavinraju** [comment] 2020-07-09 18:45
Is there any update on this issue? I got the following error when I tried the Theme from the official documentation.

> android.view.InflateException: Binary XML file line #25 in package.name:layout/mtrl_alert_dialog: Binary XML file line #36: You must supply a layout_width attribute.
    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #36: You must supply a layout_width attribute.

**Comment by belewis05** [comment] 2020-08-08 03:47
@shaikfaizal `<item name="colorPrimary">?attr/colorPrimary</item>` is a circular reference. Set it to a an actual color or color reference

**Comment by gabrielemariotti** [comment] 2020-08-13 07:04
> `<style name="Theme.MyApp" parent="Base.Theme.MyApp" />`

@shaikfaizal Can you post your full theme? What is `Base.Theme.MyApp` ?

**Comment by nimaiwalsh** [comment] 2021-03-25 06:49
Still having this issue with 1.3.0

```
    <style name="ThemeOverlay.Skedulo.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="colorPrimary">?attr/colorSurface</item>
        <item name="colorSecondary">?attr/colorSurface</item>
        <item name="colorSurface">?attr/colorSurface</item>
        <item name="colorOnSurface">?attr/colorOnSurface</item>
        <item name="alertDialogStyle">@style/MaterialAlertDialog.Skedulo</item>
        <item name="materialAlertDialogTitleTextStyle">@style/MaterialAlertDialog.Skedulo.Title.Text</item>
        <item name="buttonBarPositiveButtonStyle">@style/Widget.Skedulo.MaterialAlertDialogButton</item>
        <item name="buttonBarNeutralButtonStyle">@style/Widget.Skedulo.MaterialAlertDialogButton</item>
    </style>

    <style name="MaterialAlertDialog.Skedulo" parent="MaterialAlertDialog.MaterialComponents">
        <item name="colorPrimary">?attr/colorPrimary</item>
    </style>

    <style name="MaterialAlertDialog.Skedulo.Title.Text" parent="MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textColor">?attr/colorOnBackground</item>
    </style>

    <style name="Widget.Skedulo.MaterialAlertDialogButton" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="materialThemeOverlay">@style/ThemeOverlay.Skedulo.MaterialAlertDialogButton.Button</item>
    </style>

    <style name="ThemeOverlay.Skedulo.MaterialAlertDialogButton.Button" parent="">
        <item name="colorPrimary">?attr/colorPrimary</item>
    </style>
```

Base theme.

```
<resources xmlns:tools="http://schemas.android.com/tools">
    <!--Top level DayNight theme to be used in AndroidManifest.xml-->
    <style name="Theme.App" parent="Base.Theme.Skedulo" />

    <style name="Theme.App.Boot" parent="Base.Theme.MaterialThemeBuilder">
        <item name="colorPrimary">@color/blue_800</item>
        <item name="colorPrimaryVariant">@color/blue_400</item>
        <item name="colorSecondary">@color/blue_800</item>
        <item name="colorSecondaryVariant">@color/blue_400</item>
        <item name="colorAccent">@color/blue_900</item>
        <item name="colorSurface">@color/white</item>
        <item name="android:statusBarColor" tools:ignore="NewApi">?attr/colorSurface</item>
        <item name="android:windowLightStatusBar" tools:ignore="NewApi">true</item>
        <item name="android:windowBackground">@drawable/boot_background</item>
        <item name="android:windowAnimationStyle">@style/BootAnimation</item>
    </style>

    <!--Base custom theme which will be shared between both light and dark theme variants-->
    <style name="Base.Theme.App" parent="Base.Theme.MaterialThemeBuilder">
        <!--Material color attributes (light theme) -->
        <!--colorPrimary colors map to components and elements, such as app bars and buttons. -->
        <!--colorSecondary colors are most often used as accents on components, such as FABs and -->
        <!--selection controls.-->
        <item name="colorPrimary">@color/blue_800</item>
        <item name="colorPrimaryDark">@color/blue_900</item>
        <item name="colorPrimaryVariant">@color/blue_400</item>
        <item name="colorSecondary">@color/blue_800</item>
        <item name="colorSecondaryVariant">@color/blue_400</item>
        <item name="android:windowBackground">@color/BG1</item>
        <!--colorBackground appears behind scrollable content and is used for the default window-->
        <!--background. colorSurface is mapped to the surface of components such as cards, sheets-->
        <!--and menus. colorError is used to indicate an error state for components such as-->
        <!--text fields.-->
        <item name="android:colorBackground">@color/BG1</item>
        <item name="colorSurface">@color/white</item>
        <item name="colorError">@color/red_800</item>
        <!--"On" colors define how text, icons and strokes are colored in relation to the surface-->
        <!--on which they appear.-->
        <item name="colorOnPrimary">@color/white</item>
        <item name="colorOnSecondary">@color/black_900</item>
        <item name="colorOnBackground">@color/navy_900</item>
        <item name="colorOnSurface">@color/navy_600</item>
        <item name="colorOnError">@color/white</item>
        <!-- custom surface and background color -->
        <item name="colorSurfaceHighlight">@color/BG2</item>
        <item name="colorOnSurfaceDisabled">@color/navy_300</item>
        <item name="colorOnSurfaceAlt">@color/navy_500</item>
        <item name="colorSurface2">@color/navy_75</item>
        <item name="colorSurface3">@color/navy_300</item>
        <item name="colorOnSurface3">@color/white</item>
        <!-- Custom colors used outside of specific material components -->
        <!-- Lines including border lines -->
        <item name="colorLines">@color/navy_75</item>
        <item name="colorBorderColor">@color/navy_300</item>
        <item name="colorButtonStroke">@color/navy_300</item>
        <item name="colorApproval">@color/green_800</item>
        <item name="colorApprovalLight">@color/green_200</item>
        <!-- Component colors -->
        <item name="colorBackgroundAgendaCard">@color/navy_10</item>
        <item name="colorButtonPrimary">@color/blue_800</item>
        <item name="colorButtonPrimaryDisabled">@color/blue_200</item>
        <item name="colorButtonPrimaryPressed">@color/blue_900</item>
        <item name="colorButtonSecondary">@color/navy_50</item>
        <item name="colorButtonSecondaryText">@color/navy_900</item>
        <item name="colorButtonSecondaryDisabled">@color/navy_50</item>
        <item name="colorButtonSecondaryDisabledText">@color/navy_500</item>
        <item name="colorButtonSecondaryPressed">@color/navy_100</item>
        <item name="colorButtonAccept">@color/green_800</item>
        <item name="colorButtonAcceptDisabled">@color/green_400</item>
        <item name="colorButtonAcceptPressed">@color/green_900</item>
        <item name="colorLightToolbarTitle">@color/navy_800</item>
        <item name="colorLightToolbarMenuText">@color/blue_800</item>
        <!-- Status pill colors -->
        <item name="colorPending">@color/JSPE_pending</item>
        <item name="colorReady">@color/JRE_ready</item>
        <item name="colorTravelling">@color/JTR_travelling</item>
        <item name="colorCheckedIn">@color/JCI_checked_in</item>
        <item name="colorInProgress">@color/JIP_in_progress</item>
        <item name="colorComplete">@color/JCO_complete</item>
        <item name="colorCancelled">@color/JCA_cancelled</item>
        <item name="colorPendingForeground">@color/navy_600</item>
        <item name="colorReadyForeground">@color/white</item>
        <item name="colorTravellingForeground">@color/white</item>
        <item name="colorCheckedInForeground">@color/white</item>
        <item name="colorInProgressForeground">@color/white</item>
        <item name="colorCompleteForeground">@color/white</item>
        <item name="colorCancelledForeground">@color/white</item>
        <item name="colorUserOnline">@color/green_800</item>
        <item name="colorUserOffline">@color/navy_300</item>

        <item name="colorAlert">@color/red_800</item>
        <item name="colorAlertLight">@color/red_50</item>
        <item name="colorAlertLightest">@color/red_30</item>
        <item name="colorUrgent">@color/orange_800</item>
        <item name="colorUrgentLight">@color/orange_400</item>
        <item name="colorUrgentLightest">@color/orange_200</item>
        <item name="colorCritical">@color/red_800</item>
        <item name="colorCriticalLight">@color/red_200</item>
        <!-- Skedulo custom type attributes -->
        <item name="textAppearanceDisplayBold">@style/TextAppearance.Skedulo.Display.Bold</item>
        <item name="textAppearanceHeadingBold">@style/TextAppearance.Skedulo.Heading.Bold</item>
        <item name="textAppearanceBodyBold">@style/TextAppearance.Skedulo.Body.Bold</item>
        <item name="textAppearanceBodyMedium">@style/TextAppearance.Skedulo.Body.Medium</item>
        <item name="textAppearanceBodyRegular">@style/TextAppearance.Skedulo.Body.Regular</item>
        <item name="textAppearanceSubheadMedium">@style/TextAppearance.Skedulo.Subhead.Medium</item>
        <item name="textAppearanceSubheadRegular">@style/TextAppearance.Skedulo.Subhead.Regular</item>
        <item name="textAppearanceCaptionMedium">@style/TextAppearance.Skedulo.Caption.Medium</item>
        <item name="textAppearanceCaptionRegular">@style/TextAppearance.Skedulo.Caption.Regular</item>
        <!-- Material shape attributes -->
        <item name="shapeAppearanceSmallComponent">@style/ShapeAppearance.Skedulo.SmallComponent</item>
        <item name="shapeAppearanceMediumComponent">@style/ShapeAppearance.Skedulo.MediumComponent</item>
        <item name="shapeAppearanceLargeComponent">@style/ShapeAppearance.Skedulo.LargeComponent</item>
        <!-- Component styles -->
        <item name="toolbarStyle">@style/Base.Theme.Skedulo.Toolbar</item>
        <item name="appBarLayoutStyle">@style/Base.Theme.Skedulo.Toolbar</item>
        <item name="checkboxStyle">@style/Widget.Skedulo.Checkbox</item>
    </style>

    <style name="Base.Theme.MaterialThemeBuilder" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor" tools:ignore="NewApi">?attr/colorPrimaryDark</item>
        <item name="android:windowLightStatusBar" tools:ignore="NewApi">false</item>
        <item name="android:navigationBarColor" tools:ignore="NewApi">?android:attr/colorBackground</item>
        <item name="android:windowLightNavigationBar" tools:ignore="NewApi">true</item>
        <item name="android:navigationBarDividerColor" tools:ignore="NewApi">?attr/colorControlHighlight</item>
    </style>

    <style name="Base.Theme.App.FullScreenDialog" parent="Theme.MaterialComponents.Light.Dialog">
        <item name="colorPrimary">@color/blue_800</item>
        <item name="colorPrimaryVariant">@color/blue_400</item>
        <item name="colorSecondary">@color/blue_800</item>
        <item name="colorSecondaryVariant">@color/blue_400</item>
        <item name="android:windowLightStatusBar">false</item>
        <item name="android:windowIsFloating">false</item>
        <item name="android:windowBackground">@color/white</item>
        <item name="toolbarStyle">@style/Base.Theme.Skedulo.Toolbar</item>
        <item name="android:toolbarStyle" tools:ignore="NewApi">@style/Base.Theme.Skedulo.Toolbar</item>
        <item name="android:windowAnimationStyle">@style/DialogAnimation</item>
    </style>

    <style name="BootAnimation">
        <item name="android:activityOpenEnterAnimation">@android:anim/fade_in</item>
        <item name="android:activityOpenExitAnimation">@android:anim/fade_out</item>
        <item name="android:activityCloseEnterAnimation">@android:anim/fade_out</item>
        <item name="android:activityCloseExitAnimation">@android:anim/fade_in</item>
    </style>z

    <style name="DialogAnimation">
        <item name="android:windowEnterAnimation">@anim/slide_in</item>
        <item name="android:windowExitAnimation">@anim/slide_out</item>
    </style>

    <style name="Base.Theme.App.Toolbar" parent="@style/Widget.MaterialComponents.Toolbar.Primary">
        <!--        <item name="android:background">@color/transparent</item>-->
        <item name="android:popupTheme">@style/ThemeOverlay.AppCompat.Light</item>
    </style>
</resources>

```

Alert

```    private fun showAlertDialog() {
        MaterialAlertDialogBuilder(requireActivity(), R.style.ThemeOverlay_Skedulo_MaterialAlertDialog)
            .setTitle(resources.getString(R.string.discard_changes_title))
            .setMessage(resources.getString(R.string.discard_changes_content))
            .setNegativeButton(resources.getString(R.string.keep_editing)) { dialog, which ->
                // Respond to negative button press
            }
            .setPositiveButton(resources.getString(R.string.discard)) { dialog, which ->
                // Respond to positive button press
            }
            .show()
    }```

**Comment by drchen** [comment] 2021-11-02 20:15
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:15 UTC
Labels: bug, Need more info
