### ISSUE TITLE
[Slider] RangeSlider drawing bug when two thumb overlap

### ISSUE THREAD

**Issue by rickymohk** [material-components/material-components-android#1394] opened 2020-06-09 02:39 UTC
**Description:** Unexpected shapes drawn on the RangeSlider when two thumbs overlap
<img width="426" alt="Screenshot 2020-06-09 at 10 32 29 AM" src="https://user-images.githubusercontent.com/17548814/84099827-09101f80-aa3d-11ea-9c4c-7a34a45929ef.png">

**Expected behavior:** 
<img width="426" alt="Screenshot 2020-06-09 at 10 32 29 AM" src="https://user-images.githubusercontent.com/17548814/84099963-6c01b680-aa3d-11ea-93c2-17dd8ed455e2.png">

**Android API version:** 29

**Material Library version:** 1.3.0-alpha01

**Device:** CAT S41 Android 8.0.0

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by atidevs** [comment] 2020-10-27 14:52
Hello, 
Any new feedbacks regarding this issue (solution/workaround) ?

I got the same issue on a device running Android Oreo 8.1.0 (API level 27).

**Comment by ericlamdev** [comment] 2020-11-26 11:57
Same issue here

**Android version:** 7.0

**Device:** Samsung Galaxy S6

**Material Library version:** 1.3.0-alpha03

Does any one find the solution?

**Comment by drchen** [comment] 2022-02-18 18:46
Does this only happen on certain devices? Can you provide a reproducible sample app?

**Comment by drchen** [comment] 2022-03-16 19:01
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-16 19:01 UTC
Labels: bug, Need more info, Widget: Slider
