### ISSUE TITLE
[ChipGroup] Copy last value instead IndexOutOfBoundsException

### ISSUE THREAD

**Issue by papuge** [material-components/material-components-android#760] opened 2019-11-13 17:44 UTC
**Description:** When iterating over collection with indices (in case collection size is bigger than 1)  if we add +1 index there'll be copy chip of last value instead IndexOutOfBoundsException.

**Source code:** 
```Kotlin
for (i in tags.indices + 1) {
    val chip = Chip(tagsChipGroup.context).apply {
        text = tags[i]
        setChipBackgroundColorResource(R.color.colorCardBackground)
        isClickable = true
        textSize = resources.getDimension(R.dimen.tag_text_size)
     }
     tagsChipGroup.addView(chip)
}
```
**Android API version:** 29

**Material Library version:** 1.1.0-beta02

**Device:** Pixel 2 XL

**Comment by hunterstich** [comment] 2019-11-13 18:43
Hey, thanks for filing an issue! 
What's the `tag` collection that you're iterating through? Do you mind adding a small sample that reproduces this issue?

**Comment by matpag** [comment] 2019-11-14 12:02
This is the expected behaviour.
In Kotlin `indices` get all the available index of the list.
If your `tags` list contains 3 elements, the variable `i` will get `0, 1 and 2` values.
In the last loop round you are trying to access the [2 + 1] element (index 3) which does not exist for a list with 3 element. 

Your code will work fine simply removing the unnecessary + 1

**Comment by papuge** [comment] 2019-11-14 12:26
@matpag yep, it works fine when there is right amount of indices but I'm more interested why there's no `IndexOutOfBoundsException` when + 1 index is added.

**Comment by papuge** [comment] 2019-11-14 12:31
@hunterstich this is tag collection
 `val tags = arguments?.getStringArrayList(ARG_TAGS)?.toList()!!`
and piece of OnCreateView() method
```Kotlin
        val tags = arguments?.getStringArrayList(ARG_TAGS)?.toList()!!
        val note = arguments?.getParcelable<Note>(ARG_NOTE)
        note.run {
            headerTextView.text = this?.title ?: ""
            contentTextView.text = this?.content ?: ""

            Log.d("NoteFragment", "tags from viewModel: $tags")

            if (tags.isNotEmpty()) {
                for (tag in tags) {
                    val chip = Chip(tagsChipGroup.context).apply {
                        text = tag
                        setChipBackgroundColorResource(R.color.colorCardBackground)
                        isClickable = true
                        textSize = resources.getDimension(R.dimen.tag_text_size)
                    }
                    tagsChipGroup.addView(chip)
                }
            } else {
                view.findViewById<HorizontalScrollView>(R.id.tags_scroll).visibility = GONE
            }
        }

        editNoteButton.setOnClickListener {
            redirectToEditFragment(note!!, tags)
        }
```

**Comment by hunterstich** [comment] 2019-11-14 15:15
Hey @papuge! This looks like a Kotlin questions that doesn't really relate to our library. 

With that said, in your original code snippet you have `for (i in tags.indices + 1)`. What `tags.indices + 1` is actually doing is creating an `IntArray` of the indices in your `tags` `Collection` and then appending the `Int` 1 to that array, leaving you with the equivalent of `for (i in [0, 1, 2, 1]` (given a `tags` array with 3 items in it). This is more obvious if you replace `1` with something like `99`. `tags.indices + 99` creates an `IntArray` of the indices in `tags` and appends the `Int` 99, leaving you with `[0, 1, 2, 99]`. In that case, you _would_ get an `IndexOutOfBounds` exception if your `tags` array had less than 99 items in it.

Hopefully that helps. I'm going to go a head and close this issue.

**Closed by hunterstich** 2019-11-14 15:15 UTC
Labels: bug
