### ISSUE TITLE
[MaterialContainerTransform] View captured after the fragment is destroyed in shared element return transition

### ISSUE THREAD

**Issue by mxalbert1996** [material-components/material-components-android#1734] opened 2020-09-17 06:42 UTC
**Description:**
The reason why this matters is that image loading libraries (such as Glide which I'm using) automatically clear images when the lifecycle of the container (fragment here) is over. Usually there is no problem with this but when you are using shared element transition with MaterialContainerTransform, the views with their image cleared appear empty during return transition.
Here is a video demonstrating this: https://i.imgur.com/hkvEEZd.mp4
Actually I don't know whether this is a bug or the expected behavior but I wonder how to solve this except hacking Glide's lifecycle management.

**Expected behavior:** The view is captured before destroyed.

**Source code:** [transition-demo-fragment.zip](https://github.com/material-components/material-components-android/files/5236809/transition-demo-fragment.zip)

**Android API version:** Tested on API 29

**Material Library version:**  1.2.1 / 1.3.0-alpha02

**Device:** All devices

**Comment by mxalbert1996** [comment] 2020-12-02 09:22
I think this is the same issue as #1707.

**Comment by hunterstich** [comment] 2020-12-02 12:58
Marking this as a duplicate of #1707 and closing.

**Closed by hunterstich** 2020-12-02 12:58 UTC
Labels: bug
