### ISSUE TITLE
[MaterialButtonToggleGroup, MaterialButton] backgroundTint not working correctrly Api 21-22

### ISSUE THREAD

**Issue by logoped583st** [material-components/material-components-android#2667] opened 2022-04-26 13:37 UTC
**Description:** backgroundTint not applied on initial state and in some strange situations during switches between buttons on android Api 21-22

**Expected behavior:** backgroundTint should be applied normally without any glitches. BTW text color with selector applied as expected.
screenshot with initial state:
<img width="300" alt="изображение" src="https://user-images.githubusercontent.com/30079690/165313051-6480bae2-7f50-4844-9c0e-1949212b9e86.png">
video with material catalog from release-1.5 branch 

https://user-images.githubusercontent.com/30079690/165317041-76f68769-43ee-41ee-b9c3-738c9a109628.mp4

**Source code:** The code snippet which is causing this issue

**Minimal sample app repro:** https://github.com/logoped583st/Material-issue

**Android API version:** API 21-22

**Material Library version:** Material Android Library version you are using here (e.g., 1.5.0, 1.6.0-rc01, 1.7.0-aplpa01)

**Device:** doesn't matter

**Comment by paulkugaev** [comment] 2022-05-02 13:44
I have the same issue

**Comment by drchen** [comment] 2022-05-02 21:22
I believe it's a duplicate of https://github.com/material-components/material-components-android/issues/1422. I'll close this issue for now. : )

**Closed by drchen** 2022-05-02 21:22 UTC
Labels: bug, Widget: Button

**Comment by drchen** [comment] 2022-05-02 21:24
https://github.com/material-components/material-components-android/issues/2670 is also a relevant issue.

This issue is more prominent on Lollipop devices but also happens on all API levels in a more limited situation. A general fix for all API levels is on is way.
