### ISSUE TITLE
No auto suggestions

### ISSUE THREAD

**Issue by Dayakargoud** [material-components/material-components-android#2444] opened 2021-10-26 12:23 UTC
**Description: I have updated version to 1.5.0-alpha05 from 1.5.0-alpha04, after updating there was no theme/style suggestions  for material3 components in  Android studio.

Earlier it was working fine with 1.5.0-alpha04

**Expected behavior: Should show Available component styles in material3

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version here

**Material Library version: 1.5.0-alpha05

**Device:** Android studio 

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

> 

>

**Comment by Dayakargoud** [comment] 2021-10-29 18:29
Even I also tried Invalidate cache and Restart but didn't work.

**Comment by drchen** [comment] 2021-11-03 17:49
Hey folks. We probably figured out the root cause and the fix will be released in the next version. 

I'll keep the issue open until the version is released. Thanks for the report.

**Comment by Dayakargoud** [comment] 2021-11-14 08:13
This issue has been fixed in beta01, if you are facing this issue please update the material library version to beta01.

**Comment by drchen** [comment] 2021-11-15 20:55
Awesome! Thanks for confirming the fix. I'll close the issue. : )

**Closed by drchen** 2021-11-15 20:55 UTC
Labels: bug, studio
