### ISSUE TITLE
[MaterialDatePicker] Not able to be instantiated via XML, can only create using builder

### ISSUE THREAD

**Issue by mwolfsonturner** [material-components/material-components-android#932] opened 2020-01-22 15:35 UTC
**Description:** Currently it is not possible to create the new style date picker using standard XML, it is only possible to create using the builder from Kotlin

**Expected behavior:** I would expect to be able to access the DatePicker from XML layouts, which is consistent with other MDC components.

<img width="567" alt="Screenshot 2020-01-22 10 31 11" src="https://user-images.githubusercontent.com/59577273/72908019-e2a64d80-3d02-11ea-9887-234e33bd3043.png">

**Source code:** According to the demo code, this is the only way to instantiate a MaterialDatePicker, which is not very pragmatic:

https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/datepicker/DatePickerMainDemoFragment.java

**Android API version:** Android API 29

**Material Library version:**  '1.2.0-alpha03' (don't think this works on the latest version either, will update and test)

**Device:** not relevant
To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by mwolfsonturner** [comment] 2020-01-22 15:39
An additional comment I have about this need - is this means that I am not able to instantiate this component directly using the Navigation Components (which is restrictive for my needs).

**Comment by drchen** [comment] 2022-02-07 20:40
Close as a duplicate of https://github.com/material-components/material-components-android/issues/562

**Closed by drchen** 2022-02-07 20:40 UTC
Labels: bug
