### ISSUE TITLE
[TabLayout] requestLayout() improperly called

### ISSUE THREAD

**Issue by AleksandarAleksiev** [material-components/material-components-android#1798] opened 2020-10-15 11:40 UTC
**Description:** Warning in logcat View: requestLayout() improperly called by com.google.android.material.tabs.TabLayout$SlidingTabIndicator{f604ae3 V.ED..... ........ 0,0-1100,258} during second layout pass: posting in next frame

**Material Library version:** 1.1.0

**Device:** Emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment] 2022-05-04 21:24
Similar issue: https://github.com/material-components/material-components-android/issues/1673

**Comment by drchen** [comment] 2022-06-10 20:36
Is this reproducible on a real device?

I think we introduced a workaround to fix a framework issue that LinearLayout does not request layout when RTL changes on pre-M devices. The workaround may cause the warning under certain situations when requestLayout() is correctly called by the framework class. 

Since it's only a warning and we don't really have better way to fix this, I'll close the issue as infeasible.

**Closed by drchen** 2022-06-10 20:36 UTC
Labels: bug, Good First Issue, Widget: Tab
