### ISSUE TITLE
[BottomNavigationView] In compileSdkVersion 29, bottom nav item is blinked when it has unselected.

### ISSUE THREAD

**Issue by youmitsu** [material-components/material-components-android#628] opened 2019-09-25 09:40 UTC
**Description:** 
I'm using BottomNavigatgionView with a standard way. Today, when I upgraded my app's compileSdkVersion to 29, The behavior has changed.
The behavior is that bottom nav item is blinked when it has unselected. Is this a bug?

**Expected behavior:** 
Bottom nav item is NOT blinked.

**Source code:** 

A sample repository is here: 
https://github.com/youmitsu/BottomNavigationBugTestApp

`MainActivity.kt`:
```
class MainActivity : AppCompatActivity(), BottomNavigationView.OnNavigationItemSelectedListener {

    lateinit var binding: ActivityMainBinding

    override fun onNavigationItemSelected(item: MenuItem): Boolean {
        when (item.itemId) {
            R.id.nav_home -> {
                binding.message.text = getString(R.string.home)
                return true
            }
            R.id.nav_notification -> {
                binding.message.text = getString(R.string.notification)
                return true
            }
        }
        return false
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
        binding.bottomNav.setOnNavigationItemSelectedListener(this)
    }
}
```

`activity_main.xml`:
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity">

        <TextView
            android:id="@+id/message"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/home"
            app:layout_constraintBottom_toTopOf="@id/bottom_nav"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            tools:text="Hello World!" />

        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:id="@+id/bottom_nav"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:background="?android:attr/windowBackground"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:menu="@menu/bottom_nav" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```

`res/menu/bottom_nav.xml`: 
```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:id="@+id/nav_home"
        android:enabled="true"
        android:icon="@drawable/ic_home_black_24dp"
        android:title="home" />
    <item
        android:id="@+id/nav_notification"
        android:icon="@drawable/ic_notifications_black_24dp"
        android:title="notification" />
</menu>
```

**Android API version:** 29

**Material Library version:** 1.1.0-alpha09, 1.1.0-alpha10.

**Device:** Pixel3

**Comment by ldjcmu** [comment] 2019-09-25 17:56
Closing as a duplicate of #530

**Closed by ldjcmu** 2019-09-25 17:56 UTC
Labels: bug, duplicate
