### ISSUE TITLE
[TextInputLayout] endIconDrawable doesn't work

### ISSUE THREAD

**Issue by andrei-vas** [material-components/material-components-android#2132] opened 2021-03-15 17:40 UTC
**Goal : Set endIconDrawable** 

**Expected : Drawable is present on the screen** 
**Current : Drawable is missing from  the screen**

```
<com.google.android.material.textfield.TextInputLayout
            app:endIconDrawable="@drawable/ic_form_erase_content">

            <com.google.android.material.textfield.TextInputEditText/>
</com.google.android.material.textfield.TextInputLayout>
```

**Android 11** 

**Material version - 1.3.0-alpha02** 

**Device - Emulator**

**Comment by dsn5ft** [comment] 2021-03-15 19:26
Probably a duplicate of #2128. Can you try setting `app:endIconMode="clear_text"`? See [docs](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#adding-a-trailing-icon-to-a-text-field).

**Closed by dsn5ft** 2021-03-15 19:26 UTC
Labels: bug
