### ISSUE TITLE
Material Installation

### ISSUE THREAD

**Issue by amitkr936** [material-components/material-components-android#202] opened 2018-09-22 09:40 UTC
**com.android.support:appcompt-v7
com.android.support.constraint:constraint-layout
After deleting these 2 I get another error
**(Compilation failed; see the compiler error output for details.)

**Comment by dsn5ft** [comment] 2018-09-26 22:07
Duplicate of #103.

This is because you are using the new Material library with the legacy Support Library. You have to migrate android.support to [androidx](https://developer.android.com/studio/preview/features/#android_jetpack) in order to use com.google.android.material.

Please take a look at our [Getting Started Guide](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md) which talks about this.

**Closed by dsn5ft** 2018-09-26 22:07 UTC
