### ISSUE TITLE
[ExposedDropdownMenu] no padding when autocomplete textview is not editable

### ISSUE THREAD

**Issue by raquezha** [material-components/material-components-android#495] opened 2019-08-03 19:52 UTC
**Description:** no padding is added when autocompletetextview is not editable on api 16

**Expected behavior:** padding should be applied like the editable dropdown menu

**Source code:**     
``` xml
<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/tlField"
            style="@style/AwesomeForm.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            app:hintEnabled="false"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tvFieldLabelTitle">

        <androidx.appcompat.widget.AppCompatAutoCompleteTextView
                android:id="@+id/tvField"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="none"
                **android:editable="false"** <-- happens when editable is false (working fine when set to true)
                tools:hint="Please select something"
                android:includeFontPadding="false"
                android:maxLines="1"
                android:textColor="@color/AwesomeForm_textColor"
                android:imeOptions="flagNoExtractUi"/>

    </com.google.android.material.textfield.TextInputLayout>
```
**Android API version:** API 16

**Material Library version:** 1.1.0-alpha09

 **Device:**
1. Emulator API 17 - _working fine_
2. Emulator API 19(Android 4.4.2) - _working fine_
3. Asus Zenfone Max Pro M1 (Android 8.1.0, API 27) - _working fine_
4. Nokia 3 (Android 9, API 28) - _working fine_
5. Emulator API 16 (4.1.2) - **NOT WORKING**

 **Notes:**
AHHHHH I wasted 1 day of my weekend hahahah this only happens on API 16! (I didn't test on api lower than 16)

**Screenshots:**

on Emulator API 16 (4.1.2) see the 3rd item with text: _"Item 3"_
![device-2019-08-04-034906](https://user-images.githubusercontent.com/9584016/62416323-1fa25900-b66b-11e9-9e2b-84622f0f20a4.png)

on Emulator API 16 (4.1.2)
![device-2019-08-04-160532](https://user-images.githubusercontent.com/9584016/62421276-c3beeb00-b6d1-11e9-99ef-33a75976fa0f.png)

But if you startIconDrawable in textInputLayout and it's working fine

![device-2019-08-04-153644](https://user-images.githubusercontent.com/9584016/62421012-f5ce4e00-b6cd-11e9-9712-9710af2bae17.png)

**Comment by raquezha** [comment] 2019-08-04 08:11
For those who just want the spinner function current workound on is 
set it to editable and disable it on AutocompleteTextView:

```xml
android:editable="true"
android:enabled="false"
```

**Comment by drchen** [comment] 2021-11-02 20:07
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:07 UTC
Labels: bug, Need more info
