### ISSUE TITLE
[ExtendedFloatingActionButton] Draw Text in center of component in RTL layout

### ISSUE THREAD

**Issue by TurKurT656** [material-components/material-components-android#1909] opened 2020-11-29 19:44 UTC
**Description:** 
I'm trying to make a custom view that has extended from ExtendedFloatingActionButton. I'm drawing a text (counter) at center of this widget. this is the code snippet:
```
init {
        // Customize textPaint for counter
        paint.apply {
            textSize = context.getDimension(R.dimen.17sp)
            color = context.getColorCompat(R.color.color_on_secondary).orWhite()
            textAlign = Paint.Align.CENTER
        }
}

override fun onDraw(canvas: Canvas?) {
        super.onDraw(canvas)
        drawContent(canvas)
    }

    private fun drawContent(canvas: Canvas?) {
        if (count > 0) {
            // Show Counter
            val text = count.toString()
            val xPos = (width / 2).toFloat()
            val yPos = (height / 2) - ((paint.descent() + paint.ascent()) / 2)
            canvas?.drawText(text, xPos, yPos, paint)
            // Hide Icon
            icon = context.getDrawableCompat(R.drawable.ic_empty)
        } else {
            // Show Icon
            icon = cachedIcon
        }
    }
```
Now this code works when the layout direction is LTR. But when I change it to RTL text is not aligned to center.

**Expected behavior:**
LayoutDirection = LTR | Counter > 0
<img width="79" alt="ltr" src="https://user-images.githubusercontent.com/7152030/100551789-37f2aa00-3298-11eb-9f21-af45d1326a6d.png">
LayoutDirection = RTL | Counter > 0
<img width="75" alt="rtl" src="https://user-images.githubusercontent.com/7152030/100551793-404ae500-3298-11eb-8f19-6d389cc9e40e.png">
LayoutDirection = LTR or RTL | Counter = 0
<img width="75" alt="icon" src="https://user-images.githubusercontent.com/7152030/100551794-43de6c00-3298-11eb-828d-51b884e0c8e2.png">

**Android API version:** 30

**Material Library version:** 1.3.0-alpha04

**Device:** Android Studio Emulator

**Comment by wcshi** [comment] 2020-11-30 19:35
Why are you extending EFAB instead of creating your own custom component?

**Comment by wcshi** [comment] 2020-11-30 19:36
Instead of overriding on Draw, did you try setting text to an empty string or not setting the icon when count > 0?

**Comment by TurKurT656** [comment] 2020-12-01 15:43
I'm extending from EFAB because i want all of the functionalities of FAB. But if I extend from FAB itself I can't set gradient background to it.

When I'm setting icon to null, it's even worse. Shape of the EFAB gets an oval instead of circle.

**Comment by drchen** [comment] 2021-10-06 17:48
Hi, has the issue been solved? 

I'm going to close the issue since it looks like a bug caused by the custom logic, and I'm not sure what help we can provide here. 

I'm wondering if it's your textPaint's textAlign has been changed when it's RTL?

**Closed by drchen** 2021-10-06 17:48 UTC
Labels: bug
