### ISSUE TITLE
[MaterialTimePicker] Buttons unreachable in landscape mode

### ISSUE THREAD

**Issue by andriydruk** [material-components/material-components-android#1974] opened 2021-01-11 14:40 UTC
**Description:** In landscape mode with big Font/Display size part of the dialog is unreachable. Probably some kind of scroll needed here.

**Android API version:** 30

**Material Library version:** com.google.android.material:material:1.3.0-beta01

**Device:** Pixel 4

![image](https://user-images.githubusercontent.com/1927559/104195690-a005e580-542b-11eb-89a8-d636f7be32ec.png)

**Comment by drchen** [comment] 2022-04-15 18:30
I'll close the issue as a duplicate of #1863. I think we will have a fix for both situations. Let's just keep that one open for better tracking this.

**Closed by drchen** 2022-04-15 18:30 UTC
Labels: bug, Widget: TimePicker
