### ISSUE TITLE
[TextInputLayout] Unexpected focus acquisition

### ISSUE THREAD

**Issue by 0x7e57** [material-components/material-components-android#1930] opened 2020-12-17 08:15 UTC
**Description:** nested TextInputEditText gets focus when TextInputLayout.setEnabled(true) with a small delay and if its default is false (xml)

**Expected behavior:** nested TextInputEditText doesn't get focus

**Source code:**     
```
<com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputLayout"
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="16dp"
        android:enabled="false">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/textInputEditText"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </com.google.android.material.textfield.TextInputLayout>
```
```
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        FragmentHomeBinding viewBinding = FragmentHomeBinding.bind(view);
        Completable.complete()
                .delay(5, TimeUnit.MILLISECONDS)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(() -> viewBinding.textInputLayout.setEnabled(true));
	}
```

**Android API version:** Android 28

**Material Library version:** 1.3.0-beta01

**Device:** Xiaomi Mi A3

**Comment by drchen** [comment] 2021-11-04 19:21
Is this still reproducible? I don't see the issue on my end.

**Comment by drchen** [comment] 2022-01-12 20:29
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-01-12 20:29 UTC
Labels: bug, Need more info
