### ISSUE TITLE
Citrix XenMobile: App package contains invalid file names or folder names

### ISSUE THREAD

**Issue by pzavadska** [material-components/material-components-android#1104] opened 2020-03-11 13:54 UTC
**Description:** We have a customer who wants to use Cloud MDX Toolkit. When he tries to wrap the apk in it following issue occurs: App package contains invalid file names or folder names

This is an error when an App contains a blacklisted set of characters. This is a MDX Service only security restriction.
The black listed characters are: ; | > & “ ` $ \
(link to their known limitation: [Citrix Support Page](https://support.citrix.com/article/CTX232438))

I've checked the apk and found out that the issue is caused by these files (located depending on the library version used in drawable-21 / drawable-24 - when building I use API 29, min 24):
$ic_launcher_foreground__0.xml
$avd_hide_password__0.xml
$avd_show_password__0.xml
$avd_hide_password__1.xml
$avd_show_password__1.xml
$avd_hide_password__2.xml
$avd_show_password__2.xml

I tried to exclude them e.g. using gradle packaging options but with no success. Also I'm not even sure whether they can be safely excluded... 
Is there something I can do? Why these strange files even exist?

**Expected behavior:** App can be wrapped successfully.

**Source code:** N/A

**Android API version:** Doesn't depend on Android API version

**Material Library version:** Tried with 1.1.0-beta01, 1.1.0 and 1.2.0-alpha05

**Device:** N/A

**Comment by wcshi** [comment] 2020-03-15 13:36
What is Cloud MDX Toolkit and how is it related to the this library?

**Comment by pzavadska** [comment] 2020-03-15 13:46
It’s a MDM/MDA tool. Basically it’s used by organization to distribute only approved apps to their devices. Usually they wrap original installation files to add additional security. 
So the issue occurs when they are trying to wrap apk of our app as it contains files listed above which names start with $ (not allowed character). These files are added by this library to the apk when created as we use this library as our app dependency.

**Comment by wcshi** [comment] 2020-03-15 15:19
There are no files in the library with $ in its name, the closest we have are avd_hide_password.xml and avd_show_password.xml

There is no file named ic_launcher_foreground*.xml in the library

Seems like the problem is on your end with how the apks are generated.

**Comment by pzavadska** [comment] 2020-03-16 07:47
Problem seems to be caused by AAPT? It's weird why it happens only for the given resources. If you search around you'll find several people had an issue caused by avd_show_password.xml and avd_hide_password.xml. 
People are trying to fix it by DexPatcher tool: https://github.com/DexPatcher/dexpatcher-gradle/issues/22 (there is also content of these files so you can see what they contain...)

So seems like something can be done about it on our end (will have to try it if it really helps) but definitely the malformed files come from your library. Have no idea why they are malformed as there is nothing special about them...

**Comment by pzavadska** [comment] 2020-03-25 16:07
Just to update - I have not yet succeeded in removing this file from the apk :/

**Comment by iXyles** [comment] 2021-05-28 13:54
Has anyone figured out a way to deal with this type of issue regarding xamarin builds?

**Comment by drchen** [comment] 2022-06-10 19:03
Is this still an issue? I actually have no idea how this will happen and if it's something we can possibly fix on our end.

**Comment by petrazavadska** [comment] 2022-06-11 20:55
Not sure how this happens, but in the end it should have been accepted as a valid file name as also on their page it's stated that it's a "Known limitation of Cloud MDX Toolkit". So I think this may be closed as you probably can't do anything to prevent the splitting of the files.
Thank you for your time :)

**Closed** 2022-06-13 14:58 UTC
Labels: bug, Need more info, Issue: Other
