### ISSUE TITLE
ClassNotFoundException when unmarshalling: com.google.android.material.bottomnavigation.BottomNavigationView$SavedState

### ISSUE THREAD

**Issue by breakwhile** [material-components/material-components-android#1246] opened 2020-04-26 03:21 UTC
Hi guys, 
https://github.com/material-components/material-components-android/issues/549
This bug has been fixed in version 1.1, but it still appears.
We use 1.1 version and it contains fix code [56fbbe9](https://github.com/material-components/material-components-android/commit/56fbbe9ee525f07f2fc9e5506cd5bed3bd8f76cf)
Do You Know Why?

**Comment by wcshi** [comment] 2020-04-29 15:40
The fix is not in 1.1.0, it's in 1.2.0-alpha02 and newer versions.

**Comment by DebdeepG** [comment] 2020-08-11 10:43
I am using '1.2.0-alpha06' and it's still there.

**Comment by wcshi** [comment] 2020-08-11 16:34
@DebdeepG are you able to reproduce this bug in a standalone sample app? Any information that could help us reproduce the bug would be helpful!

**Comment by DebdeepG** [comment] 2020-08-11 16:45
Affected version: 1.2.0-alpha06

This is the respective stack trace and confirmed on android 9 :

```
Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.material.bottomnavigation.BottomNavigationView$SavedState
       at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
       at android.os.Parcel.readParcelable(Parcel.java:2781)
       at android.os.Parcel.readValue(Parcel.java:2684)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:3134)
       at android.os.Parcel.readSparseArray(Parcel.java:2367)
       at android.os.Parcel.readValue(Parcel.java:2741)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:1010)
       at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2204)
       at android.app.Activity.onRestoreInstanceState(Activity.java:1204)
       at android.app.Activity.performRestoreInstanceState(Activity.java:1159)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1317)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3215)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:185)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:170)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:147)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

<img width="1150" alt="Screenshot-Trace" src="https://user-images.githubusercontent.com/18580237/89924664-f7efb480-dc1f-11ea-9fb4-9f2d521d7c92.png">

**Comment by drchen** [comment] 2022-02-17 22:39
Is this still happening with the latest library version?

**Comment by drchen** [comment] 2022-03-16 18:59
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-16 18:59 UTC
Labels: bug, Need more info
