### ISSUE TITLE
[MaterialDatePicker] Localization for date not by default

### ISSUE THREAD

**Issue by davidgiraldoc** [material-components/material-components-android#1353] opened 2020-05-31 00:02 UTC
**Description:** I'am on an hispanic country and developing an important app for a courier company, and the users normally doesn't know how to speak english, so everything must be on Spanish. I have not fount a way to change the date locale.

**Expected behavior:** What I need is a method or a way to set the locale used by the dialog, and in that way the date displayed will be on that locale just like `Abr` instead of `Apr` and `Ene` instead of `Jan`.

**Android API version:**  sdk 29

**Material Library version:** com.google.android.material:material:1.2.0-alpha06

**Comment by CoolMind** [comment] 2020-06-02 14:06
@davidgiraldoc, ha-ha, it is a frequent question. See https://github.com/material-components/material-components-android/issues/761.

**Comment by gabrielemariotti** [comment] 2020-08-18 10:38
Duplicate of #761

**Closed** 2020-08-18 14:27 UTC
Labels: bug
