### ISSUE TITLE
[Text Fields] Support for multiple trailing icons

### ISSUE THREAD

**Issue by john-sardinha-pbx** [material-components/material-components-android#560] opened 2019-09-03 09:41 UTC
Would be useful to have more than 1 end Icon on a TextInputLayout.

My use case, I'm possibly a popular one, is having a password field with the "eye" end icon to hide and display the text, and also have an error icon.

Currently if we try to achieve this with the built in attributes:
```
app:endIconMode="password_toggle"
app:errorEnabled="true"
```
The TextInputLayout will display the "eye" icon, and once you trigger an error it will replace the "eye" icon with the error icon, removing the ability for the user to toggle the password visibility. So this feature request is to have a built in way to keep the error icon and the visiblity toggle icon.

**Comment by somesh-basicx** [comment] 2019-10-16 06:31
I came here to file this bug and really think that this should be a bug instead of a feature request because whenever an error occurs, users wan't to see what went wrong and just replace the wrong input with new one instead of just removing the whole input text because they can't toggle the password and see what is wrong.  This is expected behavior.

**Comment by drchen** [comment] 2021-07-16 17:15
I don't think it's a general principle of how to handle passwords. The top concern of passwords should be security, not convenience. 

As for the general request of adding multiple trailing icons - it can result in very bad UX and I think it will be a no-go. 
Closing the request.

**Closed by drchen** 2021-07-16 17:15 UTC
Labels: feature request

**Comment by projectdelta6** [comment] 2023-04-28 11:44
Perhaps it is best to not allow for "Multiptle" trailing icons but I do believe that the password toggle "eye" should be separated from the EndIcon so that the user can still access the password toggle when the error is set on the view.
