### ISSUE TITLE
[Android Studio][Render Problem with FAB ] java.awt.geom.IllegalPathStateException: missing initial moveto in path definition

### ISSUE THREAD

**Issue by EngAhmed53** [material-components/material-components-android#1046] opened 2020-02-21 15:50 UTC
**Description:** FAB not showing in app layout and Render problem occurred.

**Expected behavior:**  
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.awt.geom.Path2D$Double.needRoom(Path2D.java:1193)
	at java.awt.geom.Path2D.closePath(Path2D.java:1877)
	at android.graphics.Path_Delegate.close(Path_Delegate.java:824)
	at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)
	at android.graphics.Path.nClose(Path.java)
	at android.graphics.Path.close(Path.java:508)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)
	at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1160)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:945)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1011)
	at android.graphics.drawable.RippleDrawable.drawContent(RippleDrawable.java:818)
	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:675)
	at android.graphics.drawable.DrawableWrapper.draw(DrawableWrapper.java:227)
	at android.view.View.drawBackground(View.java:20412)
	at android.view.View.draw_Original(View.java:20198)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:20177)
	at android.view.View.draw_Original(View.java:20077)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20075)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20075)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20210)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:20177)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:399)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:551)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:420)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:120)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:151)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:133)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$8(RenderTask.java:783)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Source code:** Source code:
<com.google.android.material.floatingactionbutton.FloatingActionButton android:id="@+id/fab_action" 
android:layout_width="wrap_content"
 android:layout_height="wrap_content"
 android:layout_margin="16dp"
 android:src="@drawable/ic_time"
 android:tint="@color/colorWhite"
 app:layout_gravity="end|bottom" />

**Android API version:** Android API 29

**Material Library version:** Material Android Library version 1.2.0-alpha05'

**Device:** Pixel 2

**Comment by ymarian** [comment] 2020-02-21 16:13
I can't repro this. Are you using a custom style? 

Could you share a sample app reproing this issue

**Comment by fllaryora** [comment] 2020-03-08 04:40
Hi @ymarian 
My styles.xml is `<resources>

    
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>
</resources>`

And I am using a FAB like :
`<com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:backgroundTint="@android:color/white"
        app:layout_anchor="@+id/card_view"
        android:tint="@color/colorPrimary"
        android:src="@drawable/ic_arrow_right"
        app:rippleColor="@color/colorCard"
        app:layout_anchorGravity="right|end|center_vertical" />`

**Comment by ProDev2** [comment] 2020-03-26 11:41
I'm getting the same error in Android Studio's layout editor window, when using 'materialVersion=1.2.0-alpha05' like @fllaryora mentioned before me. But no crash when running.

**Comment by wcshi** [comment] 2020-03-26 15:16
Just to clarify, is this a problem that only happens in Android Studio's layout editor preview? And not in an actual app?

**Comment by Spazzze** [comment] 2020-04-16 21:55
Same for me.  Unfortanately with latest build (alpha06) problem is still here.
Yes, it is only with layout editor preview, and reproduces with any fab no matter what else in xml, I tried with 'com.google.android.material:material:1.2.0-alpha05' and 'com.google.android.material:material:1.2.0-alpha06' - problem exists. With 'com.google.android.material:material:1.2.0-alpha02' - no problem.
My AS info

> Android Studio 3.6.2
> Build #AI-192.7142.36.36.6308749, built on March 18, 2020
> Runtime version: 1.8.0_212-release-1586-b04 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

At editor there is 2 issues, one is described by issue starter, second is

> Path.op() not supported   Tip: Try to refresh the layout.

**Comment by wcshi** [comment] 2020-04-17 13:24
Could you please check whether the issue is still reproducible in Android Studio 4.x? If yes, please file a bug with the Studio team using this public issue tracker:
https://issuetracker.google.com/issues?q=componentid:192714

**Comment by Spazzze** [comment] 2020-04-17 13:37
> Could you please check whether the issue is still reproducible in Android Studio 4.x? If yes, please file a bug with the Studio team using this public issue tracker:
> https://issuetracker.google.com/issues?q=componentid:192714

no I cant because AS 3.6.2 is latest stable build and I wont install version from canary channel it can affect my work.

**Comment by n0tnull** [comment] 2020-04-17 18:44
@wcshi I can confirm it works perfectly with Android Studio 4.0 beta 4. It was not working on AS 3.6

**Comment by Fauzdar1** [comment] 2020-05-12 14:49
Facing same issue with `TextInputLayout` in `alpha-06`. Only one `TextInputLayout` is visible in the layout editor at a time and if I change any value in other invisible ones, that becomes visible and others go invisible, works like a visibility toggle. Very strange issue. In device, it seems perfect though, but I've to render the app in my device every time to see the theme changes. Also, any other material element like buttons do the same behaviour, if they're constrained with any invisible one, they go invisible too. 
Mine shows three errors:` Path.op() not supported, Layout fidelity warning and missing initial moveTo in path definition
`

**Comment by Fauzdar1** [comment] 2020-05-12 15:04
I resolved my problem of invisible `TextInputLayout`, though. Setting `BoxStrokeWidth` as `0dp` to hide the activation indicator is the issue but I'll go with this as as I want to hide it in the `Filled` mode. But, the errors remain intact.

**Comment by ahmadmssm** [comment] 2020-05-15 22:17
I'm facing this issue also with Android studio 3.6.3, is there any solution to this issue ?

**Comment by androidloverbe** [comment] 2020-05-16 14:09
Hello,

I can confirm the issue is there on latest stable build 3.6.3 Path.op() not supported also when you try to use a FloatingActionButton there is an exception in the preview here is the stack trace 

java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.awt.geom.Path2D$Double.needRoom(Path2D.java:1193)
	at java.awt.geom.Path2D.closePath(Path2D.java:1877)
	at android.graphics.Path_Delegate.close(Path_Delegate.java:824)
	at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)
	at android.graphics.Path.nClose(Path.java)
	at android.graphics.Path.close(Path.java:513)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)
	at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1160)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:945)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.graphics.drawable.RippleDrawable.drawContent(RippleDrawable.java:821)
	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:678)
	at android.view.View.drawBackground(View.java:21671)
	at android.view.View.draw_Original(View.java:21435)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:404)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:556)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:120)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:151)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:133)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$9(RenderTask.java:819)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by androidloverbe** [comment] 2020-05-18 09:09
Hello,

I can also confirm all issues disappear on android studio preview version release candidate so this must be a bug which is fixed in the "soon to be stable" version .

**Comment by ymarian** [comment] 2020-05-19 03:27
Thanks I was able to verified it's fixed.

**Closed by ymarian** 2020-05-19 03:27 UTC
Labels: bug, studio
