### ISSUE TITLE
[MaterialDatePicker] Date cannot be cleared

### ISSUE THREAD

**Issue by CoolMind** [material-components/material-components-android#1362] opened 2020-06-02 14:13 UTC
If we entered a date, we cannot remove it.

![image](https://user-images.githubusercontent.com/10630436/83530212-146ec280-a4f4-11ea-9bf6-0975476813d6.png)

For instance, it was 02.06.2020. Then I press a pencil icon and try to edit the date, then clear it and want to save. But OK button is disabled. I don't know, maybe I am wrong, but it should be enabled.

**Comment by gabrielemariotti** [comment] 2020-07-27 22:38
The `OK` button is enabled if the selected date is valid.
Cleaning the date in the input text = no date selected in the calendar view. In both cases the OK button is disabled.

**Comment by CoolMind** [comment] 2020-07-28 10:18
@gabrielemariotti, thank you!
So, can we return an `null` date after showing DatePicker (if it already has filled date)? Pressing Cancel is not suitable in this case and OK is disabled.

**Comment by gabrielemariotti** [comment] 2020-07-28 10:24
@CoolMind In this case you could add the `addOnNegativeButtonClickListener(`) and `addOnCancelListener()`.

**Comment by CoolMind** [comment] 2020-07-28 11:39
@gabrielemariotti Agree with you, thanks! But it is not a common scenario for a user. I mean, he wants to clear a previously entered date. He opens DatePicker, wants to remove the date, but has to press Cancel to clear. That's a bit strange.
In this case we can add an icon (a cross or recycle bin) to clear date without DatePicker.

**Comment by dsn5ft** [comment] 2020-07-29 18:19
I think this is a valid request, considering that if the date picker is shown with a date already selected, there's no easy way to clear it. Marking duplicate of https://github.com/material-components/material-components-android/issues/1332 though.

**Closed by dsn5ft** 2020-07-29 18:19 UTC
Labels: feature request
