### ISSUE TITLE
[Navigation drawer] Navigation drawer has square corners on pre-Q devices because ColorStateListDrawable is not supported

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3529] opened 2023-08-18 05:04 UTC
**Description:** The navigation drawer (1.11.0-alpha02) has **square** corners.
![Screenshot_20230818_133510](https://github.com/material-components/material-components-android/assets/71050561/68c2c764-ee80-4d52-b6de-0f05f48c6736)

**Expected behavior:** The navigation drawer has **rounded** corners like the navigation drawer (1.11.0-alpha01).
![Screenshot_20230818_133417](https://github.com/material-components/material-components-android/assets/71050561/7a49c94f-d821-42e6-95d1-51b1f951557b)

**Minimal sample app repro:** Catalog app

**Android API version:** 34

**Material Library version:** 1.11.0-alpha02

**Device:** Emulator 32.1.14 (API 32)

**Comment by imhappi** [comment] 2023-08-21 21:14
Going to re-open this and update the title since the fix is only for Q+ devices

pre-Q devices will require a more involved solution

**Comment by imhappi** [comment] 2023-08-21 21:21
@pekingme  just putting this on your radar for any upcoming work on the fragile `ColorDrawable` checking

**Comment by pekingme** [comment] 2023-08-28 21:03
We have https://github.com/material-components/material-components-android/pull/3538 to add the `ColorStateListDrawable` support. But this issue is caused by leveraging CSL to achieve the custom tone from the dynamic palettes for tonal surface color. Closing this issue since it won't be an issue for pre-Q devices.

**Closed by pekingme** 2023-08-28 21:03 UTC
Labels: bug, Widget: NavigationView
