### ISSUE TITLE
[ShapeableImageView] Can't cast shadow when setting ShapeAppearanceModel edges from API 23 to 28

### ISSUE THREAD

**Issue by BluestormDNA** [material-components/material-components-android#1842] opened 2020-10-30 21:02 UTC
**Description:** On a ShapeableImageView on API 28 and below once a edge is set the shadow disapears. Tried with triangle and circle custom shape. They work correctly on cardview. This works correctly on API 29 and 30

**Expected behavior:** Screenshots and/or description of expected behavior:

The last missing image should be like the second card a ShapeableImageView with a triangle inset

![imagen](https://user-images.githubusercontent.com/28767885/97756216-cf7aa680-1afa-11eb-891b-ef5300feb041.png)

**Source code:**

        val cutBottomRight = ShapeAppearanceModel.builder()
                .setBottomRightCorner(CornerFamily.CUT, ShapeAppearanceModel.PILL)
                .build()

        val insetBottomTri = ShapeAppearanceModel.builder()
                .setBottomEdge(TriangleEdgeTreatment(100f, true))
                .build()

        card1.shapeAppearanceModel = cutBottomRight
        card2.shapeAppearanceModel = insetBottomTri

        imageView1.shapeAppearanceModel = cutBottomRight
        imageView2.shapeAppearanceModel =  insetBottomTri //this one doesn't cast shadow on ShapeableImageView on api 23 to 28 but it does on cardview and on api 29 and 30

**Android API version:** 23 to 28 both included

**Material Library version:** 1.3.0-beta01

**Device:** Pixel 2 emulator

**Comment by BluestormDNA** [comment] 2020-12-01 20:28
Chcked Material Library Version: 1.3.0-alpha04, it haves the same issue.

**Comment by drchen** [comment] 2022-06-10 20:46
Is this still reproducible?

**Comment by drchen** [comment] 2022-06-27 12:54
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-06-27 12:54 UTC
Labels: bug, Need more info, Feature: Shape

**Comment by BluestormDNA** [comment] 2022-09-13 17:00
This is still reproducible as of 1.8.0 alpha 1
