### ISSUE TITLE
MaterialDatePicker setSelection

### ISSUE THREAD

**Issue by jianastrero** [material-components/material-components-android#714] opened 2019-10-25 06:23 UTC
**Description:** The selected date on the picker is always 1 day less than the given selected date.

**Expected behavior:** The selected date on the picker must be exactly the same as the given selected date.

**Source code:** 
`
MaterialDatePicker.Builder.datePicker().setSelection(selectedDate.timeInMillis)
`

**Android API version:** 
        minSdkVersion 23
        targetSdkVersion 29

**Material Library version:** 1.1.0-beta01

**Device:** Android Pixel C Emulator

**Comment by guger** [comment] 2019-10-25 22:14
I'm facing the same issue

**Comment by abn-volk** [comment] 2019-10-26 09:27
This is because MaterialDatePicker expects UTC and not local time. You need to add the current timezone offset to your timestamp:

```
val timezone = TimeZone.getDefault()
timestamp += timezone.getOffset(timestamp)
```

And then when you receive the result, subtract that offset.

This API is so unintuitive. I want the old one back.

**Comment by bohsen** [comment] 2019-10-27 12:38
Duplicate of #546

**Comment by ldjcmu** [comment] 2019-10-28 15:17
Closing based upon the duplicate and the linked comment. Yes, you have to use UTC.

**Closed by ldjcmu** 2019-10-28 15:17 UTC
Labels: bug

**Comment by adrcotfas** [comment] 2023-03-19 08:11
> This is because MaterialDatePicker expects UTC and not local time. You need to add the current timezone offset to your timestamp:
> 
> ```
> val timezone = TimeZone.getDefault()
> timestamp += timezone.getOffset(timestamp)
> ```
> 
> And then when you receive the result, subtract that offset.
> 
> This API is so unintuitive. I want the old one back.
> 
> EDIT: See [this comment](https://github.com/material-components/material-components-android/issues/546#issuecomment-545485252). I can't wait until we're able to use `LocalDate`.

This is not a solution because subtracting the offset does not consider daylight saving.  
Using Pacific Time and selecting a date before the second Sunday of March will still return one day less than the selection.  

You can find a working solution [here](https://stackoverflow.com/a/71541489).
