### ISSUE TITLE
TextInputLayout Suffix Text Bug

### ISSUE THREAD

**Issue by dodyac** [material-components/material-components-android#2341] opened 2021-08-19 09:51 UTC
when I use the material component version 1.3.0 I don't have a problem, but when I replace it with version 1.4.0 I have a problem where the suffix text is not on the right side of the textinputlayout, but is in the center of textinputlayout, please fix this.

**Comment by dodyac** [comment] 2021-09-22 01:28
I'm using like this

`                    <com.google.android.material.textfield.TextInputLayout
                        style="@style/actStyle"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="@dimen/x0dp"
                        android:hint="Unit">

                        <com.google.android.material.textfield.MaterialAutoCompleteTextView
                            android:id="@+id/unit"
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:importantForAutofill="no"
                            android:inputType="none"
                            android:text="MH/s" />
                    </com.google.android.material.textfield.TextInputLayout>`

`    <style name="actStyle" parent="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.ExposedDropdownMenu">
        <item name="boxBackgroundColor">@color/cardBackground</item>
        <item name="boxCornerRadiusTopStart">@dimen/card_corner_small</item>
        <item name="boxCornerRadiusTopEnd">@dimen/card_corner_small</item>
        <item name="boxCornerRadiusBottomStart">@dimen/card_corner_small</item>
        <item name="boxCornerRadiusBottomEnd">@dimen/card_corner_small</item>
        <item name="boxStrokeWidth">0dp</item>
        <item name="boxStrokeWidthFocused">0dp</item>
        <item name="android:layout_marginBottom">@dimen/x10dp</item>
        <item name="materialThemeOverlay">@style/acteStyle</item>
    </style>

    <style name="acteStyle" parent="@style/Widget.MaterialComponents.TextInputLayout.FilledBox.ExposedDropdownMenu">
        <item name="android:textColorPrimary">@color/text</item>
    </style>`

**Comment by drchen** [comment] 2021-10-01 15:36
I cannot reproduce the issue. Can you provide a screenshot (before/after) to better explain the issue?

**Comment by drchen** [comment] 2021-11-02 20:29
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:29 UTC
Labels: bug, Need more info
