### ISSUE TITLE
[catalog-demo] The main screen is cropped after return from feature screen

### ISSUE THREAD

**Issue by gabin8** [material-components/material-components-android#1198] opened 2020-04-09 12:57 UTC
**Description:** 
The list is not scrollable to bottom, after pressing item and getting back .
Steps to reproduce:
1. Open app's main activity.
2. Scroll to bottom.
3. Click "Transitions" item.
4. Press back (hardware or arrow).
5. See result - the bottom items are cut, the list is not scrollable to bottom.

**Expected behavior:** 
   The list shouldn't be cropped after getting back from the transitions fragment. The list position should remain the same.

**Video with the bug:** 
https://www.dropbox.com/s/3mdz4dgay5fpyes/device-2020-04-09-155543.mp4?dl=0

**Android API version:** Android 6.0

**Material Library version:** 1.2.0-alpha05

**Device:** Prestigio PSP3528DUO, Screen size 480x854, density - tvdpi

**Comment by dsn5ft** [comment] 2020-08-03 12:54
Closing as duplicate of https://github.com/material-components/material-components-android/issues/1558 which provides a little more information. Hoping to take a look at this soon, but if anyone has any ideas on what may be happening or when this started happening, feel free to comment there.

**Closed by dsn5ft** 2020-08-03 12:54 UTC
Labels: bug
