### ISSUE TITLE
[MaterialTimePicker] Keyboard is not hidden after switching from keyboard to clock mode

### ISSUE THREAD

**Issue by wedokedo** [material-components/material-components-android#3436] opened 2023-06-05 08:25 UTC
After clicking the clock icon in the MaterialTimePickerDialog the keyboard remains open which is annoying for the users . In the clock mode the keyboard is not needed and it should be hidden as soon as the clock screen appears .

**Comment by afohrman** [comment] 2023-06-05 21:42
I'm not able to reproduce this; in the Catalog app, the keyboard is hidden when the clock button is pressed. Is there anything unique about your setup? What API levels are you seeing this on? Any extra code you're using?

Could you please provide a code sample to help us reproduce?

**Comment by paulfthomas** [comment] 2023-06-06 14:44
Fixed by https://github.com/material-components/material-components-android/commit/4032a741127b4715c3bbcd4cab08494b39ae5bdb

**Closed by paulfthomas** 2023-06-06 14:44 UTC
Labels: bug, Widget: TimePicker
