### ISSUE TITLE
[MaterialDatePicker] Switching mode causes crash

### ISSUE THREAD

**Issue by mwrod** [material-components/material-components-android#1946] opened 2020-12-21 16:02 UTC
**Description:**
Following workflow only crashes on my API 30 emulator:
1. Opened MaterialDatePicker
2. Switched to Text-Mode
3. Switched to Calendar-Mode
4. Half of Calendar not visible and click on any date causes crash

<details>
  <summary>Stack Trace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setEnabled(boolean)' on a null object reference
        at com.google.android.material.datepicker.MonthAdapter.updateSelectedState(MonthAdapter.java:164)
        at com.google.android.material.datepicker.MonthAdapter.updateSelectedStateForDate(MonthAdapter.java:157)
        at com.google.android.material.datepicker.MonthAdapter.updateSelectedStates(MonthAdapter.java:140)
        at com.google.android.material.datepicker.MonthsPagerAdapter.onBindViewHolder(MonthsPagerAdapter.java:114)
        at com.google.android.material.datepicker.MonthsPagerAdapter.onBindViewHolder(MonthsPagerAdapter.java:38)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7228)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7308)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6175)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6441)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6281)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6277)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4277)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3654)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2201)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

</details>

<img src="https://user-images.githubusercontent.com/9077206/102795631-5cc8d180-43ad-11eb-9147-6f2c5486df33.gif" alt="Issue" width="320" height="569">

**Expected behavior:** The full calendar is still visible after switching modes.

**Android API version:** 30

**Material Library version:** 1.3.0-beta01

**Device:** Nexus 6 Emulator

**Comment by IgorGanapolsky** [comment] 2020-12-30 14:12
According to your stacktrace, the TextView is null:
`'void android.widget.TextView.setEnabled(boolean)'`

Which TextView is your code inflating?

**Comment by mwrod** [comment] 2020-12-30 17:56
> According to your stacktrace, this TextView is null:
> `'void android.widget.TextView.setEnabled(boolean)'`
> 
> Which TextView is your code inflating?

It should not be any TextView in my code. The Exception is coming from `com.google.android.material.datepicker.MonthAdapter`.

**Comment by IgorGanapolsky** [comment] 2020-12-31 15:48
@mwrod Are you able to reproduce this crash?  I am running this latest repo sample, and `MonthAdapter.updateSelectedState` gets called successfully every time.

**Comment by mwrod** [comment] 2021-01-01 01:50
@IgorGanapolsky Do you go through the same workflow I described in the video? Do you use a device with Android SDK 30?

**Comment by IgorGanapolsky** [comment] 2021-01-03 19:18
> @IgorGanapolsky Do you go through the same workflow I described in the video? Do you use a device with Android SDK 30?

I went through same workflow.  My device is running SDK 30.  What is `setTheme(R.style.DatePickerStyle)`?

**Comment by gaurav133** [comment] 2021-06-29 18:40
@mwrod Experienced the same crash however not sure of the steps because it occurred once. Also, for the visibility issue, if you close the keyboard first before switching to calendar view, it works fine. But in the normal scenario, visibility issue is 100% reproducible.

**Comment by drchen** [comment] 2021-07-20 20:36
I think the crash has been fixed by https://github.com/material-components/material-components-android/pull/1944

**Closed by drchen** 2021-07-20 20:36 UTC
Labels: bug
