### ISSUE TITLE
[MaterialDatePicker] Date Range Selector returns off by 1 value

### ISSUE THREAD

**Issue by froriz5** [material-components/material-components-android#967] opened 2020-01-31 21:48 UTC
**Description:** 
The Date Range Picker is returning an off-by-1 value in the `MaterialPickerOnPositiveButtonClickListener`. Meaning if the range `January 1st 2020 - January 31st 2020` is selected, the values returned are:
`December 31st 2019 - January 30th 2020`

**Expected behavior:** 
When using a `MaterialDatePicker.Builder.dateRangePicker()`, and setting the `addOnPositiveButtonClickListener`, we should receive the range selected from the picker as a `Pair<Long, Long>` representing the lower and upper bound of the range selected.

**Source code:** 
```
val picker = MaterialDatePicker.Builder.dateRangePicker().apply {
     setTitleText("Select Dates")
  
     setTheme(R.style.ThemeOverlay.MaterialComponents.MaterialCalendar)
}.build()

picker.addOnPositiveButtonClickListener { range ->
    range.first?.let { lowerBound ->
        range.second?.let { upperBound ->
            val low = Calendar.getInstance().apply { timeInMillis = lowerBound }
            val high = Calendar.getInstance().apply { timeInMillis = upperBound }

             // low will be the lower bound date - 1
             // high will be the upper bound date - 1
          }
      }
}
picker.show(supportFragmentManager, "")
```

**Android API version:** 10 Q

**Material Library version:** 1.2.0-alpha04

**Device:** Pixel 2

**Comment by pekingme** [comment] 2020-01-31 21:53
Thanks for reporting. It may be related to #882. We are working on the solution to it. Will test this as well when it's ready.

**Comment by froriz5** [comment] 2020-02-03 15:50
Update on this ticket.
It looks like I can get the correct values by first converting it to a `Calendar` object with the UTC timezone and pulling the `year, month, and day` directly out of it.

```
picker.addOnPositiveButtonClickListener { range ->
    range.first?.let { lowerBound ->
        range.second?.let { upperBound ->
            val low = Calendar.getInstance(TimeZone.getTimeZone("UTC")).apply { timeInMillis = lowerBound }
            val high = Calendar.getInstance(TimeZone.getTimeZone("UTC")).apply { timeInMillis = upperBound }

             val lowYear = low.get(Calendar.YEAR)
             val lowMonth = low.get(Calendar.MONTH) + 1 // 0 index of months
             val lowDay = low.get(Calendar.DAY_OF_MONTH)

             val highYear = high.get(Calendar.YEAR)
             val highMonth = high.get(Calendar.MONTH) + 1 // 0 index of months
             val highDay = high.get(Calendar.DAY_OF_MONTH)
          }
      }
}
```

If I try to get this data using the given milliseconds returned by the listener, that it still has that off by 1 problem.

Cc. @pekingme

**Comment by ikim24** [comment] 2020-02-03 18:56
Closing this as a duplicate of #882

**Closed by ikim24** 2020-02-03 18:56 UTC
Labels: bug, duplicate
