### ISSUE TITLE
[TextInputLayout] prefixText position is wrong when endIconMode is set

### ISSUE THREAD

**Issue by sdex** [material-components/material-components-android#2089] opened 2021-02-21 10:09 UTC
**Description:** prefixText position is wrong when endIconMode is set
![Screenshot from 2021-02-21 12-06-03](https://user-images.githubusercontent.com/3196011/108621762-4dade080-743d-11eb-9898-73fb2963ba68.png)

**Expected behavior:** Prefix text should be properly aligned.
![Screenshot from 2021-02-21 12-06-18](https://user-images.githubusercontent.com/3196011/108621773-5b636600-743d-11eb-8caf-a1569a7142d8.png)

**Source code:** 
```
                <com.google.android.material.textfield.TextInputLayout
                    android:id="@+id/contact_container"
                    style="@style/Widget.Design.TextInputLayout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_margin="8dp"
                    app:endIconDrawable="@drawable/ic_call"
                    app:endIconMode="custom"
                    app:prefixText="+65"
                    app:prefixTextAppearance="@style/TextAppearance.AppCompat.Medium">

                    <com.google.android.material.textfield.TextInputEditText
                        android:id="@+id/contact"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:hint="Contact"
                        tools:text="61234561"
                        android:inputType="phone" />

                </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** any

**Material Library version:** 1.3.0

**Device:** any + Android Studio layout editor

**Comment by felipeska** [comment] 2021-03-24 15:04
Hello, I have the same issue, I'm curious about this because I'm not using `endIconMode`

![error](https://user-images.githubusercontent.com/613443/112332625-e5def580-8c87-11eb-89b5-56b5c7cf9084.png)

First field was input manually.

Second field was filled using `setText`

**Comment by felipeska** [comment] 2021-03-24 17:14
hello @sdex this could be related wit the issue #773 

This fix worked for me:

```kotlin
inputLayout.prefixTextView.updateLayoutParams {
    height = ViewGroup.LayoutParams.MATCH_PARENT
}
inputLayout.prefixTextView.gravity = Gravity.CENTER
```
![112352191-90f7ab00-8c98-11eb-8e59-373120093320](https://user-images.githubusercontent.com/613443/112354178-6c9cce00-8c9a-11eb-9424-1ad7be52439d.png)

**Comment by sdex** [comment] 2021-03-24 17:23
@felipeska thanks for sharing this. 
I used the dirty workaround, wrapped it with FrameLayout, and put ImageButton at the end.

**Comment by nikitoSha** [comment] 2021-06-06 14:13
> 
> 
> hello @sdex this could be related wit the issue #773
> 
> This fix worked for me:
> 
> ```kotlin
> inputLayout.prefixTextView.updateLayoutParams {
>     height = ViewGroup.LayoutParams.MATCH_PARENT
> }
> inputLayout.prefixTextView.gravity = Gravity.CENTER
> ```
> 
> ![112352191-90f7ab00-8c98-11eb-8e59-373120093320](https://user-images.githubusercontent.com/613443/112354178-6c9cce00-8c9a-11eb-9424-1ad7be52439d.png)

what? prefixTextView has private access.

**Comment by drchen** [comment] 2022-05-18 13:42
Looks like a duplicate of #1773

**Closed by drchen** 2022-05-18 13:42 UTC
Labels: bug, Widget: TextField
