### ISSUE TITLE
Second TextInputLayout / TextInputEditText is not working correctly. This behaviour happening in all devices 

### ISSUE THREAD

**Issue by JobGetabu** [material-components/material-components-android#2264] opened 2021-06-22 21:57 UTC
In a dialogue, the second edit text does not work correctly. It does not add texts from keyboard.

<img src ="https://user-images.githubusercontent.com/22516895/123004428-408a0980-d3bd-11eb-86e7-318ff2753a40.png" width=250 height = 500 />

**Expected behavior:** Screenshots and/or description of expected behavior

 ```
                    <com.google.android.material.textfield.TextInputLayout
                        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="16dp"
                        android:layout_marginTop="16dp"
                        android:layout_marginEnd="16dp"
                        android:layout_weight="1"
                        android:hint="Enter item name here"
                        app:boxCornerRadiusBottomEnd="16dp"
                        app:boxCornerRadiusBottomStart="16dp"
                        app:boxCornerRadiusTopEnd="16dp"
                        app:boxCornerRadiusTopStart="16dp">

                        <com.google.android.material.textfield.TextInputEditText
                            android:id="@+id/item_name"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:inputType="textShortMessage"
                            android:lines="1"
                            android:textColor="@color/textPrimaryColor"
                            android:textSize="16sp" />

                    </com.google.android.material.textfield.TextInputLayout>

                    <com.google.android.material.textfield.TextInputLayout
                        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="16dp"
                        android:layout_marginTop="16dp"
                        android:layout_marginEnd="16dp"
                        android:layout_weight="1"
                        app:boxCornerRadiusBottomEnd="16dp"
                        app:boxCornerRadiusBottomStart="16dp"
                        app:boxCornerRadiusTopEnd="16dp"
                        app:boxCornerRadiusTopStart="16dp"
                        app:prefixText="KES"
                        app:suffixText="/=">

                        <com.google.android.material.textfield.TextInputEditText
                            android:id="@+id/item_amount"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:hint="Enter item amount here"
                            android:inputType="numberDecimal"
                            android:textColor="@color/textPrimaryColor"
                            android:textSize="16sp" />

                    </com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** Android API version here
API: 28 , 29, 30

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

tried also in version 1.3

implementation "com.google.android.material:material:1.4.0-rc01"

**Device:** Device on which the bug was encountered here
Pixel 4

**Comment by hunterstich** [comment] 2021-06-23 15:08
Hey @JobGetabu ,

Are you able to add a sample so we can reproduce this issue?

**Comment by drchen** [comment] 2022-01-12 21:23
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-01-12 21:23 UTC
Labels: bug, Need more info
