### ISSUE TITLE
[MaterialToolbar] The color of the subtitle is wrong, which is different from the color configured in the theme style

### ISSUE THREAD

**Issue by xiaoyvyv** [material-components/material-components-android#3246] opened 2023-02-18 08:07 UTC
**Description:** 
The color of the subtitle is wrong, which is different from the color configured in the theme style

**Expected behavior:** 

###  `The text color of this subtitle should be red, but now it is black.`

```
<item name="colorOnSurfaceVariant">@android:color/holo_red_light</item>
```

![图片](https://user-images.githubusercontent.com/29088158/219849134-de474b94-cc4b-4596-88f7-ad6c2bf71433.png)

**Source code:** 
```xml

    <application
        android:name=".MainApplication"
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:extractNativeLibs="true"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.ManagerTool"
        tools:targetApi="31">
    </application>

    <style name="Base.Theme.ManagerTool" parent="Theme.Material3.DayNight.NoActionBar">
        <item name="colorPrimary">@color/md_theme_light_primary</item>
        <item name="colorOnPrimary">@color/md_theme_light_onPrimary</item>
        <item name="colorPrimaryContainer">@color/md_theme_light_primaryContainer</item>
        <item name="colorOnPrimaryContainer">@color/md_theme_light_onPrimaryContainer</item>
        <item name="colorSecondary">@color/md_theme_light_secondary</item>
        <item name="colorOnSecondary">@color/md_theme_light_onSecondary</item>
        <item name="colorSecondaryContainer">@color/md_theme_light_secondaryContainer</item>
        <item name="colorOnSecondaryContainer">@color/md_theme_light_onSecondaryContainer</item>
        <item name="colorTertiary">@color/md_theme_light_tertiary</item>
        <item name="colorOnTertiary">@color/md_theme_light_onTertiary</item>
        <item name="colorTertiaryContainer">@color/md_theme_light_tertiaryContainer</item>
        <item name="colorOnTertiaryContainer">@color/md_theme_light_onTertiaryContainer</item>
        <item name="colorError">@color/md_theme_light_error</item>
        <item name="colorErrorContainer">@color/md_theme_light_errorContainer</item>
        <item name="colorOnError">@color/md_theme_light_onError</item>
        <item name="colorOnErrorContainer">@color/md_theme_light_onErrorContainer</item>
        <item name="android:colorBackground">@color/md_theme_light_background</item>
        <item name="colorOnBackground">@color/md_theme_light_onBackground</item>
        <item name="colorSurface">@color/md_theme_light_surface</item>
        <item name="colorOnSurface">@color/md_theme_light_onSurface</item>
        <item name="colorSurfaceVariant">@color/md_theme_light_surfaceVariant</item>
        <item name="colorOnSurfaceVariant">@android:color/holo_red_light</item>            <<-------- This line.
        <item name="colorOutline">@color/md_theme_light_outline</item>
        <item name="colorOnSurfaceInverse">@color/md_theme_light_inverseOnSurface</item>
        <item name="colorSurfaceInverse">@color/md_theme_light_inverseSurface</item>
        <item name="colorPrimaryInverse">@color/md_theme_light_inversePrimary</item>
    </style>

    <style name="Theme.ManagerTool" parent="Base.Theme.ManagerTool">
        
    </style>


<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            app:layout_constraintTop_toTopOf="parent"
            app:subtitle="Subtitle"
            app:title="@string/file_list_title" />
    </com.google.android.material.appbar.AppBarLayout>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 33
**Material Library version:** 1.9.0-alpha01)

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by xiaoyvyv** [comment] 2023-02-21 15:27
![图片](https://user-images.githubusercontent.com/29088158/220386068-7f7f8a5c-dcd7-4b16-8ced-8563184b2747.png)
![图片](https://user-images.githubusercontent.com/29088158/220386180-c3af16d3-2b56-411f-9e12-09edc8c2d143.png)

I checked the theme configuration items and found that the subtitle color of the `MaterialToolbar` configured in `toolbarSurfaceStyle`, but there is no using of this style in `Toolbar` or `MaterialToolbar`.

```gradle
implementation 'com.google.android.material:material:1.9.0-alpha01'
```

**Comment by hunterstich** [comment] 2023-02-21 15:49
Thanks for the quick reply.

1) Are you using dynamic color? That might be overriding the colorOnSurfaceVariant that you're setting
2) In you're layout, I think you need to set `style="?attr/toolbarSurfaceStyle` on your `MaterialToolbar` 

Let me know if that works

**Comment by xiaoyvyv** [comment] 2023-02-21 15:57
> 感谢您的快速回复。
> 
>     1. 您使用的是动态颜色吗？  这可能会覆盖您设置的 colorOnSurfaceVariant
> 
>     2. 在你的布局中，我认为你需要设置 `style="?attr/toolbarSurfaceStyle`在你的 `MaterialToolbar`
> 
> 
> 让我知道这是否有效

It's works when add，
![图片](https://user-images.githubusercontent.com/29088158/220394370-54197d0e-f0fe-466d-a705-391a3aa31401.png)
It's works when add, I also know that adding styles manually will be effective, I thought it was a global style bug, 😄

**Comment by xiaoyvyv** [comment] 2023-02-21 16:04
![图片](https://user-images.githubusercontent.com/29088158/220396044-016e0051-4ebe-4ed2-b5a1-4ca04b24e905.png)
![图片](https://user-images.githubusercontent.com/29088158/220396114-6e2afa1c-1ef5-4b12-9d0a-1c53edbd973d.png)
![图片](https://user-images.githubusercontent.com/29088158/220396343-07e9fa9a-56f9-4049-a03f-2892683e06e3.png)


Light theme and Night theme, Both `colorOnSurfaceVariant` items are red, But the color of the subtitle is always black when not set `style="?attr/toolbarSurfaceStyle` in `MaterialToolbar`

**Comment by hunterstich** [comment] 2023-02-21 20:35
Glad that worked for you. Going to go ahead and close this as working as intended but feel free to re-open if you have further questions.

**Closed by hunterstich** 2023-02-21 20:35 UTC
Labels: bug
