### ISSUE TITLE
[MaterialDatePicker.Builder] Text Input Format

### ISSUE THREAD

**Issue by GRRedWings** [material-components/material-components-android#1180] opened 2020-04-03 15:40 UTC
I am looking for 2 things. 1 would like to be able to disable the text input format button. So I can't toggle between calendar and text input.

2. if I have to display the text input, how can I make sure it's in the format I want.  Maybe the library handles locale, but I can't always be sure that the device locale will match the locale I want displayed.

**Describe the solution you'd like**
I would like 2 configuration items.  
similar to builder.setSelection() I would like the following

- builder.disableTextEntry() or builder.lockView( enum CALENDAR/TEXT)
- builder.setTextFormat(SimpleDateFormat inputFormat)

**Describe alternatives you've considered**
I think the alternative is to just live with what is there. I don't see many others.

**Comment by gabrielemariotti** [comment] 2020-07-31 17:57
For the point 1. duplicate of #1380

**Comment by dsn5ft** [comment] 2020-07-31 21:27
Point 2 duplicate https://github.com/material-components/material-components-android/issues/774

**Closed by dsn5ft** 2020-07-31 21:27 UTC
Labels: feature request
