### ISSUE TITLE
[tablayout] doesn't support data update without glitching

### ISSUE THREAD

**Issue by CoreFloDev** [material-components/material-components-android#2041] opened 2021-02-05 13:25 UTC
**Description:** when having a few tab with a viewpager when a data update is send to the adapter the data will move to a random position instead of staying at the current selected one

**Expected behaviour:** The selected tab doesn't move when there is a data update

if you need more details please see https://stackoverflow.com/questions/43056039/tablayout-scrolls-to-unkown-position-after-calling-notifydatasetchanged-on-pager/43411732 that describe the exact same issue

**Android API version:** Any

**Material Library version:** Material Android Library version 1.3.0

**Comment by drchen** [comment] 2021-11-04 18:18
I think it's a duplicate of #1999 

Closing this one to track the issue in one place.

**Closed by drchen** 2021-11-04 18:18 UTC
Labels: bug, Widget: Tab
