### ISSUE TITLE
[Chip] Can't check a chip with signleSelection=true

### ISSUE THREAD

**Issue by adelcsc** [material-components/material-components-android#2369] opened 2021-09-12 06:31 UTC
**Description:** I can't check a chip when the attribute singleSelection of the ChipGroup is set to **true**

**Source code:** 
![image](https://user-images.githubusercontent.com/26345490/132974507-9abae76f-360a-493a-ad00-d8ad5f9d4031.png)

`questionsAnswersList` is the ChipGroupView.

with isSingleSelection=false
![image](https://user-images.githubusercontent.com/26345490/132974600-589e3167-76d9-4db3-8fb4-565ed3a5df7d.png)

with isSingleSelection=true
![image](https://user-images.githubusercontent.com/26345490/132974619-f7d61ad1-d56f-4021-9681-1630ce5108cb.png)

**Android API version:** 30

**Material Library version:** 1.4.0

**Device:** Android Emulator Target: google_apis_playstore [Google Play] (API level 30)

**Comment by h3x3ncr7pt** [comment] 2021-09-22 01:50
Perhaps your chips are added statically in xml, im adding them to the ChipGroup programmatically, check the code in the image.

**Comment by josefigueroa168** [comment] 2021-09-22 17:13
I entered them programatically. When singleSelection is set to true, the last chip is checked, if it is set to false, all chips are checked. See the Java code I used below:

```Java
private void initChipGroup(ChipGroup chipGroup) {
  chipGroup.removeAllViews();
  chipGroup.setSingleSelection(true);
  String[] textArray = {"foo", "bar"};
  for (String text : textArray) {
    Chip chip = (Chip) getLayoutInflater().inflate(R.layout.chip, chipGroup, false);
    chip.setText(text);
    chip.setCheckable(true);
    chip.setChecked(true);
    chipGroup.addView(chip);
  }
}
```

![Screen Shot 2021-09-22 at 1 06 12 PM](https://user-images.githubusercontent.com/25285010/134389856-fe6ec99a-e773-4f22-8e33-975fc1f6f09d.png)

**Comment by h3x3ncr7pt** [comment] 2021-09-22 21:56
You're inflating the ChipView but im not, im adding ChipView object directly to the ChipGroup via addView method

**Comment by drchen** [comment] 2022-02-09 20:59
Hi I tested our implementation with the below code, which I think is equivalent to your kotlin implementation:
```
  private void initChipGroup(ChipGroup chipGroup) {
    chipGroup.removeAllViews();
    chipGroup.setSingleSelection(true);
    String[] textArray = {"foo", "bar"};
    for (String text : textArray) {
      Chip chip = new Chip(getContext());
      chip.setText(text);
      chip.setCheckable(true);
      chip.setId(ViewCompat.generateViewId());
      chipGroup.addView(chip);
    }
    for (int i = 0; i < chipGroup.getChildCount(); i++) {
      ((Chip) chipGroup.getChildAt(i)).setChecked(true);
    }
  }
```

I could not reproduce the issue. Since we've refactored our chip group implementation recently, can you try to cherry-pick https://github.com/material-components/material-components-android/commit/f3c6430f94bb7f82afc740e5545fd6302e9bf3aa and see if it fixes your issue?

**Comment by drchen** [comment] 2022-02-22 16:32
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-22 16:32 UTC
Labels: bug, Need more info, Widget: Chip
