### ISSUE TITLE
[BottomAppBar] performHide/performShow not working

### ISSUE THREAD

**Issue by dmitrypokrasov** [material-components/material-components-android#1361] opened 2020-06-02 13:59 UTC
Hello! For some reason, hiding the menu does not work.

xml:
![image](https://user-images.githubusercontent.com/56834239/83527677-27d05c80-a4f9-11ea-88b4-a1602d0ec6da.png)

style:
![image](https://user-images.githubusercontent.com/56834239/83526816-0884ff80-a4f8-11ea-9fb6-5447ed568ae8.png)

code:
![image](https://user-images.githubusercontent.com/56834239/83527114-674a7900-a4f8-11ea-93bd-06dee2539fbd.png)

version: 'com.google.android.material:material:1.2.0-beta01'

result:
![image](https://user-images.githubusercontent.com/56834239/83527607-10916f00-a4f9-11ea-8bd5-cd207ac1a5b4.png)

**Comment by drchen** [comment] 2021-11-02 20:16
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:16 UTC
Labels: bug, Need more info
