### ISSUE TITLE
[HeaderScrollingViewBehavior] Incorrect heightMeasureSpec passed to onMeasureChild()

### ISSUE THREAD

**Issue by h6ah4i** [material-components/material-components-android#1821] opened 2020-10-25 12:52 UTC
**Description:**

Incorrect `MeasureSpec` can be created when 

https://github.com/material-components/material-components-android/blob/cf9027f0985a9f01fa00b5ce0a60b673d42aa9dc/lib/java/com/google/android/material/appbar/HeaderScrollingViewBehavior.java#L89

**Expected behavior:** Clip to `0` if the calculated height value is negative before creating a MeasureSpec.

```diff
        int height = availableHeight + getScrollRange(header);  // !!! ex. height = 0
        int headerHeight = header.getMeasuredHeight();    // !!! ex. headerHeight = 100
        if (shouldHeaderOverlapScrollingChild()) {
          child.setTranslationY(-headerHeight);
        } else {
          height -= headerHeight;  // !!! ex.) height = 0 - 100 = -100
        }
        final int heightMeasureSpec =
            View.MeasureSpec.makeMeasureSpec(  // !!! NOTE: makeMeasureSpec doesn't take care about negative size
-               height,
+               Math.max(0, height),
                childLpHeight == ViewGroup.LayoutParams.MATCH_PARENT
                    ? View.MeasureSpec.EXACTLY
                    : View.MeasureSpec.AT_MOST);

        // Now measure the scrolling view with the correct height
        parent.onMeasureChild(
            child, parentWidthMeasureSpec, widthUsed, heightMeasureSpec, heightUsed);
```

**Android API version:** Android API Level 30

**Material Library version:** 1.1.2

**Device:** Emulator

**Comment by drchen** [comment] 2022-04-27 20:31
Hi so the case you pointed out cannot actually happen unless you are overriding getScrollRange() and returning weird values (i.e. a scroll range less than the header's measured height.)

In the default implementation or the subclass defined in AppBarLayout, getScrollRange() is guaranteed to be equal to or larger than header's measured height, so we don't really need negative value check here. 

Since returning a scroll range smaller than its height itself seems like an invalid behavior, I don't really feel we should bother adding a check here.

I'll close the issue as not reproducible.

**Closed by drchen** 2022-04-27 20:31 UTC
Labels: bug, Widget: TopAppBar
