### ISSUE TITLE
[ProgressIndicator] Indeterminate animation does not resume after turning screen off/on

### ISSUE THREAD

**Issue by akuchinke** [material-components/material-components-android#2350] opened 2021-09-01 11:05 UTC
**Description:** 
When turning the device screen off and back on (e.g. pressing the power button), the inderminate animation of both circular and linear `ProgressIndicator`s does not resume.

**Expected behavior:**
 The animation should resume.

**Steps to reproduce**  
Install the catalog app, head to the ProgressIndicator samples, view any containing an indeterminate ProgressIndicator, press the power button and turn the screen back on.

**Android API version:** 
Tested on 10 and 11, possibly more

**Material Library version:** 
All

**Device:**
Oneplus 7T
Oneplus 5T
Galaxy Tab A10.1

*Not* reproducable on emulators. (Unfortunately I was not able to pinpoint why exactly)

I think the root cause is after the screen comes back on, the system calls
https://github.com/material-components/material-components-android/blob/209bad3299c9317601bebd53e84bd5340a5b9ee2/lib/java/com/google/android/material/progressindicator/BaseProgressIndicator.java#L264

which in turn calls

https://github.com/material-components/material-components-android/blob/209bad3299c9317601bebd53e84bd5340a5b9ee2/lib/java/com/google/android/material/progressindicator/IndeterminateDrawable.java#L98
with the `animate` parameter set to `false`

Per javadocs the `animate` parameter is  supposed to control whether the visibility change should be done using the show/hide animation but is interpreted as "should the entire indeterminate animation run"
here
https://github.com/material-components/material-components-android/blob/209bad3299c9317601bebd53e84bd5340a5b9ee2/lib/java/com/google/android/material/progressindicator/IndeterminateDrawable.java#L109

**Comment by paulkugaev** [comment] 2021-09-01 23:24
@akuchinke Just checked on my Pixel 3 runnning Android 12 beta 4.2 and latest catalog app (with material components 1.5.0-alpha03). Not reproducable

**Comment by drchen** [comment] 2021-10-01 14:53
Seems like a duplicate of https://github.com/material-components/material-components-android/issues/2355. Let's move the discussion there for tracking purpose. : )

**Closed by drchen** 2021-10-01 14:53 UTC
Labels: bug
