### ISSUE TITLE
[ViewPager2] does not support direct child views

### ISSUE THREAD

**Issue by FarhadSmile** [material-components/material-components-android#2232] opened 2021-06-01 09:11 UTC
Material library version 1.4.0-beta01
Tested on Android 10

Xml: 

`
    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent" >

        <androidx.viewpager2.widget.ViewPager2
            android:id="@+id/view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:translationZ="@dimen/dimen_30dp"
            android:nestedScrollingEnabled="true"
            android:background="@drawable/xx"/>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
`

 private val PAGES = arrayOf(
            { TEST1Fragment() },
            { TEST2Fragment() },
            { TEST3Fragment() }
        )

   inner class TestAdapter(fragment: Fragment) : FragmentStateAdapter(fragment) {
        override fun createFragment(position: Int) = PAGES[position].invoke()
        override fun getItemCount() = PAGES.size
    }

viewpager.adapter = Adapter(this)

Issues:

java.lang.Throwable: java.lang.IllegalStateException: ViewPager2 does not support direct child views
	at androidx.viewpager2.widget.ViewPager2.onViewAdded(ViewPager2.java:489)
	at android.view.ViewGroup.dispatchViewAdded(ViewGroup.java:5037)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5209)
	at android.view.ViewGroup.addView(ViewGroup.java:4984)
	at android.view.ViewGroup.addView(ViewGroup.java:4924)
	at androidx.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:138)
	at androidx.transition.TransitionUtils.copyViewImage(TransitionUtils.java:64)
	at androidx.transition.Visibility.onDisappear(Visibility.java:401)
	at androidx.transition.Visibility.createAnimator(Visibility.java:257)
	at androidx.transition.Transition.createAnimators(Transition.java:747)
	at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:480)
	at androidx.transition.Transition.playTransition(Transition.java:1821)
	at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:301)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2784)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1748)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7789)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:798)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

	at uk.smileitsolutions.atom.CrashActivity.onCreate(CrashActivity.kt:28)
	at android.app.Activity.performCreate(Activity.java:7825)
	at android.app.Activity.performCreate(Activity.java:7814)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5280)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5188)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by drchen** [comment] 2021-06-18 19:34
Close this because ViewPager2 is not a Material component. Also this looks like working as intended.

If you have any further questions, please refer to:
https://stackoverflow.com/questions/63863320/viewpager2-and-fragments

**Closed by drchen** 2021-06-18 19:34 UTC
Labels: bug
