### ISSUE TITLE
[Bottom Appbar] Broken fab animation when alignmentMode is end

### ISSUE THREAD

**Issue by Skrilltrax** [material-components/material-components-android#602] opened 2019-09-14 19:13 UTC
**Description:** Whenever fabAlignmentMode is set to "end" and the animation is set to scale from 0.0 to 1.0, the translate animation from centre to the end also takes place with the scale animation. This is not an issue when the fabAlignmentMode is set to "center". Attached the gif below with both the modes.

**Expected behavior:** 
<img src="https://media.giphy.com/media/TH74IloqjNMIwmqOwQ/giphy.gif" width="400" height="800" />

**Source code:** https://github.com/Skrilltrax/BottomAppbarTest

**Android API version:** Tested on 29

**Material Library version:** Tested on 1.1.0-alpha10 and 1.1.0-alpha09

**Device:** Xiaomi Poco F1

**Comment by drchen** [comment] 2022-02-07 19:35
Is this still reproducible? I cannot reproduce this on my end.

**Comment by drchen** [comment] 2022-03-03 19:25
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-03 19:25 UTC
Labels: bug, Need more info
