### ISSUE TITLE
[TextInputLayout] Hint text over outline border when boxCornerRadiusTopStart is set

### ISSUE THREAD

**Issue by VCDo** [material-components/material-components-android#2362] opened 2021-09-08 14:24 UTC
**Description:** 
The hint text is over the outline border on the left when boxCornerRadiusTopStart is set. It was fine until I updated the material lib from 1.3.0 to 1.4.0. Could also reproduce this with the latest 1.5.0-alpha03 version.

### ### 
**Expected behavior:** 

![TextInputLayout_hint_expected](https://user-images.githubusercontent.com/2690977/132525077-7c45d65b-c818-4e2d-a8c4-dfa3d66a7cc8.jpg)

Problem:

![TextInputLayout_hint_problem](https://user-images.githubusercontent.com/2690977/132525459-c67bdc57-52a1-445e-96fd-d2d326a7f73c.jpg)

**Source code:** 

	<com.google.android.material.textfield.TextInputLayout
	    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
	    android:layout_width="match_parent"
	    android:layout_height="wrap_content"
	    android:padding="16dp"
	    app:boxCornerRadiusBottomEnd="26dp"
	    app:boxCornerRadiusBottomStart="26dp"
	    app:boxCornerRadiusTopEnd="26dp"
	    app:boxCornerRadiusTopStart="26dp"
	    app:boxStrokeWidth="1dp"
	    app:boxStrokeWidthFocused="1dp">

	    <com.google.android.material.textfield.TextInputEditText
	        android:layout_width="match_parent"
	        android:layout_height="wrap_content"
	        android:hint="HINT" />

	</com.google.android.material.textfield.TextInputLayout>`

        
**Android API version:**
30.0.2

**Material Library version:**
Tested with 1.4.0 and 1.5.0-alpha03

**Device:**
Xiaomi Mi MIX 2

**Comment by drchen** [comment] 2021-09-22 19:55
Duplicate of #2145

**Closed by drchen** 2021-09-22 19:55 UTC
Labels: bug

**Comment by VinitGrover** [comment] 2022-12-20 07:02
it's because of boxCornerRadiusTopStart, try removing that and see if it works.
