### ISSUE TITLE
[BottomAppBar] performHide() not working after configuration change

### ISSUE THREAD

**Issue by adlotsof** [material-components/material-components-android#1896] opened 2020-11-24 12:19 UTC
I control a bottom app bar in the activity, in some fragments it should be hidden, in some fragments it should be shown. performShow() and performHide() work nicely, the fragments onResume() call a method in the activity and the bottom app bar is either hidden or shown. 

**As soon as i turn the device / emulator, performHide() does not work anymore.**

When checking if bottomAppBar.isShown() its false, even tho the bottom app bar is visible on the screen.

When turning the screen and navigating away from a fragment where the bottom app bar should not be showing to another fragment where it shouldnt be showing, its hidden again, until turning the screen again, but only when calling performShow() before performHide()

```
public void hideShowCallback(int fragmentId){  

   mBottomAppBar.performShow();  

   switch(fragmentId){  
      case 1:  
      case 2: 
      case 3:   
        mBottomAppBar.performHide();  
        break;  
   } 
```
```
@Override  
    public void onResume() { 
        super.onResume(); 
        if(requireActivity() instanceof MainActivity){  
            ((MainActivity) requireActivity()).hideShowCallback(getFragmentsId());  
            Log.d(TAG, "onResume: calling to activity");  
        }  
    }  
```

I tried using various lifecycle methods from the fragment to call back to my Activity, but same result.

**Comment by drchen** [comment] 2022-06-02 19:45
Is this still reproducible? If so can you provide a minimal reproducible app?

**Comment by drchen** [comment] 2022-06-16 19:08
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-06-16 19:08 UTC
Labels: bug, Need more info, Widget: BottomSheet
