### ISSUE TITLE
[BadgeDrawable] [AppBar] Add BadgeDrawable support to top AppBar Menu Icons

### ISSUE THREAD

**Issue by zkovar** [material-components/material-components-android#1658] opened 2020-08-26 13:15 UTC
**Is your feature request related to a problem? Please describe.**
Right now, BadgeDrawable is only supported within `BottomNavigationView` and `TabLayout`. I have a design where we are trying to add a badge indicator to an icon within the top AppBar and am unable to do this.

**Describe the solution you'd like**
Add the relevant `BadgeDrawable` methods that are in `BottomNavigationView` to `MaterialToolbar` class

**Describe alternatives you've considered**
N/A

**Additional context**
If this is agreed upon by your design team, I can spend some time working on building this. Please let me know if this a feature we can support. Thanks!

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by gabrielemariotti** [comment] 2020-08-26 14:30
Duplicate of #1405

**Closed** 2020-08-26 15:13 UTC
Labels: feature request
