### ISSUE TITLE
[MaterialTimePicker] Add TimeValidator to restrict the user to select a time within a range

### ISSUE THREAD

**Issue by hegazy** [material-components/material-components-android#2299] opened 2021-07-13 15:26 UTC
I'm surprised no one had asked for this feature yet maybe I'm missing something here, I need users to be able to select the time within a range for example from 09:00 to 17:59 just like what's there for the MaterialDatePicker [CalendarConstraints](https://developer.android.com/reference/com/google/android/material/datepicker/MaterialDatePicker.Builder#setCalendarConstraints(com.google.android.material.datepicker.CalendarConstraints))

**Describe the solution you'd like**
The times not within the range provided should be disabled and not selectable.

**Describe alternatives you've considered**
An alternative is that I can validate the time after the user presses ok and have him to re-open the dialog to select it again, but not a really great experience!

**Comment by itcherry** [comment] 2021-08-17 14:54
Agree, this feature is needed 100%

**Comment by HardikLohogaonkar** [comment] 2021-08-30 18:04
Agree. Right now there is no such validation. I also added some of the validation like minTime(), maxTime() but still now no response.
(https://github.com/material-components/material-components-android/issues/2294)

**Comment by drchen** [comment] 2022-04-15 18:33
I'll close this as a duplicate of #2106. Let's move the discussion there.

**Closed by drchen** 2022-04-15 18:33 UTC
Labels: feature request, Widget: TimePicker
