### ISSUE TITLE
FloatingActionButton API 16

### ISSUE THREAD

**Issue by squm** [material-components/material-components-android#1288] opened 2020-05-11 13:22 UTC
`     Caused by: java.lang.IllegalStateException: One or more children of this LayerDrawable does not have constant state; this drawable cannot be mutated.
        at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:579)
        at android.graphics.drawable.DrawableContainer.mutate(DrawableContainer.java:414)
        at android.graphics.drawable.StateListDrawable.mutate(StateListDrawable.java:249)
        at androidx.appcompat.widget.ResourceManagerInternal.tintDrawable(ResourceManagerInternal.java:452)
        at androidx.appcompat.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:433)
        at androidx.appcompat.widget.AppCompatBackgroundHelper.applySupportBackgroundTint(AppCompatBackgroundHelper.java:128)
        at androidx.appcompat.widget.AppCompatBackgroundHelper.setSupportBackgroundTintList(AppCompatBackgroundHelper.java:96)
        at androidx.appcompat.widget.AppCompatButton.setSupportBackgroundTintList(AppCompatButton.java:108)
        at com.google.android.material.button.MaterialButton.setSupportBackgroundTintList(MaterialButton.java:264)
        at androidx.core.view.ViewCompat.setBackgroundTintList(ViewCompat.java:2656)
        at androidx.appcompat.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:60)
        at androidx.appcompat.widget.AppCompatButton.<init>(AppCompatButton.java:75)
        at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:195)
        at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:191)
        at com.google.android.material.theme.MaterialComponentsViewInflater.createButton(MaterialComponentsViewInflater.java:57)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:111)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
    	at android.view.LayoutInflater.createViewFromTa
`

**Comment by wcshi** [comment] 2020-05-11 14:43
@squm please provide steps to reproduce your crash along with a small sample app. This bug does not currently contain enough information for us to take action.

**Comment by squm** [comment] 2020-05-12 06:03
just followed Getting Started list, replacing Application Theme `Theme.MaterialComponents` ↔ `Theme.AppCompat` is causing this. Someone figured this out in this SO answer [https://stackoverflow.com/a/52361105/2000057](https://stackoverflow.com/a/52361105/2000057), unfortunately doesn't help

**Comment by leticiarossi** [comment] 2020-05-13 16:05
does following this migration guide help you? https://medium.com/androiddevelopers/migrating-to-material-components-for-android-ec6757795351

If you provide your source code with steps to reproduce the crash we'll be able to understand your issue and provide help.

**Comment by squm** [comment] 2020-05-27 08:37
> does following this migration guide help you? https://medium.com/androiddevelopers/migrating-to-material-components-for-android-ec6757795351

that guide first steps tells to replace Application Theme `Theme.MaterialComponents` ↔ `Theme.AppCompat`. Have you actually seen what you are suggesting

**Comment by consp1racy** [comment] 2020-06-17 19:22
> Have you actually seen what you are suggesting

@squm Did you mean this?

> please provide steps to reproduce your crash along with a **small sample app**

A small sample app that reproduces the issue would be helpful, thanks.

**Comment by drchen** [comment] 2021-11-02 20:15
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:15 UTC
Labels: bug, Need more info
