### ISSUE TITLE
[MaterialDatePicker] Selection header not translated

### ISSUE THREAD

**Issue by AleksandarAleksiev** [material-components/material-components-android#1764] opened 2020-09-29 11:08 UTC
<img width="295" alt="Screenshot 2020-09-29 at 11 55 14" src="https://user-images.githubusercontent.com/38103016/94550907-6fb78400-024c-11eb-9179-d379784db204.png">
**Description:** The MaterialDatepicker selection header is not translated and when no date is selected it is always in English "Selected date" 

**Expected behavior:** Selection header should be translated and there should be an API provided to customise the header text similar to the API provided to set custom title

**Source code:** `public String getHeaderText() {
    return dateSelector.getSelectionDisplayString(getContext());
  }`

**Material Library version:** 1.1.0

**Comment by gabrielemariotti** [comment] 2020-09-29 12:54
Duplicate of #761

**Closed** 2020-09-29 20:40 UTC
Labels: bug
