### ISSUE TITLE
[TabLayout] setScrollPosition is not working correctly

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3101] opened 2022-11-23 16:47 UTC
Calling `setScrollPosition()` with `updateSelectedText = true` and `updateIndicatorPosition = true` doesn't set the indicator to the specified position:
 
<table>
  <tr>
    <th>Actual result</th>
    <th>Expected result</th>
   </tr> 
   <tr>
    <td><img src="https://user-images.githubusercontent.com/82187521/203465186-831dfaca-1778-41b3-b529-cb6c9a92dd30.png" width="270px"></td>
    <td><img src="https://user-images.githubusercontent.com/82187521/203465113-3ee5030a-e626-448e-845f-82437cc9025a.png" width="270px"></td>
  </tr>
</table>

**Material Library version:** 1.8.0-alpha03

**Comment by imhappi** [comment] 2022-11-23 19:42
I believe this is WAI, actually

I took a look; ultimately this is happening because `onLayout` is called before `draw`, and `onLayout` sets the indicator position back to being under what the selected tab is. `setScrollPosition` is purely for visual updates, and does not update the selected tab (see method documentation: `   *Calling this method does not update the selected tab, it is only used for drawing purposes.`)

and it shouldn't be used to select tabs, the method usage is to input the _current_ scroll position (in a scroll container like a viewpager), with an offset of [0-1) to describe how close it is to the next tab. I'm not sure why this method is even public, I suspect it is a remnant of the past as the code is quite old.

To select a tab, you should instead use `selectTab`

**Comment by pubiqq** [comment] 2022-11-23 21:00
I set `updateIndicatorPosition = true` and I should see a visual update of my indicator, shouldn't I?

**Comment by imhappi** [comment] 2022-11-23 22:31
Hmm I see what you mean because that's what a user would expect; however, it's tricky. Technically, `setScrollPosition` is WAI in that it does indeed set the indicator drawable position. However, you're not seeing the indicator updated visually, because before the indicator is redrawn, `onLayout` is called due to the text view being selected, which sets the indicator back to where the selected tab is. I think `setScrollPosition` expects the selected tab to already have been updated before the visual updates

I personally think `setScrollPosition` should be private, because it's confusing and easy to shoot yourself in the foot with it. I It should never be called by itself as it'll update the selected state of the views but won't update TabLayout's selectedTab which keeps the state of which tab is selected. I'll bring this up with the team sometime

**Comment by pubiqq** [comment] 2022-11-24 00:08
If your logic is correct, why do you need `updateIndicatorPosition` at all if it is ignored, and the position of the indicator is updated in `onLayout()` anyway?

I agree, the method has a very unfortunate name, it has a dual purpose, has some problems with documentation, etc. But this method used to work properly, and I think consumers expect it to continue to work or some alternative will be given.

**Comment by imhappi** [comment] 2022-11-24 00:34
Ah I see that the onLayout call isn't expected and is caused by updating the tab visuals to the view selection

I do agree that although this method really shouldn't be being used, the previous behavior should be re-instated, will re-open this issue and look into this more closely after the holidays

**Closed** 2022-12-02 23:39 UTC
Labels: bug, Widget: Tab
