### ISSUE TITLE
[MaterialButton] Theming all TextButtons using borderlessButtonStyle

### ISSUE THREAD

**Issue by unc0ded** [material-components/material-components-android#2281] opened 2021-07-01 17:05 UTC
**Description:** 
The [button theming docs](https://github.com/material-components/material-components-android/blob/master/docs/components/Button.md#theming-buttons) show that theming TextButton globally (on app theme basis) can be done by using `borderlessButtonStyle` and specifying the custom style inheriting `Widget.MaterialComponents.Button.TextButton`.

However, `borderlessButtonStyle` does not apply the style attributes to all TextButtons automatically (TextButtons do inherit attributes specified by `materialButtonStyle`, but not 'borderlessButtonStyle').

<img src="https://user-images.githubusercontent.com/56927116/124154459-27671400-dab3-11eb-8ef2-1711c2678a25.png" width=40%> <img src="https://user-images.githubusercontent.com/56927116/124154467-2930d780-dab3-11eb-9458-3240a9e04b44.png" width=40%>
This means that the style needs to be applied on each and every `TextButton` manually (this works, but is cumbersome if you need all TextButtons to have the same style), which isn't really required according to the docs.

**Expected behavior:**
<img src="https://user-images.githubusercontent.com/56927116/124161372-f38fec80-daba-11eb-809e-cca6199bb672.png" width=50%> (Applied by manually using the style on the Button)

**Source code:**
- `styles.xml`
```
    <!-- Base application theme. -->
    <style name="Theme.Drogon" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        ...
        <item name="borderlessButtonStyle">@style/Widget.App.Button.TextButton</item>
    </style>

    <style name="Widget.App.Button.TextButton" parent="Widget.MaterialComponents.Button.TextButton">
        <item name="android:fontFamily">@font/rubik_bold</item>
        <item name="android:textColor">@color/white</item>
        <item name="android:textAllCaps">false</item>
        <item name="android:minWidth">0dp</item>
        <item name="android:minHeight">0dp</item>
    </style>
```
- Layout xml
```
<androidx.constraintlayout.widget.ConstraintLayout
    ...>
    <LinearLayout
        ...>

        <com.google.android.material.button.MaterialButton
            style="@style/Widget.MaterialComponents.Button.TextButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/contact_us"
            android:textSize="12sp" />

    </LinearLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Android API version:** 30

**Material Library version:** 1.4.0-rc1

**Comment by drchen** [comment] 2021-07-12 18:09
The problem is, there's no way for MaterialButton to know if it's a TextButton or not...

We can add an extra style attribute but it's no simpler than just applying the borderless style directly....

Closed this as infeasible.

**Closed by drchen** 2021-07-12 18:09 UTC
Labels: bug

**Comment by unc0ded** [comment] 2021-07-19 14:31
> The problem is, there's no way for MaterialButton to know if it's a TextButton or not...
> 
> We can add an extra style attribute but it's no simpler than just applying the borderless style directly....
> 
> Closed this as infeasible.

I meant, similar to how applying a style of `Widget.MaterialComponents.Button.OutlinedButton` on the button makes it inherit the theme attributes assigned with `materialButtonOutlinedStyle`, similar can work for Textbutton right? Because that's the way it is mentioned in the docs.

**Comment by drchen** [comment] 2021-07-19 14:36
You mean add a theme attribute for TextButton? Can't you use ?attr/borderlessButtonStyle?

**Comment by unc0ded** [comment] 2021-07-19 14:55
> You mean adding a theme attribute for TextButton? Can't you use ?attr/borderlessButtonStyle?

Yes for now I'm using that. I know it works the same way, in that case maybe the docs can be slightly updated?
