### ISSUE TITLE
[SnackBar] Wrong position when used with translucent navigation bar and CollapsingToolbarLayout

### ISSUE THREAD

**Issue by mxalbert1996** [material-components/material-components-android#1761] opened 2020-09-28 09:36 UTC
**Description:** 
When using translucent navigation bar and `CollapsingToolbarLayout`, SnackBar's marginBottom is not set correctly (using CoordinatorLayout as the parent view).
Removing the `CollapsingToolbarLayout` will solve the problem.
![device-2020-09-28-181922](https://user-images.githubusercontent.com/9391933/94414457-56182d00-01b7-11eb-96f2-8091e6338ceb.png)

**Expected behavior:** 
![device-2020-09-28-182206](https://user-images.githubusercontent.com/9391933/94414715-9ecfe600-01b7-11eb-87ea-a45bd0a854d6.png)

**Source code:**
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".MainActivity">

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <TextView
            android:id="@+id/text_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="8dp" />

    </androidx.core.widget.NestedScrollView>

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:layout_width="match_parent"
            android:layout_height="150dp"
            android:theme="?attr/actionBarTheme"
            app:contentScrim="?attr/colorPrimary"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/action_bar"
                style="?attr/actionBarStyle"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:theme="?attr/actionBarTheme"
                app:layout_collapseMode="pin" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>

    </com.google.android.material.appbar.AppBarLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Android API version:** All versions

**Material Library version:** 1.2.1 / 1.3.0-alpha02

**Device:** Devices with navigation bar

After some debugging, I found the reason which is that `CollapsingToolbarLayout` is consuming `WindowInsets` [here](https://github.com/material-components/material-components-android/blob/a6d788f28e8ffc1c394f5c429a8f9aca159a8e4f/lib/java/com/google/android/material/appbar/CollapsingToolbarLayout.java#L303) and this prevents the [`OnApplyWindowInsetsListener`](https://github.com/material-components/material-components-android/blob/89a1bf883fa614702bb43d2cfa75a38005a42421/lib/java/com/google/android/material/snackbar/BaseTransientBottomBar.java#L402) of `SnackBar` from being called, which is needed to set `marginBottom` correctly.

**Comment by yuriykulikov** [comment] 2021-08-14 23:36
Thank you! I can reproduce this on Pixel as well when switching to "'3 button" navigation bar.

**Comment by drchen** [comment] 2021-10-05 18:02
I can't reproduce the issue. Is this still reproducible with the latest library version? If so, can you provide a minimal reproducible sample app to help us debug?

**Comment by drchen** [comment] 2021-11-09 21:17
I'll close the issue due to no further info available. Please feel free to reopen it if it still happens.

**Closed by drchen** 2021-11-09 21:17 UTC
Labels: bug, Widget: TopAppBar
