### ISSUE TITLE
Viewpager (1) tabs not changing color on dark/light mode switch.

### ISSUE THREAD

**Issue by fat-tire** [material-components/material-components-android#2124] opened 2021-03-11 20:36 UTC
Every element in a view hierarchy changes color dynamically except the viewpager's tabs (the horizontal section over the top that allows you to select between fragments in the view).  This view stubbornly refuses to change.  Using a theme that should be sensitive to the theme changes (as it is for all other views).

On restart, the correct theme appears.

**Comment by drchen** [comment] 2022-06-10 21:13
It looks like WAI?

If the tab views are not auto-recreated by client settings, it should be clients' responsible to update the colors. (The simplest solution is calling `adapter.notifyDataSetChanged()` to recreate all tabs.)

I'll close the issue for now. Feel free to reopen it with a minimal reproducible sample if it's still reproducible and you think it's a Material bug.

**Closed by drchen** 2022-06-10 21:13 UTC
Labels: bug, Widget: Tab

**Comment by fat-tire** [comment] 2022-06-10 21:49
I'm actually now seeing the issue with the toolbar too, not just the viewpager tabs.  Using the latest material3 alpha02 release.  I wouldn't close this.

Also, this problem is related to the TABs (and toolbar) and not the viewpager contents.
