### ISSUE TITLE
[BottomSheet] BottomSheet goes wrong state and whole screen became untouchable 

### ISSUE THREAD

**Issue by adarzulfu** [material-components/material-components-android#1861] opened 2020-11-09 11:28 UTC
**Description:** Full description of issue here
An user interact following order
1-) Initial position = collapsed
2-) start dragging and lets the bottomsheet to get in settling 
3-) user touch the bottomsheet again before settling status ends up 
4-) It is observed that bottomsheet state is expanded or collapsed (but should be dragging) and entire screen is locked down 

**Expected behavior:** Screenshots and/or description of expected behavior
Most important one is screen should not be untouchable user can interact in all circumstances and `onStateChanged` should return true state

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

same behavior of [this issue](https://github.com/material-components/material-components-android/pull/228) plus screen is locked down and can't be touchable so users should reopen the application.
(It seems bug is not fixed on [that pr](https://github.com/material-components/material-components-android/pull/228))

**Android API version:** Android API version here
Android 10 Api 29
**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.3.0-alpha03
**Device:** Device on which the bug was encountered here
Samsung Galaxy S9
To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment] 2020-11-10 16:15
hi @adarzulfu how easily is this reproducible and could you please share a video?

**Comment by adarzulfu** [comment] 2020-11-10 21:00
I couldn't cache the wrong state issue in test environment but I could cache the lock screen error. 

[here the video](https://drive.google.com/file/d/11Rq8YyYRvaSBruAyg1O13MxisEuMfdG2/view?usp=sharing)

**Comment by drchen** [comment] 2022-05-04 21:24
Is this still reproducible?

**Comment by drchen** [comment] 2022-05-25 15:47
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-05-25 15:47 UTC
Labels: bug, Need more info, Widget: BottomSheet
