### ISSUE TITLE
[BottomSheetDialog] Content clipping after orientation change.

### ISSUE THREAD

**Issue by enginegl** [material-components/material-components-android#2358] opened 2021-09-03 09:48 UTC
**Description:** 
This issue was introduced in 1.4.0. Bottom sheet width is not invalidated on orientation change without activity recreation.
When activity has `configChanges=orientation` attribute and BottomSheet has been initialized with screen width more than 640dp bottom sheet content width won't be invalidated after orientation change:

<img src="https://github.com/enginegl/bottom-sheet-issue/blob/master/img/portrait.png?raw=true" width="216" height="456">

Demo project: https://github.com/enginegl/bottom-sheet-issue

**Expected behavior:** 
Bottom sheet width should be invalidated on orientation changes according to `maxWidth` value and actual screen width after orientation change.

**Android API version:** 
Any API version

**Material Library version:**
1.4.0

**Device:**
Android Emulator API 30, Samsung S21 Ultra, Pixel 4 XL, any other device

**Comment by drchen** [comment] 2021-10-01 14:51
I cannot reproduce the issue on my end. Is this still reproducible with the latest library version? If so, can you provide a minimal reproducible example to help us debug? Thank you very much!

**Comment by enginegl** [comment] 2021-10-04 10:49
@drchen, thanks for looking into this. 
I cannot reproduce this issue in a demo project after updating to 1.5.0-alpha04.

Do you have any insights about future stable version release date?
Thanks!

**Comment by thinhlai** [comment] 2021-10-05 10:36
I have the same issue with MaterialAlertDialogBuilder to show a simple alert, the layout of Dialog is not correct when rotating device.
![screenshot-1633429718933](https://user-images.githubusercontent.com/46520128/136006461-1cdd7b16-3c7b-4f20-9663-e711285db75e.png)

How to reproduce it
1. Set activity configChanges=orientation in AndroidManifest
2. In activity show alert dialog like this
```
MaterialAlertDialogBuilder(this).apply {
                setCancelable(false)

                setMessage("Test dialog")

                setNegativeButton("OK") { dialogInterface, _ ->
                    dialogInterface.dismiss()
                }
                show()
            }
```
3. Start app at portrait -> show dialog
4. Then rotate device to landscape 
5. Click physical home button to exit app
6. Then rotate device again to portrait
7. Press physical task manager button 
8. Select the app to resume on task manager
9. will see the issue

**Comment by drchen** [comment] 2021-11-02 20:31
Hi, we are going to release 1.5.0 beta in a couple of weeks I think. The stable version should be available soon after beta.

I'll close the issue for now. : )

**Closed by drchen** 2021-11-02 20:31 UTC
Labels: bug, Need more info
