### ISSUE TITLE
[TabLayout] TabLayout crashes randomly.

### ISSUE THREAD

**Issue by funct7** [material-components/material-components-android#618] opened 2019-09-22 05:51 UTC
**Description:** 
For simple implementation, I have code that removes all tabs and adds them in one cycle.
The line `listView.removeAllTabs()` crashes intermittently.

**Expected behavior:** Tabs are updated with the newest list reliable, all the time.

**Source code:** 
Code:
```kotlin
listView.removeAllTabs()
list.forEach {
    val tab = listView.newTab()
    tab.text = it
    listView.addTab(tab)
}
```

XML:
```xml
<com.google.android.material.tabs.TabLayout
        android:id="@+id/layout_currency_tab"
        android:layout_width="match_parent"
        android:layout_height="32dp"
        android:overScrollMode="always"
        app:layout_constraintTop_toBottomOf="@id/action_bar"
        app:tabIndicatorColor="@color/text_regular"
        app:tabIndicatorFullWidth="false"
        app:tabMode="scrollable"
        app:tabTextAppearance="@style/CurrencyCodeTab"
        app:tabTextColor="@color/text_regular" />
```

Crash log: 
```
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: JNI NewLocalRef called with pending exception java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x1010099 a=1}
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at int android.content.res.TypedArray.getColor(int, int) (TypedArray.java:477)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void android.widget.TextView.readTextAppearance(android.content.Context, android.content.res.TypedArray, android.widget.TextView$TextAppearanceAttributes, boolean) (TextView.java:3539)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void android.widget.TextView.setTextAppearance(android.content.Context, int) (TextView.java:3408)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void androidx.appcompat.widget.AppCompatTextView.setTextAppearance(android.content.Context, int) (AppCompatTextView.java:185)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void android.widget.TextView.setTextAppearance(int) (TextView.java:3395)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void androidx.core.widget.TextViewCompat.setTextAppearance(android.widget.TextView, int) (TextViewCompat.java:284)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void com.google.android.material.tabs.TabLayout$TabView.update() (TabLayout.java:2247)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void com.google.android.material.tabs.TabLayout$TabView.setTab(com.google.android.material.tabs.TabLayout$Tab) (TabLayout.java:2173)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void com.google.android.material.tabs.TabLayout$TabView.reset() (TabLayout.java:2178)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void com.google.android.material.tabs.TabLayout.removeTabViewAt(int) (TabLayout.java:1503)
2019-09-22 14:40:19.255 7685-7685/myapp.dev A/t7.myapp.de: java_vm_ext.cc:542]   at void com.google.android.material.tabs.TabLayout.removeAllTabs() (TabLayout.java:789)
```

**Android API version:** API 28

**Material Library version:** 1.0.0

**Device:** Nexus 5X emulator

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ldjcmu** [comment] 2019-09-24 15:39
Hi funct7,

Do you know if this issue occurs in the latest version of the library (a recent alpha)? It'll help us determine the importance of this issue faster.

**Comment by funct7** [comment] 2019-09-24 23:10
> Hi funct7,
> 
> Do you know if this issue occurs in the latest version of the library (a recent alpha)? It'll help us determine the importance of this issue faster.

Will check. I have to tell you though, It might take a while to know for sure because even on v1.0.0 it happens only intermittently.

**Comment by pekingme** [comment] 2019-11-04 22:21
Hi Josh [funct7],
I'm working on resolving this issue. However, I cannot reproduce the issue described. Could you please share more information about how you experienced it? A demo sample would be appreciated.
Thanks.

**Comment by funct7** [comment] 2019-11-12 04:29
@pekingme @leticiarossi I haven't had issues with this either since updating to v1.1.0, so maybe I should just close it?

**Comment by leticiarossi** [comment] 2019-11-12 18:05
Will close it since we're not able to reproduce it and you haven't seen this anymore. Feel free to reopen and attach a sample app if the issue comes up again

**Closed by leticiarossi** 2019-11-12 18:05 UTC
Labels: P3, bug

**Comment by ForceTower** [comment] 2021-01-28 14:27
This actually happens with the users of my app, and could only be resolved by clearing app data (reinstall's of the app would also crash).
I hardcoded a theme value as it seems to be the root cause of the issue. 
`<item name="android:textColorHighlight">@color/controlHighlight</item>` 

I'll update here if this solves the problem to me :D

**Comment by ForceTower** [comment] 2021-02-16 13:22
Yep, after adding the `<item name="android:textColorHighlight">@color/controlHighlight</item>` in the theme the error is gone and the users no longer need to clear app data.
