### ISSUE TITLE
[Slider] How to keep the value of Slider always show.

### ISSUE THREAD

**Issue by kimcy929** [material-components/material-components-android#1791] opened 2020-10-09 15:32 UTC
I want to keep the value of Slider always shows so how I can do this or you can support a option for this feature in the future. 
Slider is using Tooltip to show value but I don't find a way to keep Tooltip.

Currently I'm using Yahoo RangeSeekbar and it's quite old I want to use Slider to replace it.

Thanks!

![image](https://user-images.githubusercontent.com/4311848/95602264-dfb0e000-0a7e-11eb-8219-acab9ea1d1b5.png)

**Comment by gabrielemariotti** [comment] 2020-10-10 06:02
Duplicate of #1316

**Comment by hunterstich** [comment] 2020-10-13 14:05
Closing in favor of https://github.com/material-components/material-components-android/issues/1316

**Closed by hunterstich** 2020-10-13 14:05 UTC
Labels: feature request
