### ISSUE TITLE
Android Bottom App Bar Exception in 1.1.0-alpha

### ISSUE THREAD

**Issue by mustafa-almulla** [material-components/material-components-android#238] opened 2018-12-01 12:24 UTC
After I have upgraded the package to the latest release of material "com.google.android.material:material:1.1.0-alpha01" I started getting this error

2018-11-30 22:17:29.869 27633-27633/sa.sfc.fransitadawul E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sa.sfc.fransitadawul, PID: 27633
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.google.android.material.shape.MaterialShapeDrawable.prepareCanvasForShadow(MaterialShapeDrawable.java:850)
        at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:746)
        at android.view.View.getDrawableRenderNode(View.java:20463)
        at android.view.View.drawBackground(View.java:20399)
        at android.view.View.draw(View.java:20198)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
2018-11-30 22:17:29.870 27633-27633/sa.sfc.fransitadawul E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-11-30 22:17:29.938 1978-2048/? E/InputDispatcher: channel '57aaf3f sa.sfc.fransitadawul/sa.sfc.fransitadawul.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-11-30 22:17:29.938 1978-2048/? E/InputDispatcher: channel '34322d9 sa.sfc.fransitadawul/sa.sfc.fransitadawul.login.LoginActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-11-30 22:17:29.938 1978-2048/? E/InputDispatcher: channel '93033f9 sa.sfc.fransitadawul/sa.sfc.fransitadawul.splash.screen.SplashScreenActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-11-30 22:17:29.968 1926-1975/? E/SurfaceFlinger: getLayerUser(name=0xf02904b0) is dead
2018-11-30 22:17:30.464 1926-2052/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2018-11-30 22:17:30.534 1926-2052/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2018-11-30 22:17:32.980 1978-2100/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2018-11-30 22:17:37.044 1978-2100/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2018-11-30 22:17:44.936 1978-1991/? E/memtrack: Couldn't load memtrack module
Add

**Comment by hoordev** [comment] 2018-12-01 12:36
I think you got exception, beacuse this alpha release doesn't include androidx codes. Therefore check [Jetifire ](https://developer.android.com/studio/command-line/jetifier) and build own version of snapshot.

**Comment by mustafa-almulla** [comment] 2018-12-02 16:14
@hoordev if that was the case should not all the other components I am using crashes?

**Comment by ldjcmu** [comment] 2018-12-03 18:37
Duplicate of https://github.com/material-components/material-components-android/issues/235

**Closed** 2018-12-03 18:36 UTC
