### ISSUE TITLE
[TextInputLayout] [URGENT] :ambulance: Compile time error for `boxBackgroundMode` being set as a raw string `filled`

### ISSUE THREAD

**Issue by RahulSDeshpande** [material-components/material-components-android#3166] opened 2023-01-05 07:58 UTC
**Description:**
When I try to compile a bug-free Android project, the project build fails with the following error:
```kt
ERROR:
/project/app/build/intermediates/incremental/appDebug/mergeDebugResources/merged.dir/values/values.xml:10218:
AAPT: error: expected enum but got (raw string) filled.
```

**Expected behavior:**
Screenshots and/or description of expected behavior

**Source code:**
After tons of code digging, I found out that this issues is occurring because of merged values.xml Google Material library.
Following the XML code of `values.xml`:
```xml
<style name="Widget.MaterialComponents.TextInputLayout.FilledBox" parent="Base.Widget.MaterialComponents.TextInputLayout">
    <item name="materialThemeOverlay">
      @style/ThemeOverlay.MaterialComponents.TextInputEditText.FilledBox
    </item>
    <item name="boxBackgroundMode">filled</item>
    <item name="boxBackgroundColor">@color/mtrl_filled_background_color</item>
    <item name="endIconTint">@color/mtrl_filled_icon_tint</item>
    <item name="startIconTint">@color/mtrl_filled_icon_tint</item>
    <item name="boxCollapsedPaddingTop">10dp</item>
    <item name="boxStrokeColor">@color/mtrl_filled_stroke_color</item>
    <item name="shapeAppearanceOverlay">
      @style/ShapeAppearanceOverlay.MaterialComponents.TextInputLayout.FilledBox
</item>
```

**Android API version:**
`33`

**Material Library version:**
`1.8.0-beta01`

**Device:**
This is compile time error, so no device info to be provided.

**Comment by RahulSDeshpande** [comment] 2023-01-05 09:08
I even tried to run the Gradle command to execute the install task:
```kt
$ ./gradlew installAppDebug
> Task :app:processAppDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processAppDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     com.package.name-mergeAppDebugResources-79:/values/values.xml:10212: error: expected enum but got (raw string) filled.
     error: failed linking references.
```

Just want to highlight that the following Gradle task is failing here:
```kt
:app:processAppDebugResources FAILED
```

THIS IS REALLY AN BURNING ISSUE IN MY PROJECT.
ANY URGENT HELP WILL BE APPRECIATED.

🙏🏼 🙏🏼 🙏🏼

**Comment by RahulSDeshpande** [comment] 2023-01-05 10:15
More details:
```kt
Android resource linking failed
ERROR:/User/.gradle/caches/transforms-3/46b6d347cf8501bb5ef6c9d00812840f/transformed/material-1.8.0-beta01/res/values/values.xml:6306:5-6319:11: AAPT: error: expected enum but got (raw string) filled.
```

**Comment by RahulSDeshpande** [comment] 2023-01-07 00:01
@ianhanniballake @shyndman @JakeWharton 
I am so sorry to mention you all here, but this issues needs urgent attention.
This bug is not making project compile.

Thanks.

**Comment by afohrman** [comment] 2023-01-10 01:54
Hi Rahul, thanks so much for reporting this. I'm taking a look to see if I can reproduce this on my end. Could you please provide a code snippet with the project code including the TextInputLayout and any code necessary to help reproduce this? 

Also, what version are you using of the following:

- Android Studio
- Android Gradle Plugin (AGP)
- Gradle
- Java

The project should use the minimum required versions of those found here, in the **"New minimum requirements for your app's project"** section: https://github.com/material-components/material-components-android/releases/tag/1.7.0.

**Comment by drchen** [comment] 2023-02-01 19:55
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2023-02-01 19:55 UTC
Labels: bug, Widget: TextField
