### ISSUE TITLE
[MaterialDatePicker] Crash on SingleDateSelector when erasing typed in date

### ISSUE THREAD

**Issue by mcastagnolo** [material-components/material-components-android#631] opened 2019-09-26 18:59 UTC
**Description:** 

1. Show the MaterialDatePicker for selecting a single date
1. Click on the edit toggle to go to the TextInputEditText view
1. Type one digit
1. Erase the digit
1. A crash will occur

**Expected behavior:** The field should be empty with no crash.

**Source code:** 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
        at com.google.android.material.datepicker.SingleDateSelector$1.onValidDate(SingleDateSelector.java:115)
        at com.google.android.material.datepicker.DateFormatTextWatcher.onTextChanged(DateFormatTextWatcher.java:64)
```

The issue seems to be that _DateFormatTextWatcher_, within _onTextChanged_, passes a null into _onValidDate_ (line 64), which _SingleDateSelector_ passes into _select_ (line 115), which has the signature `public void select(long selection)` and can't accept null values.

**Android API version:** Tested on API 29

**Material Library version:** 1.1.0-alpha10

**Device:** Pixel 2 XL

**Comment by MGaetan89** [comment] 2019-09-26 19:43
Duplicate of #608

**Closed** 2019-09-26 20:13 UTC
Labels: bug, duplicate
