### ISSUE TITLE
[Progress Indicator] Progress Indicator invisible in RecyclerView

### ISSUE THREAD

**Issue by Sanlorng** [material-components/material-components-android#1827] opened 2020-10-27 07:59 UTC
**Description:** Progress Indicator will be invisible after recycle

**Expected behavior:** Porgress Indicator always visible

**Source code:** [TestProgressIndicator](https://drive.google.com/file/d/1KJtHoufPtO7MKmtjaiCpJacLdTaso6EQ/view?usp=sharing)
**Android API version:** Android 10/ API 29

**Material Library version:** Material Android Library version: 1.3.0-alpha03

**Device:** OnePlus 7 Pro

**Comment by matpag** [comment] 2020-10-27 12:15
Duplicate of #1662

**Closed** 2020-11-12 17:41 UTC
Labels: bug

**Comment by Sanlorng** [comment] 2020-11-16 16:15
@pekingme problem still hanppened after i compiled my app or [demo](https://drive.google.com/file/d/1KJtHoufPtO7MKmtjaiCpJacLdTaso6EQ/view?usp=sharing) with material library which contains commit [a5890bf](https://github.com/material-components/material-components-android/commit/a5890bfe6b5ebb4c466ad170439ce9c17ea6ead6)
