### ISSUE TITLE
[MaterialButton] paddingStart doesn't work

### ISSUE THREAD

**Issue by setnameinc** [material-components/material-components-android#2959] opened 2022-09-05 19:51 UTC
**Description:** `paddingStart` doesn't affect text padding, but `padding` and `paddingLeft` do
<img width="394" alt="act" src="https://user-images.githubusercontent.com/48593257/188506757-408fcf7c-e475-404b-b4ce-c4700fd8c98e.png">

**Expected behavior:** 
<img width="393" alt="exp" src="https://user-images.githubusercontent.com/48593257/188506727-f325f8c3-472e-42a0-8f2f-cf8603b33788.png">

**Source code:**
```
<com.google.android.material.button.MaterialButton
                android:id="@+id/button"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="sdf"
                android:paddingStart="48dp"
                android:gravity="start|center_vertical" />
```

**Android API version:** Android API version here

**Material Library version:** 1.8.0-alpha01

**Device:** No matter, it even doesn't shows in Android Studio XML redactor

**Comment by afohrman** [comment] 2022-09-06 18:02
Hi there, I'm unable to reproduce this issue in our catalog given the source code you provided -- see screenshot attached.
![Screenshot_20220906_135433](https://user-images.githubusercontent.com/13263374/188706155-95d99702-56c9-417c-a7bf-9fc253651dff.png)

 Are you using the Material theme in your project directly, or is it modified in some way? Specifically, are any of the padding attributes set in your theme?

I'm going to close this issue as not reproducible, but please feel free to reopen it if you have more details that can help us reproduce the issue.

**Closed** 2022-09-06 18:06 UTC
Labels: bug, not reproducible
