### ISSUE TITLE
[M3][Color][Theme] textColorHighlight/textColorHighlightInverse do not follow app colors

### ISSUE THREAD

**Issue by OxygenCobalt** [material-components/material-components-android#2452] opened 2021-10-31 22:01 UTC
**Description:** The values for `textColorHighlight` and `textColorHighlightInverse` are hard-coded with `m3_sys_color_primary`. This means that regardless of the app's theme or version, the highlighted text will always appear the same purple-ish color. I've attached a screenshot below:

![The problem](https://user-images.githubusercontent.com/65370175/139602486-7860f419-7f2c-41a5-b79a-8a5944a5e9e6.png)

[Here's one of the offending resources in the library.](https://github.com/material-components/material-components-android/blob/2db68ee84486f2bd748d39f6205294610e3fb3c4/lib/java/com/google/android/material/color/res/color/m3_highlighted_text.xml)

`m3_sys_color_light_primary` corresponds to `m3_ref_palette_primary40`, which is a hard-coded color from the default `Theme.Material3` palette.

**Expected behavior:** The values used for `textColorHighlight`/`textColorHighlightInverse` [like `m3_highlighted_text`]  should use a reference instead of a hard-coded value, like `colorPrimary` and `colorPrimaryInverse` respectively.

**Source code:**

This occurs as long as the theme is a descendent of `Theme.Material3` and if you don't override `textColorHighlight`/`textColorHighlightInverse`.

**Android API version:** 31

**Material Library version:** 1.5.0-alpha05

**Device:** Pixel 5

**Comment by drchen** [comment] 2021-11-02 14:37
Hi, I think this is working as intended. (We don't really want to tight them with theme attributes like colorPrimary or colorPrimaryInverse.)

I'll close the issue since it should not be a big issue to override it with custom colors. : )

**Closed by drchen** 2021-11-02 14:37 UTC
Labels: bug

**Comment by OxygenCobalt** [comment] 2021-11-02 17:45
Fair enough. I'm already overriding them myself, but I was unsure if this was intended behavior.

**Comment by drchen** [comment] 2021-11-02 17:50
Actually when I raised this to the team some people thought this may be a good idea to make clients' work easier.

We may (or may not) have an update to this when we have a conclusion. : )    Thanks for the report!!
