### ISSUE TITLE
[BottomSheetDialogFragment] AppTheme still does not get applied

### ISSUE THREAD

**Issue by matiasmb** [material-components/material-components-android#2283] opened 2021-07-02 13:06 UTC
**Description**: I saw this other issue closed/fixed https://github.com/material-components/material-components-android/issues/894 and this other one https://github.com/material-components/material-components-android/issues/99 but I still cannot achieve to have the AppTheme applied in my BottomSheetDialogFragment.

**Expected behavior**:
AppTheme being applied correctly to my BottomSheetDialogFragment. I still have to do the workaround of:

```
        return inflater.cloneInContext(contextThemeWrapper)
            .inflate(R.layout.view_my_bottom_sheet_dialog_fragment, container, false)
```

to make it work.

**Source code**: The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version**: 30

**Material Library version**:
1.4.0-rc01

**Notes**: I think that main issue there could be that the inflater provided by the onCreateView is using the context application that doesn't have the app theme applied.

**Comment by drchen** [comment] 2021-07-12 16:11
Hi, can you provide more clues about why you think your app theme is not applied?

For example, is there any theme attribute that you set but isn't applied?

If you can see material colors (purple primary) on the dialog that means the app theme is applied.

**Comment by drchen** [comment] 2021-10-04 19:50
I'll close the issue due to no further info available. Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2021-10-04 19:50 UTC
Labels: bug
