### ISSUE TITLE
[MaterialButton] Double ripple effect when updating appcompat from 1.4.2 to 1.5.0

### ISSUE THREAD

**Issue by LunarX** [material-components/material-components-android#2911] opened 2022-08-16 14:56 UTC
**Description:** When updating appcompat from 1.4.2 to 1.5.0 the ripple effect of my MaterialButton is triggered twice. Once at the location of the click and a second time a few frames later at the center of the button. It worked without any issue before updating appcompat.

I have linked a video that shows the double ripple effect (appcompat version 1.5.0) and one that show the expected single ripple effect (appcompat version 1.4.2). The appcompat version is the only difference between the two videos

Video of the issue:

https://user-images.githubusercontent.com/32095402/184909962-b2012644-7d9d-428e-addf-73d0a432ed5d.mp4

**Expected behavior:** 

https://user-images.githubusercontent.com/32095402/184910019-297407c0-ab89-4915-b1a1-4b15f3f23c23.mp4

Because it might be hard to see the issue without stepping through frame by frame on the video, I also added three consecutive frames of the video to better illustrate the issue.

<img width="114" alt="double_ripple_0" src="https://user-images.githubusercontent.com/32095402/184910284-3aa96140-89cd-4dcc-95e8-b591e20de37f.png">
<img width="120" alt="double_ripple_1" src="https://user-images.githubusercontent.com/32095402/184910307-e7b4cfd6-bbce-4e8e-ae6f-45a3f9ceeff3.png">
<img width="130" alt="double_ripple_2" src="https://user-images.githubusercontent.com/32095402/184910363-e2f2da0f-41de-4a8a-8711-1858051ac653.png">

**Android API version:** The issue at least occurs with api 30 and api 29 but does not happen with api 31 and api 32

**Material Library version:** 1.6.1

**Device:** Pixel 4 emulator

**Comment by drchen** [comment] 2022-08-16 18:59
Looks like a duplicate of #2833.

**Closed by drchen** 2022-08-16 18:59 UTC
Labels: bug
