### ISSUE TITLE
[MaterialButton] opaque shape inside button

### ISSUE THREAD

**Issue by Prashast09** [material-components/material-components-android#2023] opened 2021-02-01 05:50 UTC
**Description:** There is an opaque shape inside button. It is visible when background tint is set to a transparent color
<img width="498" alt="Screenshot 2021-02-01 at 11 18 52 AM" src="https://user-images.githubusercontent.com/20680005/106419796-466b6680-647f-11eb-88ef-d61d57e60e23.png">

**Expected behavior:** Opaque shape shouldn't be available

**Source code:** 
```
<com.google.android.material.button.MaterialButton
        android:id="@+id/join_class_bt"
        style="@style/ActiveBlueButton"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="24dp"
        android:text="Join Class"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toStartOf="@+id/seventy_vertical_bt_g"
        app:layout_constraintStart_toStartOf="@+id/thirty_vertical_bt_g"
        app:layout_constraintTop_toBottomOf="@id/seventy_horizontal_bt_g"
        />
```
```
<style name="ActiveBlueButton" parent="Widget.MaterialComponents.Button.TextButton">
        <item name="cornerRadius">50dp</item>
        <item name="android:textAllCaps">false</item>
        <item name="android:stateListAnimator">@animator/bt_animator</item>
        <item name="android:textSize">16sp</item>
        <item name="rippleColor">@null</item>
        <item name="android:textColor">@color/white</item>
        <item name="backgroundTint">#CC556172</item>
    </style>
```

**Android API version:** All versions

**Material Library version:** 1.2.0
**Device:** Xiomi Redmi 8

**Comment by consp1racy** [comment] 2021-02-02 02:30
Behind the translucent background you can see how shadows are drawn.
Option 1: Don't use shadow/elevation with your translucent button.
Option 2: Use fully opaque background color with shadow. 
This is how it worked since Lollipop. This is working as intended, certainly not a bug in this library.

**Comment by drchen** [comment] 2021-06-29 19:14
Closing this as it's intended behavior.

**Closed by drchen** 2021-06-29 19:14 UTC
Labels: bug
