### ISSUE TITLE
[MaterialCalendarGridView] NullPointerException in onDraw in 1.3.0

### ISSUE THREAD

**Issue by SashaCube** [material-components/material-components-android#2158] opened 2021-03-31 09:13 UTC
**Description:** I'm receiving a similar bug to https://github.com/material-components/material-components-android/issues/1338, but using version "1.3.0"

I don't have steps to reproduce, but It occurred on different devices with different android versions. Maybe there is a trick with language, most users are using 'fr'.

**Expected behavior:** expect the app will not crash

**Source code:** 

```
private fun showDatePicker(from: DateTime, to: DateTime, onSubmit: (DateTime, DateTime) -> Unit) {
        val datePicker = MaterialDatePicker.Builder.dateRangePicker()
        datePicker.setSelection(Pair(from.millis, to.millis))
        val dialog = datePicker.build()
        dialog.addOnPositiveButtonClickListener {
            onSubmit(DateTime(it.first), DateTime(it.second))
        }
        dialog.show(parentFragmentManager, dialog.javaClass.simpleName)
    }

```
**Android API versions:**  29, 28, 27, 26

**Material Library version:** 1.3.0

**Devices:** 
Huawei P20
Xiaomi Redmi 9
Samsung Galaxy S7
Samsung Galaxy S7 edge
Samsung Galaxy A41
Samsung Galaxy Note 10
Samsung Galaxy S9
OnePlus 6

**Stacktrace:**
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
       at com.google.android.material.datepicker.MaterialCalendarGridView.horizontalMidPoint(MaterialCalendarGridView.java)
       at com.google.android.material.datepicker.MaterialCalendarGridView.onDraw(MaterialCalendarGridView.java:221)
       at android.view.View.draw(View.java:23187)
       at android.widget.AbsListView.draw(AbsListView.java:7190)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23190)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22048)
       at android.view.View.draw(View.java:22917)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23190)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1154)
       at android.view.View.updateDisplayListIfDirty(View.java:22062)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4296)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4080)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3348)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
```

I going to try the latest release 1.4.0-alpha01 of the library. But I can't reproduce this issue by myself, so the only way is to receive crash information from Firebase, it's painful. Maybe someone faced the same issue, will be thankful for any help.

**Comment by mirjalal** [comment] 2021-04-15 09:17
Also tested in Samsung Galaxy A10S, HTC OneM9, Xiaomi Redmi Note 8 and the same exception thrown. However, works in Samsung Galaxy A70.

**Comment by vladyslavkhimich** [comment] 2021-04-21 08:26
Still receiving this bug on 1.4.0-alpha02 on any language (tested only English and Russian). At this moment (21.04.2021) this bug only present when choosing any range in May 2021. But when I go to the next months after May and turning back to May 2021 it's OK, however, when going from April 2021 to May 2021 it is crashing no matter what range I pick. Hope this bug will be fixed soon because I don't want to release an app with such a problem.

**Comment by mirjalal** [comment] 2021-04-21 08:35
@vladyslavkhimich because of that case (crash when choosing any range in May 2021), I changed the lib with another one.

**Comment by vladyslavkhimich** [comment] 2021-04-21 08:45
@mirjalal which one? Will highly appreciate your suggestion.

**Comment by mirjalal** [comment] 2021-04-21 15:18
@vladyslavkhimich checkout [this one](https://github.com/afollestad/material-dialogs/blob/main/documentation/DATETIME.md). Additionally, I highly recommend you to read this [issue](https://github.com/afollestad/material-dialogs/issues/2029) 🙂 Cheers 🥳

**Comment by cryptowizard** [comment] 2021-05-24 17:16
I'm getting the same on Samsung devices

**Comment by cryptowizard** [comment] 2021-06-11 08:55
> I'm getting the same crash on Lenovo TB-8504X with Android 8.1.0. Many of our users getting this crash, all with the same model device and Android version. Tried everything, cannot reproduce even when using exactly the same device model and Android version. Using version 1.3.0 of the Material Components library with the bridge app theme Theme.MaterialComponents.Light.NoActionBar.Bridge.

We had the same problem on production recently. I have managed to reproduce it by using Foldable emulator. (You will find it in awd manager ). The only way to fix it was forking the project and fixing it in MaterialComponents.

**Comment by SashaCube** [comment] 2021-06-11 09:04
> > I'm getting the same crash on Lenovo TB-8504X with Android 8.1.0. Many of our users getting this crash, all with the same model device and Android version. Tried everything, cannot reproduce even when using exactly the same device model and Android version. Using version 1.3.0 of the Material Components library with the bridge app theme Theme.MaterialComponents.Light.NoActionBar.Bridge.
> 
> We had the same problem on production recently. I have managed to reproduce it by using Foldable emulator. (You will find it in awd manager ). The only way to fix it was forking the project and fixing it in MaterialComponents.

I've used the same solution. Opened PR to this issue is based on fix which I used on prod, hope it will be rewived soon.

**Comment by drchen** [comment] 2021-06-11 21:55
It's a duplicate issue of [[datepicker.MaterialCalendarGridView] crash on select a date range across two months (second month with 6 weeks)](https://github.com/material-components/material-components-android/issues/2195)

**Closed by drchen** 2021-06-11 21:55 UTC
Labels: bug
