### ISSUE TITLE
Labeled is showing now on top of icon, that is wrong now, please team check it and fix it

### ISSUE THREAD

**Issue by soodkartik1993** [material-components/material-components-android#2602] opened 2022-03-15 13:34 UTC
<img width="390" alt="Screenshot 2022-03-15 at 7 01 17 PM" src="https://user-images.githubusercontent.com/88143960/158388991-48a4f443-20ff-41d0-8384-4bb01fa1fa35.png">

**Comment by hunterstich** [comment] 2022-03-15 16:07
Hi @soodkartik1993,

Would you be able to provide a sample app and more info on how this is reproduced?

It looks very similar to #2535

**Comment by drchen** [comment] 2022-04-05 15:03
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-04-05 15:03 UTC
Labels: Need more info, Widget: BottomNavigation
