### ISSUE TITLE
[ShapeableImageView] Padding is applied to background, unlike normal ImageView

### ISSUE THREAD

**Issue by drewhamilton** [material-components/material-components-android#1489] opened 2020-07-17 14:55 UTC
**Description:** In ShapeableImageView, `android:padding` gets applied to both the image itself and the shaped background. This is unusual compared to most views (though maybe typical for Shapeables, not sure).

**Expected behavior:**
What the normal ImageView does: pads the image, but not the background.
Top: ShapeableImageView with padding. Bottom: normal ImageView with padding.
![image](https://user-images.githubusercontent.com/2267660/87798925-e0095880-c84c-11ea-9724-4ef8b324775b.png)

It seems like the current behavior should be achieved by margin rather than padding, and that padding should leave the background alone, like it does in most Views.

**Source code:**
```xml
<ShapeableImageView
    android:layout_width="48dp"
    android:layout_height="48dp"

    android:background="?colorSecondary"
    android:padding="8dp"

    app:shapeAppearance="?shapeAppearanceSmall"
    app:srcCompat="@drawable/my_icon" />
```

**Android API version:** 21-29

**Material Library version:** 1.2.0-rc01

**Device:** Pixel 3 emulator

Looking at the ShapeableImageView source, it appears to be clear where the shape is set to honor the padding. I'd like to know if the current behavior is expected for some reason. If it is, I'd like to know if the behavior I want can be accommodated by some new attribute or something.

If there's a clear path forward I'd be happy to open a PR. And if that PR could potentially land in 1.2, I'd be happy to open a PR quickly. :) Let me know!

**Comment by ymarian** [comment] 2020-07-17 18:44
Hi the problem is that ShapeableImageView supports stroke like MaterialCardView which handles it the same way. 
We rely on people to add padding if they need the stroke to fit the view bounds. 

<img width="1047" alt="Screen Shot 2020-07-17 at 2 29 57 PM" src="https://user-images.githubusercontent.com/38727469/87820190-a5e38b00-c83b-11ea-9788-126d72630cf7.png">

For your case if it's only icons you can work around it easily with an inset drawable?


```xml
<inset
        android:drawable="@drawable/my_icon"
        android:insetBottom="8dp"
         .....
/>
```

**Comment by drewhamilton** [comment] 2020-07-17 19:49
Hmm. That's unfortunate. Would it not make sense to pad the background by half the stroke width automatically?

I'd argue that CardView was always a little "weird" about padding like this, but (Shapeable)ImageView has an existing behavior that it should aim to uphold. For this reason I would prefer that `android:padding` affect only the image while some custom attribute like `app:backgroundPadding` be created for the background.

But if consistency with MaterialCardView is more important than consistency with ImageView, can I offer a PR with the inverse? I.e. leave padding as is and add some `app:imageInset` attributes?

My goal is to ship some styles that match specific design guidelines without requiring a custom view, so the inset drawable solution is undesirable.

**Comment by drewhamilton** [comment] 2020-09-29 08:22
OK so adding an `app:contentPadding` attribute in a way that makes sense is pretty difficult. Since ImageView's `mDrawable`  is private, we can't manipulate it directly. And since a stable release now has the background being inset by `android:padding`, we can't change that behavior. I can think of 3 options:

1. In ShapeableImageView, override `setDrawable` methods to wrap the original Drawable inside an InsetDrawable. This has some pretty big problems. First, this means `getDrawable` will return a different-looking drawable than was provided to `setDrawable`. Second, this means always instantiating a new InsetDrawable whenever a Drawable is set, which is probably an undesirable performance impact. Third, I'm not sure if this would play nice with some of ImageView's internal logic, e.g. around recycling bitmap drawables or mutating the drawable to set a tint.
2. Add `app:contentPadding` to `android:padding` so that the image is automatically inset by the sum of both, but subtract `app:contentPadding` from the sum when insetting the background. This would make the `getPadding` methods inconsistent with the `android:padding` attribute which I'm sure is unacceptable. I could maybe add some `getPadding` overrides and `super.getPadding` hacks to ShapeableImageView to work around this problem.
3. Instead of anything like `app:contentPadding`, only add a boolean `app:applyPaddingToBackground` attribute. This would default to true to maintain the 1.2.0 behavior. It would provide less flexibility than the other options but would be sufficient for my use case at least.

Any more ideas and/or a preference on which direction to go with a PR?

**Comment by ymarian** [comment] 2020-09-30 16:53
Hi, 2 sounds good to me if all the combinations work well with stroke and shadows. Otherwise don't see any harm on 3

**Comment by MarinKacaj** [comment] 2020-10-06 13:30
I had the same problem, and ran into this issue.
IMO, option 2 is also better aligned with `MaterialCardView`, so it's less of a surprise for me as a consumer of this library.

**Comment by drewhamilton** [comment] 2020-10-08 07:04
I believe I have this working on a local branch. But
1. It depends on #1769. Should I wait for that to be merged before I open a PR, or still open a PR with the same changes?
2. I'm having trouble getting the IDE to recognize the existing tests as test sources so I'm not sure how to go about writing tests for this. Any pointers?

**Comment by theHilikus** [comment] 2021-04-20 22:02
is there a workaround for this in the meantime? i'm using material:material:1.3.0 and i'm trying to have the image be padded so that the circle around the image is not touching the image
![image](https://user-images.githubusercontent.com/1633408/115469047-f2605a80-a201-11eb-8473-d83a4645f710.png)
instead, I get
![image](https://user-images.githubusercontent.com/1633408/115469122-0ad07500-a202-11eb-8b8b-438cc3700f0f.png)

I'm not sure how to use the `inset` suggestion from @ymarian

**Comment by drchen** [comment] 2021-10-06 18:02
Hi Alejandro, does the contentPadding support added by Drew solve your issue?

**Comment by drchen** [comment] 2021-11-02 20:17
I'll close the issue due to no further info available. Assume contentPaddings solve the problem. Feel free to reopen it if this is still an issue.

**Closed by drchen** 2021-11-02 20:17 UTC
Labels: bug, Need more info
