### ISSUE TITLE
[Progress Indicator] Doesn't animate well with MaterialSharedAxis animation

### ISSUE THREAD

**Issue by heybradharris** [material-components/material-components-android#2334] opened 2021-08-15 21:35 UTC
**Description:** Full description of issue here

The progress indicator doesn't animate at all and freezes on a fragment pop.

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

github.com/heybradharris/class

**Android API version:** Android API version here

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

1.5.0-alpha02

**Device:** Device on which the bug was encountered here

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by hunterstich** [comment] 2021-08-16 13:32
@heybradharris Can you add a recording of what's happening? Are you setting the root of your layout as `transitionGroup=true`?

**Comment by heybradharris** [comment] 2021-08-23 18:07
https://user-images.githubuIsercontent.com/31834244/130495118-9090ea30-8a17-46f5-9d41-6d258804f5f9.MOV

I do two transitions here. First a fragment transition SharedAxis, then once the pull requests load, I do another SharedAxis using 
TransitionManager. As you can see it drops when the second transition starts.

**Comment by heybradharris** [comment] 2021-08-23 18:09
https://user-images.githubusercontent.com/31834244/130495769-752033db-97d5-4511-a4c8-1408cc95562d.MOV

**Comment by heybradharris** [comment] 2021-08-23 18:25
https://user-images.githubusercontent.com/31834244/130497722-baa9b36b-5d0c-4d1d-97b5-9cc4facf10e3.MOV

**Comment by heybradharris** [comment] 2021-08-23 18:27
These ProgressIndicators should work because they are likely to be shown first when doing Fragment Transitions

**Comment by pekingme** [comment] 2022-06-02 22:34
@heybradharris After taking a closer look at your repo, it seems to be a user error.

> First a fragment transition SharedAxis, then once the pull requests load, I do another SharedAxis using
TransitionManager. As you can see the ProgressIndicator drops when the second transition starts.

As you mentioned the second transition starts (via showPullRequests) when the PRs are loaded. Inside that function, the PI's visibility is set to invisible, which makes the PI invisible immediately. The expected behavior should be done by hiding the PI when the second transition **ends**. Alternatively, you could call `hide()` and set `app:hideAnimationBehavior="inward"` in layout. It will play the PI's hiding animation along with the second transition.

I'm closing this issue. But feel free to discuss more for any questions.

**Closed by pekingme** 2022-06-02 22:34 UTC
Labels: bug, Widget: ProgressIndicator, Feature: Transition
