### ISSUE TITLE
[BottomNavigationView] shouldn't calculate bottom system insets when keyboard popup in adjustResize

### ISSUE THREAD

**Issue by b95505017** [material-components/material-components-android#493] opened 2019-08-02 19:29 UTC
In 1.1.0-alpha09:
>Update BottomNavigation to respect bottom system insets (https://github.com/material-components/material-components-android/commit/276bec8385ec877548fc84994c0a016de2428567)

I found that in `adjustResize` mode, BottomNavigationView will be pushed up aligned with keyboard popped up, and `insets.getSystemWindowInsetBottom()` will be keyboard hight, causing `BottomNavigationView` increase padding bottom to double keyboard hight from screen bottom.

**Comment by dsn5ft** [comment] 2019-08-02 19:33
@b95505017 Thanks for reporting, can you attach a screenshot?

**Comment by b95505017** [comment] 2019-08-02 19:45
https://imgur.com/a/2N3rm1A Here are the two layout layers between `1.1.0-alpha08` and `1.1.0-alpha09`.

**Comment by wcshi** [comment] 2019-08-02 20:06
@b95505017 could you either provide a sample app or explain your layout so I can reproduce this behavior?

**Comment by b95505017** [comment] 2019-08-02 21:46
I'll try to provide a sample, but basically it has several points:
1. The `windowSoftInputMode` is `adjustResize`.
2. A layout which has EditText placed near top and BottomNavigationView at the bottom.
3. When keyboard popup, the window and the layout are resized, while BottomNavigationView received `onApplyWindowInsets`( `insets.getSystemWindowInsetBottom()` is the height of keyboard, e.g. 740px), so that BottomNavigationView padding bottom will be 740px.
4. From screen bottom, there will be 740px keyboard + 740px padding, then the real content of BottomNavigationView.

**Comment by paolovalerdi** [comment] 2019-08-02 22:06
Not only that. If your app is launched with the keyboard open (let's say from the launcher searcher) then the BottomNavigationView will get the keyboard height as the initial systemBottomInset as the bottom padding.

**Comment by rhariskumar3** [comment] 2019-08-03 11:51
> In 1.1.0-alpha09:
> 
> > Update BottomNavigation to respect bottom system insets ([276bec8](https://github.com/material-components/material-components-android/commit/276bec8385ec877548fc84994c0a016de2428567))
> 
> I found that in `adjustResize` mode, BottomNavigationView will be pushed up aligned with keyboard popped up, and `insets.getSystemWindowInsetBottom()` will be keyboard hight, causing `BottomNavigationView` increase padding bottom to double keyboard hight from screen bottom.



> @b95505017 Thanks for reporting, can you attach a screenshot?

My Bottom Navigation also changed bad.
[https://imgur.com/33AkPu9](alpha-09 - Bottom Nav View)

**Comment by wcshi** [comment] 2019-08-03 16:00
@rhariskumar3 what API version is your emulator? What system ui flags are set in your app?

**Comment by b95505017** [comment] 2019-08-03 18:02
@wcshi Here is the sample of `adjustResize` https://drive.google.com/file/d/1J7y-8QhJmSXgMuq1LKRLGRJdEdmJddcL/view?usp=sharing

**Comment by rhariskumar3** [comment] 2019-08-05 06:01
> @rhariskumar3 what API version is your emulator? What system ui flags are set in your app?

Emulator API version 29
[Code - Screenshot](https://imgur.com/15gKFY0)

**Comment by wcshi** [comment] 2019-08-05 21:11
@paolovalerdi could you please file a separate issue with steps to produce the bug and sample app, thank you

**Comment by chrisbanes** [comment] 2019-08-06 01:16
Just checked the sample from @b95505017 above. The reason this is happening is because of the following layout (my comments inline).

``` xml
<!-- The CoordinatorLayout is set to fitsSystemWindows  -->
<androidx.coordinatorlayout.widget.CoordinatorLayout
    android:fitsSystemWindows="true">

    <!-- The direct child of the CoordinatorLayout is NOT set to
         fitsSystemWindows, this means that CoL will automatically
         move this view up to match the insets. This is the first
         application of the insets. -->
    <androidx.constraintlayout.widget.ConstraintLayout>

        <!-- The descendent BottomNavigationView is passed the same insets,
             and pads itself. This is the second application. -->
        <com.google.android.material.bottomnavigation.BottomNavigationView />

    </androidx.constraintlayout.widget.ConstraintLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**So how do you fix it?**
Two options:

1) Move the BottomNavigationView up to be a child of the CoordinatorLayout, and set it to `fitsSystemWindows="true"`
2) Set the ConstraintLayout to `fitsSystemWindows="true"` AND set an `OnApplyWindowInsetsListener` on it to ignore the inset (so that only the BottomNavigation handles it). Slide 143 from this [talk](https://chris.banes.dev/talks/2017/becoming-a-master-window-fitter-lon/) goes through a similar example.

**Comment by wcshi** [comment] 2019-08-12 19:19
Thanks @chrisbanes closing issue.

**Closed by wcshi** 2019-08-12 19:19 UTC
Labels: bug
