### ISSUE TITLE
[Material Cardview] Children not being clipped when material cardview has rounded corners below API 29

### ISSUE THREAD

**Issue by seanyc4** [material-components/material-components-android#1940] opened 2020-12-18 22:39 UTC
**Description:** On API 28 and below when using a material card view with rounded corners children such as other material card views are not clipped and instead overlap the rounded corners. 

**Expected behavior:** [https://imgur.com/a/59NoNsk](url)

**Source code:** Just make a simple material card view with rounded corners. Put a nested scrollview inside and scroll through other material cardview children and you will see on api 28 and below they are not clipped and spill over the corners.

**Android API version:** bug visible on api 28 and below

**Material Library version:** 1.2.1

**Device:** Emulator pixel 4XL <= API 28

**Comment by drchen** [comment] 2021-11-02 20:27
I'll close the issue due to no further info available. 

On pre-Lolipop you will need to call setPreventCornerOverlap(true) to make the card view automatically adjust it's content paddings to avoid corner overlaps. On Lolipop+ it should clip the content to its outline nicely.

Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:27 UTC
Labels: bug, Need more info

**Comment by MaKrotos** [comment] 2023-03-23 12:55
`public class RoundedCornerLayout extends MyMaterialCardView {

    private Path path = new Path();
    private RectF rect = new RectF();
    private float[] cornerRadii = new float[8];

    public RoundedCornerLayout(Context context) {
        super(context);
        init(context, null);
    }

    public RoundedCornerLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context, attrs);
    }

    public RoundedCornerLayout(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context, attrs);
    }

    private void init(Context context, AttributeSet attrs) {
        if (attrs != null) {
            TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.RoundedCornerLayout);


            float radiusTopLeft = a.getDimension(R.styleable.RoundedCornerLayout_cornerRadiusTopLeft, 0);
            float radiusTopRight = a.getDimension(R.styleable.RoundedCornerLayout_cornerRadiusTopRight, 0);
            float radiusBottomRight = a.getDimension(R.styleable.RoundedCornerLayout_cornerRadiusBottomRight, 0);
            float radiusBottomLeft = a.getDimension(R.styleable.RoundedCornerLayout_cornerRadiusBottomLeft, 0);

            cornerRadii[0] = cornerRadii[1] =radiusTopLeft;
            cornerRadii[2] = cornerRadii[3] =radiusTopRight;
            cornerRadii[4] = cornerRadii[5] =radiusBottomRight;
            cornerRadii[6] = cornerRadii[7] =radiusBottomLeft;
            a.recycle();


            ShapeAppearanceModel shapeAppearanceModel = getShapeAppearanceModel()
                    .toBuilder()
                    .setTopLeftCorner(CornerFamily.ROUNDED, radiusTopLeft)
                    .setTopRightCorner(CornerFamily.ROUNDED, radiusTopRight)
                    .setBottomRightCorner(CornerFamily.ROUNDED, radiusBottomRight)
                    .setBottomLeftCorner(CornerFamily.ROUNDED, radiusBottomLeft)
                    .build();


            setShapeAppearanceModel(shapeAppearanceModel);


        }
        setWillNotDraw(false);
    }

    @Override
    protected void onMeasure(int widthMeasureSpec,int heightMeasureSpec){
        int count=getChildCount();
        int maxHeight=0;
        int maxWidth=0;

        for(int i=0;i<count;i++){
            final View child=getChildAt(i);
            if(child.getVisibility()!=GONE){
                measureChild(child,widthMeasureSpec,heightMeasureSpec);
                maxWidth=Math.max(maxWidth,
                        child.getMeasuredWidth());
                maxHeight=Math.max(maxHeight,
                        child.getMeasuredHeight());
            }
        }

        maxWidth+=getPaddingLeft()+getPaddingRight();
        maxHeight+=getPaddingTop()+getPaddingBottom();

        setMeasuredDimension(resolveSizeAndState(maxWidth,widthMeasureSpec , 0),
                resolveSizeAndState(maxHeight,heightMeasureSpec , 0));
    }

    @Override
    protected void onLayout(boolean changed,int l,int t,int r,int b){
        int count=getChildCount();

        for(int i=0;i<count;i++){
            final View child=getChildAt(i);
            if(child.getVisibility()!=GONE){
                child.layout(getPaddingLeft(),getPaddingTop(),
                        getPaddingLeft()+child.getMeasuredWidth(),
                        getPaddingTop()+child.getMeasuredHeight());
            }
        }
    }

    @Override
    public void draw(Canvas canvas) {
        canvas.save();
        rect.set(0f , 0f , getWidth() , getHeight());

        path.addRoundRect(rect,
                cornerRadii,
                Path.Direction.CW);

        canvas.clipPath(path);

        super.draw(canvas);

        canvas.restore();
    }
}
`
