### ISSUE TITLE
[MaterialDividerItemDecoration] It doesn't support GridLayoutManager

### ISSUE THREAD

**Issue by RaysonYeungHK** [material-components/material-components-android#3472] opened 2023-07-07 06:46 UTC
**Description:**
When GridLayoutManager is used with MaterialDividerItemDecoration, the divider is not drawn based on the childview bounding, but recyclerview bounding.

![behaved](https://github.com/material-components/material-components-android/assets/6037867/c61340f0-dd99-4b4e-b198-5e9b78368a29)

**Expected behavior:**
![expected](https://github.com/material-components/material-components-android/assets/6037867/974ec1ff-9a8e-4460-a0f9-4950176843e5)

**Source code:**
```
binding.recyclerView.apply {
    layoutManager = GridLayoutManager(this@MainActivity, 2).apply {
        spanSizeLookup = object : GridLayoutManager.SpanSizeLookup() {
            override fun getSpanSize(position: Int): Int {
                return when(position) {
                    0,
                    this@MainActivity.adapter.itemCount - 1 -> {
                        2
                    }
                    else -> {
                        1
                    }
                }
            }
        }
    }
    addItemDecoration(object : MaterialDividerItemDecoration(
        this@MainActivity,
        DividerItemDecoration.VERTICAL
    ) {
        override fun shouldDrawDivider(
            position: Int,
            adapter: RecyclerView.Adapter<*>?
        ): Boolean {
            return position in 1 until (this@MainActivity.adapter.itemCount - 1)
        }
    })
    addItemDecoration(object : MaterialDividerItemDecoration(
        this@MainActivity,
        DividerItemDecoration.HORIZONTAL
    ) {
        override fun shouldDrawDivider(
            position: Int,
            adapter: RecyclerView.Adapter<*>?
        ): Boolean {
            return position % 2 == 1
        }
    })
}
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 33

**Material Library version:** 1.9.0

**Device:** Emulator API 33

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by OxygenCobalt** [comment] 2023-07-10 14:57
Is this not a duplicate of #3079?

**Comment by paulfthomas** [comment] 2023-07-10 16:06
@OxygenCobalt thanks, seems like it!

**Closed by paulfthomas** 2023-07-10 16:06 UTC
Labels: bug, Widget: Divider
