### ISSUE TITLE
[MaterialTimePicker] It's impossible to select AM hours when time format is set to CLOCK_12

### ISSUE THREAD

**Issue by Milszym** [material-components/material-components-android#1775] opened 2020-10-05 08:52 UTC
**Description:** Hey, I have an issue with the newest **alpha03** release. It is impossible to select AM hours when time format is set to TimeFormat.CLOCK_12, because there is no toggle or anything that will allow me to do so. Please see the following screenshot:

<img width="449" alt="Screenshot 2020-10-05 at 10 50 59" src="https://user-images.githubusercontent.com/12632186/95059125-c6173d80-06f8-11eb-9d34-c598b0935597.png">

**Expected behavior:** I would expect to be allowed to specify if a picked time is AM or PM.

**Source code:** 
Picker initialization:
```
val materialPicker = MaterialTimePicker.Builder()
            .setHour(12)
            .setMinute(0)
            .setInputMode(MaterialTimePicker.INPUT_MODE_CLOCK)
            .setTimeFormat(TimeFormat.CLOCK_12H)
            .build()
        materialPicker.addOnPositiveButtonClickListener {
            onTimePicked(materialPicker.hour, materialPicker.minute)
        }
        materialPicker.show(parentFragmentManager, null)
```

Style for the activity:
```
    <style name="DialogActivity" parent="Theme.MaterialComponents.Light.Dialog.Bridge">
        <item name="windowNoTitle">true</item>
        <item name="android:windowBackground">#ffffff</item>
        <item name="materialTimePickerTheme">
            @style/ThemeOverlay.MaterialComponents.Light
        </item>
    </style>
```

**Android API version:** Android 10 (SDK 29), also tested on Android Emulator with Android 5.1.1 (SDK 22)

**Material Library version:** Material Android Library version **1.3.0-alpha03**

**Device:** Samsung Tab A 10,1 2019 (Android 10, SDK 29)

**Comment by ymarian** [comment] 2020-10-21 20:54
duplicate of https://github.com/material-components/material-components-android/issues/1774

**Closed by ymarian** 2020-10-21 20:54 UTC
Labels: bug

**Comment by Milszym** [comment] 2020-10-22 06:17
@ymarian Hey, I don't think that this is a duplicate.
This one is about not being able to choose between AM and PM hours.
I have added `colorPrimary` this way:
`<item name="colorPrimary">@color/yellow</item>`
 like you have suggested in [#1774](https://github.com/material-components/material-components-android/issues/1774), but there is still no way to select AM/PM.

Please see the following image after changing `colorPrimary` in `styles.xml`
![Screenshot 2020-10-22 at 08 16 05](https://user-images.githubusercontent.com/12632186/96832322-db050800-143e-11eb-8e98-20cecf5f96af.png)
