### ISSUE TITLE
[MaterialButton] app:icon is not visible in dynamic-feature-module when include .aar libs

### ISSUE THREAD

**Issue by Stroesku** [material-components/material-components-android#2581] opened 2022-02-25 09:57 UTC
I include in my-dynamic-delivery module - aar lib as dependencies
`implementation files('libs/sdk-2.0.11.aar')`
in this case MaterialButton inside my-dynamic-delivery and sdk-2.0.11.aar stops displaying icons in runtime
Example MaterialButton in xml:

```
<com.google.android.material.button.MaterialButton
android:id="@+id/history_close_action_view"
android:layout_width="50dp"
android:layout_height="50dp"
android:layout_gravity="center_horizontal"
android:rotation="-90"
android:textAppearance="@style/Theme.MaterialComponents"
android:theme="@style/Theme.MaterialComponents"
app:backgroundTint="@color/white"
app:icon="@drawable/ic_arrow_back"
app:iconTint="@color/black" />
```

  Pay attention to `app:icon="@drawable/ic_arrow_back"` I'm set icon in this MaterialButton and it is visible in preview, but in runtime is not.
  In this case not display absolute all drawable. I try specified @android:drawable, his same not visible.
  
  **Notice:** 
  This situation reproduced exactly when my-dynamic-delivery module is `com.android.dynamic-feature` and if I implement .aar to libs.
  In case when my-dynamic-delivery module is com.android.library all showing correct, and also when my-dynamic-delivery module is `com.android.dynamic-feature` but not implement sdk-2.0.11.aar - icon is visible in runtime.
   I've been trying to figure out what the problem is for a very long time, but haven't been able to. I've come to the conclusion that it's a library error com.google.android.material:material because all other libraries work correctly.
  
   
**About .aar sdk:** 
It is com.android.library and contain following dependencies in his gradle file:
```

apply plugin: 'com.android.library'
apply plugin: 'com.kezong.fat-aar'

apply plugin: "kotlin-android"
apply plugin: "kotlin-kapt"
apply plugin: "kotlin-parcelize"

apply plugin: "androidx.navigation.safeargs"
apply plugin: "koin"

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    // androidX
    api androidx.material
    api androidx.appcompat
    api androidx.activity
    api androidx.fragment
    api androidx.core
    api androidx.cardview
    api androidx.recyclerview
    api androidx.constraintlayout
    api androidx.webkit

    // google services
    api google.location
    api google.phone
    api google.play

    // lifecycle
    api lifecycle.extensions
    api lifecycle.runtime
    api lifecycle.common_java8
    api lifecycle.viewmodel
    api lifecycle.livedata

    // retrofit
    api retrofit.retrofit
    api retrofit.converter

    // background
    api background.coroutines_core
    api background.coroutines_android
    api background.work

    // navigation
    api navigation.fragment
    api navigation.ui

    // di
    api di.fragment
    api di.scope
    api di.viewmodel
    api di.ext

    // push
    api push.core
    api push.messaging

    // mlkit
    api mlkit.barcode
    api mlkit.face

    // image loader
    api image_loader.glide
    kapt image_loader.compiler

    //embedded/commons
    api(commons.socket) { exclude group: 'org.json', module: 'json' }
    api commons.commons_text

    embed fonts.calligraphy
    embed fonts.viewPump

    embed commons.signature_pad
    embed commons.round_imageview
    embed commons.scale_imageview
    embed commons.shortcut
    embed commons.permission
    embed commons.decoro

    embed(name: 'abbyy-rtr-sdk-1.0', ext: 'aar')
    embed(name: 'dtk_lib-1.0.8', ext: 'aar')
}
```

Actual result
![изображение](https://user-images.githubusercontent.com/62934250/155693894-abe6e728-836b-4109-8e2a-224856353b4c.png)

Expected result
![изображение](https://user-images.githubusercontent.com/62934250/155692028-251d423b-3176-446e-8aae-751ee579ef6c.png)

Android API version here: 29

**Material Library version:** Material Android Library version you are using here (1.3.0) also tested with 1.4.0 but result same

**Device:** Undependence of device. I use Samsung Galaxy A71 and Pixel 3.

**Comment by hunterstich** [comment] 2022-03-01 20:56
Hi @Stroesku,

This is strange. Do you have a sample that has the dynamic module that you can share which reproduces the issue?

I can't think of any reason off the top of my head why this might be happening. Does this happen with all/any drawable? What about if you use a Toolbar with a `navigationIcon` or another component that can be given a drawable?

**Comment by drchen** [comment] 2022-03-29 21:54
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-29 21:54 UTC
Labels: bug, Need more info
