### ISSUE TITLE
[TextInputEditText] Hint overlaps edittext

### ISSUE THREAD

**Issue by fcsd** [material-components/material-components-android#2060] opened 2021-02-11 15:36 UTC
**Description:** When edittext has focus hint doesn't up perfectly, it overlaps edittext. I use style FilledBox, same come with OutlinedBox works perfectly. 

<img width="293" alt="Screen Shot 2021-02-11 at 17 30 36" src="https://user-images.githubusercontent.com/17144698/107659333-b653cb00-6c8f-11eb-9188-0bf17fd5e803.png">

**Source code:** 
```
<com.google.android.material.textfield.TextInputLayout
                    android:id="@+id/layout_to"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:layout_marginStart="24dp"
                    android:layout_marginEnd="24dp"
                    android:hint="MY HINT"
                    style="@style/TextLayout">

                    <com.google.android.material.textfield.TextInputEditText
                        android:id="@+id/etSendTo2"
                        style="@style/EditText"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        />
                </com.google.android.material.textfield.TextInputLayout>

<style name="EditText">
        <item name="android:fontFamily">@font/golos_ui_regular</item>
        <item name="android:clickable">true</item>
        <item name="android:focusable">true</item>
        <item name="android:focusableInTouchMode">true</item>
        <item name="android:textSize">16sp</item>
        <item name="android:padding">12dp</item>
        <item name="colorControlNormal">@color/input_text</item>
        <item name="colorControlActivated">@color/dark_text</item>
        <item name="android:textColor">@color/input_text</item>
        <item name="android:background">@null</item>
    </style>

 <style name="TextLayout" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
        <item name="android:fontFamily">@font/golos_ui_regular</item>
        <item name="hintTextAppearance">@style/TextLayout.Hint</item>
        <item name="errorTextAppearance">@style/TextLayout.Error</item>
        <item name="endIconMode">clear_text</item>
        <item name="endIconDrawable">@drawable/ic_end_icon_close</item>
        <item name="hintEnabled">true</item>
        <item name="hintAnimationEnabled">true</item>
        <item name="boxBackgroundColor">@color/transparentColor</item>
    </style>

  <style name="PayCash.TextLayout.Hint" parent="TextAppearance.AppCompat.Small">
        <item name="android:textColor">@color/disable_text</item>
        <item name="android:fontFamily">@font/golos_ui_regular</item>
    </style>

    <style name="PayCash.TextLayout.Error" parent="TextAppearance.AppCompat.Small">
        <item name="android:textColor">@color/red_text</item>
        <item name="android:fontFamily">@font/golos_ui_regular</item>
        <item name="android:textSize">14sp</item>
    </style>

```

**Android API version:** any

**Material Library version:** 1.3.0
**Device:** any

**Comment by drchen** [comment] 2021-07-07 21:13
Is this still a problem on the latest library version?

**Comment by drchen** [comment] 2021-11-03 17:59
I'll close the issue due to no further information available. Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2021-11-03 17:59 UTC
Labels: bug
