### ISSUE TITLE
TextInputLayout  error hint animaiton

### ISSUE THREAD

**Issue by lencetanaskoska** [material-components/material-components-android#1275] opened 2020-05-05 09:49 UTC
When error is set on TextInputLayout if the TextInputEditText is empty and  there is no focus at the field the hint label doesn't slide down. (see screenshot). If there is no error, the hint animation works fine (the label slides down )
![Screen Shot 2020-05-05 at 11 46 33](https://user-images.githubusercontent.com/17854276/81053974-3c074680-8ec6-11ea-9a7a-d2f7a26326f5.png)

**Comment by malikbilal1997** [comment] 2020-05-05 23:03
[https://material.io/components/text-fields#anatomy](https://material.io/components/text-fields#anatomy)

> Error text
> For text fields that validate their content (such as passwords), replace helper text with error text when applicable. Swapping helper text with error text helps prevent new lines of text from being introduced into a layout, thus bumping content to fit it.
> 
> If only one error is possible, error text describes how to avoid the error
> If multiple errors are possible, error text describes how to avoid the most likely error

**Comment by lencetanaskoska** [comment] 2020-05-06 09:20
Please check the interactive demo (https://material.io/components/text-fields) 
Steps
1.  In configuration choose Assistive text -> Error text 
2. Click inside the text field so the text field has focus 
3.
![Screen Shot 2020-05-06 at 11 19 59](https://user-images.githubusercontent.com/17854276/81161219-869ec680-8f8b-11ea-9712-79b9b81c59f0.png)

4. Click outside the text filed so the text filed has NO focus 
![Screen Shot 2020-05-06 at 11 19 37](https://user-images.githubusercontent.com/17854276/81161200-7edf2200-8f8b-11ea-8a99-c433e16739a3.png)

Notice that when text field has no focus the label slides down  as in the screen shot above
Repeat this steps on Android : 
 on step 4 when the field has no focus the label is not placed down 
![Screen Shot 2020-05-06 at 11 01 52](https://user-images.githubusercontent.com/17854276/81159176-00818080-8f89-11ea-8505-c845172458b8.png)

**Comment by malikbilal1997** [comment] 2020-05-06 13:32
Adding this in Parent Layout may work for you 
`android:focusableInTouchMode="true"
android:clickable="true"
android:focusable="true"`

**Comment by gabrielemariotti** [comment] 2020-08-26 21:39
The same behavior can be reproduced with the catalog app.
<img width="303" alt="Schermata 2020-08-26 alle 23 30 54" src="https://user-images.githubusercontent.com/2583078/91359104-32e31200-e7f4-11ea-86e9-b657f7176da1.png">

**Comment by gabrielemariotti** [comment] 2020-09-17 16:07
Since the PR is merged I think the issue can be closed.

**Closed** 2022-02-17 22:46 UTC
