### ISSUE TITLE
[Material CardView] Preview fails to display layout when add CardView

### ISSUE THREAD

**Issue by maxrave-dev** [material-components/material-components-android#3199] opened 2023-01-31 11:45 UTC
**Description:** When I add CardView to any layout, my Android Studio preview layout can't display anything. 

**Expected behavior:**
- With CardView
![image](https://user-images.githubusercontent.com/113747128/215750918-6823483e-39bc-4e05-9659-22f01dc4172f.png)
- Without CardView
![image](https://user-images.githubusercontent.com/113747128/215751089-0611d3b7-3564-4942-88a5-1e26637e9119.png)

**Android API version:** 33

**Material Library version:** 1.8.0

**Device:** POCO M3

**Comment by dsn5ft** [comment] 2023-01-31 15:49
This is most likely the same root cause as #3007 and #3186 which has already been addressed by the Android Studio team.

The fix should be available in the latest [Canary build of Android Studio](https://developer.android.com/studio/preview).

**Closed by dsn5ft** 2023-01-31 15:49 UTC
Labels: bug
