### ISSUE TITLE
[BaseSlider] halo position is not updated when values are changed

### ISSUE THREAD

**Issue by j-ns** [material-components/material-components-android#1559] opened 2020-08-01 15:03 UTC
When the Slider is initialized e.g.
```
valueFrom = 0f
valueTo = 100f
stepSize = (valueTo - valueFrom) / 20 
values = listOf(newValue)  
```

and is updated to
```
valueFrom = 0f 
valueTo = 1000f
stepSize = (valueTo - valueFrom) / 20 
values = listOf(newValue)  
```

the halo position is not updated but remains on the last value position

**Material Library version:** 1.3.0-alpha02

![slider_halo_position_wrong](https://user-images.githubusercontent.com/18222843/89104313-cead7800-d418-11ea-9e54-b4c2d431737d.png)

**Comment by matpag** [comment] 2020-08-02 10:11
I've tried this:
```
final float number = 10F;
RangeSlider rangeSlider = view.findViewById(R.id.range_slider);
rangeSlider.setValueFrom(0F);
rangeSlider.setValueTo(100F);
rangeSlider.setStepSize((rangeSlider.getValueTo() - rangeSlider.getValueFrom()) / 20);
rangeSlider.setValues(number);

Button button = view.findViewById(R.id.button);
button.setOnClickListener(v -> {
    rangeSlider.setValueTo(1000F);
    rangeSlider.setValues(number);
});
```
and it worked fine. 
Can you add some details on what are you doing exactly?

**Comment by j-ns** [comment] 2020-08-02 13:23
Number 10f works for me as well. When I change it to 50f the halo is not updated.
The same effect occurs when I change the slider like:

```
valueFrom = 0f
valueTo = 1000f
stepSize = (valueTo - valueFrom) / 20 
values = listOf(50f) 

valueFrom = 0f
valueTo = 100f
stepSize = (valueTo - valueFrom) / 20 
values = listOf(50f)
```

Here is the function which updates my slider:
```
private fun onMaxValueChanged(value: Int) {
            val maxSliderValue = value.toFloat()
            val firstStepValue = maxSliderValue / 20

            binding.slider.apply {
                val firstValue = getValue(this, 0)!!
                val secondValue = getValue(this, 1)

                val newValues = mutableListOf(firstValue, secondValue)
                newValues[0] = MathUtils.clamp(firstValue, firstStepValue, maxSliderValue)

                if (secondValue != null) {
                    newValues[1] = MathUtils.clamp(secondValue, firstStepValue * 2, maxSliderValue)
                }
                if (newValues[0] == newValues[1]) newValues[0] = firstStepValue

                valueFrom = 0f
                valueTo = maxSliderValue
                stepSize = (valueTo - valueFrom) / 20
                values = newValues.mapNotNull { it }
            }
        }
```

**Comment by matpag** [comment] 2020-08-02 14:48
I tried with:
```
final float number = 50F;
RangeSlider rangeSlider = view.findViewById(R.id.range_slider);
rangeSlider.setValueFrom(0F);
rangeSlider.setValueTo(1000F);
rangeSlider.setStepSize((rangeSlider.getValueTo() - rangeSlider.getValueFrom()) / 20);
rangeSlider.setValues(number);

Button button = view.findViewById(R.id.button);
button.setOnClickListener(v -> {
    rangeSlider.setValueTo(100F);
    rangeSlider.setValues(number);
});
```
and it is working fine

**Comment by j-ns** [comment] 2020-08-02 15:09
I think I understood the halo behavior wrong. When the slider thumb is released, the halo is supposed to completely fade out. In my case the alpha channel was reduced to a value > 0, leaving the halo visible.
That seems to be caused by setting the focusable attributes of the slider to true:

```
<com.google.android.material.slider.RangeSlider  
       android:id="@+id/slider"    
       android:layout_width="match_parent"         
       android:layout_height="wrap_content"
       android:focusable="true" 
       android:focusableInTouchMode="true"   
       app:labelBehavior="gone"         />
```

Removing the lines solves the issue

**Comment by matpag** [comment] 2020-08-02 15:15
Why are you using 
```
android:focusable="true" 
android:focusableInTouchMode="true"
```
in the RangeSlider XML? Are they fixing something in your UI?

**Comment by j-ns** [comment] 2020-08-02 15:24
The Slider updates a TextField, which can also be updated via keyboard (this is propably not in line with Material Design spec, but it's working for my usecase). When the textField is focused I want to take the focus away, when the slider is activated.

**Comment by matpag** [comment] 2020-08-03 07:45
You probably are doing something wrong with Slider focus. Internally the `BaseSlider` uses this method:
https://github.com/material-components/material-components-android/blob/5fb796437291ce6b7d43b3beba13a42256db6eac/lib/java/com/google/android/material/slider/BaseSlider.java#L1327-L1338
to update the halo position.
Probably you are messing up the variable `focusedThumbIdx` which is used to update the halo.

Maybe you can try to solve your problem with some `onFocusChangeListener`s?

I think you need to post your full code and focus handling to try to fix the problem.

**Comment by j-ns** [comment] 2020-08-03 11:44
Updating the halo position is working fine, since I removed the focusable attributes. To move the focus away from the textfield I made the root layout focusable and request focus with `OnSliderTouchListener `:

```
addOnSliderTouchListener(object : RangeSlider.OnSliderTouchListener {
                     override fun onStartTrackingTouch(slider: RangeSlider) { 
                            binding.root.requestFocus()
                     }   
   })
```

**Comment by matpag** [comment] 2020-08-03 12:39
Perfect 👍 
If you think the issue is resolved you can close it

**Closed** 2020-08-03 12:47 UTC
Labels: bug
