### ISSUE TITLE
[BottomNavigationView] backgroundTint not working for white

### ISSUE THREAD

**Issue by deRonbrown** [material-components/material-components-android#3555] opened 2023-08-31 00:42 UTC
**Description:** White (i.e. `#FFFFFF`) is ignored when setting the background tint in XML. Other colors work as expected.

**Expected behavior:** The item background color is working as expected, but the container background color is not when drawing behind the gesture navigtation.

**Source code:**
This gets ignored
```
<com.google.android.material.bottomnavigation.BottomNavigationView
        style="?attr/bottomNavigationStyle"
        android:id="@+id/bottomNavView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        app:menu="@menu/bottom_nav_menu"
        app:itemBackground="@color/white"
        app:backgroundTint="#FFFFFF"/>
```
<img width="540" alt="Screenshot 2023-08-30 at 6 05 47 PM" src="https://github.com/material-components/material-components-android/assets/474564/8e001e20-4c63-4e0d-bb93-efa102a68e7c">

But here it is set as blue (i.e. `#000FFF`)
```
<com.google.android.material.bottomnavigation.BottomNavigationView
        style="?attr/bottomNavigationStyle"
        android:id="@+id/bottomNavView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        app:menu="@menu/bottom_nav_menu"
        app:itemBackground="@color/white"
        app:backgroundTint="#000FFF"/>
```
<img width="540" alt="Screenshot 2023-08-30 at 6 05 10 PM" src="https://github.com/material-components/material-components-android/assets/474564/74d0cac0-1681-4b3a-9443-fdd4087deba7">

**Android API version:** Android 13 & Android 14

**Material Library version:** 1.9.0

**Device:** Pixel 4, Pixel 7 Pro, Galaxy S21

**Comment by leticiarossi** [comment] 2023-08-31 17:41
Testing it out on our catalog everything works as expected in the most recent version of the library. Could you verify if it happens for you in the latest version? If so please attach a sample app where the issue is reproducible so we can investigate better

**Comment by leticiarossi** [comment] 2024-01-16 16:20
Closing this for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by leticiarossi** 2024-01-16 16:20 UTC
Labels: bug, Need more info, Widget: BottomNavigation
