### ISSUE TITLE
RangeSlider label not showing proper

### ISSUE THREAD

**Issue by sagarbhojaviya** [material-components/material-components-android#2235] opened 2021-06-02 13:15 UTC
**Description:** 
I am using Range slider in this label not getting show properly

**Expected behavior:** 
![image](https://user-images.githubusercontent.com/53989478/120485027-49487a80-c3d1-11eb-980a-f3029299626c.png)

**Source code:** 
  <com.google.android.material.slider.RangeSlider
                    android:id="@+id/sliderRange"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/dimen_30dp"
                    app:thumbStrokeColor="@color/colorLinkClick"
                    app:thumbStrokeWidth="1dp"
                    app:labelBehavior="floating"
                    app:thumbColor="@color/colorTheme"
                    android:valueFrom="0"
                    app:values="@array/rangeSliderValues"
                    android:valueTo="100"
                    app:haloColor="@android:color/transparent"
                    app:tickColor="@android:color/transparent"
                    android:value="20"
                    android:stepSize="5"
                    app:trackColor="@color/colorStepsLineUnselected"
                    />

**Android API version:** 
28

**Material Library version:**
   implementation 'com.google.android.material:material:1.4.0-beta01'

**Device:**
Honor 7x

**Comment by drchen** [comment] 2021-07-22 14:54
I can't reproduce the issue. Can you provide a simple reproducible app?

Also is the issue reproducible on different API levels or different devices?

**Comment by drchen** [comment] 2021-10-04 19:52
I'll close the issue due to no further info available. Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2021-10-04 19:52 UTC
Labels: bug
