### ISSUE TITLE
BottomSheetDragHandleView Shows Nothing

### ISSUE THREAD

**Issue by kozmotronik** [material-components/material-components-android#3178] opened 2023-01-19 07:27 UTC
https://github.com/material-components/material-components-android/blob/f2269bcd85dcbecab6c74168efa3c36ed549cee6/catalog/java/io/material/catalog/bottomsheet/res/layout/cat_bottomsheet_fragment.xml#L68

I'm trying to implement BottomSheetDragHandleView in my bottom sheet view. But similar to [this stackoverflow issue](https://stackoverflow.com/q/74987022/12749998) it shows nothing and when it wraps, it collapses to a 0 height. Aside from that stackoverflow question, my xml implementation is as following if it helps:
```xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context="ui.kumanda.KumandaYoneticisi">

    <data>
        <import type="com.himtec.himtec_kontrol.ui.kumanda.Kumanda"/>
        <import type="android.view.View"/>

        <variable name="kanalSayimi" type="int" />
    </data>

    <com.google.android.material.card.MaterialCardView
        android:id="@+id/kumandaMcvKok"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:checkable="false"
        android:clipChildren="false"
        android:clipToPadding="false"
        app:cardElevation="16dp"
        app:cardMaxElevation="16dp"
        app:shapeAppearanceOverlay="@style/ShapeAppearanceOverlay.RoundCorners.Top"
        app:behavior_peekHeight="@dimen/kumanda_peek_height"
        app:behavior_hideable="false"
        app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/kumandaClKok"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:clipChildren="false"
            android:clipToPadding="false">

            <com.google.android.material.bottomsheet.BottomSheetDragHandleView
                android:id="@+id/kumandaBsdhvKulp"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <com.google.android.material.textview.MaterialTextView
                android:id="@+id/kumandaMtvDurum"
                android:layout_width="0dp"
                android:layout_height="36dp"
                android:layout_marginTop="8dp"
                android:ellipsize="middle"
                android:gravity="center"
                android:padding="@dimen/him_card_content_padding_4dp"
                android:singleLine="true"
                android:text="@string/sc_bagliDegil"
                app:layout_constraintBottom_toTopOf="@+id/kumandaAyrac0"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/kumandaBsdhvKulp" />

            <View
                android:id="@+id/kumandaAyrac0"
                style="@style/Widget.Himtec.Divider.Horizontal"
                android:layout_width="0dp"
                app:layout_constraintBottom_toTopOf="@+id/kumandaTabLayout"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/kumandaMtvDurum" />

            <com.google.android.material.tabs.TabLayout
                android:id="@+id/kumandaTabLayout"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:contentDescription="@string/cd_kumandaKanalSecimSekmesi"
                android:visibility="@{kanalSayimi > 1 ? View.VISIBLE : View.GONE}"
                app:layout_constraintBottom_toTopOf="@+id/kumandaFragmentContainer"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/kumandaAyrac0"
                app:tabContentStart="@dimen/him_layout_margin_32dp"
                app:tabGravity="center"
                app:tabMode="scrollable" />

            <androidx.fragment.app.FragmentContainerView
                android:id="@+id/kumandaFragmentContainer"
                android:layout_width="0dp"
                android:layout_height="@dimen/him_kumanda_height"
                android:layout_marginTop="8dp"
                android:layout_marginBottom="8dp"
                android:clipChildren="false"
                android:clipToPadding="false"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/kumandaTabLayout"
                tools:layout="@layout/him_kumanda_bos">

            </androidx.fragment.app.FragmentContainerView>
        </androidx.constraintlayout.widget.ConstraintLayout>
    </com.google.android.material.card.MaterialCardView>
</layout>
```

**Comment by drchen** [comment] 2023-02-02 22:06
I cannot reproduce the issue on my end. Can you provide a minimal repro so we can debug on our end?

**Comment by freszu** [comment] 2023-02-08 17:29
Just ran into this issue:
This seem to happen when using m2 themes . For m2 theme `bottomSheetDragHandleStyle` is not defined and attributes from the BottomSheetDragHandleView:
```java
private static final int DEF_STYLE_RES = R.style.Widget_Material3_BottomSheet_DragHandle;
```
are not picked up for some reason.

Note!
Even if `bottomSheetDragHandleStyle` is defined and would be pointing to default m3 theme: 
```xml
<item name="bottomSheetDragHandleStyle">@style/Widget.Material3.BottomSheet.DragHandle</item>
```
It will crash as the tint color used in this style is defined only for m3 styles.

## Workaround:
define new style:
```xml
<style name="Widget.MaterialComponents.BottomSheet.DragHandle" parent="Widget.Material3.BottomSheet.DragHandle">
    <item name="tint">?colorOnSurface</item>
     <!--Alpha can be added optionally to achieve nice color blend-->
    <item name="android:alpha">0.3</item>
</style>
```

use it in your theme by adding:
```xml
    <item name="bottomSheetDragHandleStyle">@style/Widget.MaterialComponents.BottomSheet.DragHandle</item>
```

**Comment by drchen** [comment] 2023-02-08 17:39
Thanks @freszu for the report & workaround. I believe this is the right solution to this issue. : )

Since we deprecated M2 and there's a workaround for the issue, I'll close this as working as intended.

**Closed by drchen** 2023-02-08 17:39 UTC
Labels: bug, Need more info, Widget: BottomSheet

**Comment by kozmotronik** [comment] 2023-03-16 09:04
Hi guys I couldn't provide a minimal repro example in time because of the devastating earthquake occured in our country on 6 February. But seems like @freszu detected the problem and provided a solution so I will try it ASAP. Thanks.

**Comment by dlguswo333** [comment] 2024-12-15 09:27
Thank you, I'm a little bit too late to the discussion, But after changing codes from M2 to M3 the handle bar appears.
https://m3.material.io/blog/migrating-material-3
