### ISSUE TITLE
[com.google.android.material.tabs.TabLayout] tabMode="scrollable" not working when attached to fragment

### ISSUE THREAD

**Issue by kadaluarsa** [material-components/material-components-android#1884] opened 2020-11-19 01:12 UTC
**Description:** tab layout scrolling mode not working when FragmentStateAdapter attached to fragment.

**Expected behavior:** normally tab layout can scroll as FragmentStateAdapter attached to the activity.

**Source code:**  
<com.google.android.material.tabs.TabLayout
                android:id="@+id/sliding_tabs"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dimens_48dp"
                android:background="@color/white"
                app:tabGravity="fill"
                app:tabIndicatorColor="@color/colorPrimary"
                app:tabIndicatorHeight="@dimen/dimens_5dp"
                app:tabMode="scrollable"
                app:tabSelectedTextColor="@color/colorPrimary"
                app:tabTextAppearance="@style/AppTheme.CustomTab.Small"
                app:tabTextColor="@color/dark" />

class TabbedViewpagerAdapter(val fragments: MutableList<DataCategoryParent>, fa: Fragment) :
    FragmentStateAdapter(fa) {

    override fun getItemCount(): Int = fragments.size

    override fun createFragment(position: Int): Fragment {
        return TabbedCatalogueFragment.newInstanceTabbedCatalog(
            bundleOf(
                FILTERINGDATA to fragments[position].id.toString(),
                PAGE_SOURCE to fragments[position].name
            )
        )
    }
}

**Android API version:** API 29

**Material Library version:** com.google.android.material:material.1.1.0 but still exist in latest version.

**Device:** Nexus 6

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment] 2020-11-19 13:56
Could you please provide a sample app that reproduces this behavior?

**Comment by drchen** [comment] 2022-02-18 21:53
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-18 21:53 UTC
Labels: bug
