### ISSUE TITLE
[CollapsingToolbarLayout] When maxLines > 1 the Toolbar's title is duplicated if it has leading spaces

### ISSUE THREAD

**Issue by gpunto** [material-components/material-components-android#1828] opened 2020-10-27 16:55 UTC
**Description:**
When using a `Toolbar` inside a `CollapsingToolbarLayout` with `maxLines` > 1 and a title with leading spaces (e.g. " text"), the title is duplicated. One title is shown without leading spaces and the other one is shown with the spaces.

![Screenshot](https://user-images.githubusercontent.com/47775302/97334864-7f42e080-187d-11eb-84de-fd0a9713b73e.jpg)

**Expected behavior:**
The title is displayed correctly, without duplication.

**Source code:** 
```
<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.appbar.CollapsingToolbarLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/collapsing_toolbar_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:maxLines="2">

    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?android:attr/actionBarSize"
        app:title="   text" />

</com.google.android.material.appbar.CollapsingToolbarLayout>

```

**Android API version:** Android 10

**Material Library version:** 1.3.0-alpha03, but it's happening at least from 1.2.1

**Device:** Emulators (e.g. Pixel) and real devices (e.g. OnePlus 7 Pro)

**Comment by arok** [comment] 2020-11-29 20:18
Same for me but I'm using spannable and new line symbol

        ```
val span = SpannableStringBuilder().apply {
            bold { append("First line") }
            appendLine()
            append("second line")
        }
        binding.toolbar.title = span
```
<img width="361" alt="image" src="https://user-images.githubusercontent.com/155463/100552577-97a18300-32a1-11eb-8fdd-2b4cd0b26079.png">

**Comment by drchen** [comment] 2021-09-30 18:19
Closing the issue as it's a duplicate of https://github.com/material-components/material-components-android/issues/1754.

**Closed by drchen** 2021-09-30 18:19 UTC
Labels: bug
