### ISSUE TITLE
[Slider] ANR when Slider is in PopupWindow

### ISSUE THREAD

**Issue by agent10** [material-components/material-components-android#1257] opened 2020-04-28 19:30 UTC
**Description:** ANR when PopupWindow contains layout with Slider.
Trace:
>   at com.google.android.material.internal.ViewUtils.getContentView(ViewUtils.java:288)
  at com.google.android.material.slider.Slider.onAttachedToWindow(Slider.java:1284)
  at android.view.View.dispatchAttachedToWindow(View.java:17445)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)

**Expected behavior:** No ANR

**Source code:**
```kotlin
newCodeBtn.setOnClickListener {
   val v = LayoutInflater.from(requireContext()).inflate(R.layout.volume_popup_layout, null)
   val pw = PopupWindow(v, ViewGroup.LayoutParams.WRAP_CONTENT,   ViewGroup.LayoutParams.WRAP_CONTENT)
   pw.isOutsideTouchable = true
   pw.showAsDropDown(it)
            }
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@drawable/player_popup_background"
    android:orientation="horizontal">

    <ImageButton
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:background="?selectableItemBackgroundBorderless"
        app:srcCompat="@drawable/ic_subtitles" />

    <com.google.android.material.slider.Slider
        android:layout_width="300dp"
        android:layout_height="wrap_content"
        android:value="50"
        app:labelBehavior="gone"
        android:valueFrom="0"
        android:valueTo="100" />
</LinearLayout>
```

**Material Library version:** 1.2.0-alpha06

It seems that `ViewUtils.getContentView` is in endless loop and can't find "parent" for labels:
```java
@Override
  protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    // The label is attached on the Overlay relative to the content.
    for (TooltipDrawable label : labels) {
      label.setRelativeToView(ViewUtils.getContentView(this));
    }
  }
```
Tried to disable labels with app:labelBehavior="gone" but no luck.

**Comment by wcshi** [comment] 2020-04-28 21:17
Duplicate of https://github.com/material-components/material-components-android/issues/1195, fixed already synced out, should be in the next release.

**Comment by agent10** [comment] 2020-04-28 21:35
@wcshi Are you sure? I see the fix for #1195 is already in 1.2.0-alpha06 (d6501c9) but it seems it can be reproduced with another test case..

**Comment by hunterstich** [comment] 2020-04-28 22:58
Hey @agent10, what's the other test case you had in mind?

**Comment by agent10** [comment] 2020-04-29 03:26
@hunterstich With a PopupWindow:) I have it right now in 1.2.0-alpha06

**Comment by hunterstich** [comment] 2020-04-29 15:49
Oh oh got it. 

I copied your code into a project and can reproduce this on 1.2.0-alpha06 and am working on a fix. Thanks for reporting this.

**Comment by wcshi** [comment] 2020-05-12 16:21
Resolved in https://github.com/material-components/material-components-android/commit/b631ef697984c695e1a16b1017b30f035a7599ce

**Closed by wcshi** 2020-05-12 16:21 UTC
Labels: bug
