### ISSUE TITLE
[TabLayout] Tab font is being reset to Roboto (system default) while switching tabs

### ISSUE THREAD

**Issue by dimsuz** [material-components/material-components-android#965] opened 2020-01-31 14:52 UTC
**Description:** 

I have a custom TabLayout style in my theme:

```xml
<style name="BaseAppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
    <item name="tabStyle">@style/Widget.AppTheme.TabLayout</item>
</style>
<style name="Widget.AppTheme.TabLayout" parent="Widget.MaterialComponents.TabLayout">
  <item name="tabTextAppearance">@style/TextAppearance.AppTheme.Body</item>
  <item name="tabTextColor">?android:attr/textColorSecondary</item>
  <item name="tabSelectedTextColor">?attr/colorOnPrimary</item>
</style>
```
Notice it has a text appearance which uses custom ttf font I provided with the app. For this example I have set it to some exotic font. Font-family xml is at the end of this message.

I'll provide a screenshots and will annotate them below:

1. Here we see the first issue: **Selected tab doesn't use bold version of my custom font** although it is provided in the font family. Instead, it uses Roboto, which is the default system font
![screen1](https://user-images.githubusercontent.com/42920/73548512-9321f900-4449-11ea-8c45-5883a213255a.png)

2. Now I switch to another tab and we can see that **first tab's font is reset back to Roboto** too!
![screen2](https://user-images.githubusercontent.com/42920/73548518-96b58000-4449-11ea-97e1-a92b7889b1ac.png)

3. Now I switch back to first tab and the **last tab's font is replaced with Roboto**. It was correct one in the beginning.
![screen3](https://user-images.githubusercontent.com/42920/73548521-99b07080-4449-11ea-85fc-56d318af8bd0.png)

So each time I switch to some tab, its font is lost.

**Expected behavior:**
1. Font is not being reset on tab switch
2. Selected tab font uses weighted variant of the font from the font-family

**Android API version:** API 25

**Material Library version:** `1.1.0-rc01`

**Device:** Android Emulator API 25

Here's the font-family resource I used for this demo:

```xml
<font-family xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  tools:ignore="UnusedAttribute">
  <!-- How use and set fonts see wiki page "Fonts In Xml". -->

  <font
    android:font="@font/uncial_antiqua"
    android:fontStyle="normal"
    android:fontWeight="400"
    app:font="@font/uncial_antiqua"
    app:fontStyle="normal"
    app:fontWeight="400" />

  <font
    android:font="@font/uncial_antiqua_bold"
    android:fontStyle="normal"
    android:fontWeight="700"
    app:font="@font/uncial_antiqua_bold"
    app:fontStyle="normal"
    app:fontWeight="700" />

</font-family>
```

**Comment by juanm707** [comment] 2021-06-22 03:53
Any update on this? I have a similar issue where I change the selected tab's text color
`tabLayout.setTabTextColors(Color.parseColor("#727272"), Color.parseColor("#8E24AA"))`
and this changes the font as well.

**Comment by drchen** [comment] 2022-04-11 17:26
Is this still an issue? I cannot reproduce it on my end.

**Comment by drchen** [comment] 2022-04-26 20:07
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-04-26 20:07 UTC
Labels: bug, Need more info, Widget: Tab
