### ISSUE TITLE
[Chip] Unable to set chip text color

### ISSUE THREAD

**Issue by KseniaKrasotina** [material-components/material-components-android#1478] opened 2020-07-13 18:08 UTC
**Description:** Full description of issue here
I am using chip group and setting a style to customize colors:
```
    <style name="Colors_Widget.MaterialComponents.Chip.Choice" parent="Widget.MaterialComponents.Chip.Choice">
        <item name="chipBackgroundColor">@color/button_disposition_bg</item>
        <item name="chipStrokeWidth">1dp</item>
        <item name="android:textColor">@color/button_disposition_text</item>
        <item name="shapeAppearance">@drawable/button_disposition_shape</item>
    </style>
```
I faced with the problem - when my Chip is selected, background color is set properly, but I do not see the text.
My text color selector: 
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/colorPrimary" android:state_enabled="true" />
    <item android:color="@color/colorMain" android:state_selected="false"/>
    <item android:color="@color/colorPrimary" android:state_checked="true" />
    <item android:color="@color/colorMain" android:state_checked="false"/>
    <item android:color="@color/colorPrimary" android:state_selected="true" />
</selector>
```
My background selector
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/colorMain" android:state_selected="true" />
    <item android:color="@color/colorPrimary" android:state_enabled="true" />
</selector>
```

**Expected behavior:** Screenshots and/or description of expected behavior
When Chip is checked, the textColor = "@color/colorPrimary" , chipBackground = "@color/colorMain"    <item android:color="@color/colorMain" android:state_selected="true" />..

But the chip is completely painted over with the background color so I do not see the text on it. Chip text color and background color are the same =  "@color/colorMain"
**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** Android API version here
29
**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.3.0-alpha01
**Device:** Device on which the bug was encountered here
All devices
To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

Thank you in advance

**Comment by gabrielemariotti** [comment] 2020-07-15 06:41
You should use a selector like:
```

<selector xmlns:android="http://schemas.android.com/apk/res/android">

  <item android:color="..." android:state_enabled="true" android:state_selected="true"/>
  <item android:color="..." android:state_enabled="true" android:state_checked="true"/>
  <item android:color="..." android:state_enabled="true"/>
  <item android:color="..."/>

</selector>
```

**Comment by KseniaKrasotina** [comment] 2020-07-15 09:11
I have tried this way. It does not work for me. Chip becoming fully painted and text disappearing..For one moment I see the proper color, but text id disappearing fast..

**Comment by wcshi** [comment] 2020-07-28 18:26
Hi @KseniaKrasotina is this bug reproducible in a standalone app? If so, please share the app. Thanks!

**Comment by amiyo-biswas-mongia** [comment] 2021-04-24 06:06
Its a bug.

**Comment by mukkumukesh** [comment] 2021-06-03 06:07
After an update, the material lib from 1.0.0 to 1.3.0 chip text selector is not working as faced by @KseniaKrasotina . Please help

**Comment by wcshi** [comment] 2021-06-29 14:34
This commit has unblocked this bug, thanks @drchen 
https://github.com/material-components/material-components-android/commit/7adfd93d803e2797143ece017d67d7dee0392710#diff-bd0cf6ae9284df7cea48e0c1e68033f175619aed5eeea3d67a77d8fa9d8fa732

**Comment by drchen** [comment] 2021-07-08 17:33
Can't really reproduce the bug. Is this still an issue?

**Comment by drchen** [comment] 2021-10-04 19:44
I'll close the issue due to no further info available. Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2021-10-04 19:44 UTC
Labels: bug

**Comment by Anmol-Agrawal-Codes** [comment] 2023-06-06 18:17
still not working
