### ISSUE TITLE
[Theme] 1.2.0+ breaks ExtendedFloatingActionButton style in Bridge Theme

### ISSUE THREAD

**Issue by alan-camilo** [material-components/material-components-android#1780] opened 2020-10-06 17:01 UTC
**Description:** Since the 1.2.0-alpha01, the ExtendedFloatingActionButton style is broken with the theme Theme.MaterialComponents.Light.NoActionBar.Bridge. The issue is still here with 1.3.0-alpha03 version.

Maybe the issue is related with this one which has already been solved: [issues/740](https://github.com/material-components/material-components-android/issues/740)

**Expected behavior:**
With 1.1.0
![extendedfloatingactionbutton 1 1 0](https://user-images.githubusercontent.com/8865038/95235633-23e57b80-0806-11eb-8c6e-095bac787b22.png)

**Actual behavior**
Since 1.2.0-alpha01
![extended floating button 1 2 0](https://user-images.githubusercontent.com/8865038/95231457-76716880-0803-11eb-99da-84f212df90c3.png)

**Android API version:** Android Api 29

**Material Library version:** 1.2.0-alpha01 and +

**Comment by hunterstich** [comment] 2020-10-13 14:47
Hey @alan-camilo,

Can you post a full repository that reproduces this issue so we can look into it?

**Comment by alan-camilo** [comment] 2020-11-23 17:54
Hi @hunterstich 

a little month-delay to answer your demand, but here we are! I made a basic sample app which reproduce the style issue [https://github.com/alan-camilo/BasicSampleMaterial](https://github.com/alan-camilo/BasicSampleMaterial).

The project has two branches material-1.1.0 and material-1.2.1 to reproduce exactly the issue as presented in my original post.

**Comment by alan-camilo** [comment] 2021-03-22 17:28
up, the issue remains in 1.3.0

**Comment by drchen** [comment] 2022-05-18 13:41
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-05-18 13:41 UTC
Labels: bug, Widget: FloatingActionButton

**Comment by alan-camilo** [comment] 2022-05-19 09:22
Thanks, for the record I moved to material 1.3 by changing my theme from `Theme.MaterialComponents.Light.NoActionBar.Bridge` to `Theme.MaterialComponents.Light.NoActionBar`
