### ISSUE TITLE
MaterialDatePicker OK button is not visible

### ISSUE THREAD

**Issue by huize** [material-components/material-components-android#1602] opened 2020-08-10 06:08 UTC
This BUG appears only on the specific devices, the "OK" button is not visible.

#### Current behavior:
 Huawei P30
![61597040133](https://user-images.githubusercontent.com/2106901/89756146-46179180-db14-11ea-9039-0403b6642b8e.jpg)

#### Expected behavior:
Pixel 3:
![71597040166](https://user-images.githubusercontent.com/2106901/89756152-4ca60900-db14-11ea-8c74-946c21325dcb.jpg)

#### Source code:
```
 val datePicker =
                MaterialDatePicker.Builder.datePicker().setCalendarConstraints(
                    CalendarConstraints.Builder().setEnd(Date().time).build()
                ).build()
       
   datePicker.addOnPositiveButtonClickListener { newDateInMillis ->
              // do something
            }
   datePicker.showNow(supportFragmentManager!!, "datePicker")
```

**Comment by matpag** [comment] 2020-08-10 07:42
Can you try the latest version `1.3.0-alpha02` to see if the problem is still there?
Thank you

**Comment by wcshi** [comment] 2020-08-10 16:30
Duplicate of https://github.com/material-components/material-components-android/issues/1346

**Closed by wcshi** 2020-08-10 16:30 UTC
Labels: bug

**Comment by huize** [comment] 2020-08-11 09:01
> Duplicate of #1346
Not the same bug，I update the lib to 1.3.0-alpha02 。 this bug  bug still exists。

**Comment by huize** [comment] 2020-08-11 09:01
> Can you try the latest version `1.3.0-alpha02` to see if the problem is still there?
> Thank you

Not the same bug，I update the lib to 1.3.0-alpha02 。 this bug bug still exists。

**Comment by wcshi** [comment] 2020-08-11 17:59
According to https://www.gsmarena.com/huawei_p30-9530.php, Huawei p30 should have the following resolution:
1080 x 2340 pixels, 19.5:9 ratio (~422 ppi density)

@huize what font size are you using in your custom style? A screenshot of your layout inspector view would be helpful.

**Comment by huize** [comment] 2020-08-12 02:17
> According to https://www.gsmarena.com/huawei_p30-9530.php, Huawei p30 should have the following resolution:
> 1080 x 2340 pixels, 19.5:9 ratio (~422 ppi density)
> 
> @huize what font size are you using in your custom style? A screenshot of your layout inspector view would be helpful.

@wcshi  This bug occurred on a device of a user from Google play,i just set the activity style. cutive font downloaded from google fonts
```
<style name="AppTheme" parent="Theme.MaterialComponents.Light">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:fontFamily">@font/cutive</item>
    </style>
```

**Comment by huize** [comment] 2020-08-17 05:30
> According to https://www.gsmarena.com/huawei_p30-9530.php, Huawei p30 should have the following resolution:
> 1080 x 2340 pixels, 19.5:9 ratio (~422 ppi density)
> 
> @huize what font size are you using in your custom style? A screenshot of your layout inspector view would be helpful.

@wcshi 
![121597642003](https://user-images.githubusercontent.com/2106901/90360253-d2363580-e08d-11ea-982e-823db4d20ffb.jpg)

**Comment by wcshi** [comment] 2020-08-17 20:04
@huize could you please help verify
1) value of @android:string/ok in that English locale, maybe try overriding it
2) Try TimePicker and let us know if the OK button is similarly cut off
