### ISSUE TITLE
[MaterialAlertDialog] Can't edit shapeAppearance to change corner

### ISSUE THREAD

**Issue by baillyjamy** [material-components/material-components-android#1429] opened 2020-06-22 02:42 UTC
**Description:** I want to add corner to a MaterialAlertDialog but impossible to change this attribute. I followed instructions on [material documentation](https://material.io/develop/android/components/dialogs/#theming-dialogs). I literally do the same thing on my style just to see if it work. Color change but not shape.

**Expected behavior:** Have same corner as exemple on [material documentation](https://material.io/develop/android/components/dialogs/#theming-dialogs) just to see it work

**Source code:** 
```xml
<style name="ThemeOverlay.App.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="colorPrimary">@color/lightGreen</item>
        <item name="colorSecondary">@color/lightGreen</item>
        <item name="colorSurface">@color/lightGreen</item>
        <item name="colorOnSurface">@color/lightGreen</item>
        <item name="alertDialogStyle">@style/MaterialAlertDialog.App</item>
        <item name="materialAlertDialogTitleTextStyle">@style/MaterialAlertDialog.App.Title.Text</item>
        <item name="buttonBarPositiveButtonStyle">@style/Widget.App.Button</item>
        <item name="buttonBarNeutralButtonStyle">@style/Widget.App.Button</item>
    </style>

    <style name="MaterialAlertDialog.App" parent="MaterialAlertDialog.MaterialComponents">
        <item name="shapeAppearance">@style/ShapeAppearance.App.MediumComponent</item>
    </style>

    <style name="MaterialAlertDialog.App.Title.Text" parent="MaterialAlertDialog.MaterialComponents.Title.Text">
        <item name="android:textColor">@color/@color/lightGreen</item>
    </style>

    <style name="Widget.App.Button" parent="Widget.MaterialComponents.Button.TextButton.Dialog">
        <item name="shapeAppearance">@style/ShapeAppearance.App.SmallComponent</item>
    </style>

    <style name="ThemeOverlay.App.Button" parent="">
        <item name="colorPrimary">@color/lightGreen</item>
    </style>

    <style name="ShapeAppearance.App.MediumComponent" parent="ShapeAppearance.MaterialComponents.MediumComponent">
        <item name="cornerFamily">cut</item>
        <item name="cornerSize">8dp</item>
    </style>

    <style name="ShapeAppearance.App.SmallComponent" parent="ShapeAppearance.MaterialComponents.SmallComponent">
        <item name="cornerFamily">cut</item>
        <item name="cornerSize">4dp</item>
    </style>
```

```kotlin
class PersonalNoteDialogFragment : DialogFragment() {

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        return requireActivity().let { activity ->
            val builder = AlertDialog.Builder(ContextThemeWrapper(activity, R.style.ThemeOverlay_App_MaterialAlertDialog))
            val inflater = requireActivity().layoutInflater
            builder.apply {
                setView(inflater.inflate(R.layout.dialog_personal_note, LinearLayout(context), false))
                setTitle(R.string.dialog_personal_note_title)
                setPositiveButton(R.string.dialog_add) { _, _ ->
                }
                setNeutralButton(R.string.dialog_cancel) { _, _ ->
                }
                setNegativeButton(R.string.dialog_erase) { _, _ ->
                }
            }
            builder.create()
        }
    }
}
```

**Android API version:** Android API 29

**Material Library version:** 1.3.0-alpha01 or 1.2.0-beta01

**Device:** all devices

**Comment by gabrielemariotti** [comment] 2020-06-22 09:07
You can use:

```
    <style name="ThemeOverlay.App.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
        <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.App.MaterialAlertDialog</item>
    </style>

    <style name="ShapeAppearanceOverlay.App.MaterialAlertDialog" parent="">
        <item name="cornerFamily">cut</item>
        <item name="cornerSize">16dp</item>
    </style>
```

**Comment by baillyjamy** [comment] 2020-06-23 07:53
> I confirm the issue.
> 
> In the meanwhile you can use:
> 
> ```
>     <style name="ThemeOverlay.App.MaterialAlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">
>         <item name="shapeAppearanceOverlay">@style/ShapeAppearanceOverlay.App.MaterialAlertDialog</item>
>     </style>
> 
>     <style name="ShapeAppearanceOverlay.App.MaterialAlertDialog" parent="">
>         <item name="cornerFamily">cut</item>
>         <item name="cornerSize">16dp</item>
>     </style>
> ```

Unfortunately, that doesn't change anything.

**Comment by gabrielemariotti** [comment] 2020-06-23 10:24
@baillyjamy 

Did you try the style?

<img width="299" alt="Schermata 2020-06-23 alle 11 56 55" src="https://user-images.githubusercontent.com/2583078/85392873-6d0e0a00-b54c-11ea-9c3d-29c33683923e.png">

**Comment by baillyjamy** [comment] 2020-06-24 02:51
Yeah, that's what I'm trying to do.
I've prepared a [repository](https://github.com/baillyjamy/material_dialog_corner_issue) that reproduces my issue, maybe I missed something.

**Comment by gabrielemariotti** [comment] 2020-06-24 06:17
@baillyjamy  You are using `AlertDialog.Builder` instead of ` MaterialAlertDialogBuilder`

**Comment by baillyjamy** [comment] 2020-06-24 06:33
Oh sorry ! Bad habit, I didn't even realize it.
Your snippet works, but mine don't, which comes from the documentation. So I don't know if I have to close the issue.

**Comment by gabrielemariotti** [comment] 2020-06-24 06:38
My snippet is only a workaround using `shapeAppearanceOverlay`.    
I think that there is in any case a issye with `shapeAppearance`.

**Comment by procmixin** [comment] 2021-03-16 08:20
After switching to `MaterialAlertDialogBuilder`, try setting 
<br>`<item name="materialAlertDialogTheme">@style/ThemeOverlay.App.MaterialAlertDialog</item>`<br><br>in your `theme.xml` <br>under the "_AppTheme_" style.

**Comment by drchen** [comment] 2021-11-02 20:16
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:16 UTC
Labels: bug, Need more info
