### ISSUE TITLE
[BottomNavigationView] `onNavigationItemSelected` is not called on restoring state

### ISSUE THREAD

**Issue by perqin** [material-components/material-components-android#3043] opened 2022-10-21 17:20 UTC
**Description:**

 On restoring activity state, the selection state gets restored, but the `onNavigationItemSelected` callback doesn't get called.

**Expected behavior:**

 The `onNavigationItemSelected` callback should also be called.

**Source code:**

```kotlin
class MainActivity : AppCompatActivity(), BottomNavigationView.OnNavigationItemSelectedListener {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        bottomNavigationView.setOnItemSelectedListener(this)
        bottomNavigationView.selectedItemId = R.id.menuItem_views
    }

    override fun onNavigationItemSelected(item: MenuItem): Boolean {
        return when(item.itemId) {
            R.id.menuItem_views -> {
                // loadFragment(ViewsFragment.newInstance())
                true
            }
            R.id.menuItem_settings -> {
                // loadFragment(SettingsFragment.newInstance())
                true
            }
            else -> false
        }
    }
}
```

In the above code, if the user is staying in `SettingsFragment` (the second tab) and leaves and goes back later, the `SettingsFragment` doesn't get loaded because the callback is not called. However, the second tab is selected.

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 33

**Material Library version:** 1.8.0-alpha01

**Device:** Pixel 3

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment] 2022-11-18 21:25
I feel this is working as intended. The callback should only be called when a navigation item is explicitly selected. If we invoke the callback during state restoration it can actually introduce unwanted side effect because we have no idea if the callback will affect a state that's also being restored.

In your case, shouldn't your showing fragments being automatically recreated? If not, the best approach here is properly implementing your own state restoration logic to cover that case. 

I'll close this as won't fix.

**Closed by drchen** 2022-11-18 21:25 UTC
Labels: bug
