### ISSUE TITLE
[TextInputLayout] notch styling attribute is making view glitched

### ISSUE THREAD

**Issue by andrzejbogacz** [material-components/material-components-android#1441] opened 2020-06-24 18:05 UTC
**Description:** <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
at level 27 and above which is making background drawn on both sides of top notch, is making the effect attached below.

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:**" < item name="android:windowLayoutInDisplayCutoutMode">shortEdges < /item>"

**Android API version:** 27 above ( with notch available )

**Material Library version:** 1.1.0 but the same on 1.2 beta and 1.3 alpha

![textInputLayout](https://user-images.githubusercontent.com/30546097/85609077-9ebaca00-b64d-11ea-9e71-cfd2c3bd299d.png)

**Comment by drchen** [comment] 2022-02-18 19:23
Can you provide a screenshots of whole screens and the layout file you are using?

**Comment by drchen** [comment] 2022-02-18 19:45
Maybe a duplicate of #1500

**Comment by drchen** [comment] 2022-03-16 19:01
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-16 19:01 UTC
Labels: bug, Need more info
