### ISSUE TITLE
[Checkbox] setCheckedState sets wrong drawable

### ISSUE THREAD

**Issue by ChrzaszczykKamil** [material-components/material-components-android#3282] opened 2023-03-02 17:14 UTC
**Description:** When setCheckedState is called with STATE_INDETERMINATE, the drawable is being unchecked rather than set to indeterminate. The value is actually correct.

**Source code:**
```
MaterialCheckBox testBTN = findViewById(R.id.tes);
testBTN.setCheckedState(MaterialCheckBox.STATE_CHECKED);
System.out.println(testBTN.getCheckedState()); //1   -  drawable is checked and has the "v" sign
testBTN.setCheckedState(MaterialCheckBox.STATE_INDETERMINATE);
System.out.println(testBTN.getCheckedState());//2   -  drawable is unchecked rather than being "-"
```

**Android API version:** 33

**Material Library version:** 1.8.0

**Device:** Pixel 4a emulator (same thing on pixel 6a)

**Comment by leticiarossi** [comment] 2023-04-25 16:27
I'm not able to reproduce the issue. It works as expected when I try on api 33. Could you provide a sample app where the issue happens for you?

**Comment by leticiarossi** [comment] 2023-08-29 21:20
Closing due to no further info available. Please feel free to reopen with a sample app it if this is still happening in the most recent available version of the library

**Closed by leticiarossi** 2023-08-29 21:20 UTC
Labels: bug, Need more info, Widget: Checkbox
