### ISSUE TITLE
[MaterialDatePicker] Day numbers not translated

### ISSUE THREAD

**Issue by MazyNoc** [material-components/material-components-android#1403] opened 2020-06-12 12:01 UTC
**Description:** The numbers in the calendar are not translated to the selected language.

**Expected behavior:** 
DateSelector in Google Calendar : 
![Screenshot_1591962188](https://user-images.githubusercontent.com/8349346/84500588-26e7b980-acb5-11ea-93e5-20e90308c363.png)

Date selector from Material Design : 
![Screenshot_1591962176](https://user-images.githubusercontent.com/8349346/84500628-3830c600-acb5-11ea-976b-a261ca164439.png)

**Android API version:** 29

**Material Library version:** 1.3.0-alpha01

**Device:** Android phone

**Comment by matpag** [comment] 2020-06-12 21:06
Check here: https://github.com/material-components/material-components-android/issues/761
There are missing translations currently, you need to provide them by your own until this is fixed.

**Comment by gabrielemariotti** [comment] 2020-08-14 19:04
Duplicate of #761

**Closed** 2020-08-17 13:48 UTC
Labels: bug
