### ISSUE TITLE
[MaterialAlertDialogBuilder] Creating MaterialAlertDialogBuilder crashes with ThemeEnforcement when using webview

### ISSUE THREAD

**Issue by alashow** [material-components/material-components-android#1204] opened 2020-04-12 14:50 UTC
**Description:** Creating instance of MaterialAlertDialogBuilder causes the app crash with error message: ```java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).```

Weirdly enough, there are 2 conditions for it:
1. Web view in Activity view or fragment.
2. Using a wrapper for resources in `Activity.getResources`.  Like:
```kotlin 
override fun getResources(): Resources {
      return AppResources(super.getResources())
}
class AppResources(res: Resources) : Resources(res.assets, res.displayMetrics, res.configuration)
```

**Android API version:** 8.1 (it doesn't crash in 10 or R)

**Material Library version:** 1.2.0-alpha05

**Device:** Android Emulator Android 8.1

[ThemeEnforcementCrash.zip](https://github.com/material-components/material-components-android/files/4466503/ThemeEnforcementCrash.zip)

**Comment by shaikfaizal** [comment] 2020-04-21 07:26
Same issue for me  
library:   "com.google.android.material:material:$googleMaterial"
version: '1.2.0-alpha06'

**Comment by dsn5ft** [comment] 2020-04-21 19:10
Hi @alashow, can you explain the purpose of the getResources() override?

**Comment by alashow** [comment] 2020-04-21 19:14
@dsn5ft I was using https://github.com/B3nedikt/AppLocale when I found this bug and I think it was using it to set locale when resources requested.

**Comment by hantrungkien** [comment] 2020-04-25 16:07
Same issue for me with Localization library: https://github.com/akexorcist/Android-Localization

```
implementation 'androidx.core:core-ktx:1.2.0'
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'com.google.android.material:material:1.2.0-alpha06'
```

Simple layout: main_activity.xml:

```
<LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:padding="10dp">

        <WebView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:layout_marginBottom="10dp" />

        <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/input_current_password_layout"
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/input_current_password"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="textPassword"
                android:maxLines="1"
                android:singleLine="true"
                android:textColor="@android:color/black"
                android:textSize="15sp" />
        </com.google.android.material.textfield.TextInputLayout>
    </LinearLayout>
```

Log crash:

```
 Process: com.akexorcist.localizationapp, PID: 31750
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.akexorcist.localizationapp/com.akexorcist.localizationapp.MainActivity}: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class com.google.android.material.textfield.TextInputLayout
...
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
        at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
```

**Comment by hantrungkien** [comment] 2020-04-25 16:51
@alashow https://github.com/material-components/material-components-android/issues/1204

**Comment by wcshi** [comment] 2020-04-28 19:40
@alashow  could you please verify that @hantrungkien's PR fixes your crash?

**Comment by alashow** [comment] 2020-04-28 19:51
@wcshi I didn't have this problem with [akexorcist/Android-Localization](https://github.com/akexorcist/Android-Localization) but with  [B3nedikt/AppLocale](https://github.com/B3nedikt/AppLocale).

**Comment by wcshi** [comment] 2020-04-28 21:19
Could you please file an issue on akexorcist/Android-Localization and point them to the PR?
We are not convinced this is a bug in the Material android lib.

**Comment by hantrungkien** [comment] 2020-04-29 12:17
@wcshi I have tested on android 7 and android 9. This PR also have merged.

This is not a bug in the Material library. This error occurs because when changing the configuration, some developers have created new Resource objects. This causes the application's default theme to be changed and causes the Material library to throw an error.

**Comment by wcshi** [comment] 2020-04-29 14:19
Marking this as closed since it's not a bug in the library.

**Closed by wcshi** 2020-04-29 14:19 UTC
Labels: bug
