### ISSUE TITLE
[BottomNavigationView] Ability to set custom color for inactive items

### ISSUE THREAD

**Issue by TacoTheDank** [material-components/material-components-android#2138] opened 2021-03-17 23:46 UTC
**Is your feature request related to a problem? Please describe.**
Well, [here](https://imgur.com/a/8kBcYOO) is a video. Pay attention to the BottomNavigationView and see how it changes from grey to that shade of blue.

**Describe the solution you'd like**
I want to keep the grey tinting. I think there should be a styleable or set of styleables specifically for this purpose (relevant: https://github.com/material-components/material-components-android/issues/1291).

**Describe alternatives you've considered**
I've tried many things from StackOverflow (namely [this](https://stackoverflow.com/questions/40325422/selected-tabs-color-in-bottom-navigation-view) and [this](https://stackoverflow.com/questions/38799535/how-to-change-inactive-color-on-bottom-navigation); the color just lasts a second and reverts back to the color chosen by BottomNavigationView's textColorSecondary). Perhaps it's something on my end. I do not know. It is possible that the items are being re-updated when the tab is being chosen. In any case, there should be an official way to stylize inactive items. Having to use theming or a selector color resource as a workaround isn't exactly ideal or very dev-friendly.

**Additional context**
The source code for the app used in the video: https://gitlab.com/TacoTheDank/APKMirror
The relevant code is within the main activity and layout.

**Comment by imhappi** [comment] 2022-05-17 00:30
Duplicate of https://github.com/material-components/material-components-android/issues/1291

**Closed by imhappi** 2022-05-17 00:30 UTC
Labels: feature request, Good First Issue, Widget: BottomNavigation
