### ISSUE TITLE
Font family not working in 1.2.0

### ISSUE THREAD

**Issue by UzBestDeveloper** [material-components/material-components-android#1592] opened 2020-08-08 07:10 UTC
While implementing implementation 'com.google.android.material:material:1.1.0' in xml font-family works fine on device.
 but implementation 'com.google.android.material:material:1.2.0' font not changes while running on device

**Comment by gabrielemariotti** [comment] 2020-08-08 08:04
Can you provide an example?

**Comment by verNANDo57** [comment] 2020-08-09 05:05
> While implementing implementation 'com.google.android.material:material:1.1.0' in xml font-family works fine on device.
>  but implementation 'com.google.android.material:material:1.2.0' font not changes while running on device

Hello. I'm using 1.2.0 version of library and everything works good (except Bottom App  Bar ¯\_ (ツ) _/¯ )

Here is my code:

styles.xml: 

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light>
    <item name="fontFamily">@font/app_fontfamily</item>
     <item name="android:fontFamily" tools:targetApi="jelly_bean">@font/app_fontfamily</item>
```

P.s you must create "font" folder in resources with app_fontfamily.xml and .ttf fonts inside the folder.

Hope this will help you

**Comment by wcshi** [comment] 2020-08-10 17:34
Could you please explain what is "not working"? Is the font not rendering properly in Bottom App Bar?

Detailed reproducible steps or a standalone sample app would be very helpful.

**Comment by verNANDo57** [comment] 2020-08-11 05:14
> Could you please explain what is "not working"? Is the font not rendering properly in Bottom App Bar?
> 
> Detailed reproducible steps or a standalone sample app would be very helpful.

@wcshi , If you asked me, please check this post -> https://github.com/material-components/material-components-android/issues/1591

**Comment by wcshi** [comment] 2020-08-11 14:12
@verNANDo57 please help me understand how these two issues are related? Are you suggesting that the font family is causing the FAB to be misaligned?

**Comment by drchen** [comment] 2022-02-18 20:17
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-18 20:17 UTC
