### ISSUE TITLE
[ExposedDropDownMenu] Changes keyboard input type even if non-editable

### ISSUE THREAD

**Issue by alaershov** [material-components/material-components-android#1143] opened 2020-03-25 07:15 UTC
**Description:** I have a non-editable ExposedDropDownMenu (`country`) and a regular TextInputLayout below it (`phone`), with `inputType="phone"`. When `phone` input layout is focused, the keyboard is open and shows big digit keys. I tap on the `country` dropdown, and the keyboard remains open, but suddenly changes to regular text input type.

**Expected behavior:** The keyboard should hide or maybe stay in the same input type as before the click on dropdown menu.

**Source code:** https://gist.github.com/alaershov/e85222cdddef99b14059088247655615

**Android API version:** 29

**Material Library version:** 1.1.0, 1.2.0-alpha05

**Device:** Nokia 6.1

**Comment by rafid059** [comment] 2020-03-26 12:28
Problem 1: Hide keyboard when clicked on ExposedDropDownMenu if `inputType` is `none` and is supposed to work like a non-editable dropdown menu.
Solution: Just having `inputType = none` in xml doesn't work. In addition to that, you need to update `inputType` in code too.
```
(input_layout_country.editText as AutoCompleteTextView).inputType = EditorInfo.TYPE_NULL
```

Problem 2: Hide keyboard when focus from other TextInputLayout changes to the ExposedDropDownMenu
Solution: Add a view focus change listener on the dropdown menu and hide the keyboard
```
edit_text_country.onFocusChangeListener = View.OnFocusChangeListener { v: View?, hasFocus ->
    if (hasFocus) {
        hideKeyboard()
    }
}
```

**Comment by rafid059** [comment] 2020-04-17 09:05
Problem 1 from above comment is fixed in 1.2.0-alpha06 with [MaterialAutoCompleteTextView](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/MaterialAutoCompleteTextView.java). But the problem 2 is still there.

**Comment by Antimonit** [comment] 2020-06-19 16:05
Be careful with the `onFocusChangeListener`. I've spent hours today finding out why this approach does not work in our app.

Turned out that setting the `endIconMode = TextInputLayout.END_ICON_DROPDOWN_MENU` internally calls `DropdownMenuEndIconDelegate#setUpDropdownShowHideBehavior` which sets custom `OnFocusChangeListener`, effectively invalidating our custom listener :(

**Comment by KdB13** [comment] 2020-09-08 11:19
> Problem 1 from above comment is fixed in 1.2.0-alpha06 with [MaterialAutoCompleteTextView](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/MaterialAutoCompleteTextView.java). But the problem 2 is still there.

There is a correction. Problem 1 was fixed in version **1.3.0-alpha02**. See this https://github.com/material-components/material-components-android/commit/d1850a3d78f5cb124db21c2a0156a528d653ab17

**Comment by KdB13** [comment] 2020-09-08 12:21
@Antimonit I have set a custom `OnFocusChangeListener` and the code is working fine. The keyboard hid.

However, there is a small UI glitch where the **displayed list of items in dropdown** resizes just after the keyboard is hidden.

**Comment by drchen** [comment] 2022-05-04 21:10
I'll close the issue for now since this seems to be fixed. Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2022-05-04 21:10 UTC
Labels: bug, Widget: TextField
