### ISSUE TITLE
[TextInputEditText] The cursor stays at the beginning and addTextChangeListener is never triggered. Temporary fix: inputType="text", but doesn't work on anything else.

### ISSUE THREAD

**Issue by pesjak** [material-components/material-components-android#1894] opened 2020-11-22 12:47 UTC
**Description:** If you use TextInputLayout with TextInputEditText, the Cursor stays at the start and doesn't move at the end of text when writing, but is fixed at the beginning. It works if you put inputType as text, but it doesn't work for anything else. For example multiline. The textchangelistener is called only if you set the text programatically.

**Expected behavior:** Cursor follows last character when writing text.

**Source code: 

```
        binding.textInputEditText.addTextChangedListener {
            if (it != null) binding.buttonNext.isEnabled = it.trimmedLength() > 0
        }



    <com.google.android.material.textfield.TextInputLayout
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="32dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/constraintLayout">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/text_input_edit_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:imeOptions="actionNone"
            android:focusable="true"
            android:focusableInTouchMode="true"
            android:inputType="textMultiLine"
            android:minLines="3"
            android:lines="4"
            android:maxLines="8"
            android:gravity="top|start"
            android:hint="@string/creator_description_hint" />

    </com.google.android.material.textfield.TextInputLayout>

```

**Android API version:** 30

**Material Library version:** 1.3.0-alpha03

**Device:** OnePlus 6T

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by KousalyaRaj** [comment] 2021-02-11 06:58
Found a fix?

**Comment by drchen** [comment] 2022-06-16 19:07
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed** 2022-07-01 18:43 UTC
Labels: bug, Need more info, Widget: TextField

**Comment by roozbehzarei** [comment] 2022-10-10 06:52
The issue is still present. In my case the layout is RTL and the `inputType` is set to `number`. Now when the user clicks on the `TextInputEditText` inside a `TextInputLayout` and starts typing, the cursor gets split in half (the upper half stays in the beginning and the lower half moves to the end of input). The typing is working as expected but when you select the end of the input, you can't remove the input by pressing backspace, instead you have to select the beginning of the input to do it.
