### ISSUE TITLE
[MaterialDatePicker] Cannot get the first selected value after device rotation

### ISSUE THREAD

**Issue by shubham08gupta** [material-components/material-components-android#2302] opened 2021-07-15 06:21 UTC
**Description:** With the date picker already shown, after the screen is rotated, the first selected value is not obtained. After that, it works normally. 
I show a Toast whenever a value is selected. But the Toast is not shown after the screen rotation when the first value is selected. From second selection and so on, it works normally.

https://user-images.githubusercontent.com/7660565/125738939-6b8d9c17-413d-4b8a-8628-588e03fb6ecb.mp4

**Expected behavior:** MaterialDatePicker should work regardless of screen rotation.

**Source code:** 
```
val picker = MaterialDatePicker.Builder.datePicker()
            .setSelection(MaterialDatePicker.todayInUtcMilliseconds())
            .build()
        picker.addOnPositiveButtonClickListener { selectedValue ->
            Toast.makeText(requireContext(), "$selectedValue", Toast.LENGTH_SHORT).show()
        }
        picker.show(childFragmentManager, picker.toString())
```

Even `picker.selection` does not work.

**Android API version:** 30

**Material Library version:** 1.4.0

**Device:** Google Pixel 3a Android 11, API 30

**Comment by paulfthomas** [comment] 2021-07-22 18:05
Duplicate of https://github.com/material-components/material-components-android/issues/1688

**Closed by paulfthomas** 2021-07-22 18:05 UTC
Labels: Good First Issue, bug
