### ISSUE TITLE
Unable to find method 'org.gradle.api.internal.artifacts.ivyservice

### ISSUE THREAD

**Issue by Coners** [material-components/material-components-android#464] opened 2019-07-24 09:01 UTC
**Description:** Cannot Sync Build initial Clone

**Expected behavior:** Sync and Build is necessary to get started

**Source code:** n/a

**Android API version:** no idea

**Material Library version:** latest - (I just cloned it) no idea

**Device:** Windows Android Studio

this is the error:

Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry.registerPublication(Ljava/lang/String;Lorg/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublication;)V'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

![image](https://user-images.githubusercontent.com/49714898/61780180-f4fa0a00-adf9-11e9-94ae-5f699d9b8f6d.png)

**Comment by dsn5ft** [comment] 2019-07-24 14:15
Duplicate of #401 and #375.

You'll have to revert any local changes you have, specifically your `gradle-wrapper.properties` [file](https://github.com/material-components/material-components-android/blob/master/gradle/wrapper/gradle-wrapper.properties) should be using Gradle 4.6, and your `build.gradle` [file](https://github.com/material-components/material-components-android/blob/master/build.gradle) should be using `com.android.tools.build:gradle:3.3.2`.

**Closed by dsn5ft** 2019-07-24 14:15 UTC
Labels: bug

**Comment by roncsak** [comment] 2019-08-26 13:04
Well, when I change the gradle to 4.6, the following occurs:
`ERROR: Minimum supported Gradle version is 4.10.1. Current version is 4.6.`

I just cloned the repo and using Master (322cbaa) where version 4.10.1 is defined but it won't work because:
`ERROR: The specified Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.1-all.zip' does not appear to contain a Gradle distribution.`

However I could make it work with gradle version 4.10.2

**Comment by danielwilson1702** [comment] 2020-01-06 13:26
This looks to still be the case

**Comment by good-good-study** [comment] 2020-05-16 14:50
Hi, has this problem been solved? I now have the same problem as you

**Comment by Coners** [comment] 2020-05-16 15:59
this was a long time ago, it was (if I recall correctly) one of the dependencies being out of date in the build.gradle and also I added
```
android {
     compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by nisanc** [comment] 2024-05-06 14:37
I am so over gradle
