### ISSUE TITLE
[TextInputLayout] OutlinedBox height changes size after first frame

### ISSUE THREAD

**Issue by Amagi82** [material-components/material-components-android#2057] opened 2021-02-10 21:47 UTC
When a TextInputLayout containing a TextInputEditText is initially drawn, the OutlinedBox height is the same size as the TextInputEditText height, which is set to WRAP_CONTENT. Then, in `updateEditTextHeightBasedOnIcon()`, the minimum height is changed: `editText.setMinimumHeight(maxIconHeight)` 
This results in the minimum height changing on the next frame, making the box around the TextInputEditText jump in size. This happens whether or not there are visible icons on the TextInputLayout, and looks really janky. 

My affected TextInputLayouts have visibility set to GONE at first, which are later set to VISIBLE, and doing that may make it easier to reproduce. Setting the text size to 10sp is not necessary, but it makes the issue much more obvious. 

```
<com.google.android.material.textfield.TextInputLayout
                android:id="@+id/inputTest"
                style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="16dp"
                android:layout_marginEnd="16dp"
                android:hint="Hint"
                android:visibility="gone">

                <com.google.android.material.textfield.TextInputEditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:textSize="10sp" />

            </com.google.android.material.textfield.TextInputLayout>
```

Tested on Android API 30, library v1.3.0, Pixel 2XL

**Comment by Amagi82** [comment] 2021-02-10 21:49
Best workaround I've found in the meantime is manually setting the minimum height to 51dp, but that's a pretty ugly solution.

**Comment by drchen** [comment] 2022-02-24 20:38
Hi, is this still reproducible? I can't find any noticeable glitches when I follow your style and switch the text field from GONE to VISIBLE. 

If this still happens, can you attach a screen recording so I can better understanding what is going on? Thanks!

**Comment by Amagi82** [comment] 2022-02-25 08:41
Not sure, I migrated to Jetpack Compose, so it's no longer a problem on my end

**Comment by drchen** [comment] 2022-02-25 16:21
If that's the case I'll close the issue for now. : ) 

Feel free to reopen it if the issue is still happening.

**Closed by drchen** 2022-02-25 16:21 UTC
Labels: bug, Need more info, Widget: TextField
