### ISSUE TITLE
Snackbar bottom margin set even if navigation swipe gesture enabled on Samsung S10

### ISSUE THREAD

**Issue by rustamsmax** [material-components/material-components-android#1737] opened 2020-09-18 00:17 UTC
The causing code is

final void showView() {
    this.view.setOnAttachStateChangeListener(
        new BaseTransientBottomBar.OnAttachStateChangeListener() {
          @Override
          public void onViewAttachedToWindow(View v) {
            if (VERSION.SDK_INT >= VERSION_CODES.Q) {
              WindowInsets insets = view.getRootWindowInsets();
              if (insets != null) {
                extraBottomMarginGestureInset = insets.getMandatorySystemGestureInsets().bottom;
                updateMargins();
              }
            }
          }

          @Override
          public void onViewDetachedFromWindow(View v) {
            if (isShownOrQueued()) {
              // If we haven't already been dismissed then this event is coming from a
              // non-user initiated action. Hence we need to make sure that we callback
              // and keep our state up to date. We need to post the call since
              // removeView() will call through to onDetachedFromWindow and thus overflow.
              handler.post(
                  new Runnable() {
                    @Override
                    public void run() {
                      onViewHidden(BaseCallback.DISMISS_EVENT_MANUAL);
                    }
                  });
            }
          }
        });
}

**Comment by drchen** [comment] 2021-10-14 19:27
Is this reproducible on other devices?

**Comment by drchen** [comment] 2021-11-02 20:21
I'll close the issue due to no further info available. Hopefully it's obsolete and only happened on certain combinations of device/sdk version. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:21 UTC
Labels: bug, Need more info
