### ISSUE TITLE
In 1.5.0-alpha01 the slider label text is the wrong colour

### ISSUE THREAD

**Issue by drmrbrewer** [material-components/material-components-android#2312] opened 2021-07-24 21:40 UTC
At least in a dark theme, the label above the slider has a light grey background and a text colour that is a bit lighter... not very visible.  Reverting to 1.4.0 and the text colour is again dark, which is much more readable against the label background.

**Comment by drchen** [comment] 2021-07-26 13:11
Are you customizing your slider style? Can you take a screenshot and provide your theme/style files?

**Comment by drmrbrewer** [comment] 2021-07-26 14:53
@drchen I am not customising my slider style at all.  (Well I do `slider.setLabelFormatter(myLabelFormatter)` but that is only to return a plain String with a rounded value... and furthermore it makes no difference if I do NOT add this label formatter.)

My app's theme is defined as follows:

    <style name="Base.MaterialGallery" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
    ....
    </style>

Dark theme (1.4.0):
![dark-good](https://user-images.githubusercontent.com/9009792/127008843-2b42fa00-8e6e-4bd9-b68d-cc6013cc3e15.jpg)
Dark theme (1.5.0-alpha01):
![dark-bad](https://user-images.githubusercontent.com/9009792/127008903-9ffdcbec-29e2-4d78-b6d9-e1d2b3f92550.jpg)
Light theme (1.4.0):
![light-good](https://user-images.githubusercontent.com/9009792/127008921-e6407590-5616-4157-aa4c-4756cb43a84d.jpg)
Light theme (1.5.0-alpha01):
![light-bad](https://user-images.githubusercontent.com/9009792/127008928-344d8435-1cf9-4cc9-813d-becced651afc.jpg)

**Comment by drmrbrewer** [comment] 2021-08-24 15:42
@drchen this is still an issue for me with `1.5.0-alpha02`... do you have any insight as to why the styling changes suddenly going from `1.4.0` to `1.5.0-alpha01/2`?

**Comment by drmrbrewer** [comment] 2021-09-07 09:57
So with the `alpha-03` release I see that the introduction of the Material 3 theme may have caused this issue, as a side effect?  In any case, I've now switched my project over to using a theme based on Material 3, and this issue is therefore now no longer relevant (to me... maybe to others).

**Comment by drchen** [comment] 2021-09-07 13:20
Hi, thanks for the info you provided. 1.5.0-alpha02 doesn't contain Material 3 changes so they should be irrelevant....

I'll try to figure out the root cause and see if we need to fix it given that Material 3 is going to be released soon.

**Comment by drmrbrewer** [comment] 2021-09-07 13:23
> 1.5.0-alpha02 doesn't contain Material 3 changes so they should be irrelevant

I thought that maybe 1.5.0-alpha02 had some changes *in preparation for* M3 in 1.5.0-alpha03.  Maybe not, but certainly there is something that broke my styling.

**Comment by drchen** [comment] 2021-09-13 17:58
Hi I can't really reproduce the issue on my end. Can you provide a minimal reproducible example so I can take a look at your theme/style settings?

**Comment by drchen** [comment] 2021-10-01 14:09
I'll close the issue for now since I cannot reproduce it on my end and we didn't really receive other similar reports so far. Feel free to reopen it if you can provide us a minimal reproducible example to help debug. Thanks!

**Closed by drchen** 2021-10-01 14:09 UTC
Labels: bug
