### ISSUE TITLE
[TextInputLayout] removing start icon click listener leads to ripple effect never removed

### ISSUE THREAD

**Issue by SamYStudiO** [material-components/material-components-android#2363] opened 2021-09-08 19:56 UTC
**Description:** Assuming a TexInputLayout with to states and we want to make start icon clickable only for one stat, when removing click listener once start icon is clicked leads to ripple effect  stay on screen forever.

**Expected behavior:** Ripple effect is removed when click listener is removed.

**Source code:** `setStartIconOnClickListener(null)`

**Android API version:** 31

**Material Library version:** 1.5.0-alpha03

**Device:** Emulator api 31

Initial state
![InkedScreenshot_1631130453_LI](https://user-images.githubusercontent.com/3678076/132576129-29963a98-6977-4520-9a08-e4463e3ccedf.jpg)

Second state
![InkedScreenshot_1631130712_LI](https://user-images.githubusercontent.com/3678076/132576247-f878634f-a7a9-4d61-bf43-d3f033e0d580.jpg)

After clicking start icon back arrow to restore first state and setting click listener to null
![InkedScreenshot_1631130861_LI](https://user-images.githubusercontent.com/3678076/132576422-31f5e4b5-3a59-43ff-849d-0b72bc891155.jpg)

**Comment by drchen** [comment] 2021-09-15 21:33
Hi, can you provide a minimum reproducible example?

**Comment by drchen** [comment] 2022-01-12 21:10
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-01-12 21:10 UTC
Labels: bug, Widget: TextField
