### ISSUE TITLE
[Tab Layout] Tab text not showing

### ISSUE THREAD

**Issue by saurabhnmahajan** [material-components/material-components-android#921] opened 2020-01-17 21:34 UTC
**Description:** The tab text for the active tab is not showing
![Screenshot_1579289949](https://user-images.githubusercontent.com/12980612/72646887-01d06400-392c-11ea-908b-a5e64e6445ff.png)

**Expected behavior:** Tab text should not be hidden. This is the result on 1.1.0-rc01. 
No change has been made apart from material version
![Screenshot_1579289949](https://user-images.githubusercontent.com/12980612/72646893-04cb5480-392c-11ea-9ff6-44fc91f4d947.jpg)

**Android API version:** 28

**Material Library version:** 1.2.0-alpha01 and above

**Device:** Nexus 5X emulator with 22, 25, 29

I'm using a LayoutMediator to set the text. I tried to see if the text was not getting set.
Here's what the layout inspector gave:
![Screen Shot 2020-01-17 at 1 31 58 PM](https://user-images.githubusercontent.com/12980612/72647670-ecf4d000-392d-11ea-81d1-9051ef6efbbd.png)
and the `textview` properties:
![Screen Shot 2020-01-17 at 1 32 08 PM](https://user-images.githubusercontent.com/12980612/72647720-0564ea80-392e-11ea-9fb3-277810f05b14.png)

**Comment by ChristianSchroedel** [comment] 2020-03-26 16:00
I experienced a similar issue with a single Tab in the TabLayout.

In our case it is related to setting `android:layout_width="0dp"` for the TabLayout in a surrounding ConstraintLayout. After setting it back to `android:layout_width="match_parent"` the Tab was visible again.

**Comment by wcshi** [comment] 2020-04-29 21:21
Could you please share a small sample that reproduces the bug? Thanks

**Comment by seth-gravy** [comment] 2020-08-19 16:29
I'm on version 1.2.0 and sometimes get this behavior as well. (Samsung Galaxy S8 & S9)

Digging deeper on Layout Inspector, the `AppCompatTextView` inside the `TabView` has its visibility set to `GONE`. I'm trying to nail down reproduction steps.

![image](https://user-images.githubusercontent.com/40552578/90663247-0422d580-e20f-11ea-8ede-c989209f97c2.png)

**Comment by leticiarossi** [comment] 2020-08-25 20:37
hi @seth-gravy could you provide a sample app with what you're describing? so we can better investigate and reproduce the issue

**Comment by shah-nishant** [comment] 2020-08-31 21:06
We are also facing the same issue with TabLayoutMediator
<img width="1005" alt="Screenshot 2020-09-01 at 2 35 38 AM" src="https://user-images.githubusercontent.com/7080966/91768855-e59fdf80-ebfb-11ea-9722-11f7ac820303.png">
<img width="839" alt="Screenshot 2020-09-01 at 2 35 54 AM" src="https://user-images.githubusercontent.com/7080966/91768864-e8023980-ebfb-11ea-89b4-f6bb2048bc12.png">

**Comment by wcshi** [comment] 2020-09-01 15:44
@shah-nishant could you please share a sample app that reproduces this bug? Thanks in advance

**Comment by hijamoya** [comment] 2020-09-11 15:10
same issue here

**Comment by nupur-kinger** [comment] 2020-09-22 07:56
I'm also facing the same issue

**Comment by ericR-123** [comment] 2020-10-10 19:22
Simply creating a new Tab Layout template-activity in Android Studio produces this bug for me.

**Comment by wcshi** [comment] 2020-10-21 17:42
Can you share the project?

**Comment by dirname** [comment] 2021-03-01 18:53
Same issue here.

**Comment by dirname** [comment] 2021-03-01 19:08
> Can you share the project?

Creating a new Tab Layout template-activity in Android Studio.

**Comment by drchen** [comment] 2022-02-07 20:39
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-07 20:39 UTC
Labels: bug
