### ISSUE TITLE
[MaterialButton] drawableStart doesn't work, both in preview nor in device

### ISSUE THREAD

**Issue by Andrei-Stakov** [material-components/material-components-android#1174] opened 2020-04-02 11:37 UTC
**Description:** [MaterialButton] android:drawableStart doesn't work, both in preview nor in device. It ended up the same whether you're using xml drawable or bitmap.

**Expected behavior:**
Drawable expected to be drawn at the start of the MaterialButton.

**Resulted behavior:**
![Screenshot_1585826764](https://user-images.githubusercontent.com/16612525/78244257-6fddfd80-750f-11ea-8a83-e479b5ae7197.png)
From top to bottom:
drawableEnd - drawableStart - drawableTop - drawableBottom

**Source code:** 
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center"
    tools:context=".MainActivity">

    <com.google.android.material.button.MaterialButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="12dp"
        android:drawableEnd="@drawable/ic_android_black_24dp"/>

    <com.google.android.material.button.MaterialButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="12dp"
        android:drawableStart="@drawable/ic_android_black_24dp"/>

    <com.google.android.material.button.MaterialButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="12dp"
        android:drawableTop="@drawable/ic_android_black_24dp"/>

    <com.google.android.material.button.MaterialButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="12dp"
        android:drawableBottom="@drawable/ic_android_black_24dp"/>

</LinearLayout>
```

**Android API version:** API 22 and above; might have also happened on earlier APIs.

**Material Library version:** 1.1.0

**Device:** Android Studio Emulator

**Comment by Andrei-Stakov** [comment] 2020-04-02 15:35
Also, it is possible that this is related to #599 .

**Comment by Mika-89** [comment] 2020-04-03 10:01
@Andrei-Stakov 
You should try it with

`implementation 'com.google.android.material:material:1.2.0-alpha05'`

**Comment by hunterstich** [comment] 2020-04-03 13:55
Hey there!

Instead of using `drawableBottom|Top|Left|...` use `MaterialButton`'s attributes `app:icon` and `app:iconGravity`.

Like: 
```
      <Button
          style="@style/Widget.MaterialComponents.Button.OutlinedButton"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:contentDescription="@string/cat_button_icon_btn_text"
          app:icon="@drawable/ic_dialogs_24px"
          app:iconGravity="textStart"
          app:iconPadding="0dp"/>
```

The above is from our catalog demo app here:
https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/button/res/layout/cat_buttons_fragment.xml#L140-L141

I'm going to go ahead and close this but if this isn't what you were asking or doesn't solve the issue, feel free to reopen!

**Closed by hunterstich** 2020-04-03 13:55 UTC
Labels: bug

**Comment by Andrei-Stakov** [comment] 2020-04-03 14:45
@Mika-89 @hunterstich 
Oof, thanks guys! I got used to Material themes automatically inflate my buttons to MaterialButton, so I totally forgot about `app:icon`.

It works for my current needs, but on 1.1.0 (haven't tested it on alpha builds), `app:icon` doesn't really work well with drawableTop/Bottom/End/Right; it won't shown, except for the one designated in `app:icon`. Is this intended? Since on normal buttons, using drawableStart/Left added with others allows the button to have multiple drawable attached.

**Comment by Mika-89** [comment] 2020-04-03 14:47
Isn't there a icon gravity xml field for that what you want?

**Comment by Andrei-Stakov** [comment] 2020-04-03 14:55
@Mika-89 
It's only limited to `start`, `end`, `textStart `and `textEnd` for now. It fits the Material design direction, but that really makes me wonder if top/bottom option could be a viable option addition in the future.

**Comment by hunterstich** [comment] 2020-04-06 16:40
I just merged this PR which adds support for adding an icon above a button's text - https://github.com/material-components/material-components-android/pull/1129

That should be synced out soon if that helps

**Comment by AlejandroHCruz** [comment] 2020-04-30 13:17
Great progress, thank you all!

**Comment by risalfajar** [comment] 2021-03-15 15:56
I think Material Button should support drawableStart, End, etc. though.

Because there's a case where we need multiple icons on a button:
![image](https://user-images.githubusercontent.com/28381124/111182561-9b9fa980-85e1-11eb-965a-6c14d787a7e1.png)

**Comment by AllanWang** [comment] 2021-04-07 19:34
As mentioned in https://github.com/material-components/material-components-android/issues/1174#issuecomment-608473397, auto inflation makes this a problem for apps that migrate over to Material. Even if `app:icon` satisfies our use case, it is not obvious that the migration hides icons for all buttons with `drawableStart`

**Comment by marklwembe** [comment] 2021-04-22 09:06
> Also, it is possible that this is related to #599 .

It doesn't have anything to do with #599. I wasn't using the default Button View and still got the bug.

**Comment by AllanWang** [comment] 2021-04-22 09:32
@marklwembe it does somewhat relate, as you are suffering from auto inflation.

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/theme/MaterialComponentsViewInflater.java

This is why the issue is especially frustrating; just by changing the theme, we need to be aware of this and retroactively patch existing buttons.

**Comment by eloev** [comment] 2021-05-25 22:32
I met the same problem, the solution is to use
        android:drawableLeft="@drawable/ic_google" 
The IDE suggests changing to drawableStart, but then it disappears :)

**Comment by dferrandezsanchez** [comment] 2021-07-06 06:42
Ensure to add `iconTint` using app:icon

`app:icon="@drawable/ic_rubbish"
app:iconGravity="textStart"
app:iconTint="@android:color/holo_red_light"`

**Comment by adravel** [comment] 2022-07-26 04:39
> I think Material Button should support drawableStart, End, etc. though.
> 
> Because there's a case where we need multiple icons on a button: ![image](https://user-images.githubusercontent.com/28381124/111182561-9b9fa980-85e1-11eb-965a-6c14d787a7e1.png)

Is there a solution for this yet?

**Comment by amirudev** [comment] 2022-08-12 06:06
> Hey there!
> 
> Instead of using `drawableBottom|Top|Left|...` use `MaterialButton`'s attributes `app:icon` and `app:iconGravity`.
> 
> Like:
> 
> ```
>       <Button
>           style="@style/Widget.MaterialComponents.Button.OutlinedButton"
>           android:layout_width="wrap_content"
>           android:layout_height="wrap_content"
>           android:contentDescription="@string/cat_button_icon_btn_text"
>           app:icon="@drawable/ic_dialogs_24px"
>           app:iconGravity="textStart"
>           app:iconPadding="0dp"/>
> ```
> 
> The above is from our catalog demo app here: https://github.com/material-components/material-components-android/blob/master/catalog/java/io/material/catalog/button/res/layout/cat_buttons_fragment.xml#L140-L141
> 
> I'm going to go ahead and close this but if this isn't what you were asking or doesn't solve the issue, feel free to reopen!

all color of drawable asset that work changed to black

**Comment by ajadam64** [comment] 2023-05-06 09:24
Why do we have to use 3 different app:icon attributes, instead of just fixing android:drawableStart

**Comment by pavel-gontharuk** [comment] 2023-11-18 16:30
It's not about `drawableStart` specifically.
If you set `iconGravity` to `top` > `drawableTop` will stop working; set to `bot` > `drawableBot`
In other words `iconGravity` specifies what drawable will fail.
