### ISSUE TITLE
Badges in BottomNavigation: IllegalArgumentException("badgeDrawable cannot be null");

### ISSUE THREAD

**Issue by nzayatz14** [material-components/material-components-android#2054] opened 2021-02-10 14:25 UTC
**Description:**

So I am currently using badges on tabs on a bottom navigation view in my activity. Like so:

<img width="372" alt="Screen Shot 2021-02-10 at 9 08 51 AM" src="https://user-images.githubusercontent.com/6536941/107520634-a351d580-6b7f-11eb-8151-ff4e6d7cb92a.png">

I occasionally get an `IllegalArgumentException` crash report in my Google Play Console. By reading the call stack you can trace the issue back to the `createParcelableBadgeStates()` function in [BadgeUtils.java](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/badge/BadgeUtils.java).

```java
/**
   * Given a map of int keys to {@code BadgeDrawable BadgeDrawables}, creates a parcelable map of
   * unique int keys to {@code BadgeDrawable.SavedState SavedStates}. Useful for state restoration.
   *
   * @param badgeDrawables A {@link SparseArray} that contains a map of int keys (e.g. menuItemId)
   *     to {@code BadgeDrawable BadgeDrawables}.
   * @return A parcelable {@link SparseArray} that contains a map of int keys (e.g. menuItemId) to
   *     {@code BadgeDrawable.SavedState SavedStates}.
   */
  @NonNull
  public static ParcelableSparseArray createParcelableBadgeStates(
      @NonNull SparseArray<BadgeDrawable> badgeDrawables) {
    ParcelableSparseArray badgeStates = new ParcelableSparseArray();
    for (int i = 0; i < badgeDrawables.size(); i++) {
      int key = badgeDrawables.keyAt(i);
      BadgeDrawable badgeDrawable = badgeDrawables.valueAt(i);
      if (badgeDrawable == null) {
        throw new IllegalArgumentException("badgeDrawable cannot be null"); //<----- This is the error that is being thrown
      }
      badgeStates.put(key, badgeDrawable.getSavedState());
    }
    return badgeStates;
  }
```

 I have not been able to replicate it myself, but I was curious to see if anyone else knew about/had this issue because it does appear to be regularly occurring.

**Full CallStack:**

***java.lang.IllegalArgumentException***
com.google.android.material.badge.BadgeUtils.createParcelableBadgeStates

```
java.lang.IllegalArgumentException: 
  at com.google.android.material.badge.BadgeUtils.createParcelableBadgeStates (BadgeUtils.java:136)
  at com.google.android.material.bottomnavigation.BottomNavigationPresenter.onSaveInstanceState (BottomNavigationPresenter.java:114)
  at androidx.appcompat.view.menu.MenuBuilder.dispatchSaveInstanceState (MenuBuilder.java:332)
  at androidx.appcompat.view.menu.MenuBuilder.savePresenterStates (MenuBuilder.java:365)
  at com.google.android.material.bottomnavigation.BottomNavigationView.onSaveInstanceState (BottomNavigationView.java:739)
  at android.view.View.dispatchSaveInstanceState (View.java:18584)
  at android.view.ViewGroup.dispatchSaveInstanceState (ViewGroup.java:3856)
  at android.view.ViewGroup.dispatchSaveInstanceState (ViewGroup.java:3862)
  at android.view.ViewGroup.dispatchSaveInstanceState (ViewGroup.java:3862)
  at android.view.ViewGroup.dispatchSaveInstanceState (ViewGroup.java:3862)
  at android.view.ViewGroup.dispatchSaveInstanceState (ViewGroup.java:3862)
  at android.view.View.saveHierarchyState (View.java:18567)
  at com.android.internal.policy.PhoneWindow.saveHierarchyState (PhoneWindow.java:2100)
  at android.app.Activity.onSaveInstanceState (Activity.java:1717)
  at androidx.core.app.ComponentActivity.onSaveInstanceState (ComponentActivity.java:93)
  at androidx.activity.ComponentActivity.onSaveInstanceState (ComponentActivity.java:169)
  at androidx.fragment.app.FragmentActivity.onSaveInstanceState (FragmentActivity.java:509)
  at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState (AppCompatActivity.java:544)
  at android.app.Activity.performSaveInstanceState (Activity.java:1644)
  at android.app.Instrumentation.callActivityOnSaveInstanceState (Instrumentation.java:1443)
  at android.app.ActivityThread.callActivityOnSaveInstanceState (ActivityThread.java:4926)
  at android.app.ActivityThread.callActivityOnStop (ActivityThread.java:4274)
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4238)
  at android.app.ActivityThread.handleStopActivity (ActivityThread.java:4313)
  at android.app.servertransaction.StopActivityItem.execute (StopActivityItem.java:41)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1905)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6788)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)
```

**Android API version:** I have seen this error happen on devices running Android 9 all the way up to Android 11

**Material Library version:** `com.google.android.material:material:1.2.1`

**Devices thus far:** 

Google Pixel 4 XL
Samsung Galaxy A11
LGE Stylo 6
TCT (Alcatel) Alcatel 3V

Thanks!

**Comment by drchen** [comment] 2022-04-15 17:58
Are you still seeing the issue? From code analysis I don't see how this can happen....

**Comment by drchen** [comment] 2022-04-29 18:48
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-04-29 18:48 UTC
Labels: bug, Need more info, Widget: Badge, Widget: BottomNavigation

**Comment by ashub7** [comment] 2022-08-24 06:45
I am facing same issue with version `1.6.1` .. Stack Trace is almost same so not adding it here again .. Tried to reproduce it but could not its completely random .
