### ISSUE TITLE
[CheckBox] Uncheck animation missing / animation durations unbalanced

### ISSUE THREAD

**Issue by patzly** [material-components/material-components-android#2904] opened 2022-08-12 19:35 UTC
**Description:** Hi, thanks for the new beta release! I was very happy to try out the new checkbox animations, but sadly I have to say that I don't really like them :/
Personally I think the old animations were much more intuitive and smoother. The new ones are somehow missing the smoothness and playfulness of Material You. More precisely I mean the animation from **unchecked to checked** (too short in contrast to the (maybe too) long one from checked to indeterminate) and the one from **checked to unchecked** (I think it's completely missing or far too short). Also the old "bouncing" effect has much better suited the playfulness of Material You than the new static box I think.

New animation for reference:
![new](https://user-images.githubusercontent.com/33599892/184421991-c0efaa14-bdfb-447f-8a38-f22467a2ec39.gif)

**Expected behavior:** I don't know how much of the animations are new specifications of the design team, currently the new docs for checkboxes are still not available for us regarding what they thought of, but I think the hard checked-to-unchecked animation is not a good experience and has to be improved. Maybe some re-thinking of the design team is required for the animation durations in general if they look the same in their docs. Here is the old animation for reference, notice the smooth and playful checked-to-unchecked animation:

![old](https://user-images.githubusercontent.com/33599892/184421732-7f560c22-c921-431c-9b15-90db4017a4a2.gif)

Also I have to say that I don't understand why the new drawable animation files are made of filled paths instead of a simple stroke, that would make the transition to indeterminate technically much simpler and would allow rounded ends of the stroke (something I would prefer for checkboxes in my apps). Then a method `setStrokeCapRounded(rounded)` would be a very nice addition, but that would be a new feature request :)

**Android API version:** 33

**Material Library version:** 1.7.0-beta01

**Device:** Pixel 6

**Comment by leticiarossi** [comment] 2022-10-21 16:55
Hello, thanks for the feedback! The new guidelines for checkbox have been published: https://m3.material.io/components/checkbox/guidelines which includes the new animations specified by design. Will close this issue as WAI.

Feel free to file a new feature request with the other things you mentioned if you'd like (though I don't think that would be a priority for us right now!)

**Closed by leticiarossi** 2022-10-21 16:55 UTC
Labels: bug, Widget: Checkbox
