### ISSUE TITLE
[TextInputLayout] Border overlaps floating label when rounded shape appearance used

### ISSUE THREAD

**Issue by stephen-mojo** [material-components/material-components-android#2273] opened 2021-06-24 21:58 UTC
**Description:** 
I am seeing that the border outline of a TextInputLayout overlaps its floating label. The overlap issue only occurs when a rounded shape appearance is used. A square shape appearance does not exhibit this issue. This looks to be a similar issue to #2127, but this ticket was marked as fixed.

Rounded with overlap:
![example](https://user-images.githubusercontent.com/69835692/123337505-2a369780-d4fc-11eb-9abe-49c47888102c.png)

Squared with no overlap:
![squared](https://user-images.githubusercontent.com/69835692/123337514-2d318800-d4fc-11eb-94be-4442c924613f.png)

**Source code:** 
Here is a sample project that shows the issue: https://github.com/stephen-mojo/overlap-example

**Android API version:** 
Android R

**Material Library version:**
1.4.0-rc01

**Device:**
Pixel 4a

Thank you!
Stephen

**Comment by drchen** [comment] 2021-07-12 18:05
Duplicate of https://github.com/material-components/material-components-android/issues/2145

**Closed by drchen** 2021-07-12 18:05 UTC
Labels: bug
