### ISSUE TITLE
[TextInputLayout] Error message not shown after calling setError

### ISSUE THREAD

**Issue by Sonphil** [material-components/material-components-android#454] opened 2019-07-19 16:50 UTC
**Description:** 
Even though error is enabled, `TextInputLayout` doesn't display the error message after setting it. Only the outline (box) is affected. 
![image](https://user-images.githubusercontent.com/22182973/61550533-b55da780-aa20-11e9-833b-3decdafee7b8.png)

I have to call `requestLayout()` on my `TextInputLayout` to make the error message show up. This shouldn't be the case. 

After calling  `requestLayout()`: 
![image](https://user-images.githubusercontent.com/22182973/61550731-403ea200-aa21-11e9-8df9-a4db43a4db53.png)

**Expected behavior:**
Calling `setError` should make the error message show up
![image](https://user-images.githubusercontent.com/22182973/61550116-b3471900-aa1f-11e9-959b-1adc0bc9ec1d.png)

**Source code:**
I simply set the error by calling `setError`.
```kotlin
layoutPassword.error = "error_field_required"`
```
**Android API version:** 28

**Material Library version:**  1.1.0-alpha08

**Comment by doilio** [comment] 2019-07-23 06:13
Hi, what version of Android Studio are you using?

**Comment by Sonphil** [comment] 2019-07-23 06:15
Hello @doilio I use 3.4.2

**Comment by somesh-basicx** [comment] 2019-10-16 06:20
Same happens with me. I use setError inside TextWatcher and no matter what I do the error never appears. The funny thing is the same logic is working in my Java project and not with Kotlin project. Also if I press the password toggle button it shows the error but not when I call `setError`. Please fix this issue on priority it beed more than 3 months since this issue is reported.

**Comment by leticiarossi** [comment] 2019-12-02 20:57
Can you provide a sample app with the issue happening? I'm not able to reproduce it on my end

**Comment by Sonphil** [comment] 2019-12-12 17:10
@leticiarossi I'm not able to reproduce the problem anymore.

**Comment by leticiarossi** [comment] 2019-12-12 19:07
Will close this for now then. Feel free to reopen with a sample app if the issue arises again!

**Closed by leticiarossi** 2019-12-12 19:07 UTC
Labels: bug

**Comment by amir215909** [comment] 2021-07-14 09:38
Hi, I think I have the same problem. This is a sample code in which error message is not shown although error message is set
`                <com.google.android.material.textfield.TextInputLayout
                    android:id="@+id/email_text_layout"
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"
                    android:layout_width="0dp"
                    android:layout_height="@dimen/_45sdp"
                    android:layout_marginTop="@dimen/large_margin"
                    android:background="@null"
                    app:boxCornerRadiusBottomEnd="@dimen/_10sdp"
                    app:boxCornerRadiusBottomStart="@dimen/_10sdp"
                    app:boxCornerRadiusTopEnd="@dimen/_10sdp"
                    app:boxCornerRadiusTopStart="@dimen/_10sdp"
                    app:boxStrokeColor="@color/text_input_box_stroke"
                    app:boxStrokeWidth="1dp"
                    app:boxStrokeWidthFocused="1dp"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@id/segmented_button"
                    app:startIconDrawable="@drawable/ic_email"
                    app:startIconTint="@color/text_edit_start_icon">

                    <com.google.android.material.textfield.TextInputEditText
                        android:id="@+id/email_edit_text"	
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:hint="@string/email"
                        android:inputType="textEmailAddress"
                        android:paddingHorizontal="@dimen/small_padding"
                        android:textColor="?attr/textColor" />
                </com.google.android.material.textfield.TextInputLayout>`

`binding.emailTextLayout.error = getString(R.string.wrong_email)`

![Capture](https://user-images.githubusercontent.com/25514831/125597666-1ac1a5f2-7bd1-4aee-8d6f-c64bd8fbcffe.PNG)

Android API version: 29
Material Library version:1.3.0

**Comment by amir215909** [comment] 2021-07-14 09:43
Hi, I think I have the same problem. This is a sample code in which error message is not shown although error message is set
`                <com.google.android.material.textfield.TextInputLayout
                    android:id="@+id/email_text_layout"
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.Dense"
                    android:layout_width="0dp"
                    android:layout_height="@dimen/_45sdp"
                    android:layout_marginTop="@dimen/large_margin"
                    android:background="@null"
                    app:boxCornerRadiusBottomEnd="@dimen/_10sdp"
                    app:boxCornerRadiusBottomStart="@dimen/_10sdp"
                    app:boxCornerRadiusTopEnd="@dimen/_10sdp"
                    app:boxCornerRadiusTopStart="@dimen/_10sdp"
                    app:boxStrokeColor="@color/text_input_box_stroke"
                    app:boxStrokeWidth="1dp"
                    app:boxStrokeWidthFocused="1dp"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@id/segmented_button"
                    app:startIconDrawable="@drawable/ic_email"
                    app:startIconTint="@color/text_edit_start_icon">

                    <com.google.android.material.textfield.TextInputEditText
                        android:id="@+id/email_edit_text"	
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:hint="@string/email"
                        android:inputType="textEmailAddress"
                        android:paddingHorizontal="@dimen/small_padding"
                        android:textColor="?attr/textColor" />
                </com.google.android.material.textfield.TextInputLayout>`

`binding.emailTextLayout.error = getString(R.string.wrong_email)`

This is how it looks like now
![Capture](https://user-images.githubusercontent.com/25514831/125600638-51fd0b40-97a6-435c-b61b-ac35a92610be.PNG)

Expected Result
![s1](https://user-images.githubusercontent.com/25514831/125600763-f91aa6d3-50e1-4917-9a72-9c3373a369b6.PNG)



Android API version: 29
Material Library version:1.3.0

**Comment by h-tolou** [comment] 2022-04-19 04:47
hi, I have same problem and fix it by change  
android:layout_height="wrap_content"
of
TextInputLayout
