### ISSUE TITLE
[MaterialDatePicker] November only showing 29 days

### ISSUE THREAD

**Issue by Monkey-Matt** [material-components/material-components-android#1913] opened 2020-12-02 22:57 UTC
**Description:** In a particular case November only shows 29 days instead of 30 (other months can also be wrong).

The problem occurs when loading the MaterialDatePicker and either the previous or next month is displayed across 6 rows. Basically the layout gets constrained to the height of the current month (eg December 2020 with 5 rows) and the previous and next month get loaded in to the recyclerview respecting this height, however November requires 6 rows so the last row isn't rendered. When interacting with the recyclerview the height gets corrected and the correct dates will be shown (so if you start in December then scroll to January (so the November gets recycled), then back to November it will have the correct 30 days).

Steps:
- Open a MaterialDatePicker that defaults to showing December 2020.
- Scroll back one month to November 2020. Witness it only shows 29 days.
- Scroll to January 2021, then back to November 2020. Witness it now shows the correct 30 days.

Note: This also depends on what day the start of week is. I've been reproducing this issue with Monday as the start of week (due to device language setting being New Zealand English). For different start of weeks this issue will exist for different months (as different months will need the 6th row).

![device-2020-12-03-114039](https://user-images.githubusercontent.com/8265864/100940202-656f7a00-355c-11eb-8b88-4ce5729688a7.png)

**Expected behaviour:** 

![device-2020-12-03-114124](https://user-images.githubusercontent.com/8265864/100940267-7f10c180-355c-11eb-8824-6c686f0cb0bc.png)

**Source code:** Reproduced in the catalog app. 1.3.0-alpha04

**Material Library version:** 1.3.0-alpha04

**Android API version:** 29

**Device:** Lenovo TB-X605LC (have also reproduced on other tablets)

There has been a fix to a related bug #1338 however while that stopped the crash (by simply selecting the November 29th instead of the 30th) it doesn't address the root cause which is that the 30th isn't being displayed.

I attempted to find a fix but was unsuccessful. Appears to be some strange interaction between layout constraints.

**Comment by Stofferoo** [comment] 2022-01-13 11:37
+1, just saw the same issue now for January when February is prepicked in Material 1.3.0

**Comment by Stofferoo** [comment] 2022-01-13 11:46
Verified issue exists in 1.4.0 as well

**Comment by mtotschnig** [comment] 2022-02-17 13:54
Just observed the same issue, and wanted to add that the 6th row is not visible in the bug scenario, but it is rendered. By scrolling down on the calendar grid, it can be made visible.
While this allows for a workaround, it does not reduce the severity of the bug, because it is unlikely that user discovers the workaround.

**Comment by mtotschnig** [comment] 2022-02-17 14:57
There seems to be an easy fix to the bug. MonthAdapter#getCount() could return the maximum number of cells for a grid with 6 rows, i.e. 42. This would lead to the the cells after the last day in the month treated in a way identical to the cells before the first day in the month, i.e. empty cells would be rendered, and there would be 6 rows for every month, but visually this would not make any difference, because already now the space for 6 rows is already allocated, it is just not made available to the MaterialCalendarGridViews. Please let me know if a PR with this solution has any chance of being accepted.

**Comment by drchen** [comment] 2022-02-17 15:39
Hi @mtotschnig, thanks for spotting the issue!

PRs are definitely welcome. I'm just wondering why the original math doesn't work and if it actually causes more bugs that's not uncovered yet.

I'll take some time to verify the actual cause as well. In the meantime, let me close the issue as a duplicate of https://github.com/material-components/material-components-android/issues/1676, so we can better track it in one place.

**Closed by drchen** 2022-02-17 15:39 UTC
Labels: bug, Widget: DatePicker

**Comment by mtotschnig** [comment] 2022-02-17 15:52
The original math consists in saying: "count is the number of days in the month plus the empty cells that precede the first day of the month in the first row." It works for displaying all days in any given month. The problem is just that the view pager then uses the same dimensions for any preceding or following month, which might have more rows to display. I am actually not really sure how this happens, so there might be a better solution that prevents this reuse from happening. My suggested fix, just consists in using the maximum number of cells that might be needed for any month including rendering cells before and after. So it has the drawback of doing some extra view creation, but I'd consider this acceptable with respect to a bug that has regular, serious impact on usability.

**Comment by drchen** [comment] 2022-02-17 15:59
I agree with your point. Even if there might be other things we need to fix, but I think it's a very reasonable workaround.

Thank you very much!!
