### ISSUE TITLE
[TextInputLayout] Android Studio preview: weight is out of range of [0, 1000] (too low)

### ISSUE THREAD

**Issue by eygraber** [material-components/material-components-android#2531] opened 2022-01-24 17:20 UTC
```
java.lang.IllegalArgumentException: weight is out of range of [0, 1000] (too low)
	at com.android.internal.util.Preconditions.checkArgumentInRange(Preconditions.java:527)
	at android.graphics.Typeface.create_Original(Typeface.java:979)
	at android.graphics.Typeface_Delegate.create(Typeface_Delegate.java:123)
	at android.graphics.Typeface.create(Typeface.java:979)
	at com.google.android.material.internal.CollapsingTextHelper.maybeCloneWithAdjustment(CollapsingTextHelper.java:532)
	at com.google.android.material.internal.CollapsingTextHelper.setCollapsedTypefaceInternal(CollapsingTextHelper.java:475)
	at com.google.android.material.internal.CollapsingTextHelper.setCollapsedTypeface(CollapsingTextHelper.java:447)
	at com.google.android.material.internal.CollapsingTextHelper$1.apply(CollapsingTextHelper.java:403)
	at com.google.android.material.resources.CancelableFontCallback.updateIfNotCancelled(CancelableFontCallback.java:69)
	at com.google.android.material.resources.CancelableFontCallback.onFontRetrieved(CancelableFontCallback.java:49)
	at com.google.android.material.resources.TextAppearance.getFontAsync(TextAppearance.java:187)
	at com.google.android.material.internal.CollapsingTextHelper.setCollapsedTextAppearance(CollapsingTextHelper.java:407)
	at com.google.android.material.textfield.TextInputLayout.setHintTextAppearance(TextInputLayout.java:1815)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:625)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:432)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:336)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:173)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:133)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:301)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.eygraber.date_time_input.xml.TimeInputView.<init>(TimeInputView.kt:125)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:336)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:173)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:133)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:301)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:363)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:739)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$8(RenderTask.java:895)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Firebelias12** [comment] 2022-01-27 07:56
Downgrading to 'com.google.android.material:material:1.5.0' on Android Studio Bumblebee | 2021.1.1 worked for me.

**Comment by veganafro** [comment] 2022-01-27 17:05
hey @eygraber could you provide more information on how to reproduce this bug?

**Comment by eygraber** [comment] 2022-01-27 17:17
It should be reproducible with https://github.com/eygraber/android-date-time-input and Android Studio Chipmunk Canary 7 (I haven't tested with beta yet).

**Comment by veganafro** [comment] 2022-01-31 18:09
Thanks for the template @hoc081098 . I attempted to reproduce using Material version `1.6.0-alpha02` on Android Studio Arctic Fox (2020.3.1) and on Android Studio Bumblebee (2021.1.1). AS Preview worked without any exceptions on the former, but not the latter version so I'm inclined to believe that this is an error with Android Studio.

**Comment by hoc081098** [comment] 2022-01-31 18:28
@veganafro I encounter this issue when using A.S. Chipmunk (2021.2.1)

**Comment by jgaillard85** [comment] 2022-01-31 19:16
The issue only appears in Android Studio Bumblebee and more recent versions as they use Android 12 as the basis for the rendering engine, while Android Studio Arctic Fox uses Android 11. And this is an issue with the font weight adjustment feature which was introduced in Android 12

**Comment by drchen** [comment] 2022-02-04 16:28
Looks like it's beyond our control and I'm going to close it as infeasible.

**Closed** 2022-02-04 16:28 UTC
Labels: bug, studio

**Comment by eygraber** [comment] 2022-02-04 16:31
Is there a bug filed in issuetracker for this?

**Comment by TjarkC** [comment] 2022-02-04 16:35
https://issuetracker.google.com/issues/209468517

Was marked as fixed on Feb 02:
> This will be fixed in the next update of the material library

**Comment by drchen** [comment] 2022-02-04 16:51
Sorry that now I'm a bit confused by the bug story. Let me track down this for a little bit. 

But I'll keep this as closed since it's actually a duplicate of #2507

**Comment by dsn5ft** [comment] 2022-02-04 17:44
I think this will be fixed by https://github.com/material-components/material-components-android/commit/5dce006a5c1649df4eb6631c85619017728726af.

**Comment by drchen** [comment] 2022-02-04 17:56
Thanks for the clarification. I'm going to close another issue as well.
