### ISSUE TITLE
[Tablayout] Does not focus on selected tab when using accessibility swipe navigation

### ISSUE THREAD

**Issue by michaelJCBSH** [material-components/material-components-android#1449] opened 2020-06-29 22:06 UTC
Tablayout  does not focus on selected tab when using accessibility swipe navigation to swipe to tablayout

**Current behavior:**
the left most visible tab will always be focused on. 

**Expected behavior:**
The selected should be focused on

**Comment by wcshi** [comment] 2020-06-30 15:38
Could you please elaborate on how to reproduce the behavior you are reporting, either using the catalog app or a sample app, thanks

**Comment by drchen** [comment] 2022-02-18 19:31
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-18 19:31 UTC
