### ISSUE TITLE
[FAB] Request: add API for FAB to expand to more actions, as shown on the guidelines

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#1672] opened 2020-08-31 16:45 UTC
Moved from here:
https://issuetracker.google.com/issues/166155021

**Is your feature request related to a problem? Please describe.**
As shown here:
https://material.io/components/buttons-floating-action-button#types-of-transitions
under "Emit related actions" and under "Transform into a menu with the related actions" ...

**Describe the solution you'd like**
If we don't have it since it's to allow us to customize it, please put samples for the basic creation of those UIs, and put links to them on the guidelines.

**Describe alternatives you've considered**
Tried samples here.
Also didn't find API for this.

**Additional context**
Why do we write here instead of the issue tracker?

**Comment by leticiarossi** [comment] 2020-08-31 16:53
Hi, this is a duplicate of https://github.com/material-components/material-components-android/issues/656 so will be closing it here.

**Closed by leticiarossi** 2020-08-31 16:53 UTC
Labels: feature request

**Comment by AndroidDeveloperLB** [comment] 2020-08-31 17:57
@leticiarossi Thank you!
