### ISSUE TITLE
After updating material 1.6.1 to 1.7.0 overridePendingTransition doesn't work

### ISSUE THREAD

**Issue by Piwik-Tikeasy** [material-components/material-components-android#3187] opened 2023-01-25 13:47 UTC
Hello,

After updating version of material in build.gradle animation doesn't work. Works fine before in 1.6.1.  Code is the same for several years.

**Source code:** 

`  @Override
    public void startActivity(Intent intent) {
        super.startActivity(intent);
            overridePendingTransition(R.anim.test_slide_in_right, R.anim.test_slide_out_left);
}`

Animation test_slide_in_right : 
`<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:fromXDelta="100%p"
        android:toXDelta="0"
        android:duration="@android:integer/config_mediumAnimTime" />
</set>`

Animation test_slide_out_left: 
` <?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:fromXDelta="0"
        android:toXDelta="-100%p"
        android:duration="@android:integer/config_mediumAnimTime" />
</set>`

TargetSDK Version si 33, compileSDK Version 33, and minSDK 24

Capture of effect on the tablet (Android 9.0) after starting activity.
![transition](https://user-images.githubusercontent.com/26742420/214578643-7b6c5ff5-7f0d-4d21-89b5-26d9f3de564e.png)

The stacktrace is : 
`E  Unhandled exception while laying out windows
                                                                                                    java.lang.RuntimeException: Unknown animation name: cycleInterpolator
                                                                                                    	at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:192)
                                                                                                    	at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:157)
                                                                                                    	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:138)
                                                                                                    	at com.android.server.wm.AppTransition.loadAnimationRes(AppTransition.java:582)
                                                                                                    	at com.android.server.wm.AppTransition.loadAnimation(AppTransition.java:1618)
                                                                                                    	at com.android.server.wm.AppWindowToken.loadAnimation(AppWindowToken.java:1848)
                                                                                                    	at com.android.server.wm.AppWindowToken.applyAnimationLocked(AppWindowToken.java:1766)
                                                                                                    	at com.android.server.wm.AppWindowToken.setVisibility(AppWindowToken.java:422)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.handleOpeningApps(WindowSurfacePlacer.java:464)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.handleAppTransitionReadyLocked(WindowSurfacePlacer.java:321)
                                                                                                    	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:618)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:207)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:155)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:145)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.lambda$new$0(WindowSurfacePlacer.java:118)
                                                                                                    	at com.android.server.wm.-$$Lambda$WindowSurfacePlacer$4Hbamt-LFcbu8AoZBoOZN_LveKQ.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:44)`

**Comment by drchen** [comment] 2023-01-30 21:20
Don't really see how this can relate to the Material library. If you change your interpolator in XML to other types, will that work?

**Comment by Piwik-Tikeasy** [comment] 2023-01-31 07:16
I have no interpolator. This apps work with the same part of code since 2016. Build.gradle is up to date, except material 1.6.1. And if I upgrade, doesn't works....

**Comment by hunterstich** [comment] 2023-02-14 15:42
Hi @Piwik-Tikeasy,

If you're still running into this issue and able to attach a sample which reproduces the problem, that would be helpful. Otherwise, this seems unrelated to Material and I'm going to go ahead and close this issue.

**Closed by hunterstich** 2023-02-14 15:42 UTC
Labels: bug, Need more info

**Comment by elvedincuskic-volvofinans** [comment] 2023-02-28 09:26
Hi. 

I've also run into this issue. I couldn't reproduce it in a new project when trying to create a sample so I'm not sure what the cause is. 

I use the following code when starting new activities:

This is called from the first activity when opening another one on top of the current one:
```
startActivity(Intent(this, NextActivity::class.java))
overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_bottom)
```

and the animations look like this:

*R.anim.slide_in_right:*
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="@android:integer/config_mediumAnimTime"
        android:fromXDelta="100%"
        android:fromYDelta="0%"
        android:toXDelta="0%"
        android:toYDelta="0%" />
</set>
```

*R.anim.slide_out_bottom:*
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android" android:shareInterpolator="false">
  <translate
      android:duration="@android:integer/config_mediumAnimTime"
      android:fromXDelta="0%"
      android:fromYDelta="0%"
      android:toXDelta="0%"
      android:toYDelta="100%" />
</set>
```

*Stacktrace:*

```
Unhandled exception while laying out windows
android.content.res.Resources$NotFoundException: Resource ID #0x7f010048
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:204)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2133)
	at android.content.res.Resources.getAnimation(Resources.java:1166)
	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:107)
	at com.android.server.wm.AppTransition.loadAnimationRes(AppTransition.java:577)
	at com.android.server.wm.AppTransition.loadAnimation(AppTransition.java:1537)
	at com.android.server.wm.WindowManagerService.applyAnimationLocked(WindowManagerService.java:2354)
	at com.android.server.wm.AppWindowToken.setVisibility(AppWindowToken.java:368)
	at com.android.server.wm.WindowSurfacePlacer.handleClosingApps(WindowSurfacePlacer.java:454)
	at com.android.server.wm.WindowSurfacePlacer.handleAppTransitionReadyLocked(WindowSurfacePlacer.java:340)
	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:600)
	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:193)
	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:141)
	at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:2137)
	at com.android.server.wm.Session.relayout(Session.java:232)
	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:286)
	at com.android.server.wm.Session.onTransact(Session.java:159)
	at android.os.Binder.execTransact(Binder.java:674)
```

I use this parent theme for my activities: *Theme.MaterialComponents.NoActionBar.Bridge*.

It works fine with com.google.android.material:material:1.6.1. If I update to 1.7.0 or 1.8.0 the app crashes when trying to open the new activity. I'm running the app on an emulator with API 26. It works fine if I run it on my physical device (Google Pixel 7 Pro with API 33).

I'm not sure if this is occurs only when running on the emulator or if it's actually a problem on lower API versions. As I don't have a physical device with lower versions I can't test it fully and I'm not sure if I can omit this issue and release the app in production with version > 1.7.x of material.

Could you try reproducing the issue once more and dig more into it to find the issue?

**Comment by Piwik-Tikeasy** [comment] 2023-02-28 09:50
Hello,

Before writing this post I had this problem 1st, to get to the one posting on github.
Again this morning when upgrading 1.6.1 to 1.7.0
` Unhandled exception while laying out windows
                                                                                                    
android.content.res.Resources$NotFoundException: Resource ID #0x7f010031
                                                                                                    	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
                                                                                                    	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2155)
                                                                                                    	at android.content.res.Resources.getAnimation(Resources.java:1180)
                                                                                                    	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:137)
                                                                                                    	at com.android.server.wm.AppTransition.loadAnimationRes(AppTransition.java:582)
                                                                                                    	at com.android.server.wm.AppTransition.loadAnimation(AppTransition.java:1618)
                                                                                                    	at com.android.server.wm.AppWindowToken.loadAnimation(AppWindowToken.java:1848)
                                                                                                    	at com.android.server.wm.AppWindowToken.applyAnimationLocked(AppWindowToken.java:1766)
                                                                                                    	at com.android.server.wm.AppWindowToken.setVisibility(AppWindowToken.java:422)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.handleClosingApps(WindowSurfacePlacer.java:509)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.handleAppTransitionReadyLocked(WindowSurfacePlacer.java:319)
                                                                                                    	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:618)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:207)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:155)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:145)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.continueLayout(WindowSurfacePlacer.java:136)
                                                                                                    	at com.android.server.wm.WindowManagerService.continueSurfaceLayout(WindowManagerService.java:2879)
                                                                                                    	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:6011)
                                                                                                    	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:6180)
                                                                                                    	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1916)
                                                                                                    	at android.os.BinderProxy.sendDeathNotice(Binder.java:1218)`




I had managed to pass the problem, but to arrive on another ..
