### ISSUE TITLE
com.google.android.material.card.MaterialCardView not working

### ISSUE THREAD

**Issue by durgeshrjkumar** [material-components/material-components-android#3268] opened 2023-02-27 06:39 UTC
com.google.android.material.card.MaterialCardView
is not showing design preview in android studio above version 1.7. while CardView is working.

**Comment by patzly** [comment] 2023-03-02 00:46
@durgeshrjkumar Isn't this a duplicate of your own issue #3186? Also duplicate of #3136. As the comments say, just use a newer Android Studio version like Flamingo and the issue will be gone.

**Comment by imhappi** [comment] 2023-03-02 01:44
Thanks for replying @patzly ! This is indeed the same issue as the ones linked; please use a newer version of Android Studio

**Closed by imhappi** 2023-03-02 01:44 UTC
Labels: Issue: Android Studio

**Comment by durgeshrjkumar** [comment] 2023-03-02 08:28
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023


Runtime version: 11.0.15+0-b2043.56-9505619 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
This is the version of android studio I am using. ans still MaterialCardview is not displaying

**Comment by durgeshrjkumar** [comment] 2023-03-02 09:06
Now I have updated my android studio with Android Studio Giraffe | 2022.3.1 Canary 7, and its working like a charm :)
