### ISSUE TITLE
[RangeSlider] There are a line, when two thumbs are overlap.

### ISSUE THREAD

**Issue by wslaimin** [material-components/material-components-android#1924] opened 2020-12-14 09:25 UTC
**Description:** There are a line, when two thumbs are overlap
![image](https://user-images.githubusercontent.com/8746914/102063660-48c32400-3e31-11eb-822f-389735f5196b.png)

**Expected behavior:** no redundant line

**Source code:** 
xml layout:
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center">

    <com.google.android.material.slider.RangeSlider
        android:id="@+id/range_slider"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="60dp"/>
</LinearLayout>
```
java code:

```
public class MySliderActivity extends AppCompatActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.act_slider);
        RangeSlider rangeSlider=findViewById(R.id.range_slider);
        rangeSlider.setValues(10f,100f);
        rangeSlider.setValueFrom(10);
        rangeSlider.setValueTo(100);
    }
}
```

**Android API version:** 29

**Material Library version:** 1.2.1
**Device:** samsung galaxy s7

**Comment by drchen** [comment] 2021-11-04 19:29
Is this still reproducible? I never saw this when I tested the slider.

**Comment by drchen** [comment] 2022-01-12 20:25
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-01-12 20:25 UTC
Labels: bug, Need more info

**Comment by valiantwarrior** [comment] 2023-03-04 02:42
### Still happen in 1.8.0

ScreenShot
<img width="200" alt="image" src="https://user-images.githubusercontent.com/50101902/222871117-6973212f-5710-415b-9489-ede25ab3ecfb.png">

Library Version
- com.google.android.material:material:**1.8.0**

Device
- Samsung Galaxy Tab A 10.1 (**SM-P580**)
- Android 8.1.0 (**API 27**)
- Samsung Experience 9.5
- 3.18.14-15948922 ( gcc version 4.9.x 20150123 (prerelease) (GCC) )

Build
- compileSdk 33
- targetSdk 33
- minSdk 21

Repro Repo
- https://github.com/valiantwarrior/RangeSliderSample
---

### Possible workaround

#### Solution
You can check [this](https://github.com/valiantwarrior/RangeSliderSample/blob/f996af8e3e7cb2741f0a86b4832f3ccf4ad10fc9/App/app/src/main/java/kr/valor/rangeslider/MainActivity.kt#L35-L44) and [this](https://github.com/valiantwarrior/RangeSliderSample/blob/f996af8e3e7cb2741f0a86b4832f3ccf4ad10fc9/App/app/src/main/java/kr/valor/rangeslider/MainActivity.kt#L23)

```kotlin
val slider = binding.slider // or findViewById<RangeSlider>(R.id.slider)
// ...
slider.setMinSeparationValue(0.0001F) // BaseSlider.THRESHOLD
```
#### Result
<details><summary>Video</summary>

https://user-images.githubusercontent.com/50101902/222871419-1ae609ba-a160-4b99-a072-a2730d733057.mp4

</details>

#### Limitation
This approach only works if the slider's stepSize(`android:stepSize`) is 0 (continuous slider)
