### ISSUE TITLE
[MaterialDatePicker] [MaterialTimePicker] Buttons are not displayed properly

### ISSUE THREAD

**Issue by mal7othify** [material-components/material-components-android#2577] opened 2022-02-23 04:49 UTC
**Description:** Full description of issue here

**Expected behavior:** The MaterialDatePicker and MaterialTimePicker buttons (OK and Cancel) are not displayed properly in One Plus device. Refer to the screenshot below:
<img width="419" alt="Screen Shot 2022-02-23 at 7 42 47 AM" src="https://user-images.githubusercontent.com/35968097/155262983-46cefd5f-7b4c-46cf-85b4-58f5fe9479ba.png">

**Android API version:** 30 & 31

**Material Library version:** com.google.android.material:material:1.3.0 & com.google.android.material:material:1.5.0

**Device:** Device details:
Device Name: OnePlus 9 Pro 5G (edited)
Model: LE2125
OS Version: Android 12

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment] 2022-04-05 17:22
Can you provide the themes and the styles you are using? A reproducible sample will be even better.

**Comment by drchen** [comment] 2022-04-22 14:07
I'll close this issue for now due to no further info available. Please feel free to reopen it with more info.

**Closed by drchen** 2022-04-22 14:07 UTC
Labels: bug, Need more info, Widget: DatePicker, Widget: TimePicker
