### ISSUE TITLE
LinearProgressIndicator - indicator color doesn't show up

### ISSUE THREAD

**Issue by benjaminreynoso** [material-components/material-components-android#4309] opened 2024-09-23 19:36 UTC
**Description:**  We're using the com.google.android.material.progressindicator.LinearProgressIndicator component, and while calling the show() function and having the progress indicator setting indeterminate to true, it seems that only the default track color appears but not the animation, nor the color of the indicator.
 
**Expected behavior:** whenever the component is shown, the animation of the indeterminate setting should be active 
<img width="350" alt="Screenshot 2024-09-23 at 12 32 41 p m" src="https://github.com/user-attachments/assets/23fba651-423f-45c3-8461-800890e8092f">

**Source code:** The code snippet which is causing this issue

    <com.google.android.material.progressindicator.LinearProgressIndicator
        android:id="@+id/fragmentTenantProgressIndicator"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:indeterminate="true"
        android:visibility="invisible"
        app:indicatorColor="?attr/colorPrimary"

**Minimal sample app repro:** just show the view.

**Android API version:** API LEVEL 34

**Material Library version:** 1.8.0-alpha01

**Device:** Samsung A03 API LEVEL 33

**Comment by pekingme** [comment] 2024-09-24 16:43
1.8.0 is pretty old. Could you try the newer version? There're quite some bug fixing and new features since then.

**Comment by benjaminreynoso** [comment] 2024-09-24 17:11
I can confirm that the bug remains active updating to the version 1.13.0-alpha06

**Comment by pekingme** [comment] 2024-09-25 17:41
Okay! Just to clarify the steps to reproduce the issue. You have the LPI in a layout XML file as shown in the snippet. Then call `show()` in code. It doesn't animate. Is that correct?

**Comment by benjaminreynoso** [comment] 2024-09-25 18:25
You're right, no further methods are called, thank you

**Comment by pekingme** [comment] 2024-11-08 23:36
I can't reproduce this issue. Could you provide a sample app from your end? Btw, your snippet has `android:layout_width="0dp"`. Not sure if it's just a typo.

**Comment by pekingme** [comment] 2024-11-26 19:41
Closing the issue. Please comment for reopening or further discussion.

**Closed by pekingme** 2024-11-26 19:41 UTC
Labels: bug, Need more info, Widget: ProgressIndicator
