### ISSUE TITLE
[Component name] Short description of request

### ISSUE THREAD

**Issue by Adwooo** [material-components/material-components-android#2424] opened 2021-10-12 08:09 UTC
Is it possible to add floating button to this bar? 

like in this version of bar  : 
https://github.com/material-components/material-componentsandroid/blob/master/docs/components/BottomAppBar.md

The other solution lacks lapses under icons and they are really needed in my case.

**Comment by drchen** [comment] 2021-11-02 20:48
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:48 UTC
Labels: Need more info, feature request
