### ISSUE TITLE
[Carousel] The last item cannot be fully expanded if there are fewer items in the carousel than keylines

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3598] opened 2023-09-21 21:28 UTC
https://github.com/material-components/material-components-android/assets/82187521/566f143c-44d8-4eb4-8565-e05f853c3423

**Material Library version:** 1.11.0-alpha03
**Device:** Pixel 4a (5G)

**Comment by imhappi** [comment] 2023-09-22 00:26
Duplicate of https://github.com/material-components/material-components-android/issues/3599

**Closed** 2023-10-10 17:48 UTC
Labels: bug, Widget: Carousel
