### ISSUE TITLE
[TabLayout] Tab customview bug after updating to material 1.1.0

### ISSUE THREAD

**Issue by stevenwijaya** [material-components/material-components-android#1098] opened 2020-03-10 09:32 UTC
TabLayout.Tab with customview width seems forced to a specific pixel instead of wrapping my content on API 16

<img width="892" alt="Screen Shot 2020-03-10 at 15 01 49" src="https://user-images.githubusercontent.com/27192757/76298722-7e5c3f00-62ec-11ea-8603-756f3bc1c7f6.png">
left is API 16, right is API 21

My code :
```
val newTab = tablayoutid.newTab()

val tv = TextView(this)
tv.text = "Content12345"

newTab.customView = tv

tablayoutid.addTab(newTab)
```

Android API 16 & 17

stable 1.1.0

Pixel 3 XL AVD

**Comment by wcshi** [comment] 2020-05-04 16:12
Hi @stevenwijaya could you please provide a small sample app that reproduces your bug? Thanks!

**Comment by nj8522** [comment] 2021-04-23 14:28
<img width="1179" alt="Screenshot 2021-04-21 at 2 12 50 PM" src="https://user-images.githubusercontent.com/13277520/115886072-30fa4d00-a46e-11eb-8c87-54076b35143f.png">
I am having similar kind of issue with the TabLayout. Did you guys find any solution for the above problem

**Comment by drchen** [comment] 2022-02-07 22:10
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-07 22:10 UTC
Labels: bug
