### ISSUE TITLE
[Tabs] Useless tooltip on tab with text

### ISSUE THREAD

**Issue by haluzpav** [material-components/material-components-android#2074] opened 2021-02-17 10:05 UTC
**Description:** Tooltip is shown even when the tab has text, and tooltip has identical text. Probably caused by https://github.com/material-components/material-components-android/commit/fd3639092e1ffef9dc11bcedf79f32801d85e898, although there is "if tab is icon only" in description, but I don't see how it could make it "icon only". 🤷‍♂️ 

<img src="https://user-images.githubusercontent.com/24211726/108187930-4752f800-710f-11eb-9f55-92fa8d256e84.png" width=200 />

**Expected behavior:** Tooltip is **not** shown on tabs which have text, if there's no `contentDescription` specified.

**Source code:**

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.google.android.material.tabs.TabLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Tab 1" />

        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Tab 2" />

    </com.google.android.material.tabs.TabLayout>

</LinearLayout>
```

**Android API version:** 30

**Material Library version:** 1.3.0

**Device:** API 30 emulator

**Comment by hunterstich** [comment] 2021-02-18 01:03
Hey @haluzpav,

Is there a particular reason you don't want the tooltip to be displayed? 

I understand it seems redundant in the screenshot you've attached. However, I can see cases in which it might not be - the tab's text is too small or has insufficient contrast against its background.

**Comment by haluzpav** [comment] 2021-02-18 08:08
> However, I can see cases in which it might not be - the tab's text is too small or has insufficient contrast against its background.

That's just general problem with accessibility, like everywhere else. Should we now add a tooltip to every meaningful view, just in case they are too small or poorly visible? There's nothing fundamental about the tabs which would make them more likely to be less visible, compared to other views.

Or are there some material guidelines about tooltips I missed?

**Comment by hunterstich** [comment] 2021-02-18 17:22
Looking through the guidelines there is a section about not showing tooltips when they simply restate visible UI text - https://material.io/components/tooltips#placement

I'll talk bring this up with the team.

**Comment by ssand** [comment] 2021-07-19 15:58
Are there any updates regarding this issue?

**Comment by drchen** [comment] 2021-08-31 13:53
I think it looks more like a bug. The tooltip should only show when the tab has no text (i.e., icon only).

**Comment by drchen** [comment] 2021-09-01 13:52
Confirmed with the team. So the behavior is working as intended because tabs has limited displaying space. When users enlarge the text scale, we cannot enlarge tabs' text scale. Instead tooltips can provide larger text for the accessibility purpose. Closing the issue....

**Closed by drchen** 2021-09-01 13:52 UTC
Labels: bug, Needs Investigation
