### ISSUE TITLE
[TextInputLayout] Different behavior of end icon when focus lose

### ISSUE THREAD

**Issue by fcsd** [material-components/material-components-android#2191] opened 2021-04-28 15:55 UTC
**Description:** I found behavior of end icon when focus lose. When field contains only digit `android:inputType="phone"` or `android:inputType="number"` end icon not hiding and when field contains any symbol end icon hiding when focus lose. Look at screenshoot below.

**Expected behavior:** Equal behavior of these cases, perfectly control this from code or xml.

**Source code:** No special code, just simple TextInputLayout and TextInputEditText with input type
 ```
<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/layout_card_number"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="@string/card_number"
            style="@style/TextLayout">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/et_card_number"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="phone"/>

        </com.google.android.material.textfield.TextInputLayout>

 <style name="TextLayout">
        <item name="android:fontFamily">@font/golos_ui_regular</item>
        <item name="hintTextAppearance">@style/PayCash.TextLayout.Hint</item>
        <item name="errorTextAppearance">@style/PayCash.TextLayout.Error</item>
        <item name="endIconMode">clear_text</item>
        <item name="endIconDrawable">@drawable/ic_end_icon_close</item>
        <item name="endIconTint">@color/text_granite</item>
        <item name="errorIconDrawable">@null</item>
        <item name="errorTextColor">@color/brick</item>
        <item name="boxBackgroundColor">@color/transparentColor</item>
    </style>
```

**Android API version:** 29

**Material Library version:** 1.3.0

**Device:** Any

<img width="310" alt="Screen Shot 2021-04-28 at 19 01 06" src="https://user-images.githubusercontent.com/17144698/116435521-1e0fc000-a854-11eb-84bc-a63dd66c3078.png">

**Comment by drchen** [comment] 2021-06-22 21:18
Can't reproduce it with the latest version. 

Please let me know if this still happens.

**Comment by drchen** [comment] 2021-07-13 18:46
Closing the issue. Assuming it's not reproducible or fixed.

**Closed by drchen** 2021-07-13 18:46 UTC
Labels: bug
