### ISSUE TITLE
[MaterialButton] Long button text gets cut off when using maxlines=2 and ellipsize=end

### ISSUE THREAD

**Issue by geworfener** [material-components/material-components-android#841] opened 2019-12-19 17:17 UTC
**Description:** When using a MaterialButton with fixed width and fixed number of text lines, I tried to find a way to deal with dynamic button text that could be too long for the button size. When the text is too long for the button the words that don't fit will simply not be displayed by default, thus not indicating that there are words missing. When setting "ellipsize" to "end" the three dots get displayed, but the beginning of the text will be cut off in some situations.

**Steps to reproduce:** Check out and run this sample project: [https://github.com/geworfener/MaterialButtonEllipsizeBug](https://github.com/geworfener/MaterialButtonEllipsizeBug)

Alternatively:
1. Create a new Android project with a single activity.
2. Add material lib and set material theme.
3. Use the following activity layout:
```<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.button.MaterialButton
        android:layout_width="128dp"
        android:layout_height="wrap_content"
        android:maxLines="2"
        android:ellipsize="end"
        android:text="Hello world, this is a long text!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Actual behavior:** 

The first letter of the second text line gets cut off.

![image](https://user-images.githubusercontent.com/6763984/71192737-28e23a00-2289-11ea-933e-08fe8950997b.png)

**Expected behavior:** All words of the text are displayed fully.

**Android API version:** 28

**Material Library version:** 1.1.0-beta02, 1.2.0-alpha02

**Device:** Pixel 3a XL

**Comment by mgursch** [comment] 2020-01-09 13:34
+1

**Comment by gabrielemariotti** [comment] 2020-08-02 17:46
It happens also using `android:maxLines="1"`:

        <com.google.android.material.button.MaterialButton
            android:layout_width="128dp"
            android:layout_height="wrap_content"
            android:maxLines="1"
            android:ellipsize="end"
            android:text="Hello world, this is a long text!"
             />

<img width="110" alt="Schermata 2020-08-02 alle 19 45 05" src="https://user-images.githubusercontent.com/2583078/89128823-abf29080-d4f8-11ea-8443-ef5e82b89826.png">

It doesn't happen with an `AppCompatButton`:

<img width="101" alt="Schermata 2020-08-02 alle 19 45 59" src="https://user-images.githubusercontent.com/2583078/89128853-cb89b900-d4f8-11ea-85b9-4930736ee253.png">

**Comment by C0nstan** [comment] 2020-09-08 09:12
It still occurs in 1.2.0.
This is a serios functionality bug, wherefore we cant use the MaterialButton in our project.
Is there a time plan when this is getting fixed?

**Comment by tusharkathuria** [comment] 2020-09-17 14:03
I faced same with material text view. Is there any update on this?

**Comment by AnujK2901** [comment] 2020-10-02 02:54
It is still not fixed in 1.2.1

**Comment by samG4** [comment] 2020-11-27 11:25
need a fix soon.

**Comment by maximmcr** [comment] 2021-01-12 11:38
Still not fixed in 1.3.0 beta1

**Comment by Sammekl** [comment] 2021-01-19 12:42
Just as a (temporary) workaround, using both `maxLines="1"` and the deprecated `singleLine="true"` will fix the issue.

Without `singleLine="true"` you will get this issue

```
android:maxLines="1"
android:singleLine="true"
android:ellipsize="end"
```

**Comment by geworfener** [comment] 2021-01-20 19:36
Yes, single line is working, but this issue is about 2 lines of text.

**Comment by marius-m** [comment] 2021-12-10 10:07
I'm having this issue as well, however overriding `android:paddingTop="0dp"` in any direction fixed my problem. Hopefully this will work for you too 🤞

**Comment by drchen** [comment] 2022-04-14 20:26
I can't really reproduce the issue, tried different settings and they all look good to me.

I'll close this issue as obsolete. Please feel free to reopen it if it's still happening with the latest library version.

**Comment by anhduy5689h** [comment] 2022-04-20 07:32
I had the same issue, and I fixed it by set `android:maxWidth="1000dp"`

**Comment by drchen** [comment] 2022-04-20 13:35
@anhduy5689h which version of the library were you using?

**Comment by geworfener** [comment] 2022-04-23 19:49
@drchen The issue still exists for me with latest library versions 1.6.0-rc01 and 1.7.0-alpha01 - please checkout my example project that I just updated with the latest dependencies [https://github.com/geworfener/MaterialButtonEllipsizeBug](https://github.com/material-components/material-components-android/issues/url)

**Comment by drchen** [comment] 2022-04-25 15:04
Thanks! I'll take a second look.

**Comment by drchen** [comment] 2022-05-02 20:43
Can you update your theme to Material 3 and see if it works? 

I copied your settings but still could not reproduce the issue. The only thing seems suspicious to me is the out-dated theme.

**Closed** 2022-05-24 20:20 UTC
Labels: bug, Need more info, Widget: Button

**Comment by geworfener** [comment] 2022-05-29 17:43
Seems to be fixed for me after switching to Material3, thanks!

**Comment by drchen** [comment] 2022-05-31 15:22
Cool. Thanks for confirmation!! : )
