### ISSUE TITLE
[MaterialButton] OutlinedButton not showing

### ISSUE THREAD

**Issue by JiongBull** [material-components/material-components-android#850] opened 2019-12-25 02:26 UTC
**Description:** MaterialButton in Widget.MaterialComponents.Button.OutlinedButton style doesn't show anything.

![image](https://user-images.githubusercontent.com/4413502/71429252-b649e200-2700-11ea-9511-41db5d9f8b77.png)

**Expected behavior:** 

![image](https://user-images.githubusercontent.com/4413502/71429040-851ce200-26ff-11ea-98d9-cbe30d407f13.png)

**Source code:**

```xml
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.google.android.material.button.MaterialButton
            android:id="@+id/material_button"
            style="@style/Widget.MaterialComponents.Button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Default Button"/>

        <com.google.android.material.button.MaterialButton
            android:id="@+id/material_unelevated_button"
            style="@style/Widget.MaterialComponents.Button.UnelevatedButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Unelevated Button"/>

        <com.google.android.material.button.MaterialButton
            android:id="@+id/materialoutline_button"
            style="@style/Widget.MaterialComponents.Button.OutlinedButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Outlined Button"/>

        <com.google.android.material.button.MaterialButton
            android:id="@+id/material_text_button"
            style="@style/Widget.MaterialComponents.Button.TextButton"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Text Button"/>

        <com.google.android.material.button.MaterialButton
            android:id="@+id/material_icon_button"
            style="@style/Widget.MaterialComponents.Button.Icon"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Icon Button"
            app:icon="@drawable/success"/>

        <com.google.android.material.button.MaterialButton
            android:id="@+id/material_icon_text_button"
            style="@style/Widget.MaterialComponents.Button.TextButton.Icon"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Icon Text button"
            app:icon="@drawable/success"/>
    </LinearLayout>
```

**Android API version:** API Code 25

**Material Library version:** 1.2.0-alpha03

**Device:** Android emulator 7.1

**It works with 1.1.0-rc01.**

**Comment by tcqq** [comment] 2019-12-25 08:44
+1

**Comment by afohrman** [comment] 2019-12-26 20:58
I tested this with an API 25 emulator and the outlined button looks fine in the catalog: 
![image](https://user-images.githubusercontent.com/13263374/71490267-05267300-27f8-11ea-9b8d-ee3d3af3710a.png)

Did you encounter this issue on an emulator or in the design preview?

**Comment by tcqq** [comment] 2019-12-27 05:02
@afohrman design preview.

**Comment by divingpixel** [comment] 2020-01-09 09:09
I have the same problem, when I apply the style @style/Widget.MaterialComponents.Button.OutlinedButton
API 29 emulator

I get a Render problem : 
`java.awt.geom.IllegalPathStateException: missing initial moveto in path definition   at java.awt.geom.Path2D$Double.needRoom(Path2D.java:1193)   at java.awt.geom.Path2D.closePath(Path2D.java:1877)   at android.graphics.Path_Delegate.close(Path_Delegate.java:824)   at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)   at android.graphics.Path.nClose(Path.java:-1)   at android.graphics.Path.close(Path.java:508)   at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)   at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)   at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1142)   at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:940)   at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1011)   at android.graphics.drawable.DrawableWrapper.draw(DrawableWrapper.java:227)   at android.graphics.drawable.RippleDrawable.drawContent(RippleDrawable.java:818)   at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:675)   at android.view.View.drawBackground(View.java:20412)` ...

**Comment by ikim24** [comment] 2020-01-31 20:44
This is a duplicate of https://github.com/material-components/material-components-android/issues/776

**Closed by ikim24** 2020-01-31 20:44 UTC
Labels: bug, duplicate

**Comment by Alirezaaraby** [comment] 2020-04-03 15:59
I solved this problem with:
`implementation 'com.google.android.material:material:1.1.0-alpha09'`

**Comment by soodkartik24** [comment] 2020-05-19 19:56
I solved this problem with:
implementation 'com.google.android.material:material:1.2.0-alpha02

**Comment by udayarajurs** [comment] 2020-08-27 18:07
I solved this problem with:
implementation 'com.google.android.material:material:1.1.0

**Comment by combatistor** [comment] 2020-09-17 09:13
This bug reappears in version 1.2.1

**Comment by Cavitedev** [comment] 2020-11-29 16:17
I have solved the bug by updating the layout viewer in Android Studio, a messaged appeared at the bottom of the issues asking me to update and restart

**Comment by samuelowino** [comment] 2021-07-23 06:00
This issue reappears in 1.4.0

**Comment by Nasib555** [comment] 2023-03-18 05:03
I got rid of it by Updating Android Studio to the latest version.
