### ISSUE TITLE
[MaterialButton] click event not working on Google Pixel 5

### ISSUE THREAD

**Issue by agustinsivoplas** [material-components/material-components-android#1928] opened 2020-12-16 14:02 UTC
**Description:** The click event does not working in Google Pixel 5 (Android 11)

**Expected behavior:** Click event is triggered (works on Google Pixel 3a with Android 11)

**Source code:** 

```
<com.google.android.material.button.MaterialButton
        android:id="@+id/signInFingerprintButton"
        style="@style/PrimaryTextButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" 
        android:text="@string/fingerprint"
        app:icon="@drawable/ic_fingerprint"
        app:iconTint="@color/colorPrimaryDark"
        app:layout_constraintEnd_toStartOf="@+id/signInPasscodeButton"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

```
<style name="PrimaryTextButton" parent="Widget.MaterialComponents.Button.TextButton">
        <item name="textAllCaps">false</item>
        <item name="android:layout_height">@dimen/button_height</item>
        <item name="rippleColor">@color/ripple_gray</item>
        <item name="android:textColor">@color/colorPrimaryDark</item>
        <item name="android:textSize">@dimen/text_size_extra_small</item>
        <item name="android:lineSpacingExtra">1sp</item>
        <item name="fontFamily">@font/avenir_next_demibold_font</item>
    </style>
```
**Android API version:** Android 11

**Material Library version:** 1.2.0-alpha06

**Device:** Google Pixel 5

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1648539/102357876-948ae000-3f8d-11eb-8132-cef95ed2c2c5.gif)

**Comment by eemi2010** [comment] 2020-12-17 20:16
Same on Android 5 Pixel 2. Is there a workaround for this ? Another event maybe ?

**Comment by drchen** [comment] 2021-11-04 19:28
Is this still reproducible?

**Comment by drchen** [comment] 2022-01-12 20:28
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-01-12 20:28 UTC
Labels: bug, Need more info
