### ISSUE TITLE
[SwitchCompat] Uses wrong "off" color in Theme.Material3.DayNight

### ISSUE THREAD

**Issue by gmikhail** [material-components/material-components-android#3295] opened 2023-03-08 09:13 UTC
**Description:** The bug appears when using app theme `Theme.Material3.DayNight`, but not appears in default theme `Theme.MaterialComponents.DayNight`.

![Screenshot 2023-03-08 102548](https://user-images.githubusercontent.com/4838367/223669014-5e426e19-a09f-4b71-9a9b-5303d98e3467.png)

Note: this problem related to this issue ( https://issuetracker.google.com/issues/271871302 ) because `androidx.preference:preference` library seems to use the same widget component by default. 

**Expected behavior:**  Similar look like in app theme `Theme.MaterialComponents.DayNight`.

![Screenshot 2023-03-08 110817](https://user-images.githubusercontent.com/4838367/223670733-1ceadef6-c5e3-443e-adee-c323bd24f86d.png)

**Android API version:** 30

**Material Library version:** 1.8.0

**Comment by drchen** [comment] 2023-03-08 18:18
Hi, Material themes are supposed to work with Material components. It's not guaranteed that AppCompat components will be styled correctly with Material themes. : )

I'll close this as working as intended.

**Closed by drchen** 2023-03-08 18:18 UTC
Labels: bug

**Comment by dsn5ft** [comment] 2023-03-08 20:06
Also this is how you can have preferences use a MaterialSwitch:

https://github.com/material-components/material-components-android/issues/2828#issuecomment-1187563903
