### ISSUE TITLE
[Material Time Picker] AM/PM mode does not work in landscape on tablet

### ISSUE THREAD

**Issue by jlr-frameo** [material-components/material-components-android#2288] opened 2021-07-06 06:43 UTC
**Description:**
AM/PM input mode does not work on a tablet in landscape orientation - the controls are not shown (see screenshots below).

**Expected behavior:** 
![device-2021-07-06-083934](https://user-images.githubusercontent.com/82439432/124554043-cedaa280-de35-11eb-8225-6f7d791522f5.png)

**Actual behavior:** 
![device-2021-07-06-082554](https://user-images.githubusercontent.com/82439432/124554092-dac66480-de35-11eb-80fa-0498e1d4243e.png)

**Android API version:**
6.0.1

**Material Library version:**
1.4.0 (also tried 1.3.0)

**Comment by drchen** [comment] 2022-04-15 18:27
I think it's a duplicate of #1863. Let's just keep that issue open to better track this.

**Closed by drchen** 2022-04-15 18:27 UTC
Labels: bug, Widget: TimePicker
