### ISSUE TITLE
Issue with migration from alpha05 to alpha06 bug

### ISSUE THREAD

**Issue by sanaxes** [material-components/material-components-android#379] opened 2019-05-24 15:09 UTC
I have very simple hierarchy. Super class is abstract Activity with Navigation drawer and another super class thah extends from this super class - BaseActivity. On verisons of material design library 1.0.0 - 1.1.0-alpha05 this code is work good. But when i'm update to 1.1.0-alpha06 i have this problem on start activity:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ru.sanaxes.easybox, PID: 4479
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.sanaxes.easybox/ru.sanaxes.easybox.ui.DatabasesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.getDecorView()' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3364)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548)
                      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
                      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
                      at android.os.Handler.dispatchMessage(Handler.java:109)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:7539)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.getDecorView()' on a null object reference
                      at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:675)
                      at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:618)
                      at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:540)
                      at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
                      at ru.sanaxes.easybox.ui.NavigationActivity.onCreate(NavigationActivity.java:47)
                      at ru.sanaxes.easybox.ui.BaseActivity.onCreate(BaseActivity.java:69)
                      at ru.sanaxes.easybox.ui.DatabasesActivity.onCreate(DatabasesActivity.java:30)
                      at android.app.Activity.performCreate(Activity.java:7441)
                      at android.app.Activity.performCreate(Activity.java:7431)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3343)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548) 
                      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
                      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
                      at android.os.Handler.dispatchMessage(Handler.java:109) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:7539) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 


-- My classes --

public abstract class NavigationActivity extends AppCompatActivity implements NavigationView.OnNavigationItemSelectedListener {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.setContentView(R.layout.activity_base);
        super.onCreate(savedInstanceState);
        ....
    }
}

public abstract class BaseActivity extends NavigationActivity {
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState); 
        ....
    }

    @Override
    public void setContentView(@LayoutRes int layoutResID) {
        LayoutInflater inflater = (LayoutInflater) getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View layout = inflater.inflate(layoutResID, null);
        baseLinearLayout.addView(layout);
    }


}
```

**Comment by EdwardMuturi** [comment] 2019-05-28 13:51
@sanaxes do you mind adding a bug label to this issue, maybe it might help for easy identification
Been having the issue too, I have the same structure too.

1. MultipleChoiceQuestionActivity extends BaseQuestionActivity
2. BaseQuestionActivity extends BaseStoryActivity 
3. BaseStoryActivity extends AppCompatActivity


**what's working:** com.google.android.material:material:1.1.0-alpha04
**error cause identified**:    'com.google.android.material:material:1.1.0-alpha06

``` gradle
2019-05-28 16:33:26.155 23882-23924/com.elimu.hadithi.kiswahili E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
2019-05-28 16:33:28.517 23882-23924/com.elimu.hadithi.kiswahili E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
2019-05-28 16:33:33.282 23882-23924/com.elimu.hadithi.kiswahili E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
2019-05-28 16:33:37.000 23882-23924/com.elimu.hadithi.kiswahili E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
2019-05-28 16:33:38.121 23882-23882/com.elimu.hadithi.kiswahili E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.elimu.hadithi.kiswahili, PID: 23882
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.elimu.hadithi.kiswahili/com.elimu.storytime.activities.questions.MultipleChoiceQuestionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.getDecorView()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2897)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.getDecorView()' on a null object reference
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:675)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:618)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:540)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
        at com.elimu.storytime.activities.questions.MultipleChoiceQuestionActivity.onCreate(MultipleChoiceQuestionActivity.java:49)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2772)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2897) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6548) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857) 
```

**Comment by EdwardMuturi** [comment] 2019-05-29 08:39
@sanaxes [this](https://help.github.com/en/articles/applying-labels-to-issues-and-pull-requests) is what I mean.

**Comment by melaniegoetz** [comment] 2019-05-29 21:45
Thank you for reporting this! Made a buganizer bug https://b.corp.google.com/issues/133872957 to investigate and address this Null pointer issue. Closing this github issue.

**Closed by melaniegoetz** 2019-05-29 21:45 UTC

**Comment by cketcham** [comment] 2019-08-20 16:44
@sanaxes This looks like it might be caused by an alpha version of our dependency on appcompat. Could you try with the latest version and reopen this issue if it's still a problem? thanks.
