### ISSUE TITLE
MaterialContainerTransform Card bounds jumps during animation

### ISSUE THREAD

**Issue by ColtonIdle** [material-components/material-components-android#1704] opened 2020-09-11 07:37 UTC
@dsn5ft I'm following up on a bug I ended the conversation with from here: https://github.com/material-components/material-components-android/issues/1224

Heres the repo of the original issue https://github.com/ColtonIdle/ContainerTransformOrSharedElement

Here's the current code:

```
class FirstFragment : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_first, container, false)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val hold = Hold()
        hold.duration = 300
        exitTransition = hold
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        view.findViewById<View>(R.id.cardView).setOnClickListener { card ->
            val extras = FragmentNavigatorExtras(card to "shared_element_container")
            findNavController().navigate(R.id.action_FirstFragment_to_SecondFragment, null, null, extras)
        }
    }
}
```

```
class SecondFragment : Fragment() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val enterTransform = MaterialContainerTransform()
        enterTransform.duration = 300
        enterTransform.drawingViewId = R.id.myactual
        sharedElementEnterTransition = enterTransform

        val returnTransform = MaterialContainerTransform()
        returnTransform.duration = 300
        sharedElementReturnTransition = returnTransform
         returnTransform.drawingViewId = R.id.cardView
    }
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_second, container, false)
    }
}
```

first fragment xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    android:clipToPadding="false"
    tools:context=".FirstFragment">

    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/materialToolbar"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:title="First Fragment"
        android:background="?attr/colorPrimary"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.card.MaterialCardView
        android:id="@+id/cardView"
        android:layout_width="0dp"
        android:transitionName="shared_element_container"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginEnd="16dp"
        android:layout_marginBottom="16dp"
        android:clipChildren="false"
        android:clipToPadding="false"
        app:cardUseCompatPadding="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:maxHeight="300dp"
                android:transitionName="sharedImage"
                android:scaleType="centerCrop"
                android:id="@+id/imageView"
                android:src="@drawable/unsplash" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_margin="8dp"
                android:orientation="vertical">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                android:transitionName="sharedText1"
                    android:id="@+id/textView1"
                    android:text="Line 1"
                    android:textAppearance="?attr/textAppearanceHeadline4" />

                <TextView
                    android:id="@+id/textView2"
                android:transitionName="sharedText2"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines."
                    android:textAppearance="?attr/textAppearanceBody1" />
            </LinearLayout>

        </LinearLayout>
    </com.google.android.material.card.MaterialCardView>

</androidx.constraintlayout.widget.ConstraintLayout>
```

second fragment xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    android:clipToPadding="false"
    tools:context=".FirstFragment">

    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/materialToolbar"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:title="Second Fragment"
        android:background="?attr/colorPrimary"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <LinearLayout
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:orientation="vertical"
        android:background="?attr/colorSurface"
        android:id="@+id/myactual"
        android:transitionName="shared_element_container"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/materialToolbar">

        <ImageView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:adjustViewBounds="true"
            android:transitionName="sharedImage"
            android:maxHeight="300dp"
            android:scaleType="centerCrop"
            android:src="@drawable/unsplash" />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="8dp"
            android:orientation="vertical">

            <TextView
                android:layout_width="wrap_content"
                android:transitionName="sharedText1"

                android:layout_height="wrap_content"
                android:text="Line 1"
                android:textAppearance="?attr/textAppearanceHeadline4" />

            <TextView
                android:layout_width="wrap_content"
                android:transitionName="sharedText2"

                android:layout_height="wrap_content"
                android:text="Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines. Line 2 is a bunch of lines."
                android:textAppearance="?attr/textAppearanceBody1" />
        </LinearLayout>

    </LinearLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

Here is how it looks like using `    implementation 'com.google.android.material:material:1.3.0-alpha02'`

![blah2](https://user-images.githubusercontent.com/31751141/92884573-f6acd580-f3df-11ea-823c-31e7fe229bea.gif)

You can see there is a really bad jump when going in the reverse direction (hitting the back button). Is there something wrong with my code, or is it the mdc motion library?

**Comment by dsn5ft** [comment] 2020-09-11 16:53
Is the repo updated with the "current code" you provided so I can reproduce this?

**Comment by ColtonIdle** [comment] 2020-09-18 04:37
@dsn5ft nope. I just pasted all of my current code in the ticket. I'll make a note to circle back to this and update the repo.

**Comment by ColtonIdle** [comment] 2021-10-08 04:32
All info was provided. I don't think there's anything missing.

**Comment by hunterstich** [comment] 2021-12-03 23:50
Hi @ColtonIdle,

It looks like you just needed to set a few things up differently.

If you give me access to push to your example repo, I can do that. Otherwise, heres a zip of the project with fixes - 
[ContainerTransformOrSharedElementFixed.zip](https://github.com/material-components/material-components-android/files/7652916/ContainerTransformOrSharedElementFixed.zip)

Basically:
• Set your shared elements to the containers of what will persist between screens. In your example's case, this is the `MaterialCardView` in `FirstFragment` and the `LinearLayout` in the `SecondFragment`. No "inner" shared elements are necessary. MaterialContainerTransform doesn't manipulate the contents of the container but rather just swaps them out during the animation to make it look like they're being persisted.
• Remove all the transition names from the views in the fragment layouts other than the `MaterialCardView` and `LinearLayout` mentioned above.
• Set your `fragment_second` `LinearLayout` to have `android:background="?android:windowBackground"` (or whatever color the linear layout's background should be other than transparent. During the animation, when the second fragment is being faded in on top of the first fragment, this will prevent the first fragment from being visible beneath it. Alternatively, a method called `MaterialContainerTransform.setAllContainerColors()` was added in https://github.com/material-components/material-components-android/commit/e00df6d075d9f99f4fc74f06bb16b76a9a935a86 if you want to upgrade your project's material components lib version.
• Customize MaterialContainerTransform to not show a scrim so the toolbar that exists in each fragment isn't dimmed during the animation. This is done with `materialContainerTransform.scrimColor = Color.TRANSPARENT`.

Let me know if that helps. Closing but feel free to reopen if you still run into issues.

**Closed by hunterstich** 2021-12-03 23:50 UTC
Labels: bug, Widget: Transition

**Comment by ColtonIdle** [comment] 2021-12-04 02:30
Yeah. This is a year old. We're all using compose now at work so none of this matters anymore. 😂

**Comment by a1782680475** [comment] 2022-09-02 03:10
> Hi @ColtonIdle,
> 
> It looks like you just needed to set a few things up differently.
> 
> If you give me access to push to your example repo, I can do that. Otherwise, heres a zip of the project with fixes - [ContainerTransformOrSharedElementFixed.zip](https://github.com/material-components/material-components-android/files/7652916/ContainerTransformOrSharedElementFixed.zip)
> 
> Basically: • Set your shared elements to the containers of what will persist between screens. In your example's case, this is the `MaterialCardView` in `FirstFragment` and the `LinearLayout` in the `SecondFragment`. No "inner" shared elements are necessary. MaterialContainerTransform doesn't manipulate the contents of the container but rather just swaps them out during the animation to make it look like they're being persisted. • Remove all the transition names from the views in the fragment layouts other than the `MaterialCardView` and `LinearLayout` mentioned above. • Set your `fragment_second` `LinearLayout` to have `android:background="?android:windowBackground"` (or whatever color the linear layout's background should be other than transparent. During the animation, when the second fragment is being faded in on top of the first fragment, this will prevent the first fragment from being visible beneath it. Alternatively, a method called `MaterialContainerTransform.setAllContainerColors()` was added in [e00df6d](https://github.com/material-components/material-components-android/commit/e00df6d075d9f99f4fc74f06bb16b76a9a935a86) if you want to upgrade your project's material components lib version. • Customize MaterialContainerTransform to not show a scrim so the toolbar that exists in each fragment isn't dimmed during the animation. This is done with `materialContainerTransform.scrimColor = Color.TRANSPARENT`.
> 
> Let me know if that helps. Closing but feel free to reopen if you still run into issues.

But how can I use setallcontainercolors in oncreate? This will report an error;
![image](https://user-images.githubusercontent.com/32875468/188051353-0c2a68bc-9ae0-409f-ab10-016f40e3992f.png)

**Comment by a1782680475** [comment] 2022-09-02 03:47
![image](https://user-images.githubusercontent.com/32875468/188055144-ba7c1100-7287-41b6-afa3-729b55520478.png)
I solved this problem in this way. Is there a way to directly obtain the color value without judging whether it is a dark mode?

**Comment by a1782680475** [comment] 2022-09-02 05:10
> Hi @ColtonIdle,
> 
> It looks like you just needed to set a few things up differently.
> 
> If you give me access to push to your example repo, I can do that. Otherwise, heres a zip of the project with fixes - [ContainerTransformOrSharedElementFixed.zip](https://github.com/material-components/material-components-android/files/7652916/ContainerTransformOrSharedElementFixed.zip)
> 
> Basically: • Set your shared elements to the containers of what will persist between screens. In your example's case, this is the `MaterialCardView` in `FirstFragment` and the `LinearLayout` in the `SecondFragment`. No "inner" shared elements are necessary. MaterialContainerTransform doesn't manipulate the contents of the container but rather just swaps them out during the animation to make it look like they're being persisted. • Remove all the transition names from the views in the fragment layouts other than the `MaterialCardView` and `LinearLayout` mentioned above. • Set your `fragment_second` `LinearLayout` to have `android:background="?android:windowBackground"` (or whatever color the linear layout's background should be other than transparent. During the animation, when the second fragment is being faded in on top of the first fragment, this will prevent the first fragment from being visible beneath it. Alternatively, a method called `MaterialContainerTransform.setAllContainerColors()` was added in [e00df6d](https://github.com/material-components/material-components-android/commit/e00df6d075d9f99f4fc74f06bb16b76a9a935a86) if you want to upgrade your project's material components lib version. • Customize MaterialContainerTransform to not show a scrim so the toolbar that exists in each fragment isn't dimmed during the animation. This is done with `materialContainerTransform.scrimColor = Color.TRANSPARENT`.
> 
> Let me know if that helps. Closing but feel free to reopen if you still run into issues.

The same bug occurs when I use materialcardviewelevatedstyle. I can use setallcontainercolors to solve this problem on Android 6.0, but not on Android 12
