### ISSUE TITLE
[CollapsingToolbarLayout] The attribute expandedTitleMarginEnd does not work

### ISSUE THREAD

**Issue by Back4fire** [material-components/material-components-android#2240] opened 2021-06-05 16:27 UTC
When the text size in collapsedTitleTextAppearance and expandedTitleTextAppearance are same, the expandedTitleMarginEnd seems to be ignored. But if the difference between the two text sizes is >= 0.001, everything will be perfect.  After a rough walking through the source code, the issue should be relevant to the logic "isClose()" in CollapsingTextHelper. The issue still exists in 1.4.0-beta01. 

The source code of the CollapsingToolbarLayout in the layout xml:
```
       <com.google.android.material.appbar.CollapsingToolbarLayout
                  android:id="@+id/toolbar_layout"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent"
                  android:fitsSystemWindows="true"
                  app:contentScrim="@color/teal_200"
                  app:collapsedTitleTextAppearance="@style/TextAppearance.Design.CollapsingToolbar.Expanded"
                  app:expandedTitleTextAppearance="@style/TextAppearance.Design.CollapsingToolbar.Expanded"
                  app:expandedTitleMargin="64dp"
                  app:layout_scrollFlags="scroll|exitUntilCollapsed"
                  app:maxLines="2"
                  app:statusBarScrim="@color/teal_200"
                  app:title="This is a very long title that is really really long"
                  app:toolbarId="@+id/toolbar"/>
```

The layout preview:
<img width="331" alt="WX20210606-001827@2x" src="https://user-images.githubusercontent.com/20295792/120898272-c0de0a00-c65c-11eb-84b1-10dcae2a3f11.png">

The attribute app:expandedTitleMargin="64dp" does not work.

**Comment by drchen** [comment] 2022-04-28 21:36
It's a duplicate of https://github.com/material-components/material-components-android/issues/2459.
Let's keep tracking the issue in one place.

**Closed by drchen** 2022-04-28 21:36 UTC
Labels: bug, Widget: TopAppBar
