### ISSUE TITLE
[RangeSlider] When app:labelBehavior="visible", thumbs staying displayed while scrolling

### ISSUE THREAD

**Issue by anthonydelahoz** [material-components/material-components-android#3119] opened 2022-11-29 12:03 UTC
Hello,

Graphic bug when i have a RangeSlider in a NestedScrollView and app:labelBehavior="visible"
The thumb stay at the initial position of the Slider

![image](https://user-images.githubusercontent.com/58596714/204523685-62b476f4-3683-4b6d-9b12-6109cf07afbe.png)

        <com.google.android.material.slider.RangeSlider
            android:id="@+id/continuousRangeSlider"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="8dp"
            android:stepSize="1"
            android:valueFrom="0"
            android:valueTo="96"
            app:labelBehavior="visible" />

Android 7 & 13

Material Library version: com.google.android.material:material:1.7.0

**Comment by leticiarossi** [comment] 2022-11-30 22:39
Thank you for reporting, will close this as duplicate of https://github.com/material-components/material-components-android/issues/2869

**Closed by leticiarossi** 2022-11-30 22:39 UTC
Labels: bug, Widget: Slider
