### ISSUE TITLE
[BottomSheet] Calling requestLayout() will cause bottom sheet to be placed in wrong position

### ISSUE THREAD

**Issue by mxalbert1996** [material-components/material-components-android#1880] opened 2020-11-18 00:54 UTC
**Description:** Calling `requestLayout()` when a bottom sheet is shown will cause the bottom sheet to be moved down.
Video: https://i.imgur.com/Ioyvsf3.mp4

**Expected behavior:** Calling `requestLayout()` shouldn't change the bottom sheet's position.

**Source code:** [BottomSheetTest.zip](https://github.com/material-components/material-components-android/files/5557038/BottomSheetTest.zip)

**Android API version:** Tested on API 29 & 30

**Material Library version:** 1.2.1 / 1.3.0-alpha03

**Comment by AlexandreG** [comment] 2021-01-14 14:25
this seems to be related to this issue
https://github.com/material-components/material-components-android/issues/1373

at least app:gestureInsetBottomIgnored="true" solved it for me

**Comment by drchen** [comment] 2022-06-01 18:28
Is this still reproducible with the latest library version?

**Comment by drchen** [comment] 2022-06-16 19:07
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-06-16 19:07 UTC
Labels: bug, Need more info, Widget: BottomSheet
