### ISSUE TITLE
[MaterialDatePicker] MaterialDatePicker crashes with mode=INPUT_MODE_TEXT 

### ISSUE THREAD

**Issue by jarroyoesp** [material-components/material-components-android#3399] opened 2023-05-15 09:25 UTC
**Description:** Steps to Reproduce it:

- Build a MaterialDatePicker with InputMode=MaterialDatePicker.INPUT_MODE_TEXT
- Crash happens

**Expected behavior:** Open `MaterialDatePicker` without crashing

**Source code:**
```kotlin
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            AppTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    DatePicker()
                }
            }
        }
    }

    @Composable
    private fun DatePicker(){
        val activity = LocalContext.current as AppCompatActivity
        MaterialDatePicker.Builder.datePicker().apply {
            setTitleText("title")
            setInputMode(MaterialDatePicker.INPUT_MODE_TEXT)
        }.build().run {
            show(activity.supportFragmentManager, "fragmentTag")
        }
    }
}
```

**Minimal sample app repro:** You can find a sample project here: https://github.com/jarroyoesp/MaterialDatePickerIssue

**Android API version:** Android API 30+

**Material Library version:** 
- Material: "com.google.android.material:material:1.9.0"
- Jetpack Compose version: 1.5.0-alpha04
- Jetpack Compose component used: com.google.android.material.datepicker.MaterialDatePicker
- Android Studio Build: Android Studio Flamingo | 2022.2.1 Patch 1 Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
- Kotlin version: 1.8.20

**Device:** Android devices/emulator with API version 30+

**Stack trace:**
```
FATAL EXCEPTION: main
Process: com.jarroyo.datepickerissue, PID: 7601
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
	at androidx.core.view.SoftwareKeyboardControllerCompat$Impl30.hide(SoftwareKeyboardControllerCompat.java:220)
	at androidx.core.view.SoftwareKeyboardControllerCompat.hide(SoftwareKeyboardControllerCompat.java:81)
	at androidx.core.view.WindowInsetsControllerCompat$Impl30.hide(WindowInsetsControllerCompat.java:633)
	at androidx.core.view.WindowInsetsControllerCompat.hide(WindowInsetsControllerCompat.java:189)
	at com.google.android.material.internal.ViewUtils.hideKeyboard(ViewUtils.java:91)
	at com.google.android.material.internal.ViewUtils.hideKeyboard(ViewUtils.java:84)
	at com.google.android.material.datepicker.DateSelector.lambda$showKeyboardWithAutoHideBehavior$0(DateSelector.java:142)
	at com.google.android.material.datepicker.DateSelector$$ExternalSyntheticLambda0.onFocusChange(Unknown Source:2)
	at android.view.View.onFocusChanged(View.java:8116)
	at android.widget.TextView.onFocusChanged(TextView.java:10839)
	at android.view.View.clearFocusInternal(View.java:7953)
	at android.view.View.clearFocus(View.java:7932)
	at android.view.ViewGroup.clearFocus(ViewGroup.java:1188)
	at android.view.ViewGroup.clearFocus(ViewGroup.java:1188)
	at android.view.ViewGroup.clearFocus(ViewGroup.java:1188)
	at android.view.View.setFlags(View.java:16165)
	at android.view.View.setVisibility(View.java:11719)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.onStart(SpecialEffectsController.java:736)
	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:308)
	at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:267)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2202)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
	at com.google.android.material.datepicker.MaterialDatePicker.startPickerFragment(MaterialDatePicker.java:454)
	at com.google.android.material.datepicker.MaterialDatePicker.onStart(MaterialDatePicker.java:353)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Sending signal. PID: 7601 SIG: 9
------------------
```

**Comment by mtotschnig** [comment] 2023-05-15 09:43
The problem is likely being caused because you show the dialog directly in your composable function, which is something you are not supposed to do. Composable functions are not supposed to have side effects.

**Comment by mtotschnig** [comment] 2023-05-15 10:38
@leinardi I had supposed that it would work, when you show the dialogue from a launched effect, or in the onClick handler of a button. But my assumption was false. You are right, there is a problem with MaterialDatePicker.INPUT_MODE_TEXT. I can reproduce the problem also in these scenarios.

**Comment by paulfthomas** [comment] 2023-05-15 14:47
This should be fixed by https://github.com/material-components/material-components-android/commit/7ccf6708b0299317c3757c4d86a47827839c9ef7, please reopen if you still have issues.

**Closed by paulfthomas** 2023-05-15 14:47 UTC
Labels: bug
