### ISSUE TITLE
[TextInputLayout] Espresso test of screen containing TextInputLayout with endIcon fails with AppNotIdleException

### ISSUE THREAD

**Issue by kbrz** [material-components/material-components-android#502] opened 2019-08-06 07:30 UTC
Hello,

**Description:** I have a few screens containing TextInputLayouts. If any of those inputs have endIcon set (e.g. endIconMode=passwordToggle, endIconMode=custom) then all tests fail with AppNotIdleException. If I change endIconMode=none everything works as before (I was using version 1.0.0, now updating to 1.1.0-alpha09). In 1.0.0 I was using setPasswordVisibilityToggle... methods.

**Expected behavior:** Espresso tests are passing as in previous version.

**Android API version:** 21, 28

**Material Library version:** 1.1.0-alpha09

**Device:** Android emulator configured for espresso testing.

I am also unable to use layout inspector on such screen.

> The device may be too slow, the captured view may be too complex, or the view may contain animations.

With endIconMode=none there is no problem with capturing layout.

**Comment by kbrz** [comment] 2019-08-06 10:18
I did some debugging and it happens only when TextInputLayout is inside ConstraintLayout and is constrained like start<->parent:start, end<->parent:end, and its layout_width=0dp. When I changed layout_width=match_parent the issue is gone.

**Comment by ldjcmu** [comment] 2019-10-01 06:52
As this is for test cases and has a workaround, I'm going to close this issue.

**Comment by stephanesallaberry** [comment] 2019-12-09 15:14
@kbrz I have the exact opposite: if I set width to 0dp, it works. If I set it to match_parent test fails ¯\_(ツ)_/¯

**Comment by markomeara** [comment] 2020-03-25 15:49
I am experiencing the same problem however the TextInputLayout is not in a ConstraintLayout, and therefore the workaround does not work for me.

**Comment by kkhcheng** [comment] 2020-06-30 09:52
> As this is for test cases and has a workaround, I'm going to close this issue.

This should not be closed as the work around does not work for everyone

**Comment by ilandbt** [comment] 2021-07-13 19:10
Is there a fix for this?

**Comment by ilandbt** [comment] 2021-08-05 11:50
@drchen  is there anything I can do to help to debug this issue?

**Comment by drchen** [comment] 2021-10-04 19:21
I'm sorry that I guess we won't really have the capacity to work on this until the next year, given the issue is only test related and therefore with relatively low priority. However, if you can help us identify the root cause that will be very helpful.

**Comment by jmarks213** [comment] 2021-12-16 12:00
Greetings - I spent the last week racking my head around a bug which this issue thread describes.  I spent so much time looking at coroutines, did not expect the problem with this GUI element.

In solidarity, I have created a sample repo which reproduces this issue every time just run the instrumentation test.  Changing the TextInputLayout's width to match_parent fixes the bug as noted above.

https://github.com/jmarks213/TextInputEditTextBug

**Comment by drchen** [comment] 2022-06-13 22:04
For API 21 & 22, I believe it's a duplicate of https://github.com/material-components/material-components-android/issues/1673.

I cannot reproduce the issue on API 28. Can you double confirm this is reproducible on API 28 (or any API levels other than 21/22) as well?

**Comment by drchen** [comment] 2022-06-27 12:55
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening on any API levels other than 21 or 22.

**Closed by drchen** 2022-06-27 12:55 UTC
Labels: bug, Need more info, Widget: TextField, Issue: Test
