### ISSUE TITLE
[TextInputLayout] Add click listener for error icon 

### ISSUE THREAD

**Issue by agent10** [material-components/material-components-android#1213] opened 2020-04-16 07:50 UTC
There is a possibility to set a click listener only for start/end icons but not for error icon.

**Comment by dsn5ft** [comment] 2020-04-16 18:36
Hi @agent10, can you let us know what your use case is for allowing clicks on the error icon? Our designers want to understand this better before opening up this pattern.

**Comment by agent10** [comment] 2020-04-16 18:42
Hi, we have two cases:
1) Clear text field
2) Showing extended info

**Comment by dsn5ft** [comment] 2020-04-16 19:49
Ah I see.

1. For clearing the text field, is the issue is that the clear X button (`clear_text ` `endIconMode`) gets hidden when the ! error icon is shown?

2. For that extended info, have you considered using the `setError` message which shows up below the text field when there's an error?

**Comment by agent10** [comment] 2020-04-16 19:57
1. We don't have X button for clearing text in normal case. Only when error happened - to quick clear the field.
2. We use error message with short info. We would like to show some kind of dialog(toast/another screen) with extended info when user clicked on the error icon.

**Comment by dsn5ft** [comment] 2020-04-17 22:46
Our designers agree that you should be able to set a click listener on the error icon, we'll take a look at merging in your PR soon.

**Comment by dsn5ft** [comment] 2020-04-22 19:08
Fixed in https://github.com/material-components/material-components-android/commit/1b124afa0264908f1f84b37554c659e2e10bf050 (import of #1215)

**Closed by dsn5ft** 2020-04-22 19:08 UTC
Labels: feature request

**Comment by BirenLadva18** [comment] 2021-02-01 10:05
is it possible to set onclick on custom icon in TextInputLayout ?? if yes then pls tell me how...
