### ISSUE TITLE
[MaterialContainerTransform] freezes LottieImageView

### ISSUE THREAD

**Issue by brayanm23** [material-components/material-components-android#2077] opened 2021-02-17 19:47 UTC
**Description:** MaterialContainerTransform freezes LottieImageView.

I am using MaterialContainerTransform to transition from a fragment to an activity, I am setting the transitionName to android.R.id.content. The transition is executed well but in the destination activity I have a lottie and it is frozen.

https://user-images.githubusercontent.com/32348263/108259227-9c0e6700-713f-11eb-9bc1-c8ad84644a51.mov

**Android API version:** All

**Material Library version:** 1.3.0

**Device:** Xiaomi mi A2, Pixel XL

**Comment by hunterstich** [comment] 2021-02-18 00:56
Hey @brayanm23,

Does this happen if you use something like an `androidx.transition.Slide`? Or a transition from AndroidX instead of Material?

Would you be able to attach a sample that reproduces this?

**Comment by drchen** [comment] 2021-11-03 17:53
I'll close the issue due to no further information available. Feel free to reopen it more explanations.

**Closed by drchen** 2021-11-03 17:53 UTC
Labels: bug
