### ISSUE TITLE
[CollapsingToolbarLayout] RecyclerView bottom cut when coming back from another fragment

### ISSUE THREAD

**Issue by NitroG42** [material-components/material-components-android#1070] opened 2020-02-28 14:04 UTC
**Description:** Issue can be seen on the official Catalog app. This video will show the issue : https://streamable.com/y2r6l
To resume, you go to the bottom of a list - on a screen which contains a CollapsingToolbar.
Going to another fragment (by clicking on an item) and then coming back will make the list be "cut" on the bottom of the size of the collapsingtoolbar (minus the standard size of the toolbar it seems).
The only way to make the cut disappears is expanding the collapsingtoolbar (by going on top of the screen), then scroll back.
Again see the streamable link to see exactly the steps and the problem.
It is also reproducible on apps I worked on with a similar setup and behavior.

**Expected behavior:** Screenshots and/or description of expected behavior
No cut !

**Source code:** Official Material Catalog app

**Android API version:** Tested on API 28

**Material Library version:** Last commit a36826b01852d8a65aabd2bc81604ed0e72422ed
Also happens on every others versions.

**Device:** Device on which the bug was encountered here
Pixel XL, Pixel 4, many more

**Comment by extmkv** [comment] 2020-03-27 12:11
Did you found a workaround for this problem?

**Comment by zakrodionov** [comment] 2020-05-07 09:32
Oh Google, this bug has been around for many years, and even in your project it is reproduced each time, is it really impossible to fix it?

**Comment by nijat-ahmadli** [comment] 2020-07-23 08:39
Workaround is to add `android:layout_marginBottom="?attr/actionBarSize"` to your `RecyclerView`

**Comment by dsn5ft** [comment] 2020-08-03 12:55
Closing as duplicate of https://github.com/material-components/material-components-android/issues/1558 which provides a little more information. Hoping to take a look at this soon, but if anyone has any ideas on what may be happening or when this started happening, feel free to comment there.

**Closed by dsn5ft** 2020-08-03 12:55 UTC
Labels: bug
