### ISSUE TITLE
[MaterialTimePicker] button overlaps with inputMode imageView 

### ISSUE THREAD

**Issue by aitizazsyed02** [material-components/material-components-android#2407] opened 2021-10-04 09:34 UTC
**Description:** 
It's not working with API level 30 on Nokia 7.2 but working with API level 26 on Nexus 6P.

**Expected behavior:** Screenshots shows on click behavior on both buttons to show negativeButton is overlapping to the inputMode imageView.

![Screenshot_20211004-114452](https://user-images.githubusercontent.com/18308906/135823022-4f964a51-bbf5-4053-a7d2-34dde416cb9b.png)

**Android API version:** 30

**Material Library version:** 1.4.0

**Device:** Nokia 7.2, Nexus 6p

**Comment by drchen** [comment] 2021-10-04 15:53
Hi it looks like you are customizing your themes/styles. Can you provide your theme/style settings? 

I'll suggest you to check your button styles first.

**Comment by aitizazsyed02** [comment] 2021-10-04 22:21
Custom Button style declared in the theme will affect  MaterialTimePicker button?

Then does it works for the Nexus 6P (API 26) in my case and not working for Nokia 7.2 (API 30)

**Comment by drchen** [comment] 2021-11-02 20:45
Yes it's using ?attr/borderlessButtonStyle defined in your themes. (You can override the attribute in the theme overlay specified in ?attr/materialTimePickerTheme)

Are you overriding anything in resources folders of different SDK versions?

**Comment by aitizazsyed02** [comment] 2021-11-03 07:52
No, didn't override anything related to button in different SDK versions.

**Comment by drchen** [comment] 2022-02-04 18:36
Can you provide a reproducible sample for us to debug?

**Comment by drchen** [comment] 2022-03-03 19:34
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-03 19:34 UTC
Labels: bug, Need more info, Widget: TimePicker
