### ISSUE TITLE
[Slider] Layout broken when using Slider on dialog

### ISSUE THREAD

**Issue by SupasinTatiyanupanwong** [material-components/material-components-android#3004] opened 2022-10-03 12:29 UTC
**Description:**
Dialog custom layout broken when using `Slider` inside. Given the layout as described in the next section.
The dialog custom layout is set by using `AlertDialog.Builder(context).setView(viewResId).build()`.

When using `Space` in place of `Slider`
![Screenshot_20221005_100841](https://user-images.githubusercontent.com/14759073/193972693-5d640b0b-d58f-4f7f-b131-01b7000d86dc.png)

When replaced `Space` with `Slider`
![Screenshot_20221005_100720](https://user-images.githubusercontent.com/14759073/193972572-e9cae1a9-2839-45f9-a683-4d7310d1f98a.png)

**Expected behavior:**
The whole should look the same when not using Slider. Slider itself should not interfere how its parent should lay their children. Without changes made to the root or parent view of Slider, the result should look like:
![Screenshot_20221005_101051](https://user-images.githubusercontent.com/14759073/193972988-d3d17a1c-61d9-48c8-b416-591884f87f94.png)

In this screenshot, I rewrote the layout from using LinearLayout as parent to ConstraintLayout.

**Source code:** The code snippet which is causing this issue
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:paddingHorizontal="?dialogPreferredPadding">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:ellipsize="end"
                android:paddingTop="16dp"
                android:paddingEnd="8dp"
                android:paddingBottom="4dp"
                android:text="Coverage (meters)"
                android:textColor="?android:textColorPrimary"
                android:textSize="16sp"
                android:textStyle="bold" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:includeFontPadding="false"
                android:textColor="?colorPrimary"
                android:textSize="34sp"
                android:textStyle="bold"
                tools:text="100" />

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="-4dp"
            android:layout_marginEnd="-4dp"
            android:orientation="horizontal">

            <com.google.android.material.button.MaterialButton
                android:layout_width="?minTouchTargetSize"
                android:layout_height="?minTouchTargetSize"
                android:minWidth="?minTouchTargetSize"
                android:minHeight="?minTouchTargetSize"
                app:icon="@drawable/ic_remove_filled_24dp" />

            <!-- TODO: Try to uncomment this back in and comment out Slider below -->
<!--            <Space-->
<!--                android:layout_width="0dp"-->
<!--                android:layout_height="0dp"-->
<!--                android:layout_weight="1" />-->

            <com.google.android.material.slider.Slider
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:layout_gravity="center"
                android:layout_marginHorizontal="8dp"
                android:stepSize="0.1"
                android:valueFrom="4.5"
                android:valueTo="9"
                app:labelBehavior="gone"
                app:tickVisible="false" />

            <com.google.android.material.button.MaterialButton
                android:layout_width="?minTouchTargetSize"
                android:layout_height="?minTouchTargetSize"
                android:minWidth="?minTouchTargetSize"
                android:minHeight="?minTouchTargetSize"
                app:icon="@drawable/ic_add_filled_24dp" />

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="-4dp"
            android:layout_marginEnd="-4dp"
            android:orientation="horizontal"
            android:paddingHorizontal="?minTouchTargetSize">

            <TextView
                android:layout_width="?minTouchTargetSize"
                android:layout_height="wrap_content"
                android:gravity="center"
                tools:text="0" />

            <Space
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_weight="1" />

            <TextView
                android:layout_width="?minTouchTargetSize"
                android:layout_height="wrap_content"
                android:gravity="center"
                tools:text="100" />

        </LinearLayout>

    </LinearLayout>

</LinearLayout>
```

Both `AlertDialog.Builder(context).setView(viewResId).build()` and `MaterialAlertDialogBuilder(context).setView(viewResId).build()` experienced the same result.

**Android API version:** 25, 27, 30, 31, 32

**Material Library version:** 1.6.1

**Device:** Samsung Galaxy Tab A7 Lite, Samsung Galaxy Tab A 8.0" (2019), Skydroid H16, Skydroid H12

**Comment by imandaliya** [comment] 2022-10-04 07:17
@SupasinTatiyanupanwong added image are not showing, may be link broken, upload new images

**Comment by SupasinTatiyanupanwong** [comment] 2022-10-05 03:23
@imandaliya  Screenshots reupload

**Comment by hunterstich** [comment] 2022-10-20 14:44
Hi @SupasinTatiyanupanwong,

I can't get this to reproduce in our catalog. Using MaterialAlertDialogBuilder and they layout you provided, both the Space and the Slider take up the same width. See below.


| Slider      | Space |
| ----------- | ----------- |
| ![slider](https://user-images.githubusercontent.com/7459254/196980886-a213b97f-a6dc-42d5-809a-b30b0b045fc9.png)      | ![space](https://user-images.githubusercontent.com/7459254/196980842-00effb8c-c94c-4fcd-92e8-5e3eeb564405.png)       |

Any chance you'd be able to upload a sample that reproduces the issue?

**Comment by drchen** [comment] 2022-11-28 21:11
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-11-28 21:11 UTC
Labels: bug, Widget: Slider
