### ISSUE TITLE
[EditText] ResourceNotFound Exception design_password_eye.xml

### ISSUE THREAD

**Issue by fkirc** [material-components/material-components-android#670] opened 2019-10-11 06:34 UTC
This is a very nasty bug since it only happens on some devices in the field.
I cannot reproduce this on my local development devices.
Note that our app is deployed as "Android App Bundle" from the Play Store.

I flagged this as a material library bug because the missing resource is part of the material library.

We use the following versions:
`com.google.android.material:material:1.0.0`
`androidx.appcompat:appcompat:1.1.0`

There are a few similar stackoverflow and github reports:

https://stackoverflow.com/questions/42789175/textinputlayout-crashing-in-android-lollipop-and-above

https://github.com/firebase/FirebaseUI-Android/issues/1600

Here is a stacktrace from the Firebase Crashlytics console:
> Caused by android.content.res.Resources$NotFoundException
> File res/drawable-v21/design_password_eye.xml from drawable resource ID #0x7f07011d
> android.content.res.ResourcesImpl.loadDrawableForCookie (ResourcesImpl.java:837)
> android.content.res.ResourcesImpl.loadDrawable (ResourcesImpl.java:659)
> android.content.res.Resources.getDrawableForDensity (Resources.java:891)
> android.content.res.Resources.getDrawable (Resources.java:833)
> android.content.Context.getDrawable (Context.java:605)
> androidx.core.content.ContextCompat.c (ContextCompat.java:2)
> androidx.appcompat.widget.AppCompatDrawableManager.getDrawable (AppCompatDrawableManager.java:11)
> androidx.appcompat.widget.AppCompatDrawableManager.c (AppCompatDrawableManager.java:2)
> androidx.appcompat.content.res.AppCompatResources.b (AppCompatResources.java:4)
> androidx.appcompat.widget.TintTypedArray.b (TintTypedArray.java:19)
> com.google.android.material.textfield.TextInputLayout.<init> (TextInputLayout.java:3)
> com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes (ThemeEnforcement.java:2)
> com.google.android.material.textfield.TextInputLayout.<init> (TextInputLayout.java:2)
> java.lang.reflect.Constructor.newInstance0 (Constructor.java)
> java.lang.reflect.Constructor.newInstance (Constructor.java:334)
> android.view.LayoutInflater.createView (LayoutInflater.java:647)
> android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:790)
> android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:730)
> android.view.LayoutInflater.rInflate (LayoutInflater.java:863)
> android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:824)
> android.view.LayoutInflater.rInflate (LayoutInflater.java:866)
> android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:824)
> android.view.LayoutInflater.rInflate (LayoutInflater.java:866)
> android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:824)
> android.view.LayoutInflater.rInflate (LayoutInflater.java:866)
> android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:824)
> android.view.LayoutInflater.rInflate (LayoutInflater.java:866)
> android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:824)
> android.view.LayoutInflater.inflate (LayoutInflater.java:515)
> android.view.LayoutInflater.inflate (LayoutInflater.java:423)
> androidx.databinding.DataBindingUtil.inflate (DataBindingUtil.java:1)

**Comment by ldjcmu** [comment] 2019-10-11 14:33
Closing this as we think it's fixed at head. That commit is not in any released version yet, but will be in 1.1.0-beta02 and alpha 1.2.0.

**Closed by ldjcmu** 2019-10-11 14:33 UTC
Labels: bug

**Comment by fkirc** [comment] 2019-10-11 14:35
Can you provide a link to this commit?
How can we ensure that this kind of crashes does not occur again?

**Comment by ldjcmu** [comment] 2019-10-11 14:39
7dc56dfcdd38ee11ca39aabd6c32428fa02c3bc4. The issue is likely dual caused by minifyEnabled and shrinkResources. You may be able to update your configs for those processes in your build to prevent the issue right now (https://developer.android.com/studio/build/shrink-code) .

**Comment by fkirc** [comment] 2019-10-11 14:45
Well, I am using all of App Bundle, minifyEnabled and shrinkResources.

However, it is hard to fix this with a meaningful ProGuard rule as long as I am not able to reproduce this issue locally.

**Comment by fkirc** [comment] 2019-10-11 14:54
As a sidenote:
According to the Firebase crash reports, this happened on Android 8.0.0 (Samsung devices like Galaxy S7).
