### ISSUE TITLE
The style on this component requires your app theme to be Theme.AppCompat (or a descendant).

### ISSUE THREAD

**Issue by Generic-droid** [material-components/material-components-android#3135] opened 2022-12-09 00:55 UTC
The following classes could not be instantiated:
- com.google.android.material.navigation.NavigationView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE. 

java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:212)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:147)
	at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
	at com.google.android.material.internal.ScrimInsetsFrameLayout.<init>(ScrimInsetsFrameLayout.java:64)
	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:145)
	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:141)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

It's not the only one View, where I see this bug. It's there:

The following classes could not be instantiated:
- com.google.android.material.card.MaterialCardView (Open Class, Show Exception, Clear Cache)
- com.google.android.material.divider.MaterialDivider (Open Class, Show Exception, Clear Cache)
Exception Details java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

And there:
The following classes could not be instantiated:
- com.google.android.material.button.MaterialButton (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

![image](https://user-images.githubusercontent.com/58906194/206596284-a1a01c31-409a-4cdd-a110-5bc70caf4361.png)

Source code:
AndroidManifest.xml
android:theme="@style/Theme.MyApp"

themes.xml
<style name="Theme.MyApp" parent="Theme.Material3.DayNight.NoActionBar">

themes.xml (night)
<style name="Theme.MyApp" parent="Theme.Material3.DayNight.NoActionBar">

Android API version: 21 - 33 Android Studio Dolphin | 2021.3.1 Patch 1

Material Library version: 1.8.0-alpha03

**Comment by Generic-droid** [comment] 2022-12-09 03:23
I solve this issue by changing Theme for Preview to my actual theme 
![image](https://user-images.githubusercontent.com/58906194/206616816-277ae8ce-c38a-4df4-89b3-f7d65f1e8a34.png)

but new issue accuared:

The following classes could not be instantiated:
- com.google.android.material.card.MaterialCardView (Open Class, Show Exception, Clear Cache)
- com.google.android.material.appbar.AppBarLayout (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  

Exception Details 
java.lang.IllegalArgumentException: Motion easing theme attribute must be an @interpolator resource for ?attr/motionEasing*Interpolator attributes or a string for ?attr/motionEasing* attributes.   at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:74)   at com.google.android.material.card.MaterialCardViewHelper.<init>(MaterialCardViewHelper.java:161)   at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:174)   at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:160)   at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)   at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)   at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)   at java.lang.reflect.Constructor.newInstance(Constructor.java:490)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)   at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:204)   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1165)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1123)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)   at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:204)   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1165)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1123)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)   at android.view.LayoutInflater.inflate(LayoutInflater.java:686)   at android.view.LayoutInflater.inflate(LayoutInflater.java:505)

I reduce material version to 1.7.0 that's work perfect.

**Comment by hunterstich** [comment] 2022-12-09 16:26
Hey @Generic-droid,

Thanks for filing an issue. 

I just want to confirm that this is only happening in Android Studio preview and you're not seeing any crash or anything when you actually run the app?

If that's the case, I can reach out to the Android Studio Preview team and see what might be causing the issue.

**Comment by shwoghk14** [comment] 2022-12-11 04:58
> Hey @Generic-droid,
> 
> Thanks for filing an issue.
> 
> I just want to confirm that this is only happening in Android Studio preview and you're not seeing any crash or anything when you actually run the app?
> 
> If that's the case, I can reach out to the Android Studio Preview team and see what might be causing the issue.

I also have same issue #3136. My case is no crash when run the app but only wrong in android studio preview.

**Comment by hunterstich** [comment] 2022-12-12 11:42
Closing as a duplicate of https://github.com/material-components/material-components-android/issues/3136

**Closed by hunterstich** 2022-12-12 11:42 UTC
Labels: bug
