### ISSUE TITLE
[MaterialButton] iconGravity textStart not working on initial view binding

### ISSUE THREAD

**Issue by luke-c** [material-components/material-components-android#2153] opened 2021-03-25 17:10 UTC
**Description:** 
Updated from Material 1.2.1 to 1.3.0 and some of our MaterialButton's which uses iconGravity textStart have stopped working correctly. 

This is how the layout looks on 1.3.0. The icon is no longer aligned to the start of the text.
![Screenshot 2021-03-25 at 17 07 27](https://user-images.githubusercontent.com/567702/112513779-959d8b80-8d8c-11eb-8a0a-6772c4a85eab.png)

Strangely, if I navigate to another screen, then go back to the screen with the above layout the layout looks correct again.

**Expected behavior:**
This is how our layout behaves on 1.2.1
![Screenshot 2021-03-25 at 17 06 21](https://user-images.githubusercontent.com/567702/112513619-6dae2800-8d8c-11eb-85e2-2b0552771769.png) 

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

Layout file:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="0dp"
    android:layout_height="48sp"
    android:background="@drawable/border_bottom"
    android:orientation="horizontal">

    <com.google.android.material.button.MaterialButton
        android:id="@+id/filterButton"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:visibility="gone"
        app:icon="@drawable/ic_filter"
        app:iconGravity="textStart"
        tools:text="Filter" />

    <View
        android:id="@+id/divider"
        android:layout_width="1dp"
        android:layout_height="match_parent"
        android:layout_marginTop="12dp"
        android:layout_marginBottom="12dp"
        android:background="@color/border" />

    <com.google.android.material.button.MaterialButton
        android:id="@+id/sortButton"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:visibility="gone"
        app:icon="@drawable/ic_sort"
        app:iconGravity="textStart"
        tools:text="Sort by" />
</LinearLayout>
```

View Binding code in Fragment:
```
    sortButton.visibility = View.VISIBLE
    sortButton.isEnabled = true
    sortButton.text = sortButtonText
    filterButton.visibility = View.VISIBLE
    filterButton.isEnabled = true
    filterButton.text = filterButtonText
```

**Android API version:** 30

**Material Library version:** 1.3.0, 1.4.0-alpha-01

**Device:** Android Emulator

**Comment by sbelloz** [comment] 2021-05-19 16:00
Same for me, but I can't downgrade version because I'm using features of `1.3.0`. 
Extending `MaterialButton` and reset `iconGravity` into `onMeasure` fix the problem  👍

**Comment by drchen** [comment] 2021-06-25 21:30
I can't reproduce the issue on my end. 

Can you try to set the outer LinearLayout's width to wrap_content instead?
I'm suspecting it has to do with changing outer layout's width programmatically.

If this does not solve the issue, can you provide a minimum reproducible example app so we can debug on our end? thanks!

**Comment by drchen** [comment] 2021-10-04 19:47
I'll close the issue due to no further info available. Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2021-10-04 19:47 UTC
