### ISSUE TITLE
[AppBarLayout] Status bar background color moving around when using fitsSystemWindows=true

### ISSUE THREAD

**Issue by FlorianWalther** [material-components/material-components-android#947] opened 2020-01-25 10:17 UTC
**Description:** When using `android:fitsSystemWindows="true"` on the `AppBarLayout` in a collapsing toolbar setup, the status bar background color moves down for a moment when scrolling up fast.

Recording of the problem (gif): https://imgur.com/DMzi68O
Frame where it happens: https://imgur.com/sSfYtW9

**Expected behavior:** The status bar background color should stay in the same places at all times.

```  
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:fitsSystemWindows="true"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="280dp"
        android:fitsSystemWindows="true"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:contentScrim="@color/colorPrimary"
            app:layout_scrollFlags="scroll|enterAlways|enterAlwaysCollapsed|snap"
            app:toolbarId="@id/toolbar">

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="true"
                android:scaleType="centerCrop"
                app:layout_collapseMode="parallax"
                android:src="@drawable/image" />

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>

    </com.google.android.material.appbar.AppBarLayout>

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="16dp"
            android:text="@string/dummy_text" />

    </androidx.core.widget.NestedScrollView>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
``` 

**Android API version:** 21+

**Material Library version:** 1.0.0

**Device:** Nexus 5x Emulator and Samsung Galaxy Note 8 physical device

**Comment by caballo111** [comment] 2020-09-25 03:25
Hello, inside the CollapsingToolbarLayout try setting

`app:statusBarScrim="@color/colorPrimary"`

**Comment by drchen** [comment] 2021-09-30 18:36
Hi, is this still reproducible?

**Comment by drchen** [comment] 2021-10-15 13:25
I'll close the issue due to no further info available. I'll view caballo111's answer as the right one. : )

**Closed by drchen** 2021-10-15 13:25 UTC
Labels: bug, Need more info
