### ISSUE TITLE
[BottomNavigationView] No layout pass after keyboard shown with BottomNavigationView and ConstraintLayout 2.0.0-beta02

### ISSUE THREAD

**Issue by lwasyl** [material-components/material-components-android#598] opened 2019-09-13 17:44 UTC
**Description:** When BottomNavigationView is used with ConstraintLayout 2.0.0-beta02, there is some weird behavior after showing the keyboard with `adjustResize` input mode. Basically seems like layout passes don't happen when keyboard is hidden, and first layout only happens on some other layout-triggering event. This results in views being in weird places. Here's gif showing the issue. Notice how the bottom navigation stays above the place it was at the beginning even when touching items. Once some item is clicked layout is triggered, and the bottom navigation snaps into place.

![bnv_bug](https://user-images.githubusercontent.com/3951580/64882737-045d3d00-d65e-11e9-80a3-49796040f438.gif)

**Expected behavior:** When keyboard is hidden, all views are placed where they belong in the layout.

**Source code:** https://github.com/lwasyl/bottom_navigation_issue repository reproduces the issue. Please only look at LoginActivity class - I started with the default template and didn't delete all other irrelevant classes. Additionally I believe this behavior has other implications, like lists not refreshing until scrolled and newly pushed fragments not rendering. I experience these on my daily project which I can't share, and didn't have time to reproduce these issues in the trpto project yet.

**Android API version:** 24 and 28 (probably irrelevant)

**Material Library version:** 1.1.0-alpha10, constraint layout 2.0.0-beta2. With constraint layout 1 the issue doesn't reproduce

**Device:** Google play emulator API 28, other devices too

I consider this a major bug since it breaks essentially every screen on which keyboard will show. I've used `adjustNothing` soft input mode before, but it's not appropriate on most of the screens.

**Comment by lwasyl** [comment] 2019-09-16 10:38
I opened the relevant issue on the ConstraintLayout side as well: https://issuetracker.google.com/issues/141023486

**Comment by CnuFederer** [comment] 2019-09-19 12:36
After updating to latest material version, I do have an issue in BottomNavigation.
Earlier I've used 
`          ..  android:windowSoftInputMode="adjustPan">
`
Due to this, I have faced abnormal bottom nav behavior, like, even though I've selected another icon, the initial icon was held up as if it was selected.
I've changed the setting to
`          ..  android:windowSoftInputMode="adjustNothing">
`
Now everything works fine!!

**Comment by lwasyl** [comment] 2019-10-02 09:15
Is there any update on this? I'm really lost as to how would I even work around this. @wcshi You did change something about window insets after which _I think_ the issue appeared, could this be related somehow?

**Comment by wcshi** [comment] 2019-10-02 10:45
Is this bug reproducible if you use 1.10-alpha08, before the window insets changes?

**Comment by lwasyl** [comment] 2019-10-02 11:45
It is :\ Sorry, could've checked this before. Could there be any other point that changed something which could be a trigger here?

**Comment by xxfast** [comment] 2020-08-05 05:43
reproducible in 1.3.0-alpha01

**Comment by wcshi** [comment] 2020-08-05 17:03
@xxfast could you please elaborate? How are you able to reproduce this bug? It would be most helpful if you could provide a sample app, thanks!

**Comment by drchen** [comment] 2022-02-07 19:28
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-02-07 19:28 UTC
Labels: bug
