### ISSUE TITLE
[TextInputLayout] API 21 endIconTint/endIconDrawable color is broken

### ISSUE THREAD

**Issue by melounovycukr** [material-components/material-components-android#985] opened 2020-02-06 07:21 UTC
**Description:** 
**endIconTint** or **endIconDrawable** are not working on Android API 21.
Drawable color is always overriden by red (unknown) color.

**Expected behavior:** Should be respecting drawable color or specified tint.

**Source code:** 
` app:endIconDrawable="@drawable/ic_icon"
    app:endIconTint="@color/yellow"`

**Android API version:** API 21

**Material Library version:** 1.1.0, 1.2.0-alpha04

**Device:** Any Android with API 21

**Comment by leticiarossi** [comment] 2020-02-06 20:50
can you provide a sample app? I'm not able to reproduce the issue

**Comment by tbsandee** [comment] 2020-02-28 00:15
I see something related on sdk 21 device (emulator), my navigation button is always red. Works fine on other sdk versions.

**Comment by gabrielemariotti** [comment] 2020-08-27 06:09
I am not able to reproduce the issue on API21 with `1.2.0` and `1.3.0-alpha02`

```
<com.google.android.material.textfield.TextInputLayout
      style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
      app:endIconDrawable="@drawable/ic_accelerator_24px"
      app:endIconTint="@color/blue_700"

```
<img width="314" alt="Schermata 2020-08-27 alle 08 06 20" src="https://user-images.githubusercontent.com/2583078/91398338-33070000-e83c-11ea-9f64-4c6d87e82b01.png">

**Comment by drchen** [comment] 2021-10-06 16:44
I'll close the issue as non-reproducible. : )

Feel free to reopen it if this is still a problem.

**Closed by drchen** 2021-10-06 16:44 UTC
Labels: bug
