### ISSUE TITLE
[Tablayout] Serious bug, viewpager2, tablayout, fragment

### ISSUE THREAD

**Issue by BraveHL** [material-components/material-components-android#3313] opened 2023-03-22 02:26 UTC
**Description:** Full description of issue here

Serious bug, I use viewpager2, tablayout, fragment, do sliding page, if only slide the page to switch fragment, no problem, if you click tab to switch, there will be a blank page, but this blank page is not the kind of fragment code error, I click on the current page at this time, the current fragment page is displayed, this should be a bug, at this time, I put the smoothScroll of TabLayoutMediator=false, then this problem will not occur, but at this time, the sliding effect is terrible and does not meet my needs, please fix this problem

When clicking the tab switch, the white screen, sometimes the fourth will be triggered, sometimes you need to click more than 10, note that it is clicked sequentially, not randomly

After loading the page for the first time, clicking the second tab will cause the FragmentStateAdapter's createFragment method to execute twice, position 1 and 2, and then click the other tabs in turn, and createFragment will become executed again, followed by 3, 4... It seems to be related to this exception

        val count = 30
        mViewBinding.tlChannels.tabMode = TabLayout.MODE_SCROLLABLE

        mViewBinding.vp.adapter = object : FragmentStateAdapter(this) {
            override fun createFragment(position: Int): Fragment {
                val fragment = ExampleFragment()
                fragment.arguments = Bundle().apply {
                    // Our object is just an integer :-P
                    putString("Example", "Fragment $position")
                }
                return fragment
            }

            override fun getItemCount(): Int {
                return count
            }
        }
        
        TabLayoutMediator(
            mViewBinding.tlChannels, mViewBinding.vp, true, true
        ) { tab, position -> 
            tab.text = "T" + (position + 1)
        }.attach()

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** The code snippet which is causing this issue

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** Android API version here

targetSdk 33

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

1.8.0 and 1.9.0-beta01

**Device:** Device on which the bug was encountered here

device Sdk 32

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

I used 1.8.0 and 1.9.0-beta01 and both have this issue

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by imhappi** [comment] 2023-03-22 20:47
Hi! I'm having some trouble understanding your issue; to clarify, you have a tablayout in a viewpager and when you click on a tab, it's showing a blank screen instead of the correct fragment?

I tried to reproduce your issue with something similar to your code sample, but I wasn't able to reproduce. 

Here is what I tried:
```
  class TestAdapter extends FragmentStateAdapter {

    public TestAdapter(@NonNull FragmentManager fragmentManager,
        @NonNull Lifecycle lifecycle) {
      super(fragmentManager, lifecycle);
    }

    @NonNull
    @Override
    public Fragment createFragment(int position) {
      return new Test();
    }

    @Override
    public int getItemCount() {
      return 2;
    }
  }

    TestAdapter adapter = new TestAdapter(getChildFragmentManager(), getLifecycle());
    mViewPager.setAdapter(adapter);

    new TabLayoutMediator(tabLayout, mViewPager,
        (tab, position) -> {
          tab.setText("test" + position);
        }).attach();


```

Can you provide some more information on repro steps, or a share a small sample app that you are able to repro this on?

**Comment by BraveHL** [comment] 2023-03-23 02:34
> Hi! I'm having some trouble understanding your issue; to clarify, you have a tablayout in a viewpager and when you click on a tab, it's showing a blank screen instead of the correct fragment?
> 
> I tried to reproduce your issue with something similar to your code sample, but I wasn't able to reproduce.
> 
> Here is what I tried:
> 
> ```
>   class TestAdapter extends FragmentStateAdapter {
> 
>     public TestAdapter(@NonNull FragmentManager fragmentManager,
>         @NonNull Lifecycle lifecycle) {
>       super(fragmentManager, lifecycle);
>     }
> 
>     @NonNull
>     @Override
>     public Fragment createFragment(int position) {
>       return new Test();
>     }
> 
>     @Override
>     public int getItemCount() {
>       return 2;
>     }
>   }
> 
>     TestAdapter adapter = new TestAdapter(getChildFragmentManager(), getLifecycle());
>     mViewPager.setAdapter(adapter);
> 
>     new TabLayoutMediator(tabLayout, mViewPager,
>         (tab, position) -> {
>           tab.setText("test" + position);
>         }).attach();
> ```
> 
> Can you provide some more information on repro steps, or a share a small sample app that you are able to repro this on?

You need to write the value of getItemCount() larger, such as the same as I wrote, write 30, then click the second tab, the third, the fourth, and so on, click to the last, and a certain start in the middle will definitely happen, my side is doing a random number of tabs on the page, so it will take a lot of tabs to test, in addition, what is your fragment, preferably a list

**Comment by imhappi** [comment] 2023-03-24 00:14
What do you mean scroll backwards quickly? Can you attach videos?

And why do you have to detach/reattach the mediator when you are updating/switching the tab...?

This is the documentation for detach:
```
  /**
   * Unlink the TabLayout and the ViewPager. To be called on a stale TabLayoutMediator if a new one
   * is instantiated, to prevent holding on to a view that should be garbage collected. Also to be
   * called before {@link #attach()} when a ViewPager2's adapter is changed.
   */
```
You should only have to detach it in the scenarios listed above.

The scrolling you are seeing is probably caused by this line in the `attach` method:
`tabLayout.setScrollPosition(viewPager.getCurrentItem(), 0f, true);`
If you are switching your viewpager and you are seeing some unexpected scrolling/an unexpected selected tab, make sure that the viewpager has the correct current item set.

Closing this ticket as I don't believe this is a bug in our library

**Closed by imhappi** 2023-03-24 00:14 UTC
Labels: bug, Widget: Tab

**Comment by yrickwong** [comment] 2023-12-10 01:18
@BraveMomo how do you solve the blank problem?

**Comment by sulemanafzal** [comment] 2024-07-24 16:47
> **Description:** Full description of issue here
> 
> Serious bug, I use viewpager2, tablayout, fragment, do sliding page, if only slide the page to switch fragment, no problem, if you click tab to switch, there will be a blank page, but this blank page is not the kind of fragment code error, I click on the current page at this time, the current fragment page is displayed, this should be a bug, at this time, I put the smoothScroll of TabLayoutMediator=false, then this problem will not occur, but at this time, the sliding effect is terrible and does not meet my needs, please fix this problem
> 
> When clicking the tab switch, the white screen, sometimes the fourth will be triggered, sometimes you need to click more than 10, note that it is clicked sequentially, not randomly
> 
> After loading the page for the first time, clicking the second tab will cause the FragmentStateAdapter's createFragment method to execute twice, position 1 and 2, and then click the other tabs in turn, and createFragment will become executed again, followed by 3, 4... It seems to be related to this exception
> 
> ```
>     val count = 30
>     mViewBinding.tlChannels.tabMode = TabLayout.MODE_SCROLLABLE
> 
>     mViewBinding.vp.adapter = object : FragmentStateAdapter(this) {
>         override fun createFragment(position: Int): Fragment {
>             val fragment = ExampleFragment()
>             fragment.arguments = Bundle().apply {
>                 // Our object is just an integer :-P
>                 putString("Example", "Fragment $position")
>             }
>             return fragment
>         }
> 
>         override fun getItemCount(): Int {
>             return count
>         }
>     }
>     
>     TabLayoutMediator(
>         mViewBinding.tlChannels, mViewBinding.vp, true, true
>     ) { tab, position -> 
>         tab.text = "T" + (position + 1)
>     }.attach()
> ```
> 
> **Expected behavior:** Screenshots and/or description of expected behavior
> 
> **Source code:** The code snippet which is causing this issue
> 
> **Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.
> 
> **Android API version:** Android API version here
> 
> targetSdk 33
> 
> **Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
> 
> 1.8.0 and 1.9.0-beta01
> 
> **Device:** Device on which the bug was encountered here
> 
> device Sdk 32
> 
> To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.
> 
> I used 1.8.0 and 1.9.0-beta01 and both have this issue
> 
> We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

Hi Dear If you use Simple ViewPager Its working fine
