### ISSUE TITLE
[Button] Visual feedback is poorly visible on API 33

### ISSUE THREAD

**Issue by pubiqq** [material-components/material-components-android#3606] opened 2023-09-25 18:44 UTC
https://github.com/material-components/material-components-android/assets/82187521/38b2b3c9-964e-4672-adfc-6970a4478566

**Material Library version:** 1.11.0-alpha03

**Device:** Pixel 4a (5G)
**Android API version:** 13 (Build TQ3A.230901.001)

**Comment by afohrman** [comment] 2023-09-27 19:35
Hi @pubiqq, thanks for filing this. I tried reproducing this in the Catalog and 
[the ripple appears to be working well](https://github.com/material-components/material-components-android/assets/13263374/fcf17bd5-e163-44e6-b0e9-421929df5491) on my API 33 Pixel 6 Pro emulator. 
My library version does include a couple of extra commits since 1.11.0-alpha03, but nothing that seems related to button or ripples. Are there any other steps necessary to reproduce this, other than just opening the demo and pressing the buttons?

**Comment by patzly** [comment] 2023-09-27 23:34
@afohrman This is an issue that started it's appearance with the June Pixel feature drop and affects all Android 13 Pixel users because the Pixel team closed the related issues as Won't fix. After I joined Android 14 beta at Beta4 the issue disappeard.
The related issues: [284998114](https://issuetracker.google.com/issues/284998114), [286978709](https://issuetracker.google.com/issues/286978709), [287880143](https://issuetracker.google.com/issues/287880143)

> 1. Specify ?attr/selectableItemBackground or RippleDrawable (ex. #3F000000) as RippleEffect to a target View
> 2. Tap the View that implemented RippleEffect
> 3. RippleEffect-color is paler than displayed on Android 13. It looks like happen if the color alpha of RippleEffect is lower than 50%.

> Status: Won't Fix (Obsolete)
Thank you for reporting this issue. We were able to reproduce the issue on the public Android U Beta3.1 build. However, the issue is not reproducible on our internal development build (which is ahead of the beta release). Please test it on a future release and let us know if you are still having issues.

So this is not related to MDC, a Pixel commit for Android 13 seems to have changed the way ripples are rendered system-wide and an Android 14 commit seems to have changed it back, but it's really not good that all Android 13 Pixels are still affected and the Pixel team doesn't care.

**Comment by afohrman** [comment] 2023-09-29 18:13
@patzly Thanks for the background. I'm going to close this issue since there's nothing we can do within the MDC library to fix this system-wide Android 13 framework issue. @pubiqq please direct info about this bug to the existing issues ([284998114](https://issuetracker.google.com/issues/284998114), [286978709](https://issuetracker.google.com/issues/286978709), [287880143](https://issuetracker.google.com/issues/287880143)).

**Closed** 2023-09-29 18:14 UTC
Labels: bug, Widget: Button
