### ISSUE TITLE
[Tabs] Problem with the animation of tab switching with ViewPager or ViewPager2

### ISSUE THREAD

**Issue by fankes** [material-components/material-components-android#3383] opened 2023-05-07 21:06 UTC
**Description:**

Problem with the animation of tab switching with ViewPager or ViewPager2

**Expected behavior:**

When TabLayout is bound to ViewPager or ViewPager2, the transition animation has a bug that reaches the end instantaneously.

**!!!Notice!!!** This bug was not found in `com.google.android.material:material:1.5.0` and is a new bug after `1.8.0`

I've found out this can't be a ViewPager or ViewPager2's bug, because I fallback to the dependency version `com.google.android.material:material:1.5.0` would fixes it.

Here's what happens when the bug occurs:

https://user-images.githubusercontent.com/37344460/236702423-99987f77-0793-4d2d-a39d-ec8f6f840828.mov

Here's is the expected behavior:

https://user-images.githubusercontent.com/37344460/236702476-8d72dcad-6062-4b79-ade1-78cc7052c164.mov

**Source code:**

In the ViewPager's OnPageChangeCallback:

```kotlin
override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) {
    val updateText = scrollState != ViewPager.SCROLL_STATE_SETTLING || previousScrollState == ViewPager.SCROLL_STATE_DRAGGING
    val updateIndicator = !(scrollState == ViewPager.SCROLL_STATE_SETTLING && previousScrollState == ViewPager.SCROLL_STATE_IDLE)
    // bound the tab layout here.
    tabLayout.setScrollPosition(position, positionOffset, updateText, updateIndicator)
}
```

**Android API version:**

Android 13 API 33

**Material Library version:**

`com.google.android.material:material:1.10.0-alpha02`

already tests `1.9.0` and `1.8.0`

**Comment by imhappi** [comment] 2023-05-08 07:31
Are you calling `tabLayout.setupWithViewPager(pager)`? You should not need to call `setScrollPosition` if you are using a viewpager; see https://github.com/material-components/material-components-android/blob/master/docs/components/Tabs.md#using-tabs-with-viewpager on how to use the tablayout with the viewpager

Please feel free to re-open if this does not solve the issue

**Comment by fankes** [comment] 2023-05-08 16:31
No, `tabLayout.setupWithViewPager(pager)` can still reproduce this problem

**Comment by fankes** [comment] 2023-05-08 16:32
This problem can reproduce with `ViewPager`

**Comment by fankes** [comment] 2023-05-08 17:46
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/tabs/TabLayout.java#L1630

**Comment by fankes** [comment] 2023-05-08 17:57
> Please feel free to re-open if this does not solve the issue

I can't open the issue because the repo doesn't give me this permission.

But the custom `setScrollPosition` still public, it still allow the developer calling it to setup a custom ViewPager listener, manually set listeners did not update the internal variable `viewPagerScrollState`  [see here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/tabs/TabLayout.java#L1630)

Then [here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/tabs/TabLayout.java#L815) is where the animation problem occurs.
Some developers like to bind ViewPager to implement some custom functions by themselves instead of using `tabLayout.setupWithViewPager(pager)`.

I think this is necessary, it should be a bug.

**Comment by imhappi** [comment] 2023-05-08 18:35
Will re-open and investigate, but please use `setupWithViewPager` as a workaround

I don't believe that that line is where the animation problem is occurring, as that line controls scrolling. I believe that the animation issue is caused by there needing to be some necessary method calls that are called for you when using the viewpager, that are called for you in the callbacks set up by `setupWithViewPager`. ie.`updateViewPagerScrollState` in `onPageScrollStateChanged`.

**Comment by fankes** [comment] 2023-05-08 20:09
Yes, but this method `updateViewPagerScrollState` is package-private, which will cause trouble for developers who want to call `setScrollPosition` manually. I also said that this problem does not exist in previous versions.

The code where the problem occurs should be as described below.

As I mentioned above, the code in several places is indeed not an animation problem, but there is a method `scrollTo` that will cause this problem because of the wrong `viewPagerScrollState` detected.

```java
// We want to scroll if alwaysScroll is true, the viewpager is being dragged, or if we should
// scroll by the rules above.
if (toMove || viewPagerScrollState == SCROLL_STATE_DRAGGING || alwaysScroll) {
  scrollTo(position < 0 ? 0 : scrollXForPosition, 0);
}
```

**Comment by imhappi** [comment] 2023-05-12 18:29
Hi @fankes as I mentioned above, `scrollTo` is not related to the indicator animation and is not the cause of the issue.

The issue is actually occurring in `jumpToIndicatorPosition`, because the TabLayout's record of the ViewPager scroll state is not updated because as I mentioned in my previous comment, they are called for you in the callbacks set up by setupWithViewPager

I'm just curious, why can't you add your own onPageChange listeners to the viewpager if you'd like to add custom logic on viewpager state change? I'm happy to make `updateViewPagerScrollState` public, but I don't think it's necessary.

Going to close this, but please comment if there's a reason you can't call `setupWithViewPager` and add your own onPageChange listener if you need to implement custom logic in the callbacks

**Closed by imhappi** 2023-05-12 18:29 UTC
Labels: bug, Widget: Tab

**Comment by fankes** [comment] 2023-05-13 03:21
The `TabLayoutOnPageChangeListener` implements `ViewPager.OnPageChangeListener` but its internal `onPageScrollStateChanged` calls `tabLayout.updateViewPagerScrollState`, but this method `updateViewPagerScrollState` is package-private.

If I didn't want to use `setupWithViewPager`, I'd have to customize the onPageChange listener you said, which would cause the same problem as the video I provided above, which is still unresolved.

Can you understand what i mean?

**Comment by fankes** [comment] 2023-05-13 03:40
[Here](https://github.com/fankes/TabLayoutDemo) is a demo to reproduce this problem.

**Comment by imhappi** [comment] 2023-05-15 15:31
Yes, but why do you not want to use `setupWIthViewPager`, if you want to copy the callbacks anyways? You can always add onPageListeners to the viewpager if you want other custom logic

**Comment by fankes** [comment] 2023-05-15 17:27
I just want to manually create tabs instead of automatically binding to follow the viewpager and then manually bind to the viewpager

**Comment by imhappi** [comment] 2023-05-15 18:06
Why do you want to manually create new tabs and then re-implement the onPageListener implemented in TabLayout in the same way?

You can always get the tab with `tabLayout.getTabAt` to get the tabs after they are instantiated from the given viewpager adapter after the `setupWithViewPager` call. You can also still add more onPageListeners after calling `setupWithViewPager`.

As I said, I'm happy to make `updateViewPagerScrollState` public, but we'd rather encourage users to use `setupWithViewPager`, as not calling that method may result in parts of the tablayout not working properly (eg. as this issue).

**Comment by imhappi** [comment] 2023-05-15 18:39
"Intentional" is not the right word, but our code assumes that `setupWithViewPager` will be called if being linked with a viewpager (note that it's called for you automatically if the tablayout is a child of the viewpager)

If our library has any future changes that update the callbacks that are setup by calling `setupWithViewPager`, this may break your code again since your custom callbacks will not have those updates. So we encourage users to use `setupWithViewPager`.

I'm happy to make `updateViewPagerScrollState` public if you provide a use case on why you cannot call `setupWithViewPager`; you mentioned that it's because you want to manually create tabs. Is there a reason why you can't get the tab afterwards with `tabLayout.getTabAt`?

**Comment by fankes** [comment] 2023-05-15 18:57
I had submitted a [demo](https://github.com/fankes/TabLayoutDemo) above

**Comment by imhappi** [comment] 2023-05-15 19:21
The demo you linked does not show a use case of why you cannot call `setupWithViewPager`

**Comment by fankes** [comment] 2023-05-16 00:09
In any case, no matter what form of customization is used to call the public method, it still has bugs，you cannot deny that.

If you think everyone should call `setupWithViewPager`, then `setScrollPosition` should not be made public anymore.
