### ISSUE TITLE
[TabLayout] Setting a custom drawable with intrinsic height as the selected tab indicator will not appear on screen

### ISSUE THREAD

**Issue by steffanc** [material-components/material-components-android#2378] opened 2021-09-16 22:16 UTC
**Description:**
- Setting a custom drawable with an intrinsic height as the selected tab indicator for a `TabLayout` will cause it to be drawn with a height of 0 and not appear on screen

Repro:
- The following steps use a minimal custom TabLayout implementation that inherits from `com.google.android.material.tabs.TabLayout`
- In the `init` block of the custom TabLayout class, create a custom drawable for use as the selected tab indicator
- Set the intrinsic height of the drawable as advised in the documentation for the deprecated method, `TabLayout#setSelectedTabIndicatorHeight`
- Call `TabLayout#setSelectedTabIndicator` and pass the drawable
- Call `TabLayout#setSelectedTabIndicatorColor` to set a color
- The drawable does not appear on screen

When inspecting the `SlidingTabIndicator#draw` method, it can be seen that the indicator height is actually set to the bounds height (which is 0) and then skips setting it to the intrinsic height

Workaround:
- Call the deprecated method, `TabLayout#setSelectedTabIndicatorHeight`, in order to set the height on the drawable bounds

**Expected behavior:** The drawable's height should be the intrinsic height as advised by `TabLayout#setSelectedTabIndicatorHeight` documentation

**Source code:**
Problem:
```
init {
        val drawable = ShapeDrawable(RectShape())
        drawable.intrinsicHeight = 7
        setSelectedTabIndicator(drawable)
        setSelectedTabIndicatorColor(context.getColorCompat(android.R.color.holo_red_dark))
}
```

Workaround:
```
init {
        val drawable = ShapeDrawable(RectShape())
        drawable.intrinsicHeight = 7
        setSelectedTabIndicator(drawable)
        setSelectedTabIndicatorColor(context.getColorCompat(android.R.color.holo_red_dark))
        setSelectedTabIndicatorHeight(drawable.intrinsicHeight)
}
```

**Android API version:** Android 11 (API level 30)

**Material Library version:** 1.3.0 or higher

**Device:** Samsung Galaxy S10 SM-G973U1

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment] 2021-09-17 01:04
It's a duplicate of #2354

**Closed by drchen** 2021-09-17 01:04 UTC
Labels: bug
