### ISSUE TITLE
[AutoCompleteTextView] Exposed Dropdown Menu not showing items

### ISSUE THREAD

**Issue by filipedelimabrito** [material-components/material-components-android#2012] opened 2021-01-28 03:17 UTC
**Description:** 

[Exposed Dropdown Menu](https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md#implementing-an-exposed-dropdown-menu) doesn't show items after user selection and fragment transition.

Following is the basic xml declaration:

    <com.google.android.material.textfield.TextInputLayout
        ...
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
     
             <AutoCompleteTextView
                .... 
                android:id="@+id/dropdown"
                android:dropDownHeight="300dp"
                android:inputType="none" />
    </com.google.android.material.textfield.TextInputLayout>

And, the declared code on the fragment (inside `onViewCreated()`):

        val items = listOf("Material", "Design", "Components", "Android")
        val adapter = ArrayAdapter(requireContext(), R.layout.item_menu, items)
        dropdown.setAdapter(adapter)
        dropdown.setText(items[0], false)

As mentioned [here](https://material.io/components/menus/android#exposed-dropdown-menus), it was set on `AutoCompleteTextView's` _setText_ method  (_dropdown.setText("", false)_) the filter parameter as false. However, after navigating to a next fragment and coming back to it, only the pre-selected text is shown on the dropdown.

Fragments are changed using [navigation component](https://developer.android.com/guide/navigation) (v. `2.3.2`).

**Expected behavior:** Dropdown should show all items.

**Android API version:** `Android API 30`

**Material Library version:** `1.3.0-rc01`

**Device:** `Emulator - Pixel 4 XL`

**Comment by mschief148** [comment] 2021-02-26 06:11
I got the same problem, with setText("something", false) change the fragment and coming back only shows selected item on the list

**Comment by heriawanfx** [comment] 2021-03-28 06:13
You can implement this extention on onClickListener to make all list keep showing after it clicked.

`fun AutoCompleteTextView.showDropdown(adapter: ArrayAdapter<String>?) {
    if(!TextUtils.isEmpty(this.text.toString())){
        adapter?.filter?.filter(null)
    }
}`

**Comment by jishindev** [comment] 2021-05-28 05:18
Any update on this?

**Comment by AbdulazizRasulbek** [comment] 2021-06-07 14:50
The same problem

**Comment by gson2019** [comment] 2021-06-07 15:22
Same problem seen, any updates ?

**Comment by amg** [comment] 2021-06-16 04:40
same issue, in 1.4.0-rc01 as well

**Comment by amg** [comment] 2021-06-16 05:00
> You can implement this extention on onClickListener to make all list keep showing after it clicked.
> 
> ```
> fun AutoCompleteTextView.showDropdown(adapter: ArrayAdapter<String>?) {
>     if(!TextUtils.isEmpty(this.text.toString())){
>         adapter?.filter?.filter(null)
>     }
> }
> ```
> 
> And also add focusable="false" to AutoCompleteTextView in xml.

This does seem to work as a temp workaround 🤔 🙏

**Comment by jerryOkafor** [comment] 2021-06-25 03:05
Currently experiencing the same problem here, does any one have a fix for this?

**Comment by jerryOkafor** [comment] 2021-06-25 03:48
> Currently experiencing the same problem here, does any one have a fix for this?

Temp solution working for me is to move part of the code to onResume():

```
override fun onResume() {
        super.onResume()

        val arrayAdapter =
            ArrayAdapter(requireContext(), R.layout.menu_list_item, floorEntries)
        binding.tvFloor.setAdapter(null)
        binding.tvFloor.setAdapter(arrayAdapter)

        setSelectedFloor()
    }
```

**Comment by lencetanaskoska** [comment] 2021-08-11 11:55
Same problem on material version 1.4.0 had to implement custom array adapter with custom/no filter

**Comment by Volua** [comment] 2021-12-18 05:21
> You can implement this extention on onClickListener to make all list keep showing after it clicked.
> 
> ```
> fun AutoCompleteTextView.showDropdown(adapter: ArrayAdapter<String>?) {
>     if(!TextUtils.isEmpty(this.text.toString())){
>         adapter?.filter?.filter(null)
>     }
> }
> ```
> 
> And also add focusable="false" to AutoCompleteTextView in xml.

If it is in fragment you better put this extension in onResume, this way filters are canceled automatically.

**Comment by drchen** [comment] 2022-04-13 01:50
It's a duplicate of https://github.com/material-components/material-components-android/issues/1464. Unfortunately it's an Android framework issue and I'm trying to push for a workaround on the Material side or AppCompat.

**Closed by drchen** 2022-04-13 01:50 UTC
Labels: bug, Widget: TextField

**Comment by Leshachok** [comment] 2022-05-14 11:34
Faced the same problem.
Downgrading 'androidx.navigation:navigation-ui-ktx' library from 2.4.2 to version 2.3.5 helped me

**Comment by nadar71** [comment] 2022-09-06 14:06
Faced the same damn problem, here it solves putting all in onResume, as already written by someone else:
https://www.youtube.com/watch?v=741l_fPKL3Y

**Comment by GentritIbishi** [comment] 2022-09-07 21:16
> > Currently experiencing the same problem here, does any one have a fix for this?
> 
> Temp solution working for me is to move part of the code to onResume():
> 
> ```
> override fun onResume() {
>         super.onResume()
> 
>         val arrayAdapter =
>             ArrayAdapter(requireContext(), R.layout.menu_list_item, floorEntries)
>         binding.tvFloor.setAdapter(arrayAdapter)
> 
>         setSelectedFloor()
>     }
> ```

This works perfectly, thank you !

**Comment by behelit** [comment] 2022-12-01 06:21
This is still a problem at 2022.12.01 using material:1.7.0

**Comment by RasulOs** [comment] 2022-12-19 06:26
Same problem. The problem was solved by putting an ArrayAdapter in the onResume() method.

**Comment by Sweeneyliu114514** [comment] 2023-09-08 08:06
As of now (Sept 2023) this bug still exists in material 1.9

**Comment by EnriekNP** [comment] 2024-03-21 02:52
this issue still happening for me...

**Comment by bbang208** [comment] 2024-04-10 18:05
This issue still occurs in version 1.11.0.

**Comment by parawanderer** [comment] 2025-03-07 23:51
Still happening in material `1.12.0` 😞
