### ISSUE TITLE
[Color] Some attributes have been marked as private

### ISSUE THREAD

**Issue by therealsujitk** [material-components/material-components-android#2541] opened 2022-01-30 18:27 UTC
**Description:** 

On using certain attributes such as `colorPrimaryContainer` and `colorSecondartContainer`, I get the following warning in android studio.

> The resource @attr/colorPrimaryContainer is marked as private in com.google.android.material:material:1.6.0-alpha02

This warning however does not affect the built application.

**Expected behavior:**

These attributes are not supposed to be private.

**Source code:** 

This warning shows in resource files

```xml
android:color="?attr/colorPrimaryContainer"
```

As well as in code

```java
MaterialColors.getColor(context, R.attr.colorPrimaryContainer, 0);
```

**Android API version:** Android API 31

**Material Library version:** 1.6.0-alpha02

**Device:** Ubuntu 20.04, Running Android Studio Bumblebee 2021.1.1

**Comment by dsn5ft** [comment] 2022-01-31 14:56
Duplicate of https://github.com/material-components/material-components-android/issues/2538 and fixed by https://github.com/material-components/material-components-android/commit/0c8fc4144e28d570f4b1bc41e650b57e36165cd8.

**Closed by dsn5ft** 2022-01-31 14:56 UTC
Labels: bug
