### ISSUE TITLE
[Android] Android Studio complaints when using ThemeOverlay.MaterialComponents instead of ThemeOverlay.AppCompat

### ISSUE THREAD

**Issue by sudhirkhanger** [material-components/material-components-android#681] opened 2019-10-16 11:39 UTC
**Description:** I have added `Theme.MaterialComponents` as per the Getting started [guide](https://material.io/develop/android/docs/getting-started/).

I have also replaced `ThemeOverlay.AppCompat` with `ThemeOverlay.MaterialComponents` which has no mention in the getting started guide. When I create an Activity I get the following error.
![Screenshot_20191016_164335](https://user-images.githubusercontent.com/841656/66914728-118e9280-f035-11e9-84af-7a6ee2dfe281.png)
> Ignoring conflict for the value: AppTheme.AppBarOverlay wanted: "<style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />" but it already is: "<style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.MaterialComponents.Dark.ActionBar" />" in the file: styles.xml
> 
> Ignoring conflict for the value: AppTheme.PopupOverlay wanted: "<style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />" but it already is: "<style name="AppTheme.PopupOverlay" parent="ThemeOverlay.MaterialComponents.Light" />" in the file: styles.xml

**Expected behavior:** Screenshots and/or description of expected behavior
* I would expect that Android Studio should not show this warning.
* **Please add instruction to the the getting started guide regarding `ThemeOverlay.MaterialComponents`**

**How to reproduce:**
* Create a new project via Android Studio.
* Make changes as per the Getting started guide.
* Replace ThemeOverlay.AppCompat with ThemeOverlay.MaterialComponents as shown below.
* Create a new Basic Activity.
```
<style name="AppTheme.AppBarOverlay"parent="ThemeOverlay.MaterialComponents.Dark.ActionBar" />
<style name="AppTheme.PopupOverlay" parent="ThemeOverlay.MaterialComponents.Light" />
```
**Android API version:** 29
**Material Library version:** 1.0.0
**Device:** Android Studio (Fedora 30 KDE).

**Comment by DanKyungu** [comment] 2020-06-13 07:12
Use this
```
<style name="AppTheme.AppBarOverlay"parent="ThemeOverlay.MaterialComponents.Dark.ActionBar" />
<style name="AppTheme.PopupOverlay" parent="ThemeOverlay.MaterialComponents.Light" />
```
The problem is that you just have to replace **Dark** by **DarkNight**

**Comment by drchen** [comment] 2022-02-07 20:04
Is this still an issue?

**Comment by drchen** [comment] 2022-03-03 19:26
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-03 19:26 UTC
Labels: bug, Need more info
