### ISSUE TITLE
The subheader looks not the same when switching between LTR and RTL, Why? (DrawerLayout)

### ISSUE THREAD

**Issue by tahasami2500** [material-components/material-components-android#2975] opened 2022-09-17 07:32 UTC
There is padding beginning of the subheader in the LTR (English language)

![2](https://user-images.githubusercontent.com/24863605/190845774-09fe6ac7-b239-42ca-a54f-4fc1b488abd7.jpg)

But there is no padding beginning of the subheader in the RTL (Arabic language)

![1](https://user-images.githubusercontent.com/24863605/190845772-5d4a54f1-126f-41ec-be5f-7a565088a632.jpg)

How can I solve this problem?

**Comment by drchen** [comment] 2022-09-20 20:47
Let's close this as a duplicate of #2976 for better tracking. : )

**Closed by drchen** 2022-09-20 20:47 UTC
Labels: bug
