### ISSUE TITLE
[MaterialButtonToggleGroup] getCheckedButtonId() doesn't retrieve the first selection

### ISSUE THREAD

**Issue by DavidHewWing** [material-components/material-components-android#970] opened 2020-02-03 02:47 UTC
**Description:** 
When I call `materialToggleButtonGroup.checkButtonId` the first selection doesn't return the right id, instead -1, however every selection that is a different button after the initial works

May be similar to: 
https://github.com/material-components/material-components-android/issues/956

**Steps**
1. Create MaterialButtonToggleGroup and Add Buttons
2.  Add click listeners and to the buttons and log the `materialToggleButtonGroup.checkButtonId`
3. Click a button
4. Notice it returns: *-1*
5. Click on another button
6. Notice it returns the correct id

**Expected behavior:** 
`materialButtonToggleGroup.checkButtonid` should return the correct Id every time.

**Source code:** 
**Fragment.kt**
```
button.setOnClickListener {
    val checkedButtonId = roster_add_player_button_group.checkedButtonId
    Log.d("Position: ", "$checkedButtonId")
}
```
Layout.xml
```
        <com.google.android.material.button.MaterialButtonToggleGroup
            android:id="@+id/roster_add_player_button_group"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="32dp"
            android:layout_marginEnd="32dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.0"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/textView3"
            app:selectionRequired="true"
            app:singleSelection="true">

            <com.google.android.material.button.MaterialButton
                android:id="@+id/roster_add_player_handler_button"
                style="?attr/materialButtonOutlinedStyle"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:text="Handler" />

            <com.google.android.material.button.MaterialButton
                android:id="@+id/roster_add_player_cutter_button"
                style="?attr/materialButtonOutlinedStyle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Cutter" />

            <com.google.android.material.button.MaterialButton
                android:id="@+id/roster_add_player_hybrid_button"
                style="?attr/materialButtonOutlinedStyle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Hybrid" />

        </com.google.android.material.button.MaterialButtonToggleGroup>
```

**Android API version:**
API 26

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.2.0-alpha04 (Latest)

**Comment by ymarian** [comment] 2020-02-03 15:44
Does seem like a duplicate of
https://github.com/material-components/material-components-android/issues/956

**Closed by ymarian** 2020-02-03 15:44 UTC
Labels: bug
