### ISSUE TITLE
[BottomSheetBehavior] BottomSheetBehavior scrolls down after expanding. 

### ISSUE THREAD

**Issue by polyak01** [material-components/material-components-android#849] opened 2019-12-24 06:20 UTC
**Description:** I have a RecyclerView inside BottomSheet. Firstly it has a few items, but after user action, the app shows additional items. When items height is more than the height of the screen - it scrolls down to the end of the list. And a few upper elements are not visible until I half-close this bottom sheet view. 

**Expected behavior:** How can I expand the bottom sheet to full screen without any scrolling?  

**Android API version:** Android 10

**Material Library version:** (1.0.0 and 1.1.0-rc01)

**Device:** google pixel 2

**Comment by drchen** [comment] 2021-10-13 20:57
You can use addBottomSheetCallback() to listen to state changes and enable/disable your recyclerview's scrolling. : )

Since the issue is a bit old, I'll just close it. Feel free to reopen if you have more questions.

**Closed by drchen** 2021-10-13 20:57 UTC
Labels: bug
