### ISSUE TITLE
[BottomNavigator] Error when migrated to version 1.3.0

### ISSUE THREAD

**Issue by paulo-coutinho** [material-components/material-components-android#2064] opened 2021-02-12 00:49 UTC
Hi,

When i migrate from version 1.2.1 to version 1.3.0 i get this error:

```
2021-02-11 21:46:46.447 16352-16352/br.com.ubook.ubookapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.ubook.ubookapp, PID: 16352
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getPaddingBottom()' on a null object reference
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:108)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:89)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:85)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.getNewItem(BottomNavigationMenuView.java:634)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:563)
        at com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:67)
        at com.google.android.material.bottomnavigation.BottomNavigationView.inflateMenu(BottomNavigationView.java:349)
        at br.com.ubook.ubookapp.ui.fragment.MainFragment.createAll(MainFragment.kt:185)
        at br.com.ubook.ubookapp.ui.fragment.BaseFragment.onCreateView(BaseFragment.kt:127)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at br.com.ubook.ubookapp.ui.activity.BaseActivity.onStart(BaseActivity.kt:552)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7348)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3138)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

The line with error is:

```
navigationLeft.inflateMenu(R.menu.navigation_left_3)
```

And the content is:

```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:id="@+id/tab_home_left"
        android:icon="@drawable/ic_tab_home"
        android:title="@string/title_featured" />

    <item
        android:id="@+id/tab_my_products_left"
        android:icon="@drawable/ic_tab_my_products"
        android:title="@string/title_my_products" />

</menu>
```

I revert it to 1.2.1 to make it work for now.

**Comment by hunterstich** [comment] 2021-02-18 01:56
Hey Paulo,

Are you able to attach a small sample that reproduces this issue?

**Comment by paulo-coutinho** [comment] 2021-02-19 00:16
Hi,

Im publish a project demo here (but i cannot reproduce the error):
https://github.com/paulo-coutinho/bottom-nav-md-demo

This is the line with problem (labelGroup = null):
https://github.com/material-components/material-components-android/blob/d6ddf00dbfadcc742a46818df7a6b5e90f892682/lib/java/com/google/android/material/navigation/NavigationBarItemView.java#L107

And the problem is in this line (screenshot):
![image](https://user-images.githubusercontent.com/395096/108438194-87a89800-722d-11eb-8809-b18ce0df3d7c.png)

Thanks.

**Comment by hunterstich** [comment] 2021-02-22 16:01
So that sample repo doesn't reproduce this issue?

What is `labelGroup`? Is that a view of your own?

**Comment by paulo-coutinho** [comment] 2021-02-22 17:49
Hi,

My sample don't throw the same error.

But i put the line of error ^^.

The labelGroup is from your source code. The screenshot is about your source code when error happen. I see that you make a find in view for the element labelGroup and it is null in my app.

**Comment by jae-90** [comment] 2021-03-22 18:26
Hi, I am facing the same problem.

Was there a solution for this?

**Comment by paulo-coutinho** [comment] 2021-03-22 21:59
I didn't found one.

**Comment by paulo-coutinho** [comment] 2021-03-25 20:34
Our friend here found the problem.

We have created a new file "res/layout/design_bottom_navigation_item.xml" to replace the original and add our accessibility text.

But it has 3 years and our file don't have the ID field that is recently added ```android:id="@+id/labelGroup"``` causing the crash.

We only need add this ID on BaseLineLayout element and it was fixed.

Thanks.

**Comment by drchen** [comment] 2021-07-15 19:42
Thanks for the update. : )  Glad to hear it's been fixed!  Closing the issue...

**Closed by drchen** 2021-07-15 19:42 UTC
Labels: bug

**Comment by Prakhar-kuls** [comment] 2022-04-07 09:05
For me, it was duplicating files from two different versions, one from main and other from dependency. Solved it by forcing one of the version main application already was having.

configurations.all {
        resolutionStrategy { 
            force 'com.google.android.material:material:1.2.1'
        }
    }

**Comment by hemalHD** [comment] 2022-11-30 09:06
can someone provide proper solutation because i am also facing same issue?
![image](https://user-images.githubusercontent.com/42856848/204753718-b544ed5f-ee10-440f-8bb0-ac5905dfc86c.png)

**Comment by Prakhar-kuls** [comment] 2022-11-30 12:58
@hemalHD what is the version you are using for `com.google.android.material:material` in app' build:gradle and in any of module or dependency? 
Can you check in dependency graph if `1.2.1` is being used.

**Comment by vivek-meesho** [comment] 2024-04-15 16:27
This issue is still happening when upgrading from 1.2.1 to 1.3.0

This has been [raised](https://stackoverflow.com/questions/72619142/nullpointerexception-attempt-to-invoke-virtual-method-int-android-view-viewgro) on StackOverflow as well

Resolved it by created a duplicate of `design_bottom_navigation_item.xml` and put it `res/layout`, got idea from @paulocoutinhox's comment 

<img width="381" alt="Screenshot 2024-04-15 at 9 39 31 PM" src="https://github.com/material-components/material-components-android/assets/100408301/e3f31c71-fbc9-4d67-843c-f205bcd2b1ce">
