### ISSUE TITLE
Sync the project and failed

### ISSUE THREAD

**Issue by PykeChen** [material-components/material-components-android#70] opened 2018-03-30 05:01 UTC
### Overview
Hello!

sync project and report the following error:

Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/animation' (needed by modules: 'lib', 'tests'.)
Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/bottomappbar' (needed by modules: 'lib', 'tests'.)
Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/bottomnavigation' (needed by modules: 'lib', 'tests'.)
Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/bottomsheet' (needed by modules: 'lib', 'tests'.)
Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/button' (needed by modules: 'lib', 'tests'.)
Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/canvas' (needed by modules: 'lib', 'tests'.)
Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/card' (needed by modules: 'lib', 'tests'.)
Error:Unable to find module with Gradle path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/chip' (needed by modules: 'lib', 'tests'.)
.......

 - I used the solution [Build Failed #58 ](https://github.com/material-components/material-components-android/issues/58) but it not be ok!
- Android Studio 3.0.1

**Comment by vladislavu-hyuna** [comment] 2018-04-04 14:45
Faced the same issue

**Comment by dsn5ft** [comment] 2018-04-24 19:43
Closing as duplicate of #51. Looks like Studio doesn't like the "/"s in module names, even though it is supported by Gradle from the command line. Will have a fix for this soon.

**Closed by dsn5ft** 2018-04-24 19:43 UTC
