### ISSUE TITLE
[TextInputLayout] TextInputLayout falls down 12dp when hintEnabled is set to "false"

### ISSUE THREAD

**Issue by YaMo97** [material-components/material-components-android#1386] opened 2020-06-07 03:03 UTC
**Description:** The `TextInputLayout` falls down `12dp` when floating label is disabled using `app:hintEnabled="false"` and when placed in a LinearLayout.

**Screenshot** -
![image](https://user-images.githubusercontent.com/13934280/83959277-a2ea9780-a898-11ea-8400-6ffc34d10d1f.png)

**Expected behavior:**  `TextInputLayout` on the left has Floating Label disabled by using `app:hintEnabled=false` and `TextInputLayout` on the right has Floating Label Enabled.
The left one falls down, when it should not and stay aligned with the right one.
Error is enabled in both the Fields.

**Source code:** 
```
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal" >

        <com.google.android.material.textfield.TextInputLayout
            style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"
            android:layout_width="200dp"
            android:layout_height="wrap_content"
            app:errorEnabled="true"
            app:hintEnabled="false" >

            <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="Floating Label/Hint Disabled" />

        </com.google.android.material.textfield.TextInputLayout>

        <com.google.android.material.textfield.TextInputLayout
            style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"
            android:layout_width="200dp"
            android:layout_height="wrap_content"
            app:errorEnabled="true"
            android:hint="Floating Label/Hint Enabled" >

            <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

        </com.google.android.material.textfield.TextInputLayout>
</LinearLayout>
```

**Android API version:** 28

**Material Library version:** `implementation 'com.google.android.material:material:1.1.0'`

**Device:** Android Studio Preview Window and Redmi 4X (India)

**Workaround:** If I offset the top margin by 12 dp - `android:marginTop="-12dp"`, it aligns with right one.

**Comment by kroegerama** [comment] 2020-06-07 08:07
Same for `1.2.0-beta01`.

**Comment by matpag** [comment] 2020-06-12 20:54
Have you tried moving the `android:hint="Floating Label/Hint Disabled"` to the `TextInputLayout` instead?.
Your second `TextInputLayout` has the hint applied to it and not int the child.

Because I don't think hint is fully supported in `TextInputEditText`

**Comment by YaMo97** [comment] 2020-06-13 09:27
@matpag Same issue persists even if I remove `android:hint` completely from the `TextInputEditText`.

Also, if you'll notice, I have set `app:hintEnabled="false"` in the `TextInputLayout`.
The purpose of above technique is to only show a placeholder hint while disabling the floating label. 

Link - [Enabling/Disabling Floating Hints - Android TextInputLayout Example - JournalDev](https://www.journaldev.com/14748/android-textinputlayout-example#enablingdisabling-floating-hints).

**Comment by matpag** [comment] 2020-06-13 10:36
You are right.
I've made some more tests now and can confirm the bug is there

**Comment by YaMo97** [comment] 2020-06-19 03:55
I think the reason placeholder only shows when textfield has focus is because it is meant to work along with the Floating Label such that the following is possible: -
- If not focused then hide placeholderText and show Label as hint/placeholder
- else if focused then slide the label up making it float, and show the placeholderText.

This prevents overlapping of Label (as hint) and placeholderText when TextField is not focused.

**Comment by ymarian** [comment] 2020-06-24 12:04
Does it look better if you set `android:baselineAligned="false"` to the linearlayout?

**Comment by VyacheslavDev** [comment] 2021-02-19 10:26
android:baselineAligned="false" line helped. Thanks

**Comment by drchen** [comment] 2022-04-15 20:32
I think it's a duplicate of #1113. Let's close this one and move the discussion there to better track the issue.

**Closed by drchen** 2022-04-15 20:32 UTC
Labels: bug, Widget: TextField
