### ISSUE TITLE
[MaterialTextView] InflateViewException in creating custom dialog using MaterialAlertDialogBuilder.

### ISSUE THREAD

**Issue by monil1334** [material-components/material-components-android#2047] opened 2021-02-05 20:15 UTC
**Description:** Full description of issue here
The app crashes whenever building a custom dialog using context that is not from appcompatActivity. I tried changing themes, removing theme completely but still crashes. Wanted to create my own custom dialog so i can call it from anywhere but still keeps on crashing during inflation. I am failing to understand what is missing?

Theme is

<style name="TextView" parent="Widget.MaterialComponents.TextView">
        <item name="android:textColor">?attr/colorPrimary</item>
        <item name="android:textAppearance">@style/TextAppearance.MaterialComponents.Subtitle1</item>
</style>

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="20dp">

    <ImageView
        android:id="@+id/custom_dialog_top_icon"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_marginTop="10dp"
        android:src="@drawable/ic_logo"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.textview.MaterialTextView
        android:id="@+id/custom_dialog_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        android:gravity="center"
        android:text="@string/sms_verification_waiting"
        style="@style/TextView.Caption"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/custom_dialog_top_icon" />

    <ListView
        android:id="@+id/custom_dialog_items"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:divider="@null"
        android:paddingStart="40dp"
        android:paddingTop="10dp"
        android:paddingEnd="40dp"
        android:paddingBottom="10dp"
        android:textColor="?attr/colorPrimary"
        android:visibility="gone"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/custom_dialog_text" />

    <com.google.android.material.button.MaterialButton
        android:id="@+id/custom_dialog_positive_button"
        style="@style/CAAlertDialog.Button"
        android:text="@string/dialog_grant"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@id/custom_dialog_text"
        tools:visibility="visible" />

    <com.google.android.material.button.MaterialButton
        android:id="@+id/custom_dialog_negative_button"
        style="@style/CAAlertDialog.Button"
        android:layout_marginEnd="10dp"
        android:text="@string/no"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="@id/custom_dialog_positive_button"
        app:layout_constraintEnd_toStartOf="@id/custom_dialog_positive_button"
        tools:visibility="visible" />

</androidx.constraintlayout.widget.ConstraintLayout>

 E AndroidRuntime: FATAL EXCEPTION: main
02-05 14:04:41.583 13761 13761 E AndroidRuntime: android.view.InflateException: Binary XML file line #9 in com.a.c:layout/content_alert: Binary XML file line #9 in com.a.c/content_alert: Error inflating class com.google.android.material.textview.MaterialTextView
02-05 14:04:41.583 13761 13761 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #9 in com.a.c:layout/content_alert: Error inflating class com.google.android.material.textview.MaterialTextView
02-05 14:04:41.583 13761 13761 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.a.ac.a.a.a.as.<init>(as.kt:22)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.a.ac.a.a.a.aqzz(vda.kt:15)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.a.ac.a.a.a.sas(bss.kt:15)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.a.ac.a.a.a.ssav(a.kt:386)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.a.ac.a.a.a.cav(a.kt:168)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.a.ac.a.a.a.asav$1.a(a.kt:43)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.View.performClick(View.java:7448)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7425)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.View.access$3600(View.java:810)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28305)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-05 14:04:41.583 13761 13761 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040144 a=8}
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.widget.TextView.readTextAppearance(TextView.java:4006)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.widget.TextView.<init>(TextView.java:1093)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at android.widget.TextView.<init>(TextView.java:994)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:100)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:93)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:88)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:83)
02-05 14:04:41.583 13761 13761 E AndroidRuntime:        ... 26 more

API version 30

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
Material Lib 1.3.0

**Device:** Device on which the bug was encountered here
Emulator

**Comment by drchen** [comment] 2021-09-22 14:57
Has the issue been solved? 

If you see "UnsupportedOperationException: Failed to resolve attribute...", it usually means your theme settings are not correct. You may want to check if:

1. Your app/activity themes are correctly inheriting Material themes.
2. Right context are being used to create your views.
3. You are not overriding theme inheritance in variant style folders, say, values-night.

I'll close the issue since it's a bit old and it's probably not a library issue.
Feel free to provide more info if you still have the problem. We can try our best to help you debug.

**Closed by drchen** 2021-09-22 14:57 UTC
Labels: bug

**Comment by axitasavani** [comment] 2022-03-04 05:50
Hi, @drchen  I have faced this same issue and i have reported in this "https://github.com/material-components/material-components-android/issues/492#issuecomment-1058845739", Can you please tell me out to find or reproduced this crash and also what is the solution?
