### ISSUE TITLE
[Drawable] drawableLeftCompat doesn't work

### ISSUE THREAD

**Issue by alexgargui** [material-components/material-components-android#1176] opened 2020-04-02 18:57 UTC
**Description:** When upgrade to the latest version of material components the app doesnt started and said APPT: drawableLeftCompat and drawableStartCompat not found.

<img width="944" alt="Captura de Pantalla 2020-04-02 a la(s) 12 55 36" src="https://user-images.githubusercontent.com/11659121/78291194-317e1980-74e2-11ea-9caf-0b3166608b50.png">

**Source code:** mtrl_alert_select_dialog_multichoice.xml

**Android API version:** 21

**Device:** Emulated device

**Comment by hunterstich** [comment] 2020-04-03 13:49
Hey there. Do you mind filing a small sample that reproduces this so we can investigate what's happening?

**Comment by remstos** [comment] 2020-04-07 10:29
Seing this as well on a React Native project, interested in the resolution.

**Comment by Cyclonecat** [comment] 2020-08-05 02:30
I also encountered this problem and I cannot solve it now.

.gradle/caches/transforms-2/files-2.1/aaffe7b1f20928a98602bfbe26cc6cd0/material-1.1.0/res/layout/mtrl_alert_select_dialog_multichoice.xml:30: AAPT: error: attribute drawableLeftCompat 
.gradle/caches/transforms-2/files-2.1/aaffe7b1f20928a98602bfbe26cc6cd0/material-1.1.0/res/layout/mtrl_alert_select_dialog_multichoice.xml:30: AAPT: error: attribute drawableStartCompat 
.gradle/caches/transforms-2/files-2.1/aaffe7b1f20928a98602bfbe26cc6cd0/material-1.1.0/res/layout/mtrl_alert_select_dialog_singlechoice.xml:30: AAPT: error: attribute drawableLeftCompat 
.gradle/caches/transforms-2/files-2.1/aaffe7b1f20928a98602bfbe26cc6cd0/material-1.1.0/res/layout/mtrl_alert_select_dialog_singlechoice.xml:30: AAPT: error: attribute drawableStartCompat

**Comment by wcshi** [comment] 2020-08-05 17:02
@Cyclonecat please see https://github.com/material-components/material-components-android/issues/1176#issuecomment-608443912

**Comment by chankruze** [comment] 2021-05-31 16:01
@alexgargui @remstos 

I was inactive in community for past few months and today i started again, use `app:drawableStartCompat="@drawable/<whatever>"` and also add `xmlns:app="http://schemas.android.com/apk/res-auto"` namespace.

Hope this helps.

**Comment by drchen** [comment] 2021-10-06 14:42
Is this still an issue?

**Comment by drchen** [comment] 2021-11-02 20:14
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:14 UTC
Labels: bug, Need more info
