### ISSUE TITLE
[TextInputLayout] Error message animations stops

### ISSUE THREAD

**Issue by joernahrens** [material-components/material-components-android#607] opened 2019-09-17 14:30 UTC
**Description:** When setting an error twice after a very short time the error message stops at some point and is not positioned correctly. In my case a TextWatcher is adding an error message to the TextInputLayout.
![Screen Shot 2019-09-17 at 16 28 58](https://user-images.githubusercontent.com/17003882/65050808-49d47f80-d968-11e9-9163-377aaeb6977f.png)

**Expected behavior:** This is the normal behavior (when not typing 2 characters too quickly)
![Screen Shot 2019-09-17 at 16 30 26](https://user-images.githubusercontent.com/17003882/65050942-80aa9580-d968-11e9-831d-b7965f4dbce5.png)

**Source code:** Make a call like `textInputLayout.error = context.resources.getString(R.string.invalid_phone_number)` twice in a row (with only short delay).

The bug can be circumvented by checking `if (!textInputLayout.isErrorEnabled)` before setting the error.

**Android API version:** Tested on API 21 and 29

**Material Library version:** 1.1.0-alpha10

**Device:** Pixel 3 with Android Q, Emulator with Android 5

**Comment by ldjcmu** [comment] 2019-09-17 15:22
Thanks for the report, we'll look into how we can fix this.

**Comment by hoc081098** [comment] 2019-10-16 16:46
Same issue

**Comment by leticiarossi** [comment] 2019-11-19 22:31
Could you attach a sample app? I'm not able to reproduce the issue on my end

**Comment by joernahrens** [comment] 2019-11-20 14:04
Here you are @leticiarossi https://github.com/joernahrens/TextInputValidation

**Comment by leticiarossi** [comment] 2019-11-20 23:12
Thank you for the sample app. I don't see the issue happening in 1.2.0-alpha01 and up so I believe it was fixed in https://github.com/material-components/material-components-android/commit/4bd83e5fc921186616c95f416321138a61007dba!

**Closed by leticiarossi** 2019-11-20 23:12 UTC
Labels: bug
