### ISSUE TITLE
[MaterialContainerTransform] startView is visible over the endView container

### ISSUE THREAD

**Issue by moliverac8** [material-components/material-components-android#2257] opened 2021-06-17 10:25 UTC
**Description:** The startView (FAB in this case) in the MaterialContainerTransform between two fragments is visible above the endView during the animation process.

**Expected behavior:** Startview dissapears with the animation when the transition starts

**Source code:** 
```
enterTransition = MaterialContainerTransform().apply {
                startView = requireActivity().findViewById(R.id.newRecipeBtn)
                endView = binding.recipePager
                duration = resources.getInteger(R.integer.motion_duration_large).toLong()
                scrimColor = Color.TRANSPARENT
                containerColor = ContextCompat.getColor(requireContext(), R.color.secondaryColor)
                startContainerColor = ContextCompat.getColor(requireContext(), R.color.secondaryColor)
                endContainerColor = ContextCompat.getColor(requireContext(), R.color.colorSurface)
            }

```
[VisualBugSample](https://i.stack.imgur.com/GLOLM.gif)

**Android API version:** API 30

**Material Library version:** 1.3.0

**Device:** Pixel 4 API 27 Emulator

**Comment by Udhayarajan** [comment] 2021-10-30 04:10
@moliverac8  have you solved this issue?

**Comment by Udhayarajan** [comment] 2021-10-30 07:32
Hey, I have figured out the solution. I don't know why my brain works as dumb for the past 3 days.

### Reason
 Lemme to the point, actually the thing was our 2nd fragment's background is `Color.TRANSPARENT` by default. In any kind of animation, just the view gets updated not the physical size. For example, if you have an animation to scale fab, fab won't get affected by scaling anim. Similar thing happening here.

### Clarification
 I hope you followed [codeLab](https://codelabs.developers.google.com/codelabs/material-motion-android#4), there they set `emailCarview` as `startView`. If you noticed entire `fragment_compose.xml`  is covered with views with no space left for `Color.TRANSPARENT`. Thereby everything is fine there.

### How to fix
Just add `android:background="?attr/colorSurface"` on your 2nd fragment/activity. Don't worry about themes, it will be fine as normal.

I suggest you, close this issue as it is not a bug and developers(**material-components**) need not to worry about it.

**Closed** 2021-10-30 10:19 UTC
Labels: bug, Widget: Transition
