### ISSUE TITLE
[Chips] Chips don't work with external keyboard for accessible users

### ISSUE THREAD

**Issue by SukhvirKaur57** [material-components/material-components-android#1134] opened 2020-03-23 05:34 UTC
**Description:** I need to use Choice chips in a ChipGroup, everything is working as I want except the external keyboard is not supported. When I try to navigate through the chip using keyboard tab or arrow keys the focus gets stuck either on first or last chip of my ChipGroup. 

**Expected behaviour:** 
When a bluetooth or wired keyboard is connected to device the user should be able to navigate all the chips in a ChipGroup using tab and arrow keys.

**Source code:** 

```
  <com.google.android.material.chip.ChipGroup
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:paddingStart="20dp"
            app:chipSpacing="10dp"
            app:singleSelection="true">

            <com.google.android.material.chip.Chip
                android:id="@+id/chip_1"
                style="@style/Widget.MaterialComponents.Chip.Choice"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Chip 1"
                android:textAppearance="@style/Widget.MaterialComponents.Chip.Choice"
                app:checkedIconEnabled="true"
                app:chipEndPadding="12dp"
                app:chipStartPadding="12dp" />

            <com.google.android.material.chip.Chip
                android:id="@+id/chip_2"
                style="@style/Widget.MaterialComponents.Chip.Choice"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Chip 2"
                android:textAppearance="@style/Widget.MaterialComponents.Chip.Choice"
                app:checkedIconEnabled="true"
                app:chipEndPadding="12dp"
                app:chipStartPadding="12dp" />

            <com.google.android.material.chip.Chip
                android:id="@+id/chip_3"
                style="@style/Widget.MaterialComponents.Chip.Choice"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Chip 3"
                android:textAppearance="@style/Widget.MaterialComponents.Chip.Choice"
                app:checkedIconEnabled="true"
                app:chipEndPadding="12dp"
                app:chipStartPadding="12dp" />
        </com.google.android.material.chip.ChipGroup>
`````

**Android API version:** API-23 and API-28

**Material Library version:**  version 1.1.0

**Device:** Pixel 3, 3XL

**Comment by wcshi** [comment] 2020-03-23 17:12
@SukhvirKaur57 is the bug reproducible using the chipgroup demo in the catalog app?

I  using an external keyboard with a pixel 3XL phone running Android Q and i was able to navigate using the tabs key.

**Comment by drchen** [comment] 2021-10-14 21:10
I'll close the issue due to no further info and some relevant fix has been pushed a while ago.

Feel free to reopen it if it's still reproducible with the latest library version.

**Closed by drchen** 2021-10-14 21:10 UTC
Labels: bug
