### ISSUE TITLE
[MaterialDatePicker] Manual Date input does not work on Samsung device

### ISSUE THREAD

**Issue by p1415604x** [material-components/material-components-android#984] opened 2020-02-06 06:56 UTC
Description:
When clicking the "edit" button next to "Selected Date" on the picker to manually input a date with the edit text it is not possible to enter a valid date with the Samsung stock keyboard since the number keyboard that is opened does not allow to enter "/" or ".".

Expected behavior: It should be possible to enter a valid date with the keyboard, either by automatically inserting the special characters to complete the date or by using keyboard variant that supports these needed characters.

Android API version: 28 / Android 9.0

Material Library version: 1.2.0-alpha04

Device: Samsung A50 (SM-A505FN)

**Comment by leticiarossi** [comment] 2020-02-06 15:36
Closing this as duplicate of https://github.com/material-components/material-components-android/issues/901

**Closed by leticiarossi** 2020-02-06 15:36 UTC
Labels: bug
