### ISSUE TITLE
TextInputLayout endIcon paddings issue

### ISSUE THREAD

**Issue by Zeliret** [material-components/material-components-android#365] opened 2019-05-16 11:28 UTC
Hi guys!
Something wrong with the endIcon paddings in this control. 
Check it out:
![Z2gSZZAc](https://user-images.githubusercontent.com/975526/57850518-c6065d00-77e6-11e9-94f6-88fc66a96770.jpeg)

```xml
<com.google.android.material.textfield.TextInputLayout
                android:id="@+id/address_place_layout"
                style="@style/Widget.TextInputLayout.Primary"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:endIconDrawable="@drawable/ic_clear"
                app:endIconMode="clear_text"
                app:startIconDrawable="@drawable/ic_location_default_light"
                app:startIconTint="@color/palette_hint">

                <com.google.android.material.textfield.TextInputEditText
                    android:id="@+id/address_place"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:hint="@{vm.isPickUp ? @string/place_placeholder_pick_up : @string/place_placeholder_drop_off}"
                    android:inputType="textMultiLine"
                    android:text="@={vm.placeSearchLive}"/>
            </com.google.android.material.textfield.TextInputLayout>
```

**Comment by william-reed** [comment] 2019-05-16 14:51
which version of this library are you using?

**Comment by Zeliret** [comment] 2019-05-16 15:00
@william-reed 1.1.0-alpha06

**Comment by william-reed** [comment] 2019-05-16 15:16
hm ok i only asked because this was brought into alpha-04, https://github.com/material-components/material-components-android/commit/b7f520d0f6763efc858ffa69be7ce5abb176fcdc. I would recommend opening an issue on the google issue tracker and someone from google will usually respond within a day

**Comment by samsruti** [comment] 2019-05-17 03:05
@Zeliret It's working for me.
Version: material:1.1.0-alpha06

Can you try to check the style: "Widget.TextInputLayout.Primary"?

**Comment by Zeliret** [comment] 2019-05-17 07:18
@samsruti Here is my style:
```xml
<style name="Widget.TextInputEditText.Primary" parent="Widget.MaterialComponents.TextInputEditText.OutlinedBox">
        <item name="android:paddingTop">@dimen/padding_20</item>
        <item name="android:paddingBottom">@dimen/padding_20</item>
        <item name="hintTextAppearance">@style/TextAppearance.Hint</item>
    </style>
```
I do not see any problems in this style. =(

**Comment by Zeliret** [comment] 2019-05-17 13:26
I have tried alpha-04 and it seems there is no such problem in this particular version.

**Comment by leticiarossi** [comment] 2019-05-17 14:02
I'm not able to reproduce the issue. Could you provide a simplified version of your app where the issue happens so I can take a look?

**Comment by Zeliret** [comment] 2019-05-17 14:48
Give me some time, I will return here with an example in a couple of days. Thank you.

**Comment by quangpg95** [comment] 2019-06-13 16:07
I have the same error. Have you solved this problem?

**Comment by leticiarossi** [comment] 2019-07-10 15:13
I believe this has been fixed in https://github.com/material-components/material-components-android/commit/15b721c750c017ac213fcec50536f79fb811e858

**Closed by leticiarossi** 2019-07-10 15:13 UTC

**Comment by P1NG2WIN** [comment] 2024-07-10 12:58
I have the same problem. My TextInputLayout is inflated from code using viewbinding, and at first the right padding doesn't work and the text gets under the removal icon until i change visiblity to GONE and then to VISIBLE. Also if you remove endIconMode="clear_text" from the xml, there is no bug.
