### ISSUE TITLE
"Theme.MaterialComponents.." breakes drawer_layout.openDrawer()

### ISSUE THREAD

**Issue by brucemax** [material-components/material-components-android#133] opened 2018-06-05 18:02 UTC
### Overview
 - When I changed theme to "Theme.MaterialComponents.." method android.support.v4.widget.DrawerLayout.openDrawer() stop working, menu not open after calling this method

### Version number

 implementation 'com.android.support:design:28.0.0-alpha1'

### Operating system and device
Xiaomi Mi A1 Android 8.0.0

**Comment by dsn5ft** [comment] 2018-06-05 18:30
Duplicate of #132

This is a known issue that has been fixed and will be available in the next release coming soon - https://buganizer.corp.google.com/issues/74357002.

The workaround is to add the following to your App Theme:
```
<item name="navigationViewStyle">@style/Widget.Design.NavigationView</item>
```

**Closed by dsn5ft** 2018-06-05 18:30 UTC
