### ISSUE TITLE
[CircularProgressIndicator] setBounds() doesn't work for CircularProgressIndicator

### ISSUE THREAD

**Issue by fsgjlp** [material-components/material-components-android#2657] opened 2022-04-20 15:09 UTC
Code:
```java
    TextView textView1 = view.findViewById(R.id.text_view_1);
    textView1.setText("BitmapDrawable");

    TextView textView2 = view.findViewById(R.id.text_view_2);
    textView2.setText("ChipDrawable");

    TextView textView3 = view.findViewById(R.id.text_view_3);
    textView3.setText("IndeterminateDrawable");

    ///////

    Drawable drawable1 = ContextCompat.getDrawable(getContext(), android.R.drawable.ic_delete);
    drawable1.setBounds(200, 0, 250, 50);
    TextViewCompat.setCompoundDrawablesRelative(textView1, drawable1, null, null, null);

    ChipDrawable drawable2 = ChipDrawable.createFromAttributes(getContext(), null, 0, com.google.android.material.R.style.Widget_MaterialComponents_Chip_Action);
    drawable2.setBounds(200, 0, 250, 50);
    TextViewCompat.setCompoundDrawablesRelative(textView2, drawable2, null, null, null);

    CircularProgressIndicatorSpec spec = new CircularProgressIndicatorSpec(getContext(), null, 0, com.google.android.material.R.style.Widget_MaterialComponents_CircularProgressIndicator_ExtraSmall);
    IndeterminateDrawable<?> drawable3 = IndeterminateDrawable.createCircularDrawable(getContext(), spec);
    drawable3.setVisible(true, true);
    drawable3.setBounds(200, 0, 250, 50);
    TextViewCompat.setCompoundDrawablesRelative(textView3, drawable3, null, null, null);
```
Result:
![image](https://user-images.githubusercontent.com/102207540/164262037-917ff005-94a8-4b5c-9824-9ff60b19d1ae.png)

Reproduced on Material 1.6.0-rc01

**Comment by dsn5ft** [comment] 2022-04-20 19:17
Hi @fsgjlp when you say "doesn't work" do you just mean how the alignment of the progress indicator is different than the 2 examples above it?

**Comment by fsgjlp** [comment] 2022-04-20 21:48
Yes, exactly!

**Comment by drchen** [comment] 2022-05-27 18:26
Duplicate of https://github.com/material-components/material-components-android/issues/2364

**Closed by drchen** 2022-05-27 18:26 UTC
Labels: bug, Widget: ProgressIndicator
