### ISSUE TITLE
[Snackbar] Empty space between gesture navigation bar and Snackbar when Snackbar is used in CoordinatorLayout and AppCompat theme

### ISSUE THREAD

**Issue by plnice** [material-components/material-components-android#1977] opened 2021-01-12 13:17 UTC
**Description:**

After updating to material 1.1.0-alpha10 and later, when `Snackbar` is used in the `CoordinatorLayout`, the app is using `AppCompat`-based theme, and user has Android 10+ gesture navigation enabled device, there is an empty space between navigation bar and the `Snackbar`. The issue can be reproduced with this project: https://github.com/plnice/SnackbarTest. Trying to override `snackbarStyle` in the app's theme (e.g. setting `layout_margin` or `padding` to `0`) doesn't have any effect. 

<img src="https://user-images.githubusercontent.com/1078123/104318834-3e538300-54e0-11eb-81c9-239e69a0ef93.png" width="300px" />

**Expected behavior:** There is no empty space between navigation bar and the Snackbar.

**Source code:** https://github.com/plnice/SnackbarTest

**Android API version:** 29 and later (Android 10, 11)

**Material Library version:** The wrong behavior was introduced in 1.1.0-alpha10, the issue is still reproducible with 1.3.0-beta01.

**Device:** Pixel 2XL, Android 11 (most likely other Android 10+ devices with gesture navigation enabled are affected)

**Comment by ikim24** [comment] 2021-01-12 17:37
Closing as this behavior is working as intended. When swipe to dismiss is enabled on the Snackbar, that space is necessary in order to ensure that gesture navigation and the Snackbar swipe to dismiss gesture aren't conflicted.

**Closed by ikim24** 2021-01-12 17:37 UTC
Labels: bug

**Comment by plnice** [comment] 2021-01-12 18:21
@ikim24 when swipe-to-dismiss is disabled, the behavior is the same. I've disabled swipe-to-dismiss by setting empty behavior to `CoordinatorLayout` - see https://github.com/plnice/SnackbarTest/commit/228c5b69293cfcc38455da7c723cce7a29f6ad5b. Is there any other way I can disable swipe-to-dismiss so there's no space between gesture navigation bar and the snackbar?

**Comment by ikim24** [comment] 2021-01-12 20:36
You can call `setGestureInsetBottomIgnored` https://github.com/material-components/material-components-android/blob/15a2307e917508fd11b9d835768af5cf33151c27/lib/java/com/google/android/material/snackbar/BaseTransientBottomBar.java#L527 to ignore the gesture inset on the bottom

**Comment by plnice** [comment] 2021-01-13 08:46
That's what I was missing :-) Thanks for your help!
