### ISSUE TITLE
[BottomSheetBehavior] Size changes are ignored if the sheet is settling to a state

### ISSUE THREAD

**Issue by saket** [material-components/material-components-android#1059] opened 2020-02-25 19:26 UTC
**Description:** 
We're building a sheet that loads data asynchronously after opening, causing the sheet to change its size and it seems like `BottomSheetBehavior` doesn't react well to size changes if it's ongoing a settle animation. 

We are currently using a custom bottomsheet that was copied from Plaid's implementation, but I'm trying to move to `BottomSheetBehavior` so that we don't have to maintain this ourselves.

**Expected behavior:**
Here's a screenrecording of the sample app: https://github.com/saket/BottomSheetPlease/blob/master/video.mp4. The `Toggle without anim` shows the correct behavior of the sheet. The `Toggle with anim` doesn't.

**Source code:** 
[https://github.com/saket/BottomSheetPlease](https://github.com/saket/BottomSheetPlease/blob/master/app/src/main/java/me/saket/bottomsheetplease/MainView.kt#L61)

**Android API version:** 
28

**Material Library version:** 
1.1.0

**Device:** 
Pixel 3 emulator

**Comment by drchen** [comment] 2022-06-01 20:59
Is this still reproducible with the latest library version?

**Comment by drchen** [comment] 2022-06-16 19:07
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-06-16 19:07 UTC
Labels: bug, Need more info, Widget: BottomSheet
