### ISSUE TITLE
[MaterialDatePicker] Crash with bridge themes

### ISSUE THREAD

**Issue by jereld** [material-components/material-components-android#494] opened 2019-08-02 23:36 UTC
**Description:**
Crash occurs due to missing materialCalendarTheme attribute in bridge themes.

Error message:

> java.lang.IllegalArgumentException: com.google.android.material.picker.MaterialDatePicker requires a value for the com.company.myapplication:attr/materialCalendarTheme attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).

**Material Library version:**
1.1.0-alpha09

**Comment by dsn5ft** [comment] 2019-08-06 19:44
Thanks for reporting. We will consider moving all of our non-AppCompat/Framework attributes from our Full themes into our Bridge themes, since that should have no effect on apps being migrated from AppCompat to MaterialComponents.

For now you could set the following in your theme:

```
    <item name="materialCalendarStyle">@style/Widget.MaterialComponents.MaterialCalendar</item>
    <item name="materialCalendarFullscreenTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen</item>
    <item name="materialCalendarTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
```

**Comment by jereld** [comment] 2019-08-08 21:00
Unfortunately, adding the materialCalender attributes to a bridge theme causes a ClassCastException to be thrown when displaying the MaterialDatePicker

> java.lang.ClassCastException: androidx.appcompat.widget.AppCompatButton cannot be cast to com.google.android.material.button.MaterialButton at com.google.android.material.picker.MaterialDatePicker.onCreateView(MaterialDatePicker.java:188)

**Comment by dsn5ft** [comment] 2019-08-15 16:31
Thanks for reporting, we'll address this so MaterialDatePicker works with the Bridge themes.

**Comment by ldjcmu** [comment] 2019-09-18 15:17
This is fixed. We removed explicit references to MaterialButton in the MaterialDatePicker

**Comment by AntoGeekz** [comment] 2019-10-15 14:14
Any news about this problem plz?

**Comment by tomblenz** [comment] 2020-02-03 19:33
Hi, I'm experiencing the same error in 1.1.0.

`java.lang.IllegalArgumentException: com.google.android.material.datepicker.MaterialDatePicker requires a value for the com.newzealand.drive.dev:attr/materialCalendarTheme attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).`

My theme inherits from a bridge theme

`<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge">`

**Comment by rakesh1988** [comment] 2020-02-10 05:17
> Hi, I'm experiencing the same error in 1.1.0.
> 
> ```
> java.lang.IllegalArgumentException: com.google.android.material.datepicker.MaterialDatePicker requires a value for the xxxx:attr/materialCalendarTheme attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
> ```
> 
> My theme inherits from a bridge theme
> 
> `<style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge">`

@tomblenz  any fix for this issue?

**Comment by tomblenz** [comment] 2020-02-10 06:54
> @tomblenz any fix for this issue?

The workaround above works still 

```
<item name="materialCalendarStyle">@style/Widget.MaterialComponents.MaterialCalendar</item>
<item name="materialCalendarFullscreenTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen</item>
<item name="materialCalendarTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
```

**Comment by tomblenz** [comment] 2020-02-10 06:55
@ldjcmu you should re-open this

**Comment by vapstor** [comment] 2020-03-20 10:29
With those lines

> > @tomblenz any fix for this issue?
> 
> The workaround above works still
> 
> ```
> <item name="materialCalendarStyle">@style/Widget.MaterialComponents.MaterialCalendar</item>
> <item name="materialCalendarFullscreenTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen</item>
> <item name="materialCalendarTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
> ```

`com.google.android.material.datepicker.MaterialDatePicker requires a value for the br.com.cargafacil:attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).`

colorSurface?

**Comment by Ridvmodi** [comment] 2020-03-25 18:03
@vapstor any fix for the colorSurface issue ?

**Comment by hamzakapadiaa** [comment] 2020-03-28 19:41
@vapstor
Try this:
<item name="colorSurface">#FFFFFF</item>

**Comment by hamzakapadiaa** [comment] 2020-03-28 19:42
@vapstor 
Try this:
<item name="colorSurface">#FFFFFF</item>

**Comment by hamzakapadiaa** [comment] 2020-03-28 19:44
@vapstor 
Try this:
`<item name="colorSurface">#FFFFFF</item>`

**Comment by Ridvmodi** [comment] 2020-03-30 07:31
> With those lines
> 
> > > @tomblenz any fix for this issue?
> > 
> > 
> > The workaround above works still
> > ```
> > <item name="materialCalendarStyle">@style/Widget.MaterialComponents.MaterialCalendar</item>
> > <item name="materialCalendarFullscreenTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen</item>
> > <item name="materialCalendarTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
> > ```
> 
> `com.google.android.material.datepicker.MaterialDatePicker requires a value for the br.com.cargafacil:attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).`
> 
> colorSurface?

Fixed this by inheriting the theme From Theme.MaterialComponents instread of ThemeOverlay

 <style name="bookingActivityTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:timePickerDialogTheme">@style/timePickerTheme</item>
    </style>

**Comment by dangmeng** [comment] 2020-04-26 09:19
https://material.io/develop/android/docs/getting-started/  
Hope it helps you!

**Comment by Jeff11** [comment] 2020-06-29 12:34
The workaround does the job. This can be closed

**Closed** 2020-06-29 16:59 UTC
Labels: bug

**Comment by klaszlo8207** [comment] 2020-06-30 06:16
It is not working at all

**Here is my codes**

 <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar.Bridge">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="materialCalendarFullscreenTheme">
            @style/CustomThemeOverlay_MaterialCalendar_Fullscreen
        </item>
    </style>

    <style name="CustomThemeOverlay_MaterialCalendar_Fullscreen" parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen">
        <item name="materialCalendarStyle">@style/Custom_MaterialCalendar.Fullscreen</item>
        <item name="colorSurface">#FFFFFF</item>
    </style>

    <style name="Custom_MaterialCalendar.Fullscreen" parent="@style/Widget.MaterialComponents.MaterialCalendar.Fullscreen">
        <item name="android:windowFullscreen">false</item>
    </style>


**then**

        val builder = MaterialDatePicker.Builder.dateRangePicker()
        builder.setTheme(**R.style.CustomThemeOverlay_MaterialCalendar_Fullscreen**)

when I remopve the **colorSurface** field, then I get the **colorSurface error** thing

when I have it I get this :

android.view.InflateException: Binary XML file line #23: Binary XML file line #17: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class TextView
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0300ab a=2}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)

WTF going on?

**Comment by klaszlo8207** [comment] 2020-06-30 06:34
When I using the built in style with the 1.3.0.alpha01

builder.setTheme(R.style.ThemeOverlay_MaterialComponents_MaterialCalendar)

Then I get the same:

java.lang.IllegalArgumentException: com.google.android.material.datepicker.MaterialDatePicker requires a value ...
attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).

**Comment by thefabbulus** [comment] 2020-08-01 11:46
> It is not working at all, please reopen it
> 
> **Here is my codes**
> 
> ```
>  <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar.Bridge">
>         
>         <item name="colorPrimary">@color/colorPrimary</item>
>         <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
>         <item name="colorAccent">@color/colorAccent</item>
>         <item name="materialCalendarFullscreenTheme">
>             @style/CustomThemeOverlay_MaterialCalendar_Fullscreen
>         </item>
>     </style>
> ```
> 
> ```
> <style name="CustomThemeOverlay_MaterialCalendar_Fullscreen" parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen">
>     <item name="materialCalendarStyle">@style/Custom_MaterialCalendar.Fullscreen</item>
>     <item name="colorSurface">#FFFFFF</item>
> </style>
> 
> <style name="Custom_MaterialCalendar.Fullscreen" parent="@style/Widget.MaterialComponents.MaterialCalendar.Fullscreen">
>     <item name="android:windowFullscreen">false</item>
> </style>
> ```
> 
> **then**
> 
> ```
>     val builder = MaterialDatePicker.Builder.dateRangePicker()
>     builder.setTheme(R.style.CustomThemeOverlay_MaterialCalendar_Fullscreen)
> ```
> 
> when I remove the **colorSurface** field, then I get the **colorSurface error** thing
> 
> when I have it I get this :
> 
> android.view.InflateException: Binary XML file line #23: Binary XML file line #17: Error inflating class TextView
> Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class TextView
> Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0300ab a=2}
> at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
> 
> **at com.google.android.material.datepicker.MaterialDatePicker.onCreateView(MaterialDatePicker.java:209)**
> 
> WTF going on?
> 
> I just using
> 
> implementation("com.google.android.material:material:1.3.0-alpha01")
> 
> the same with the Bridge style

Still happening.

**Comment by dsn5ft** [comment] 2020-08-03 13:12
I just tried this with `com.google.android.material:material:1.3.0-alpha01`, and the date picker dialog opened fine with no crash:

```
<style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar.Bridge">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>

    <item name="materialCalendarFullscreenTheme">
        @style/CustomThemeOverlay_MaterialCalendar_Fullscreen
    </item>
</style>

<style name="CustomThemeOverlay_MaterialCalendar_Fullscreen" parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen">
    <item name="materialCalendarStyle">@style/Custom_MaterialCalendar.Fullscreen</item>
</style>

<style name="Custom_MaterialCalendar.Fullscreen" parent="@style/Widget.MaterialComponents.MaterialCalendar.Fullscreen">
    <item name="android:windowFullscreen">false</item>
</style>
```

```
MaterialDatePicker.Builder.dateRangePicker()
    .setTheme(R.style.CustomThemeOverlay_MaterialCalendar_Fullscreen)
    .build()
    .show(getSupportFragmentManager(), "TAG");
```

Please provide a minimal sample app that reproduces the issue.

**Comment by IgorGanapolsky** [comment] 2021-01-06 20:07
I am getting the same crash.  Here is how I defined my style:
`<style name="ThemeOverlay.Catalog.MaterialCalendar.Custom" parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar">
		<item name="colorPrimary">@color/myprimary_01</item>
		<item name="colorOnPrimary">@color/myprimary_02</item>
		<item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>
		<item name="materialCalendarStyle">@style/Widget.MaterialComponents.MaterialCalendar</item>
		<item name="materialCalendarFullscreenTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar.Fullscreen</item>
		<item name="materialCalendarTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
	</style>`

**Comment by ikim24** [comment] 2021-01-07 15:31
Please provide a minimal sample app that reproduces the issue.

**Comment by 4mr0m3r0** [comment] 2021-01-19 22:50
> CustomThemeOverlay_MaterialCalendar_Fullscreen

This solution works for me even with com.google.android.material:material:1.1.0 version. Thanks.

**Comment by mecoFarid** [comment] 2021-03-05 06:22
> The workaround does the job. This can be closed

What?

**Comment by rosghub** [comment] 2021-06-24 18:17
I think what's not been mentioned (?) yet is that your app theme (theme used in manifest application tag) needs to inherit `Theme.MaterialComponents.*`

**Comment by deviant-studio** [comment] 2021-09-21 13:55
wow, 2 years anniversary. i suppose bug is fixed? oh, looks like nope. well, let's wait another 2 years

**Comment by Jeff11** [comment] 2021-09-21 14:22
This is marked as closed. You could open a new issue and link this one.

**Comment by drchen** [comment] 2021-09-21 15:17
Hey folks, I don't know the history here, but I'll suggest you stopping using bridge themes if that's possible. 

1. Bridge themes are not designed to theme Material components. Even if we can try our best to make them more or less compatible, the compatibility can be fragile and easily broken. 
2. Material 3 won't support bridge themes anymore.

Therefore, I believe there won't be a fix of the bridge themes due to the upcoming release of Material 3. 
So if the workaround doesn't serve your need, please seriously consider about moving to non-bridge themes. 

If you have a difficulty of adapting your current themes to use non-bridge themes, please let us know.

**Comment by mj397** [comment] 2022-05-27 12:41
it is working, I just tried it and it's working fine when setting the main theme to Theme.MaterialComponents.Light.DarkActionBar.Bridge and then use the custom style to the dialog.

**Comment by shuytp** [comment] 2023-03-03 08:50
> https://material.io/develop/android/docs/getting-started/ Hope it helps you!

Very useful, thank you

**Comment by KhaledHawwas** [comment] 2025-05-19 19:40
after hours of fixing even with 1.12.0 still didn't work with all those workaround ,I switched `1.3.0-alpha01` and I got this 

![Image](https://github.com/user-attachments/assets/8f0cedc1-bf45-4f16-a9c2-2c23a7b13bcb)

**Comment by KhaledHawwas** [comment] 2025-05-19 19:43
All those wasted time 

![Image](https://github.com/user-attachments/assets/53107ae3-857c-4b10-8714-4e40add5072b)
