### ISSUE TITLE
[TextInputLayout] Disabled widget state doesn't use color from ColorStateList

### ISSUE THREAD

**Issue by tluksa** [material-components/material-components-android#515] opened 2019-08-09 21:08 UTC
**Description:** Setting ColorStateList for TextInputLayout attributes "android:textColorHint" or "hintTextColor" doesn't set color in disabled state.

**Expected behavior:** These attributes should utilize different colors from ColorStateList.

**Material Library version:** 1.1.0-alpha09

**Comment by maxkolotilin** [comment] 2019-08-18 14:42
Observe the same issue

**Comment by ldjcmu** [comment] 2019-10-01 21:03
We agree we want to fix this. Duplicate of #593.

**Closed by ldjcmu** 2019-10-01 21:03 UTC
Labels: bug
