### ISSUE TITLE
[Slider] Slider causes the app to suspend, when back from the fragment with enter/exit transition

### ISSUE THREAD

**Issue by Wewe12** [material-components/material-components-android#1195] opened 2020-04-08 17:51 UTC
**Description:** 
Slider causes the app to suspend when pressing back on the fragment which was open with enter and exit transition. 

Usecase: 
1. Open the new fragment with slider using this function:

```kotlin
fun Fragment.replaceWithStartEndTransition(fragment: Fragment){
    parentFragmentManager.commit {
        addToBackStack(null)
        fragment.enterTransition = Slide(Gravity.END)
        fragment.exitTransition = Slide(Gravity.START)
        replace(R.id.container, fragment)
    }
}
```

2. Click the back button. 

3. App is suspended

After change `replaceWithStardEndTransition` funtion  to `replace`:
```kotlin
fun Fragment.replace(fragment: Fragment) {
    parentFragmentManager.commit {
        addToBackStack(null)
        replace(R.id.container, fragment)
    }
}
```
everything works fine. 

**Expected behavior:** Fragment will close normally with exit transition. 

**Source code:** 
Example code:
https://github.com/Wewe12/SliderTestApp

The sample app contains two buttons that show the difference. 
The first one open SliderFragment using  `replace(fragment: Fragment)` function. 
After clicking back, SliderFragment disappeared normally. 

The second button  is using `replaceWithStartEndTransition(fragment: Fragment)` to open SliderFragment. After clicking back whole applications suspends. 

**Android API version:** 
29

**Material Library version:** 
1.2.0-alpha05

**Device:** 
Samsung S9 Plus Android 10
Emulator Pixel 3XL API R
Emulator Pixel 2 Android 8.1

**Comment by hunterstich** [comment] 2020-04-09 13:48
Hey thanks for reporting this!

I can reproduce this. It looks like it's because Visibility.java(Slide transition) is adding Slider to an OverlayViewGroup when dissapearing and is calling  Slider#onAttachedToWindow, which looks for a parent and get's stuck inside [a while loop](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/internal/ViewUtils.java#L285-L292) when it can't find one. Working on a fix now.

**Comment by adendiamond** [comment] 2020-04-10 02:40
I should have come straight here to look for an issue, I was trying to find out what it was for a while, and it finally worked when I commented out my slider 😕

**Comment by hunterstich** [comment] 2020-04-13 17:23
Fixed in the above commit. Should have a new 1.2.0-alpha06 release out today or tomorrow with this fix

**Closed** 2020-04-13 17:22 UTC
Labels: bug

**Comment by Wewe12** [comment] 2020-04-14 09:22
Works well. Thanks @hunterstich
