### ISSUE TITLE
[Typography] Parent styles of Body1 and Body2 looks wrong

### ISSUE THREAD

**Issue by konifar** [material-components/material-components-android#261] opened 2019-01-06 09:33 UTC
https://github.com/material-components/material-components-android/blob/6c70169e8d4ae77429a9c57785e443b2a18b4aa3/lib/java/com/google/android/material/typography/res/values/styles.xml#L97-L113

**Comment by ikim24** [comment] 2019-01-07 16:37
Closing as working as intended.

Material's typography has 1 as the largest size (note that H1 size > H2 size and Body1 size > Body2 size on https://material.io/design/typography/the-type-system.html#type-scale) whereas AppCompat typography goes the other direction (for exampley Display4 size > Display3 size).

**Closed by ikim24** 2019-01-07 16:37 UTC
