### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [material-components/material-components-android#375] opened 2019-05-23 11:21 UTC
I get this:
![image](https://user-images.githubusercontent.com/5357526/58248879-02493880-7d66-11e9-98dd-f565008b6f1f.png)

**Comment by leticiarossi** [comment] 2019-05-23 14:27
Hi, can you upload the stacktrace of the error as well as your build.gradle file?

**Comment by dsn5ft** [comment] 2019-05-23 14:30
I think this is a duplicate of #320, we will look into updating our gradle build tools version soon.

**Closed by dsn5ft** 2019-05-23 14:30 UTC

**Comment by AndroidDeveloperLB** [comment] 2019-05-23 14:32
So you need more info or not?

**Comment by dsn5ft** [comment] 2019-05-23 14:35
I don't think so, this is just what happens when you clone the project and update it's gradle version.

**Comment by AndroidDeveloperLB** [comment] 2019-05-23 14:38
Yes. That's true...
Is it fixed somehow though? The other issue is closed...

**Comment by dsn5ft** [comment] 2019-05-23 14:46
You can fix the issue locally by not updating the gradle version. This issue is being tracked at https://issuetracker.google.com/130879774.

**Comment by AndroidDeveloperLB** [comment] 2019-05-26 12:36
@dsn5ft Can you please fix it though?

**Comment by dsn5ft** [comment] 2019-05-28 15:43
Yes we will look into updating our gradle build tools version soon and fixing this issue.

**Comment by AndroidDeveloperLB** [comment] 2019-05-28 15:50
Thank you

**Comment by dsn5ft** [comment] 2019-05-29 19:37
So I fixed the left shift operator error by replacing << with doLast:

```
task exampleTask {
  doLast {
  }
}
```

But it looks like we'll have to stay on Gradle 4.6 for now because Gradle 5.1 doesn't work with out Maven plugin for generating AARs (https://github.com/dcendents/android-maven-gradle-plugin/issues/80#issuecomment-453226505). Eventually we will update to Gradle 5.1 and the new Maven Publish Plugin once that supports generating Android AARs (https://docs.gradle.org/current/userguide/publishing_maven.html).

**Comment by AndroidDeveloperLB** [comment] 2019-05-29 20:12
Did you do a commit&push? I don't think I see this change...

**Comment by dsn5ft** [comment] 2019-05-29 20:21
It's submitted internally and will be synced to GitHub soon.

**Comment by dsn5ft** [comment] 2019-05-29 21:04
https://github.com/material-components/material-components-android/commit/6f2f112b29719986b9e055c700547b507266af7f

**Comment by AndroidDeveloperLB** [comment] 2019-05-29 21:11
ok thanks. please let me know

**Comment by dsn5ft** [comment] 2019-05-29 21:18
See comment above, the commit is https://github.com/material-components/material-components-android/commit/6f2f112b29719986b9e055c700547b507266af7f.

**Comment by AndroidDeveloperLB** [comment] 2019-05-29 21:55
For some reason I don't get how to clone this one. Was hoping you do it to the main one.

**Comment by dsn5ft** [comment] 2019-05-30 14:06
Not sure exactly what you mean, the commit is on the master branch. So if you have our repository cloned already, then you should be able to just do a `git pull`. If not then you can re-clone it with `git clone https://github.com/material-components/material-components-android.git`.

**Comment by AndroidDeveloperLB** [comment] 2019-05-30 17:48
OK this is what I get now:
![image](https://user-images.githubusercontent.com/5357526/58652451-4ca95700-831c-11e9-8860-7446395ef5ca.png)

**Comment by dsn5ft** [comment] 2019-05-30 18:16
This is because of what I mentioned in https://github.com/material-components/material-components-android/issues/375#issuecomment-497080095.

You'll have to revert any local changes you have, specifically your `gradle-wrapper.properties` [file](https://github.com/material-components/material-components-android/blob/master/gradle/wrapper/gradle-wrapper.properties) should be using Gradle 4.6, and your `build.gradle` [file](https://github.com/material-components/material-components-android/blob/master/build.gradle) should be using `com.android.tools.build:gradle:3.2.1`.

**Comment by AndroidDeveloperLB** [comment] 2019-05-31 07:55
OK tried to clone again, and now it works.
But I don't remember I've made any changes before. I don't think I could revert to anything...

**Comment by dsn5ft** [comment] 2019-05-31 14:11
It was probably because Android Studio automatically prompts to update the Gradle versions for the project.

**Comment by AndroidDeveloperLB** [comment] 2019-05-31 21:09
Maybe. I don't remember. Sorry for that
