### ISSUE TITLE
[MaterialDatePicker] Allow overriding default date format for the manual date input

### ISSUE THREAD

**Issue by kingsleyadio** [material-components/material-components-android#1053] opened 2020-02-23 18:48 UTC
In the current 1.2.0-alpha05 as of today, MaterialDatePicker offers no way to override the default date format for the text input dates, but instead opts for an automatic computation. However, the result does not work for our target users, hence it would be great if there was a way to override the default.
For more context, I'm working on an app that targets users in Nigeria, and the general date format is **dd/MM/yyyy**. However `UtcDates.getTextInputFormat()` returns a date formatter with **M/d/yy** which is very confusing to users, especially because month and day positions have been swapped.

`1.1.0-alpha09` introduced a way to override this default pattern by simply overriding the `mtrl_picker_text_input_date_format` string resource.
However, for some other reasons in #695, this ability was removed in `1.2.0-alpha02`

**Desired solution**
To be able to specify a pattern in the MaterialDatePicker builder, which altogether avoids overriding the private string resource. The resource could also be made public so it may be overridden like was possible in `1.1.0-alpha09`

**Considered alternative**
Forcing default locale to `en_NG`, but this doesn't really give the desired result. The format was still `M/d/yy`

**Comment by drmrbrewer** [comment] 2020-07-27 10:00
@kingsleyadio is it still not possible to override the default date format?

**Comment by drmrbrewer** [comment] 2020-07-27 10:02
Duplicate of https://github.com/material-components/material-components-android/issues/774 ?

**Comment by dsn5ft** [comment] 2020-07-29 18:21
Closing as duplicate of https://github.com/material-components/material-components-android/issues/774

**Closed by dsn5ft** 2020-07-29 18:21 UTC
Labels: feature request
