### ISSUE TITLE
[Crash] No compoment related: Crash when calling getLocales() on API level <= 19

### ISSUE THREAD

**Issue by Alexey-Verkhovsky** [material-components/material-components-android#2059] opened 2021-02-11 14:44 UTC
**Description:** 
In version 1.3.0 there is a bug that causes a fatal crash, that cannot be handled with try/catch construction. 
Looks like the library inserts a new locale, that cannot be parsed on old API levels.
The stacktrace is attached.
[stacktrace.txt](https://github.com/material-components/material-components-android/files/5966151/stacktrace.txt)

Also when running on newer API levels the code runs fine, but in comparison to version 1.2.1 there is a one new locale:
![изображение](https://user-images.githubusercontent.com/72796626/107651142-39752100-6c90-11eb-8209-e9cf088f4001.png)

**Expected behavior:** No crashes, `getLocales()` method simply returns an array of locales.

**Source code:** 
```

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getResources().getAssets().getLocales(); // <- The crash happens here
    }
}
```

**Android API version:** <=19

**Material Library version:** 1.3.0

**Device:** Emulators with API levels 16-19

**Comment by consp1racy** [comment] 2021-02-13 09:36
Hi, you may want to [file a bug in Android Gradle Plugin](https://issuetracker.google.com/issues/new).

You don't want to go around all libraries and figure out which one started using new features, that happen to not be compatible with whatever setup you have. If there is a feature that your min SDK isn't compatible with, AGP should strip it and let you know.

**Comment by drchen** [comment] 2021-11-03 18:02
It looks like the issue has been fixed in newer library versions? Feel free to reopen it if it's still reproducible.

**Closed by drchen** 2021-11-03 18:02 UTC
Labels: bug
