### ISSUE TITLE
[TextView] Emoji larger than the TextView

### ISSUE THREAD

**Issue by iboalali** [material-components/material-components-android#782] opened 2019-11-20 21:24 UTC
**Description:** When I set a _TextView_ to be full screen with the text fitting as much as possible in it, and set one and only one emoji glyph as text, the sides of the emoji glyph gets rendered outside of the _TextView_. This happens only in Portrait mode.

![device-2019-11-20-215843_small](https://user-images.githubusercontent.com/5447995/69278459-ab240380-0be2-11ea-9fd2-53f908ee3a57.png)

**Expected behavior:** The emoji glyph to be rendered inside the _TextView_

![device-2019-11-20-220105_small](https://user-images.githubusercontent.com/5447995/69278478-b37c3e80-0be2-11ea-91a7-d8f5f1a4cc88.png)

My workaround was, to add one space character before and one after the emoji glyph. The result is as seen in the image above.

**Source code:** 
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.material.textview.MaterialTextView
            android:id="@+id/text"
            style="@style/Widget.MaterialComponents.TextView"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:background="?attr/colorSurface"
            android:gravity="center"
            android:maxLines="1"
            app:autoSizeMaxTextSize="500sp"
            app:autoSizeMinTextSize="32sp"
            app:autoSizeTextType="uniform"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```

**Android API version:** 
Target SDK 29
Min SDK 21

**Material Library version:** 
material:1.1.0-beta02 and material:1.2.0-alpha02

**Device:** 
* Emulator 29.2.1-5889189 on Android 10
* Pixel 3XL on Android 10

**Comment by hunterstich** [comment] 2019-11-26 15:12
Hey there,

Thanks for taking the time to create an issue. I had a look at this and it appears that this behavior is reproducible in the framework `android.widget.TextView`. Since MaterialTextView is just a thin wrapper around TextView, would you mind filing a bug with the Android framework?

The correct component to file a bug would be here - https://issuetracker.google.com/issues?q=status:open%20componentid:192715
For more info on filing bugs on Android with issuetracker, see https://source.android.com/setup/contribute/report-bugs

Going ahead and closing this in favor of tracking on issuetracker!

**Closed by hunterstich** 2019-11-26 15:12 UTC
Labels: bug

**Comment by iboalali** [comment] 2019-12-18 20:59
For reference here is the link to the Google issue tracker:
https://issuetracker.google.com/issues/145803853
