### ISSUE TITLE
Generate apks from aab with bundletool with error: failed to deserialize resources.pb: unknown type 'macro'

### ISSUE THREAD

**Issue by LinMingkui** [material-components/material-components-android#3168] opened 2023-01-06 06:34 UTC
**Description:** 
When I upgrade Material from 1.6.1 to 1.7.0, I can run and pack APK normally, but the packed AAB is problematic and cannot generate apks and can not update to Google Play.

```
C:\Users\lin\AppData\Local\Temp\8722851090609859796\proto.apk: error: failed to deserialize resources.pb: unknown type 'macro'.
C:\Users\lin\AppData\Local\Temp\8722851090609859796\proto.apk: error: failed to load APK.
[BT:1.4.0] Error: Command '[C:\Users\lin\AppData\Local\Temp\AutoValue_BuildApksCommand7367736904129931534\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\lin\AppData\Local\Temp\8722851090609859796\binary.apk, C:\Users\lin\AppData\Local\Temp\8722851090609859796\proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[C:\Users\lin\AppData\Local\Temp\AutoValue_BuildApksCommand7367736904129931534\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\lin\AppData\Local\Temp\8722851090609859796\binary.apk, C:\Users\lin\AppData\Local\Temp\8722851090609859796\proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.model.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
        at com.android.tools.build.bundletool.model.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
        at com.android.tools.build.bundletool.model.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:41)
        at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:122)
        at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:101)
        at com.android.tools.build.bundletool.io.SplitApkSerializer.writeToDisk(SplitApkSerializer.java:68)
        at com.android.tools.build.bundletool.io.SplitApkSerializer.writeSplitToDisk(SplitApkSerializer.java:42)
        at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addSplitApk(ApkSetBuilderFactory.java:106)
        at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:461)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:225)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
**Version**
```
Android Studio Dolphin | 2021.3.1 Patch 1
Material Library version: 1.7.0
bundletool version: 1.13.2
compileSdk: 33
minSdk: 21
targetSdk: 31
Gradle version: 7.4.2
Gradle Plugin version: 7.2.0
```

**Comment by leofirespotter** [comment] 2023-01-08 02:41
Seconded, happening to me as well
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/[REDACTED]/src/bundletool.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
/tmp/9467326442166004902/proto.apk: error: failed to deserialize resources.pb: unknown type 'macro'.
/tmp/9467326442166004902/proto.apk: error: failed to load APK.
[BT:0.10.3] Error: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[/tmp/3512084736080895049/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/9467326442166004902/binary.apk, /tmp/9467326442166004902/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
java.lang.RuntimeException: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[/tmp/3512084736080895049/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/9467326442166004902/binary.apk, /tmp/9467326442166004902/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
	at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:59)
	at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitForAll(ConcurrencyUtils.java:42)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:582)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.serializeApks(ApkSerializerManager.java:180)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.populateApkSetBuilder(ApkSerializerManager.java:101)
	at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:229)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:110)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:524)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: java.util.concurrent.ExecutionException: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[/tmp/3512084736080895049/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/9467326442166004902/binary.apk, /tmp/9467326442166004902/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.android.tools.build.bundletool.io.ConcurrencyUtils.waitFor(ConcurrencyUtils.java:49)
	... 10 more
Caused by: com.android.tools.build.bundletool.model.Aapt2Command$Aapt2Exception: Command '[/tmp/3512084736080895049/output/linux/aapt2, convert, --output-format, binary, -o, /tmp/9467326442166004902/binary.apk, /tmp/9467326442166004902/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
	at com.android.tools.build.bundletool.model.Aapt2Command$CommandExecutor.execute(Aapt2Command.java:62)
	at com.android.tools.build.bundletool.model.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:36)
	at com.android.tools.build.bundletool.io.ApkSerializerHelper.writeToZipFile(ApkSerializerHelper.java:159)
	at com.android.tools.build.bundletool.io.ApkSerializerHelper.writeToZipFile(ApkSerializerHelper.java:144)
	at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDiskInternal(StandaloneApkSerializer.java:88)
	at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDiskAsUniversal(StandaloneApkSerializer.java:61)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addStandaloneUniversalApk(ApkSetBuilderFactory.java:136)
	at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:391)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:184)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by afohrman** [comment] 2023-01-10 01:59
Thanks for reporting. Could you please see if it compiles without using bundletool? That would help determine whether the issue is related to bundletool.

**Comment by LinMingkui** [comment] 2023-01-10 02:21
> Thanks for reporting. Could you please see if it compiles without using bundletool? That would help determine whether the issue is related to bundletool.

Thank you for your reply, are you talking about this? This can be installed directly.

![image](https://user-images.githubusercontent.com/47204593/211446993-f5f08f47-8d4f-41af-8036-dc03ef11da72.png)

**Comment by drchen** [comment] 2023-01-25 16:59
@pekingme do you have any ideas about this?

**Comment by darrentaft** [comment] 2023-01-31 13:11
You're using a VERY old version of Bundletool there (1.4.0 - Feb 2021).  Upgrade to the latest version (1.13.2) and your issues will disappear.  I've just been through this myself (I was on 1.5.0).

**Comment by drchen** [comment] 2023-01-31 20:31
Thanks @darrentaft. I'll close the issue since upgrading bundletool seems fixing the issue. 

Please feel free to reopen this if it still happens with the latest bundletool version.

**Closed by drchen** 2023-01-31 20:31 UTC
Labels: bug, Issue: Build Failure

**Comment by est7** [comment] 2024-12-26 11:00
I used the latest bundletool and still had this problem. When I downgraded to 1.6, the problem disappeared.

--------------
[BT:1.17.2] Error: Command '[/var/folders/40/4t56wpcs13xd4y7px3xd6tz40000gn/T/AutoValue_BuildApksCommand16133303820340007664/output/macos/aapt2, convert, --output-format, binary, -o, /var/folders/40/4t56wpcs13xd4y7px3xd6tz40000gn/T/5998736134771563229/binary2.apk, /var/folders/40/4t56wpcs13xd4y7px3xd6tz40000gn/T/5998736134771563229/proto1.apk]' didn't terminate successfully (exit code: 134). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[/var/folders/40/4t56wpcs13xd4y7px3xd6tz40000gn/T/AutoValue_BuildApksCommand16133303820340007664/output/macos/aapt2, convert, --output-format, binary, -o, /var/folders/40/4t56wpcs13xd4y7px3xd6tz40000gn/T/5998736134771563229/binary2.apk, /var/folders/40/4t56wpcs13xd4y7px3xd6tz40000gn/T/5998736134771563229/proto1.apk]' didn't terminate successfully (exit code: 134). Check the logs.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:71)
        at com.android.tools.build.bundletool.androidtools.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:38)
        at com.android.tools.build.bundletool.androidtools.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:71)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertAndOptimizeProtoApk(Aapt2ResourceConverter.java:158)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter$ResourceConverter.convertResourcesToBinary(Aapt2ResourceConverter.java:125)
        at com.android.tools.build.bundletool.io.Aapt2ResourceConverter.lambda$convert$3(Aapt2ResourceConverter.java:105)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by just-wanghai** [comment] 2025-01-16 07:01
@LinMingkui have you found a solution yet ?

**Comment by LinMingkui** [comment] 2025-01-16 07:30
> [@LinMingkui](https://github.com/LinMingkui) have you found a solution yet ?

@just-wanghai  As for me, it was caused by a conflict between Material version 1.6.1 and above and the [AabResGuard](https://github.com/bytedance/AabResGuard) plugin. Therefore, I have to stick to using Material version 1.6.1.

**Comment by just-wanghai** [comment] 2025-01-16 07:37
> > [@LinMingkui](https://github.com/LinMingkui) have you found a solution yet ?
> 
> [@just-wanghai](https://github.com/just-wanghai) As for me, it was caused by a conflict between Material version 1.6.1 and above and the [AabResGuard](https://github.com/bytedance/AabResGuard) plugin. Therefore, I have to stick to using Material version 1.6.1.

thanks

**Comment by est7** [comment] 2025-01-16 08:38
> > > [@LinMingkui](https://github.com/LinMingkui?rgh-link-date=2025-01-16T07%3A37%3A41.000Z) have you found a solution yet ?
> > 
> > 
> > [@just-wanghai](https://github.com/just-wanghai?rgh-link-date=2025-01-16T07%3A37%3A41.000Z) As for me, it was caused by a conflict between Material version 1.6.1 and above and the [AabResGuard](https://github.com/bytedance/AabResGuard?rgh-link-date=2025-01-16T07%3A37%3A41.000Z) plugin. Therefore, I have to stick to using Material version 1.6.1.
> 
> thanks

upgrade aabresguard buildtools version should be resolve it
