### ISSUE TITLE
[Other] Broken Activity transitions after upgrading to 1.10.0

### ISSUE THREAD

**Issue by danijel-vrecic** [material-components/material-components-android#3644] opened 2023-10-19 07:37 UTC
**Description:** 
Activity transitions are broken after upgrading google-material from 1.9.0 to 1.10.0
Restarting the app does not help to fix the issue. Restarting the phone or downgrading to 1.9 fix the problem.

**Expected behavior:** 
After update, the transitions should remain intact.

**Source code:**
Theme `Theme.MaterialComponents.DayNight.NoActionBar.Bridge`
```
  override fun startActivity(intent: Intent?) {
      super.startActivity(intent)
      overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_left);
  }

  override fun finish() {
      super.finish()
      overridePendingTransition(R.anim.slide_in_right, R.anim.slide_out_right);
  }
```

**Minimal sample app repro:** 
Branch `master` has `com.google.android.material:material:1.9.0`
Branch `maintenance/upgrade-google-material-to-1-10-0` has `com.google.android.material:material:1.10.0`
https://github.com/danijel-vrecic/override-pending-transition-issue

**Android API version:**
API 28, API 34

**Material Library version:** com.google.android.material:material:1.10.0

**Device:**
- Huawei P10 (API 28) 
- Pixel 6 (API 34)
- Emulators (API28, API34)

**Comment by vensantai** [comment] 2023-10-24 04:03
I got the same issue, too.

**Comment by dsn5ft** [comment] 2023-10-25 14:39
@danijel-vrecic @vensantai can you provide some more detail on what the issue is and how specifically the transitions become broken after updating to 1.10.0?

Do the transitions crash your app? Do they animate in a strange way? Do they not run at all?

Also as a test, can you try using `Theme.Material3.DayNight.NoActionBar` instead of `Theme.MaterialComponents.DayNight.NoActionBar.Bridge` to see if that helps?

Thank you!

**Comment by danijel-vrecic** [comment] 2023-10-26 06:52
@dsn5ft I tried `Theme.Material3.DayNight.NoActionBar` and got the same result. The problem is that the window is animated in a strange way.

Emulator API28
[Screen_recording_20231026_084918-material_1-10-0.webm](https://github.com/material-components/material-components-android/assets/5602357/7ad46679-6970-4bc7-a0da-f4e3a54889a9)

**Comment by Chozzle** [comment] 2023-11-14 23:55
Is this related to this issue? https://issuetracker.google.com/issues/300310597

**Comment by nikclayton** [comment] 2023-11-18 13:12
@dsn5ft Please can you add this problem to the release notes for 1.10.0, so that other people facing the same problem don't have to go digging through issue reports, and people who haven't upgraded yet can make a more informed decision about whether they should.

**Comment by dsn5ft** [comment] 2023-11-27 15:33
@nikclayton good idea, updated https://github.com/material-components/material-components-android/releases/tag/1.10.0

Also closing out this issue as the root cause is not within the Material library, based on http://issuetracker.google.com/issues/300310597#comment6.

**Closed by dsn5ft** 2023-11-27 15:33 UTC
Labels: bug, Need more info, Feature: Transition
