### ISSUE TITLE
BottomSheetDialogFragment ShapeAppearance bug

### ISSUE THREAD

**Issue by Zeliret** [material-components/material-components-android#325] opened 2019-04-24 09:39 UTC
I have discovered a strange behavior. If I set this snipped as a shapeAppearanceOverlay to the bottom sheet, I get a glitch. When I try to close the bottom sheet by dragging to the bottom I can see that rounded corners animate out for a moment and return back after that. 
I think it should be rounded all the way while I'm dragging the dialog and became square only in full height mode, shouldn't it?
```xml
<style name="ShapeAppearanceOverlay.App.BottomSheet.Modal" parent="ShapeAppearanceOverlay.MaterialComponents.BottomSheet.Modal">
        <item name="cornerSizeTopLeft">@dimen/custom_corner_large</item>
        <item name="cornerSizeTopRight">@dimen/custom_corner_large</item>
    </style>
```

**Comment by gsajith** [comment] 2019-04-24 22:09
Could you please provide some more context for this bug? Specifically, any relevant XML for this bottom sheet, as well as any code you're using to programmatically initialize, modify, or show the bottom sheet.

**Comment by Zeliret** [comment] 2019-04-25 07:49
@gsajith Sure. Thanks for the replying.

My bottom sheet superclass. I just inherit it and show with ::show(childFragmentManager)
```kotlin
abstract class BaseBottomSheetDialogFragment
    : BottomSheetDialogFragment(),
        HasSupportFragmentInjector {
    @Inject
    lateinit var viewModelFactory: ViewModelFactory
    @Inject
    lateinit var childFragmentInjector: DispatchingAndroidInjector<Fragment>

    protected open val skipCollapsed = false

    override fun onAttach(context: Context) {
        AndroidSupportInjection.inject(this)
        super.onAttach(context)
    }

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        val dialog = super.onCreateDialog(savedInstanceState) as BottomSheetDialog
        dialog.setOnShowListener { dialogInterface ->
            val d = dialogInterface as BottomSheetDialog
            val bottomSheet = d.findViewById<View>(com.google.android.material.R.id.design_bottom_sheet) as FrameLayout
            val behavior = BottomSheetBehavior.from(bottomSheet)
            behavior.skipCollapsed = skipCollapsed
            if (skipCollapsed)
                behavior.state = BottomSheetBehavior.STATE_EXPANDED

//            d.window?.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION)
//            d.window?.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
//            d.window?.navigationBarColor = ContextCompat.getColor(requireContext(), R.color.white)
        }

        return dialog
    }

    override fun supportFragmentInjector(): AndroidInjector<Fragment>? {
        return childFragmentInjector
    }

    override fun onSaveInstanceState(outState: Bundle) {
        StateSaver.saveInstanceState(this, outState)
        super.onSaveInstanceState(outState)
    }

    @CallSuper
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        StateSaver.restoreInstanceState(this, savedInstanceState)
    }

    protected open fun getTagLabel(): String {
        return TAG
    }

    fun show(manager: FragmentManager) {
        show(manager, getTagLabel())
    }

    companion object {
        private const val TAG = "dialog"
    }
}
```

The layout:
```xml
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

    </data>

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.core.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fillViewport="true"
            android:scrollbarStyle="insideOverlay"
            android:scrollbars="vertical">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:padding="@dimen/padding_16">
            </androidx.constraintlayout.widget.ConstraintLayout>
        </androidx.core.widget.NestedScrollView>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</layout>
```

Video: https://www.evernote.com/l/AmiRaAtmJ-FHdI2Maaw_lP3F63_E5HErteY

**Comment by hrach** [comment] 2019-04-25 08:03
Having exactly the same issue 👍

**Comment by melaniegoetz** [comment] 2019-04-25 22:13
Hi @Zeliret, thanks for bringing this to our attention! Someone internally noticed a similar issue and is contributing a fix -- I'll comment back here when that fix is synced out!

**Comment by Zeliret** [comment] 2019-08-01 12:02
Alpha09 is here but still no fix for that issue ;(

**Comment by ogoons** [comment] 2019-08-29 14:09
I need this. Please fix it as soon as possible.

**Comment by touficbatache** [comment] 2019-09-01 16:00
Happens to me too!

**Comment by h6ah4i** [comment] 2020-01-02 07:36
Same here. I'm using v1.2.0-alpha03 😭

**Comment by ThanosFisherman** [comment] 2020-03-13 11:52
I'm facing a similar issue where when I click a list item on a rounded corner of BottomSheetDialogFragment then the rounded corners turn into a squared corners. See the video attached.

https://drive.google.com/open?id=1iO8ljZXsHEOkttsoQo9lgm0cyIaTivvr

**Comment by acegishniz** [comment] 2020-05-27 18:08
I have the same issue!

**Comment by keciciler** [comment] 2020-11-13 09:01
Same issue whenever the bottom sheet content takes focus, round corners have gone completely.

**Comment by darwind** [comment] 2021-01-19 18:05
Any news on this bug?

It seems like the issue is a bit different in the current version of the Material Design library (1.3.0-rc01), where the rounded only gets removed (animated) when the bottom sheet reaches its full height.

When the bottom sheet reaches its full height on its own (the user release the bottom sheet before it's at full heigh), the rounded/cut corners doesn't transform, however if you swipe the bottom sheet all the way to the full height of the bottom sheet, the corners transform.

See the attached video: https://drive.google.com/file/d/1D2lrW7axTEE-aPqElmiq9SXXBKgRKPrt/view

**Comment by Jnthndjgr** [comment] 2022-01-20 12:30
Any update on this? Still encountering the issue

**Comment by drchen** [comment] 2022-04-18 19:53
I couldn't manage to reproduce it. Can you provide more details like screen recording and your theme/style settings if it's still reproducible?

**Comment by drchen** [comment] 2022-05-04 19:29
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-05-04 19:29 UTC
Labels: bug, Need more info, Widget: BottomSheet
