### ISSUE TITLE
[Material Button] icon is gone when CircularProgressDrawable is set

### ISSUE THREAD

**Issue by javaherisaber** [material-components/material-components-android#1209] opened 2020-04-15 06:00 UTC
**Description:** when using CircularProgressDrawable as icon for MaterialButton
icon is gone
interestingly when setting this drawable to ExtendedFloatingActionButton (which is child of MaterialButton), it works fine

**Source code:**
``` kotlin
import androidx.swiperefreshlayout.widget.CircularProgressDrawable

val drawable = CircularProgressDrawable(this)
drawable.setColorSchemeColors(ContextCompat.getColor(this, R.color.colorPrimary))
drawable.strokeWidth = 8f
button.icon = drawable
drawable.start()
```

**Android API version:** 28 Pie

**Material Library version:** 1.1.0

**Device:** Google Pixel 3A

**Comment by dsn5ft** [comment] 2020-04-21 18:39
Can you send a sample app that reproduces this issue, with some screenshots as well?

**Comment by javaherisaber** [comment] 2020-04-22 06:32
Sure.
[Here](https://github.com/javaherisaber/CircularProgressDrawable) is the sample app
## Default icon
<img src="https://github.com/javaherisaber/CircularProgressDrawable/raw/master/img/default.png" width="256" height="455">

## Loading icon
<img src="https://github.com/javaherisaber/CircularProgressDrawable/raw/master/img/loading.png" width="256" height="455">

**Comment by liakiq** [comment] 2020-04-22 06:35
Same problem here, a workaround is having fix iconsize in your materialButton.

**Comment by javaherisaber** [comment] 2020-04-22 06:53
@liakiq 
having fixed iconsize worked for me.
I wonder this could be handled internally, like how it's handled for ExtendedFloatingActionButton

**Comment by drchen** [comment] 2021-10-06 15:55
It's a duplicate of #2095 and has been fixed. : )

**Closed by drchen** 2021-10-06 15:55 UTC
Labels: bug
