### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by Winghin2517** [material-components/material-components-android#58] opened 2018-01-30 16:46 UTC
Hello

The current build is failing. Here is the error message when I load this into Android Studio. Please can you fix. Thanks

Error:Project with path ':lib:lib/java:lib/java/android:lib/java/android/support:lib/java/android/support/design:lib/java/android/support/design/bottomsheet' could not be found in project ':lib'.

Consult IDE log for more details (Help | Show Log)

**Comment by coofeeing** [comment] 2018-02-12 01:49
me too...did you solved?

**Comment by YmlMark** [comment] 2018-02-14 18:16
Also having this problem.

**Comment by SheepYang1993** [comment] 2018-02-23 03:36
add code in setting.gradle
```include ':lib:java:android:support:design:bottomsheet'
include ':lib:java:android:support:design:dialog'
include ':lib:java:android:support:design:floatingactionbutton'
include ':lib:java:android:support:design:typography'
include ':lib:java:android:support:design:color'
include ':lib:java:android:support:design:card'

**Comment by PrashantShendage** [comment] 2018-02-23 17:10
Okay Thanks

**Comment by dsn5ft** [comment] 2018-03-20 11:17
Closing as duplicate of #51

**Closed by dsn5ft** 2018-03-20 11:17 UTC
