### ISSUE TITLE
[CollapsingToolbarLayout] Expanded text uses width of collapsed text

### ISSUE THREAD

**Issue by outofdate** [material-components/material-components-android#2318] opened 2021-07-30 12:13 UTC
**Description:** If you met some specific conditions like text size of collapsed and expanded text sizes, then you get some strange behavior of expanded text.
By design requirements we have collapsed text size of `22sp` and expanded `28sp`. Margin left and right are `16dp`.
Also we have three menu icons shown in toolbar and back arrow.
In this configuration we get that expanded text is almost of the size of collapsed text. If you change collapsed text size to something like `16sp` - then it looks normal, but with `22sp` expanded text is shrinked. 
![image](https://user-images.githubusercontent.com/3635135/127650142-d4b5d835-7f21-4cc5-8ec2-2e0ad9ba76a6.png)

**Source code:** 
on my humble opinion problem caused somewhere in method `calculateUsingTextSize` of `CollapsingTextHelper` class.
![image](https://user-images.githubusercontent.com/3635135/127650618-729ad4f8-52a8-4359-968b-4e6781b9b3ac.png) 
**Material Library version:** 1.2.1 to 1.5.0-alpha 

also i made repo with this the sample of the problem https://github.com/outofdate/collapsing_toolbar_bug. 

Thank you!

**Comment by drchen** [comment] 2021-11-09 21:15
Hi, thanks for the report. I'll close this as a duplicate of #2459 

I made a fix and it's pending for internal review now. : )

**Closed by drchen** 2021-11-09 21:15 UTC
Labels: bug, Widget: TopAppBar

**Comment by outofdate** [comment] 2021-11-23 08:25
Well, it's not duplicate. #2459 is duplicate.
