### ISSUE TITLE
[Accessibility] Why the recommended touch target size on android devices is 48 x 48 dp? 

### ISSUE THREAD

**Issue by iamrafan** [material-components/material-components-android#1279] opened 2020-05-07 00:34 UTC
Hi Team,

Can you please help us understand the rationale behind Material design's touch target guidelines recommending making touch targets at least 48 x 48 dp on Android devices, despite the WCAG and iOS guidance mentioning 44 x 44 CSS pixels and 44 x 44 pt respectively?

**Comment by wcshi** [comment] 2020-05-07 16:41
https://material.io/design/usability/accessibility.html#layout-and-typography:

"Touch targets are the parts of the screen that respond to user input. They extend beyond the visual bounds of an element. For example, an icon may appear to be 24 x 24 dp, but the padding surrounding it comprises the full 48 x 48 dp touch target.

For most platforms, consider making touch targets at least 48 x 48 dp. A touch target of this size results in a physical size of about 9mm, regardless of screen size. The recommended target size for touchscreen elements is 7-10mm. It may be appropriate to use larger touch targets to accommodate a larger spectrum of users.
Note that on iOS, 44 x 44 pt is the recommended touch target. For platform-specific implementation guidance, visit the developer resource page."

This is not a bug, so removing the label.

**Comment by iamrafan** [comment] 2020-05-08 16:50
Can you please elaborate further on why 48 instead of 44?  

Also, can you please let us know if there are any plans to align to 44 in the future as per WCAG recommendation? Having consistency in the size requirements might help the teams using shared components for both Android and iOS apps

**Comment by wcshi** [comment] 2021-10-10 17:03
Thank you for your feedback. We will investigate this further.

**Comment by WalidMaata** [comment] 2021-10-18 19:35
we should always use 48x48 dp at least for all clickable components ? for example for button and chip ?

**Comment by wcshi** [comment] 2021-12-20 20:14
@WalidMaata that's correct

**Comment by hellohj** [comment] 2022-03-11 22:20
I'm also curious about the rationale. Looking forward to hearing some details. Thank you.

**Comment by codeledger** [comment] 2022-07-18 01:16
Android was released in 2008 and did mention in older documentation touch target size of 48 dp = 9 mm as originally quoted in StackOverflow post [Android Minimum Button Height: 48dp = 9mm?](https://stackoverflow.com/q/10112780/295004). I don't see any mention of target size in WCAG until [WCAG 2.1](https://www.w3.org/TR/WCAG21/) which was published in 2018. While the standard was probably informed by development in mobile browsing, the size on Android carries over from Android's inception.

**Comment by drchen** [comment] 2022-08-18 14:57
Hey folks, thanks everyone for providing your insights/questions. 

I'm sorry that I think the info mentioned in https://material.io/design/usability/accessibility.html#layout-and-typography is all we have. Also it's following Android's design guideline. : )

**Closed by drchen** 2022-08-18 14:57 UTC
Labels: Awaiting Design Feedback, Issue: Accessibility, Issue: Design
