### ISSUE TITLE
[MaterialDatePicker] Month Name Language is not correct

### ISSUE THREAD

**Issue by akshayzee** [material-components/material-components-android#2710] opened 2022-05-18 11:55 UTC
**Description:** I had set the locale to english language with country India. But, in the MaterialDatePicker dialog, only the month name is coming in different language.

<img width="435" alt="Screenshot 2022-05-18 at 5 04 46 PM" src="https://user-images.githubusercontent.com/103482141/169030509-5f37f921-eae3-4312-8c5e-9664452ce6bc.png">

**Expected behavior:** The month name should by in the correct language as with other components in the dialog like cancel/ok/select date etc.

**Source code:** 
```kt
val picker = MaterialDatePicker.Builder.datePicker().build()
picker.show(activity.supportFragmentManager, "TAG")
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** API 32 

**Material Library version:** "com.google.android.material:material:1.4.0"

**Device:** Pixel XL

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by akshayzee** [comment] 2022-05-18 12:26
closing this issue

**Comment by pekingme** [comment] 2022-06-03 22:43
This is very odd. I don't think MDC lib manage any string translation about Month. It could be a bug in framework as we invoke [this](https://github.com/material-components/material-components-android/blob/1fe1618fca91f9431b82c60fa8a7a2e1f18d83cd/lib/java/com/google/android/material/datepicker/DateStrings.java#L36). 

Anyway, I'm not able to reproduce this now. I'm closing this issue. If it's still observed on your end, feel free to reopen.

**Closed by pekingme** 2022-06-03 22:43 UTC
Labels: bug, Widget: DatePicker, Issue: Internationalization
