### ISSUE TITLE
[CollapsingToolbarLayout] Showing padding bottom in ImageView

### ISSUE THREAD

**Issue by burhankhanzada** [material-components/material-components-android#885] opened 2020-01-08 11:54 UTC
**Description:**
When using `android:fitsSystemWindows="true"` and `android:adjustViewBounds="true"` together for `ImageView` in `CollapsingToolbarLayout` its give padding to `ImageView` at bottom

**Expected behavior:**
![Screenshot_1578649721](https://user-images.githubusercontent.com/18241005/72143796-333fb180-33b9-11ea-8b09-780e29271b25.png)

**Current behavior:**
![Screenshot_1578483416](https://user-images.githubusercontent.com/18241005/71975591-2b0b3900-3236-11ea-82f4-f0a72d99d264.png)

**Source code:**
`<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <androidx.core.widget.NestedScrollView
        android:id="@+id/nestedScrollView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <include
            android:id="@+id/include_bundle_detail_layout"
            layout="@layout/include_bundle_detail_layout" />

    </androidx.core.widget.NestedScrollView>

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBarLayout"
        style="@style/Widget.Base.AppBarLayout"
        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsingToolbarLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="true"
            app:contentScrim="?attr/colorPrimarySurface"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:titleEnabled="false">

            <ImageView
                android:id="@+id/imageView_bundleOfferImage"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:adjustViewBounds="true"
                android:fitsSystemWindows="true"
                android:scaleType="centerCrop"
                android:visibility="gone"
                app:layout_collapseMode="parallax"
                tools:ignore="ContentDescription"
                tools:src="@drawable/playstore_feature_graphic"
                tools:visibility="visible" />

            <View
                android:id="@+id/view_image_upper_gradient"
                android:layout_width="match_parent"
                android:layout_height="96dp"
                android:background="@drawable/gradient_black_transparent"
                android:visibility="gone"
                app:layout_collapseMode="pin"
                tools:visibility="visible" />

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                style="@style/Widget.Base.Toolbar"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>

    </com.google.android.material.appbar.AppBarLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
`
**Android API version:**
29

**Material Library version:**
1.2.0-alpha03

**Device:**
All emulator and real devices

**Sample App:** https://github.com/burhankhanzada199888/CollapsingToolbarLayoutWithImageBugSample

**Comment by pekingme** [comment] 2020-01-08 20:28
Hi @burhankhanzada199888, thanks for reporting this. I need some clarification. The screenshot you put in "Expected behavior" has a blue area under the image. Is that the "padding" you mean? In which case, it should be "Actual behavior". If not, could you also put a screenshot of the actual behavior, or share a small sample project at your convenience?

**Comment by burhankhanzada199888** [comment] 2020-01-10 07:10
I have updated my first comment with sample app to demonstrate this issue

**Comment by nxtstep** [comment] 2021-01-19 22:06
+1

**Comment by nxtstep** [comment] 2021-01-19 22:07
@burhankhanzada did you find any solution/workaround for this?

**Comment by mayuri-kulkarni** [comment] 2021-06-02 11:11
+1

**Comment by burhankhanzada** [comment] 2021-06-02 20:34
Please [see](https://stackoverflow.com/questions/67812181/collapsingtoolbarlayout-showing-padding-bottom-in-imageview/67812182#67812182) this i have posted a solution that i have on stackoverflow

**Comment by drchen** [comment] 2021-09-30 18:38
It looks like a duplicate of https://github.com/material-components/material-components-android/issues/520. 

I think this has been fixed. Feel free to reopen the above issue if this is still reproducible. Thanks!

**Closed by drchen** 2021-09-30 18:38 UTC
Labels: bug

**Comment by v7lin** [comment] 2022-01-06 12:31
i have same issue with "com.google.android.material:material:1.4.0"
