### ISSUE TITLE
[BottomAppBar] Child view is gone when keyboard is opened

### ISSUE THREAD

**Issue by craftingmod** [material-components/material-components-android#564] opened 2019-09-04 14:32 UTC
**Description:** BottomAppBar's child view disappeared if keyboard is opened with activity's `android:windowSoftInputMode="adjustResize"` option. If you don't open keyboard then you can see green rect(child view). But if you open keyboard and activity was resized, you can't see green rect(child view) and that view's height became 0 height.

**Expected behavior:**
- Before keyboard open

![](https://github.com/craftingmod/BottomAppBarBug/raw/master/beforekeyboard.jpg)

- After keyboard open:

![](https://github.com/craftingmod/BottomAppBarBug/raw/master/afterkeyboard.jpg)

**Source code:** [github](https://github.com/craftingmod/BottomAppBarBug) - A simple project of screenshot

**Android API version:** 29

**Material Library version:** 1.1.0-alpha09

**Device:** [Razer Phone 2](https://forum.xda-developers.com/razer-phone-2)

```To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).```

**Comment by cketcham** [comment] 2019-10-16 20:34
I can't reproduce this. I think this bug may have been fixed with some changes made to how insets are handled. Can you try `1.1.0-beta01` to see if it's still an issue? If it is, please re open this bug and if you can add a sample project we can use to debug the issue, that would be helpful. thanks!

**Closed by cketcham** 2019-10-16 20:34 UTC
Labels: bug
