### ISSUE TITLE
[BottomAppBar] Bug with FloatingActionButton

### ISSUE THREAD

**Issue by NOS-AE** [material-components/material-components-android#535] opened 2019-08-24 12:01 UTC
The BottomAppBar(with fab) is in a fragment, click fab then start another fragment with a edittext view inside, I click it and the soft keyboard shows. When returning to the fragment with BottomAppBar inside, I found that the fab has been translateY about 3 or 4 dp(positive), after seconds, it suddenly goes back to the original place...longer the keyboard stay more time the fab takes to go back to it's place

Phone: HUAWEI HONOR V9

SDK version: 28

Library version: 1.1.0-alpha09

**Comment by drchen** [comment] 2021-11-02 20:08
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:08 UTC
Labels: bug, Need more info
