### ISSUE TITLE
[Button] android:background not working

### ISSUE THREAD

**Issue by DreamerLeon** [material-components/material-components-android#889] opened 2020-01-09 07:54 UTC
**Description:** after I change my app them to `Theme.MaterialComponents.NoActionBar` , In my xml file `Button` label's `android:background="@drawable/login_btn_bg"`  not working,and I can't set others color、shape or selector,they are not work.

**Expected behavior:** `Button` label's `android:background=` can normal work , when I set my app them to `Theme.MaterialComponents.NoActionBar` or others Material thems

**Source code:** `    <style name="CommonAppTheme" parent="Theme.MaterialComponents.NoActionBar">
        
        <item name="colorPrimary">@color/common_colorPrimary</item>
        <item name="colorPrimaryDark">@color/common_colorPrimaryDark</item>
        <item name="colorAccent">@color/common_colorAccent</item>
        <item name="buttonStyle">@style/commonButtonStyle</item>
        <item name="materialButtonStyle">@style/commonButtonStyle</item>
    </style>`

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="commonButtonStyle" parent="Widget.MaterialComponents.Button">
        <item name="android:insetTop">0dp</item>
        <item name="android:insetBottom">0dp</item>
        <item name="android:insetLeft">0dp</item>
        <item name="android:insetRight">0dp</item>
        <item name="android:minHeight">0dp</item>
        <item name="android:textColor">@color/common_text_color</item>
    </style>
</resources>`
`        <Button
            android:id="@+id/btnLogin"
            android:layout_width="match_parent"
            android:layout_height="38dp"
            android:layout_marginLeft="31dp"
            android:layout_marginTop="61dp"
            android:layout_marginRight="31dp"
            android:background="@drawable/btn_bg"
            android:gravity="center"
            android:text="@string/common_immediately"
            android:textSize="15sp" />`
**Android API version:** Android 8.1

**Material Library version:** 1.0.0

**Device:** le pro 3

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by pekingme** [comment] 2020-01-09 23:48
Hi @DreamerLeon, could you try with a newer version of the library? If possible, please provide a sample app to reproduce this issue. It can help us to understand the problem and make a decision to resolve it faster. Thanks.

**Comment by DreamerLeon** [comment] 2020-01-10 01:25
> Hi @DreamerLeon, could you try with a newer version of the library? If possible, please provide a sample app to reproduce this issue. It can help us to understand the problem and make a decision to resolve it faster. Thanks.

New version(1.2.0-alpha03) also has this problem ,  I will write a demo Later on and post on github ,Thanks for your answer.

**Comment by DreamerLeon** [comment] 2020-01-10 01:59
> Hi @DreamerLeon, could you try with a newer version of the library? If possible, please provide a sample app to reproduce this issue. It can help us to understand the problem and make a decision to resolve it faster. Thanks.

[MDCIssueDemo](https://github.com/DreamerLeon/MDCIssueDemo)
This project can reproduce this issue.

**Comment by pekingme** [comment] 2020-01-10 20:37
Thanks @DreamerLeon for the demo. This is a known issue. Currently the solution to this is to set the background programmatically. We are working on a solution for the xml attribute. Hope that it can land soon.

**Comment by DreamerLeon** [comment] 2020-01-14 08:54
> Thanks @DreamerLeon for the demo. This is a known issue. Currently the solution to this is to set the background programmatically. We are working on a solution for the xml attribute. Hope that it can land soon.

Thx for your answer!

**Comment by hamed8080** [comment] 2020-01-25 06:11
hope next beta fix this . I need add boilerplate code for background!

**Comment by ImAreeb** [comment] 2020-03-08 20:02
I am using latest version  **com.google.android.material:material:1.2.0-alpha05.**
This problem still exists. I can't override button color using background attribute in XML

**Comment by diegoalvis** [comment] 2020-03-26 23:21
Any update of this?
I changed my app theme due crash using **Material TabLayout** but this broke all the buttons and TextInputLayouts so I rolled back. Looking forward for next beta sadly can't use the TabLayout yet.

**Comment by DreamerLeon** [comment] 2020-04-01 01:24
@diegoalvis This problem still exits,I hope someone can fix it

**Comment by wcshi** [comment] 2020-04-01 14:26
Fixed in https://github.com/material-components/material-components-android/commit/309d71860f0686137277915fb09e7502cbafc2b4

**Closed by wcshi** 2020-04-01 14:26 UTC
Labels: bug

**Comment by AlejandroHCruz** [comment] 2020-04-08 14:37
Hi, could you make a new alpha release with this fix? It's quite important for me and others :)
Thank you!
@wcshi

**Comment by pejman-74** [comment] 2020-04-11 13:24
Stills' waiting.🙄

**Comment by AlejandroHCruz** [comment] 2020-04-13 18:22
@pejman-74 In case it's useful, my workaround is to use a FrameLayout with an ImageButton and a (Material)TextView

**Comment by wcshi** [comment] 2020-04-13 18:44
Stay tuned, a new alpha release is coming this week.

**Comment by KidusMT** [comment] 2020-04-17 13:46
it worked well with the update on: `com.google.android.material:material:1.2.0-alpha06`

**Comment by AlejandroHCruz** [comment] 2020-04-17 19:18
Friday release! 🤩🙈

**Comment by NehaDShakya** [comment] 2020-04-20 19:42
Updated to : com.google.android.material:material:1.2.0-alpha06
Can only change button back ground to #00000000.

**Comment by nicoqueijo** [comment] 2020-04-22 03:16
Still not working for me.

```
<Button
     android:id="@+id/button_one"
     style="@style/ButtonStyle"
     android:text="@string/button_one" />
```

```
<style name="ButtonStyle">
     <item name="android:textSize">32sp</item>
     <item name="android:textColor">@drawable/background_button_text_color</item>
     <item name="android:background">@drawable/background_button</item
</style>
```

**background_button.xml:**
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white" android:state_pressed="true" />
    <item android:drawable="@android:color/transparent" android:state_pressed="false" />
</selector>
```

**background_button_text_color.xml:**
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@android:color/black" android:state_pressed="true" />
    <item android:color="@android:color/white" android:state_pressed="false" />
</selector>
```


![](https://im4.ezgif.com/tmp/ezgif-4-cb718b03e125.gif)

I am getting a black background instead of white when the button is pressed. Not sure what I'm doing wrong. Any help? I am on 1.2.0-alpha06, btw.

**Comment by nickruddeni** [comment] 2020-04-22 12:31
Using `1.2.0-alpha06` and still can not override the `android:background` property with my own xml drawable. I'm using `Theme.MaterialComponents.DayNight`

**Comment by nicoqueijo** [comment] 2020-04-22 14:39
> Still not working for me.
> 
> ```
> <Button
>      android:id="@+id/button_one"
>      style="@style/ButtonStyle"
>      android:text="@string/button_one" />
> ```
> 
> ```
> <style name="ButtonStyle">
>      <item name="android:textSize">32sp</item>
>      <item name="android:textColor">@drawable/background_button_text_color</item>
>      <item name="android:background">@drawable/background_button</item
> </style>
> ```
> 
> **background_button.xml:**
> 
> ```
> <selector xmlns:android="http://schemas.android.com/apk/res/android">
>     <item android:drawable="@android:color/white" android:state_pressed="true" />
>     <item android:drawable="@android:color/transparent" android:state_pressed="false" />
> </selector>
> ```
> 
> **background_button_text_color.xml:**
> 
> ```
> <selector xmlns:android="http://schemas.android.com/apk/res/android">
>     <item android:color="@android:color/black" android:state_pressed="true" />
>     <item android:color="@android:color/white" android:state_pressed="false" />
> </selector>
> ```
> 
> ![](https://camo.githubusercontent.com/70ab01cae58762fd70b5de1fbd443f8f8b36597b/68747470733a2f2f692e696d6775722e636f6d2f53674c613435722e676966)
> 
> I am getting a black background instead of white when the button is pressed. Not sure what I'm doing wrong. Any help? I am on `1.2.0-alpha06`, btw.

Update: was able to get it working thanks to the help of a couple folks on [stackoverflow](https://stackoverflow.com/a/61366681/5906793).

**Comment by nicoqueijo** [comment] 2020-04-22 16:15
@nickruddeni Check the update on the bottom of my post.

**Comment by AdislanSaidov** [comment] 2020-04-24 15:49
the same problem. Using `1.2.0-alpha06 `, still not working

**Comment by AdislanSaidov** [comment] 2020-04-24 16:12
solved with `android:backgroundTint`

**Comment by dsn5ft** [comment] 2020-04-29 13:11
I think this is because we still set `backgroundTint` in our default `MaterialButton` style:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/values/styles.xml#L45

So if you are using a custom `android:background`, you have to make sure to null out `backgroundTint` (either `app:backgroundTint="@null"` or `app:backgroundTint="@empty"`), so that your custom background doesn't get tinted.

Or, if all you care about is the color of the button, then you can just use `app:backgroundTint` instead of `android:background`, but be sure to set it to a color selector like ours to handle disabled state:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/color/mtrl_btn_bg_color_selector.xml

**Comment by Bhavnaharitsa** [comment] 2020-05-11 04:19
> Still not working for me.
> <Button
>      android:id="@+id/button_one"
>      style="@style/ButtonStyle"
>      android:text="@string/button_one" />
> 
> <style name="ButtonStyle">
>      <item name="android:textSize">32sp</item>
>      <item name="android:textColor">@drawable/background_button_text_color</item>
>      <item name="android:background">@drawable/background_button</item
> </style>
> 
> background_button.xml:
> <selector xmlns:android="http://schemas.android.com/apk/res/android">
>     <item android:drawable="@android:color/white" android:state_pressed="true" />
>     <item android:drawable="@android:color/transparent" android:state_pressed="false" />
> </selector>
> 
> background_button_text_color.xml:
> <selector xmlns:android="http://schemas.android.com/apk/res/android">
>     <item android:color="@android:color/black" android:state_pressed="true" />
>     <item android:color="@android:color/white" android:state_pressed="false" />
> </selector>
> 
> 
> I am getting a black background instead of white when the button is pressed. Not sure what I'm doing wrong. Any help? I am on 1.2.0-alpha06, btw.
> Update: was able to get it working thanks to the help of a couple folks on stackoverflow.

Worked like magic, thank you for telling +1

**Comment by DreamerLeon** [comment] 2020-05-11 05:53
> solved with `app:backgroundTint`

Still not working for me , I set a drawable

**Comment by Bhavnaharitsa** [comment] 2020-05-11 07:24
> > solved with `app:backgroundTint`
> 
> Still not working for me , I set a drawable

It doesn't work for drawables, you can only use to change colors and it clears says "tint" :)

**Comment by AlejandroHCruz** [comment] 2020-05-11 08:03
It didn't work for drawables for me either, see my hack comment above
________________________________
De: V Bhavna Haritsa <notifications@github.com>
Enviado: lunes, 11 de mayo de 2020 9:24
Para: material-components/material-components-android <material-components-android@noreply.github.com>
CC: Alejandro H. Cruz <j.alejandro_1093@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [material-components/material-components-android] [Button] android:background not working (#889)


solved with app:backgroundTint

Still not working for me , I set a drawable

It doesn't work for drawables, you can only use to change colors and it clears says "tint" :)

**Comment by codejunk1e** [comment] 2020-05-12 12:09
This didn't work for me :-(

**Comment by codejunk1e** [comment] 2020-05-12 12:25
> I think this is because we still set `backgroundTint` in our default `MaterialButton` style:
> 
> https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/values/styles.xml#L45
> 
> So if you are using a custom `android:background`, you have to make sure to null out `backgroundTint` (either `app:backgroundTint="@null"` or `app:backgroundTint="@empty"`), so that your custom background doesn't get tinted.
> 
> Or, if all you care about is the color of the button, then you can just use `app:backgroundTint` instead of `android:background`, but be sure to set it to a color selector like ours to handle disabled state:
> 
> https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/color/mtrl_btn_bg_color_selector.xml

This worked like a charm! Thanks

**Comment by wolasoft** [comment] 2020-05-16 09:04
> I think this is because we still set `backgroundTint` in our default `MaterialButton` style:
> 
> https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/values/styles.xml#L45
> 
> So if you are using a custom `android:background`, you have to make sure to null out `backgroundTint` (either `app:backgroundTint="@null"` or `app:backgroundTint="@empty"`), so that your custom background doesn't get tinted.
> 
> Or, if all you care about is the color of the button, then you can just use `app:backgroundTint` instead of `android:background`, but be sure to set it to a color selector like ours to handle disabled state:
> 
> https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/button/res/color/mtrl_btn_bg_color_selector.xml

This Worked like a charm too! Thanks

**Comment by Cloud9Clone** [comment] 2020-06-12 23:41
Yes, the provided solution with the Tint works. However, the issue with the drawable is still active. So the only option I guess is to change it programmatically if you want to perform color change on pressed button. (I'm talking about the normal Button from the AndroidX package, not the Material one).

**Comment by yabee5566** [comment] 2020-07-03 04:27
Set background with xml drawable still not work. 
If someone wants a dirty workaround, just use TextView instead of Button.

**Comment by OhhhThisVarun** [comment] 2020-07-11 13:18
Yes, it's not working. Do it programmatically 

```
 myButton.background = ContextCompat.getDrawable(requireContext(), R.drawable.my_background)
```

**Comment by cutiko** [comment] 2020-07-20 22:36
I'm having the same problem for checkbox, setting the properties to `@null` or `@empty` didn't worked, try with `app` and `android` for `backgroundTint` and `buttonTint`, using an _old theme_ solved it for me:

```
    <CheckBox
       ...
        android:button="@drawable/custom_drawable"
        android:theme="@style/Theme.AppCompat.Light" />
```

Why is this closed?

**Comment by ajinkyaw** [comment] 2020-07-22 04:23
Mentioned workaround by @wolasoft  works well, 
but it is giving issues to other components. 
Please re-open so that it gets more stable.

**Comment by dsn5ft** [comment] 2020-07-22 20:47
@cutiko If you want to use a custom drawable for CheckBox and disable the Material tinting, can you try setting `app:useMaterialThemeColors="false"`?

**Comment by mecoFarid** [comment] 2020-08-12 08:00
> Fixed in [309d718](https://github.com/material-components/material-components-android/commit/309d71860f0686137277915fb09e7502cbafc2b4)

@wcshi 

Using:
Library version: `1.2.0`
Android version: `29`
Device: `Pixel 3 emulator`

Still not working

**Comment by wcshi** [comment] 2020-08-12 15:20
@mecoFarid please share a sample app and explain the expected result and observed result.

**Comment by mecoFarid** [comment] 2020-08-12 16:47
@wcshi Here is the sample project. https://github.com/mecoFarid/MaterialCompButton

**Observed result:**
Button background color is reset to `colorPrimary` which is purple in the sample project.

**Steps to get the expected result:**
1. In `styles` extend `Theme.AppCompat.Light.DarkActionBar` instead of `Theme.MaterialComponents.Light.NoActionBar`
2. `activity_main.xml` use `Button` instead of `com.google.android.material.button.MaterialButton`
You'll see a button with a red background which is the expected result.

**Comment by wcshi** [comment] 2020-08-12 16:58
Did you follow the steps in https://github.com/material-components/material-components-android/issues/889#issuecomment-629613444?

**Comment by mecoFarid** [comment] 2020-08-12 18:44
@wcshi It worked, thank you. I love how android SDK is becoming more about painful, hidden workarounds than a smooth development kit.

**Comment by madcodding** [comment] 2020-08-17 23:24
Ok i have the ultimate solution  for drawables as backgrounds app:shapeAppearance="@drawable/yourdrawable" and set another with android:background="@drawable/yourdrawable" this fixed my buttons with drawables as backgrounds

**Comment by varunam** [comment] 2020-08-27 16:07
It's working in latest release 1.2.0

**Comment by DreamerLeon** [comment] 2020-08-28 06:57
> It's working in latest release 1.2.0

I still need set `app:backgroundTint="@null"` , else drawable background will not working

**Comment by whilson03** [comment] 2020-09-05 22:12
still not working

Library version: 1.2.0

**Comment by smithaaron** [comment] 2020-09-08 14:15
This doesn't work for me on 1.2.1. This is what I've tried:

`<com.google.android.material.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab_filter"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/material_design_spacing_large"
            app:backgroundTint="@color/sort_fab_bg_selector"
            android:layout_gravity="end"
            app:maxImageSize="56dp"
            app:srcCompat="@drawable/ic_search_and_filter" />`

`<com.google.android.material.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab_filter"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/material_design_spacing_large"
            app:backgroundTint="@null"
            android:background="@color/sort_fab_bg_selector"
            android:layout_gravity="end"
            app:maxImageSize="56dp"
            app:srcCompat="@drawable/ic_search_and_filter" />`

Either way, the button is just black and the drawable isn't visible.

**Comment by ymarian** [comment] 2020-09-08 14:34
@smithaaron this bug is for MaterialButton not for FloatingActionButton

**Comment by CamiloVega** [comment] 2020-09-14 22:35
@ymarian I think they are related. I just updated to Material 1.2.1, and FAB was working like a charm, after the update it is not working properly

**Comment by Veisy** [comment] 2020-10-05 21:25
This problem continues, 
version 1.3.0-alpha03

**Comment by ABHISHEK-AMRUTE** [comment] 2020-10-14 05:11
If you are concerned only about the `android:background` and not `android:backgroundTint` (as in my case), the following worked for me.
Set both `android:background` and `android:backgroundTint` programmatically
Here the `android:backgroundTint` is set to colour which I have used in my custom background.
~~~
        button1.setBackground(ContextCompat.getDrawable(getContext(),R.drawable.create_lobby_button));
        button2.setBackground(ContextCompat.getDrawable(getContext(),R.drawable.join_lobby_button));
        button1.setBackgroundTintList(this.getResources().getColorStateList(R.color.colorPrimaryDark));
        button2.setBackgroundTintList(this.getResources().getColorStateList(R.color.navigationbar_color));
~~~

**Comment by IamAashis** [comment] 2020-12-18 07:39
> solved with `app:backgroundTint`

Ya thanks it works

**Comment by hemantlakhotia204** [comment] 2021-02-01 13:34
Change Theme in styles from Theme.MaterialComponents.DayNight.DarkActionBar to Theme.MaterialComponents.DayNight.DarkActionBar.Bridge
It worked for me!

**Comment by HenryMacharia254** [comment] 2021-02-04 13:05
I changed from Button to com.google.android.material.button.MaterialButton and all was well in that the theme colors were applied.

**Comment by BelalElhawary** [comment] 2021-03-13 15:38
fix it by change Theme.MaterialComponents.NoActionBar to Theme.MaterialComponents.NoActionBar.Bridge and it will work

**Comment by KavinduDissanayake** [comment] 2021-03-13 17:44
just use for xml 

 app:backgroundTint="@color/purple_700"

that's it and it will be change the  button color  

No need to change the Theme it should be 
"Theme.MaterialComponents.DayNight.NoActionBar" Or  "Theme.MaterialComponents.DayNight.NoActionBar"

**Comment by cholidridwan** [comment] 2021-03-20 22:55
> Change Theme in styles from Theme.MaterialComponents.DayNight.DarkActionBar to Theme.MaterialComponents.DayNight.DarkActionBar.Bridge
> It worked for me!

this also works for me, didn't need to add more xml / java code
Thanks

**Comment by yash10019coder** [comment] 2021-06-04 16:28
still not works for me

#
this is code for my button
`<Button
        android:id="@+id/button"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="32dp"
        android:layout_marginLeft="32dp"
        android:layout_marginEnd="32dp"
        android:layout_marginRight="32dp"
        android:gravity="center|left"
        android:background="@drawable/background_button"
        android:text="SEND"
        app:layout_constraintBottom_toTopOf="@+id/button3"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/editTextTextPersonName" />`
this is the background code for my button

`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle"

    >
    <solid android:color="#200540"

        />
    <corners
        android:radius="100dp"
        />
    <stroke android:color="@color/purple_500"
        android:width="10dp"
        />

</shape>`

**Comment by Swavis** [comment] 2021-06-06 18:51
In my case it works - `btn.setBackgroundTintMode(null);`

**Comment by Fs0ci3ty19** [comment] 2021-06-19 21:53
> To work around this issue, do one of the following:
> 
> * Add `app:backgroundTint="@null"` in xml or programmatically - `btn.setBackgroundTintMode(null);`
> * Change Theme `Theme.MaterialComponents.DayNight.DarkActionBar` to `Theme.MaterialComponents.DayNight.DarkActionBar.Bridge`
> 
> Both the solutions works fine.

Theme.MaterialComponents.DayNight.DarkActionBar.Bridge
This one worked for me Thanks!!

**Comment by ginagigo123** [comment] 2021-07-23 09:29
Theme.MaterialComponents.DayNight.DarkActionBar 
change to 
Theme.AppCompat.DayNight.DarkActionBar works for me!

**Comment by riverorange78** [comment] 2022-07-01 03:59
c# ms vs 2022
Theme.MaterialComponents.Light.DarkActionBar
change to
Theme.MaterialComponents.Light.DarkActionBar.Bridge works for me!

**Comment by Anshul-Jangra** [comment] 2022-07-28 01:18
In my app I used gradient on button, it runs but sometimes button is shown in normal button color. Can anyone tell me what is the problem?

**Comment by Naught33** [comment] 2022-07-28 05:47
Well the problem is that when I use drawables it looks okay on the xml design but once I install the app on my phone the color of the button goes back to default, althought the shape stays as I want it but the color ...

**Comment by WangberlinT** [comment] 2022-10-11 10:04
still exist on 1.5.0

**Comment by Anshul-Jangra** [comment] 2022-10-11 10:09
Thanks but it's resolved
