### ISSUE TITLE
[Slider] New style from new MediaPlayer (Tiramisu)

### ISSUE THREAD

**Issue by wennerryle** [material-components/material-components-android#3378] opened 2023-05-05 15:34 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a custom slider style that looks like a slider from the new MediaPlayer

**Describe alternatives you've considered**
Maybe the new component for it's, with methods for stop and start animation

**Additional context**
https://9to5google.com/2023/03/08/android-14-dp2-media-player/

**Comment by leticiarossi** [comment] 2023-05-05 15:55
Marking this as a duplicate of https://github.com/material-components/material-components-android/issues/2690

**Closed by leticiarossi** 2023-05-05 15:55 UTC
Labels: feature request
