### ISSUE TITLE
[Chip] Layout preview window does not render Chip elements

### ISSUE THREAD

**Issue by pappbence96** [material-components/material-components-android#895] opened 2020-01-10 14:00 UTC
**Description:** 
After upgrading to version `1.2.0-alpha03` the layout preview window does not render Chip elements. They are drawn completely blank without any background, stroke, text or icons. This is solely a visual issue with the preview window as Chips are properly rendered when running on a device.
The preview window messages show the following render problems:

- `Path.op()` not supported
- `java.awt.geom.IllegalPathStateException`: missing initial moveto in path definition

These elements are properly rendered when using version `1.2.0-alpha02`

**Expected behavior:** 
Chips should be rendered properly in the preview window.
This is using `1.2.0-alpha03`
<img src="https://user-images.githubusercontent.com/22445736/72157569-8d8c4280-33b8-11ea-921d-662783661154.png" width="500">
This is using `1.2.0-alpha02`
<img src="https://user-images.githubusercontent.com/22445736/72157598-9d0b8b80-33b8-11ea-9afc-85cded6f9bb5.png" width="500">

**Source code:**
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

        <com.google.android.material.chip.Chip
            android:layout_height="wrap_content"
            android:layout_width="wrap_content"
            android:text="This chip should be visible"
            android:theme="@style/Widget.MaterialComponents.Chip.Choice"/>

</LinearLayout>
```

**Android API version:** 
23

**Material Library version:** 
1.2.0-alpha03

**Device:**
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019

**Comment by pappbence96** [comment] 2020-01-10 14:02
This part of the stack trace could show where in the library the exception originates from:
```
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at ...
	at android.graphics.Path.close(Path.java:508)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)
	at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1142)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:940)
	at com.google.android.material.chip.ChipDrawable.draw(ChipDrawable.java:559)
	at android.graphics.drawable.DrawableWrapper.draw(DrawableWrapper.java:227)
	at ...
```

**Comment by joshuamking-driveclutch** [comment] 2020-01-15 16:43
And buttons and TextInputLayouts render like this: 
![image](https://user-images.githubusercontent.com/44779725/72452901-4c1adf00-378c-11ea-9453-5fafcb9729c4.png)

**Comment by letmewearshoes** [comment] 2020-01-16 05:42
same problem

**Comment by a1573595** [comment] 2020-01-24 12:50
same problem

**Comment by pappbence96** [comment] 2020-01-29 15:05
The issue is still present in 1.2.0-alpha04

**Comment by someAndroidDeveloper** [comment] 2020-02-18 16:24
have same issue with "textInputLayouts".
I'm using AndroidX with material component theme. everything works fine at runtime but the 
layout preview is not working right

I've nearly tested all versions, none of them show up correctly.

**Comment by joshuamking-driveclutch** [comment] 2020-02-18 16:59
@someAndroidDeveloper Last I tried, `1.2.0-alpha02` still worked fine in the layout preview. You may have to run a `./gradlew clean` and re-sync your project. The other reason is a dependency you have may have a dependency on >= `1.2.0-alpha03`. This is not recommended as it could cause unknown issues, but if you want to force a version, I've found this to work (put it in your projects build.gradle, not the modules'):

```

allprojects {
    repositories {
          . . .
     }
     . . .

    configurations {
        all {
            resolutionStrategy.eachDependency { details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.material') {
                    details.useVersion '1.2.0-alpha02'
                }
            }
        }
    }
}
```

Also for those wondering, updating to Android Studio 3.6 RC 3 doesn't help. 😔

**Comment by someAndroidDeveloper** [comment] 2020-02-20 15:30
@joshuamking-driveclutch 
I tried the `1.2.0-alpha02` it works somehow but the preview dies after running the app or switching to other layouts and it showed me some class cast exceptions.
Right now I've downgraded the material library to `1.0.0` which I was using before, it's all normal now.

**Comment by joshuamking-driveclutch** [comment] 2020-02-20 19:50
@someAndroidDeveloper Well hopefully this will be fixed in the next version.. I can't downgrade right now. 😔 
FYI: 1.1.0 is stable so you should be able to use that just fine.

**Comment by wcshi** [comment] 2020-02-20 22:18
Could you please try using Android Studio 4 preview 2 or newer? I am unable to reproduce the issue.

**Comment by wcshi** [comment] 2020-02-22 15:51
Filed an issue against the Android Studio team, please follow progress or provide additional information here: https://issuetracker.google.com/issues/150040392

**Comment by joshuamking-driveclutch** [comment] 2020-02-24 16:20
I just confirmed: This is occurring in `Android Studio 3.6 RC 3` and `Android Studio 3.5.3`. It does not appear to be happening in `Android Studio 4.0 Canary 9`.

**Comment by xmanu** [comment] 2020-02-28 12:24
Still occurring in Android Studio 3.6...

**Comment by joshuamking-driveclutch** [comment] 2020-02-28 13:11
Good news is it's fixed in Android Studio 4.0 Beta 1. I'm using that with no issues right now.

**Closed** 2020-02-28 17:54 UTC
Labels: bug

**Comment by nelsonnedes** [comment] 2020-04-11 20:07
Android Studio 3.6.2
Build #AI-192.7142.36.36.6308749, built on March 18, 2020

Estou usando esta versão mas esta dandos o mesmo erros.

Exemplo:

1°)  Erro:
Path.op() not supported

2°)  Erro:
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition   at java.awt.geom.Path2D$Double.needRoom(Path2D.java:1193)   at java.awt.geom.Path2D.closePath(Path2D.java:1877)   at android.graphics.Path_Delegate.close(Path_Delegate.java:824)   at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)   at android.graphics.Path.nClose(Path.java:-1)   at android.graphics.Path.close(Path.java:513)   at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)   at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)   at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1160)   at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:945)   at com.google.android.material.chip.ChipDrawable.draw(ChipDrawable.java:559)   at android.graphics.drawable.DrawableWrapper.draw(DrawableWrapper.java:240)   at android.graphics.drawable.RippleDrawable.drawContent(RippleDrawable.java:821)   at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:678)   at android.view.View.drawBackground(View.java:21671)   at android.view.View.draw_Original(View.java:21435)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:21417)   at android.view.View.draw_Original(View.java:21317)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21089)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4388)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)   at android.view.View.draw_Original(View.java:21315)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21089)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4388)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)   at android.view.View.draw_Original(View.java:21315)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21089)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4388)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)   at android.view.View.draw_Original(View.java:21446)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:21417)   at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1961)   at android.view.View.draw_Original(View.java:21317)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21089)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4388)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)   at android.view.View.draw_Original(View.java:21315)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21089)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4388)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)   at android.view.View.draw_Original(View.java:21315)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21089)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4388)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)   at android.view.View.draw_Original(View.java:21315)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21089)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4388)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)   at android.view.View.draw_Original(View.java:21446)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:21417) Copy stack to clipboard   Tip: Try to refresh the layout.

**Comment by yoobi** [comment] 2020-05-07 17:31
I got the same bug in `1.2.0-alpha06`

**Comment by wcshi** [comment] 2020-05-07 17:39
This is a bug in AS, please use AS 4.0 beta 1 or wait for it to become stable

**Comment by joshuamking-driveclutch** [comment] 2020-05-07 17:42
In my experience, you have to use AS 4.0+ AND beta build tools which sucks, but it does seem to work.. 😕

**Comment by kirkaDev** [comment] 2020-06-05 06:00
> same problem

my Chip components displayed like a checkboxes

`                <com.google.android.material.chip.Chip
                    android:id="@+id/chip2"
                    android:textSize="12sp"
                    style="@style/Widget.MaterialComponents.Chip.Filter"
                    app:chipIcon="@drawable/ic_launcher_background"
                    android:text="Take the pills"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"/>`

![chips](https://user-images.githubusercontent.com/8686389/83842149-b3c1ce80-a71b-11ea-9edd-4e7bede07762.jpg)

**Comment by Valexx55** [comment] 2020-06-18 11:40
Same problem using Android Studio 4.0. ChipGroup and Chips are not visible on preview. Need to deploy on physical device "to preview" :(

**Comment by wcshi** [comment] 2020-06-18 16:22
@Valexx55 could you please share a screenshot? Do you chips look like checkboxes?

**Comment by ptreitler** [comment] 2020-11-09 10:17
I still get this problem with v1.2.1. Chips are blank rectangles in the layout preview.
I get an error **Render Problem**:
```
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.awt.geom.Path2D$Double.needRoom(Path2D.java:1193)
	at java.awt.geom.Path2D.closePath(Path2D.java:1877)
	at android.graphics.Path_Delegate.close(Path_Delegate.java:824)
	at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)
	at android.graphics.Path.nClose(Path.java)
	at android.graphics.Path.close(Path.java:513)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)
	at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1160)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:945)
	at com.google.android.material.chip.ChipDrawable.draw(ChipDrawable.java:564)
	at android.graphics.drawable.DrawableWrapper.draw(DrawableWrapper.java:240)
	at android.graphics.drawable.RippleDrawable.drawContent(RippleDrawable.java:821)
	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:678)
	at android.view.View.drawBackground(View.java:21671)
	at android.view.View.draw_Original(View.java:21435)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:404)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:556)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:115)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:143)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:125)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$11(RenderTask.java:966)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wcshi** [comment] 2020-11-09 16:36
What version of Android Studio are you using @ptreitler i am able to see chip rendered correctly in AS 4.1 rc3

**Comment by ptreitler** [comment] 2020-11-09 21:28
@wcshi 
```
Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: CheckStyle-IDEA, com.github.jk1.ytplugin, org.intellij.plugins.markdown, org.jetbrains.kotlin, com.codota.csp.intellij, kotest-plugin-intellij, io.protostuff.protostuff-jetbrains-plugin, Dart, io.flutter
```

**Comment by kungpaogao** [comment] 2021-01-18 00:55
I'm also having the same issue with Android Studio 4.1.1 and Material 1.2.1. If I downgrade the Material library to 1.1.0, it renders without errors.

**Comment by wcshi** [comment] 2021-01-19 19:55
@kungpaogao could you please share a screenshot of what you are seeing in AS 4.1.1?

**Comment by kungpaogao** [comment] 2021-01-20 02:27
> @kungpaogao could you please share a screenshot of what you are seeing in AS 4.1.1?

Sure! Let me know if I'm just implementing something incorrectly.

![image](https://user-images.githubusercontent.com/11168401/105118805-12ff0400-5a9d-11eb-9af1-488fc6d698e5.png)

Here's the corresponding code:
```xml
<com.google.android.material.chip.ChipGroup
    android:id="@+id/dining_list_filter"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom|center_horizontal"
    android:layout_marginVertical="16dp"
    app:layout_collapseMode="none"
    app:selectionRequired="true"
    app:singleSelection="true">

    <com.google.android.material.chip.Chip
        android:id="@+id/chip_filter_all"
        style="@style/Flux.FilterChipStyle"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:text="@string/all" />

    <com.google.android.material.chip.Chip
        android:id="@+id/chip_filter_north"
        style="@style/Flux.FilterChipStyle"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:text="@string/north" />

    <com.google.android.material.chip.Chip
        android:id="@+id/chip_filter_west"
        style="@style/Flux.FilterChipStyle"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:text="@string/west" />

    <com.google.android.material.chip.Chip
        android:id="@+id/chip_filter_central"
        style="@style/Flux.FilterChipStyle"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:text="@string/central" />

</com.google.android.material.chip.ChipGroup>
```

**Comment by kungpaogao** [comment] 2021-01-22 03:55
Okay, I did some more digging, and it turns out that enabling "Use new Layout Rendering Engine" under the "Experimental" section in settings fixed it for me!!

This is the post that suggested the fix: https://stackoverflow.com/questions/64060759/render-problem-path-op-not-supported-in-latest-material-design-version

**Comment by kiquenet85** [comment] 2021-01-29 22:12
![image](https://user-images.githubusercontent.com/2637748/106332622-235d6e80-6255-11eb-9050-ec6c095e4307.png)

It seems the root reason is some attribute missing.
