### ISSUE TITLE
[MaterialCalendarGridView] NullPointerException in onDraw

### ISSUE THREAD

**Issue by tipa** [material-components/material-components-android#1338] opened 2020-05-28 10:32 UTC
**Description:** MaterialDatePicker crashes when using `setSelection` and `MaterialCalendar` as `materialCalendarFullscreenTheme`. The crash happens when swiping to the left after the dialog shows up.

**Source code:** 
```
<item name="materialCalendarFullscreenTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
```

```
MaterialDatePicker.Builder.dateRangePicker()
    .setSelection(new Pair(1485129600000l, 1590537600000l))
    .build()
    .show(getSupportFragmentManager(), "...");
```

**Expected behavior:** no crash

**Android API version:** 29

**Material Library version:** 1.2.0-alpha06

**Device:** Device on which the bug was encountered here
Galaxy A10
Pixel 2
P10 lite
OnePlus 7 Pro

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getRight()' on a null object reference
        at com.google.android.material.datepicker.MaterialCalendarGridView.onDraw(MaterialCalendarGridView.java:158)
        at android.view.View.draw(View.java:21609)
        at android.widget.AbsListView.draw(AbsListView.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.draw(View.java:21612)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
        at android.view.View.updateDisplayListIfDirty(View.java:20431)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21336)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.draw(View.java:21612)
        at com.android.internal.policy.DecorView.draw(DecorView.java:815)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:580)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:586)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:659)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3876)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3676)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2998)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1935)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8023)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
        at android.view.Choreographer.doCallbacks(Choreographer.java:986)
        at android.view.Choreographer.doFrame(Choreographer.java:902)```

**Comment by ph3mmy** [comment] 2020-06-01 23:03
I just experienced this on the android Emulator with API level 29 as well

**Comment by Armen101** [comment] 2020-06-04 06:10
I have the same issue. Please fix it ASAP

**Comment by Armen101** [comment] 2020-06-04 06:11
I use  ''com.google.android.material:material:1.1.0''

**Comment by Armen101** [comment] 2020-06-05 08:19
I also want to add a comment when I open the application with the French language everything is correct, it happens when I use English

**Comment by mikedirin** [comment] 2020-06-24 17:36
I see this bug as well. If a date range is set from today to three month later and open the calendar dialog, as soon as swipe to right fast the crash happens. Looks like it happens on 9, was not able to reproduce it on api 23

**Comment by ryancphil** [comment] 2020-06-26 20:02
I can reproduce this is `1.3.0-alpha01` as well.

**Comment by ymarian** [comment] 2020-06-30 17:56
Should be fixed please try on the latest snapshot

https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md

**Closed by ymarian** 2020-06-30 17:56 UTC
Labels: bug
