### ISSUE TITLE
[TextInputLayout] Having placeholderText breaks component height

### ISSUE THREAD

**Issue by keciciler** [material-components/material-components-android#1741] opened 2020-09-18 14:20 UTC
**Description:** When the TextInputLayout has placeholderText attribute, has focused, text is empty. If their container goes from visible to gone. Then when the container goes to visible state again textInputLayout will have 2x of it orginal height. Like at 2 lines of height.

**Expected behavior:** TextInputLayout should stay at the same height.

**Source code:** Nothing special just, 
 app:hintAnimationEnabled="false" & has app:placeholderText

**Android API version:** Tested on API 23

**Material Library version:** 1.2.0

**Device:** Samsun S10 Plus

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment] 2022-05-18 15:21
I can't reproduce the issue. Since it's pretty old and if it's still reproducible it should be very prominent, let me close this as obsolete. Please feel free to reopen it if it's still reproducible.

**Closed by drchen** 2022-05-18 15:21 UTC
Labels: bug, Widget: TextField
