### ISSUE TITLE
[Slider] Completly breaks android studio layout preview

### ISSUE THREAD

**Issue by johnnyzen** [material-components/material-components-android#992] opened 2020-02-06 20:26 UTC
This is a terrible and nasty bug, so please fix as soon as you can!

I cannot use "com.google.android.material.slider.Slider" as it stops Android Studio from showing layout previews on any other layout (even if it doesnt include com.google.android.material.slider.Slider)

The only way to get layout preview again, is to invalidate cache and restart android studio. If I go into the "infected" layout, it breaks the layout preview again

Using: com.google.android.material:material:1.2.0-alpha04'
With Android Studio: 

Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by giorgosneokleous93** [comment] 2020-02-06 20:50
There is also a ticket at issuetracker: https://issuetracker.google.com/issues/148890024

**Comment by johnnyzen** [comment] 2020-02-07 10:11
Thank you for your reply. I have commented on the link you sent. Is this more of a android studio issue?

**Comment by leticiarossi** [comment] 2020-02-07 16:08
Hi, this is a bug in Studio and should hopefully be fixed in the next Canary build.

Will close this bug as duplicate of https://github.com/material-components/material-components-android/issues/845

**Closed by leticiarossi** 2020-02-07 16:08 UTC
