### ISSUE TITLE
[BottomAppBar] FAB doesn't return to the right place after calling inputmethod

### ISSUE THREAD

**Issue by XayahSuSuSu** [material-components/material-components-android#3114] opened 2022-11-27 07:12 UTC
**Description:** 

https://user-images.githubusercontent.com/44322170/204123645-faf8a2b2-1777-4387-bc1b-7cdb33b32467.mp4

**Source code:**

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true">

        <!-- views -->

        <com.google.android.material.bottomappbar.BottomAppBar
            android:id="@+id/bottomAppBar"
            style="@style/Widget.Material3.BottomAppBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            android:fitsSystemWindows="true" />

        <com.google.android.material.floatingactionbutton.FloatingActionButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:contentDescription="@null"
            app:layout_anchor="@id/bottomAppBar"
            app:srcCompat="@drawable/ic_round_add" />

    </androidx.coordinatorlayout.widget.CoordinatorLayout>
</layout>
```

```
setSupportActionBar(binding.bottomAppBar)
```

**Android API version:** Android API 33

**Material Library version:** 1.8.0-alpha03

**Device:** Xiaomi 10 Ultra

**Comment by 1552980358** [comment] 2022-11-28 09:20
Maybe adding margins, with insets to FloatingActionButton can solve it

**Comment by drchen** [comment] 2022-11-28 16:47
According to what @1552980358 said, it looks like caused by the same issue as #3097.

I'll close this one for better tracking purpose.

**Closed by drchen** 2022-11-28 16:47 UTC
Labels: bug
