### ISSUE TITLE
[MaterialDatePicker] Crash on SingleDateSelector

### ISSUE THREAD

**Issue by green985** [material-components/material-components-android#2169] opened 2021-04-07 11:07 UTC
Crashlytics  show 

Attempt to read from field 'java.lang.Long com.google.android.material.datepicker.SingleDateSelector.a' on a null object reference

https://github.com/material-components/material-components-android/issues/608
https://github.com/material-components/material-components-android/issues/590

Possible duplicated but in new version of material design library, this bug still not solved.
Used material design version = "1.3.0-beta01"

I changed my library version to "1.4.0-alpha02" but I believed on new release, this bug not solved.

Devices version Android 9-10-11.

Thanks your attention and thanks for all your works.

**Comment by drchen** [comment] 2021-06-15 16:51
The crash looks not like a duplicate of #608 or #590. 

Can you provide the complete stack trace of the crash?

**Comment by green985** [comment] 2021-06-15 17:09
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.Long com.google.android.material.datepicker.SingleDateSelector.a' on a null object reference
       at com.google.android.material.datepicker.SingleDateSelector.getSelection(SingleDateSelector.java:1)
       at com.google.android.material.datepicker.MaterialDatePicker.getSelection(MaterialDatePicker.java:1)
       InputValidationExtKt.isBirthdayValid(InputValidationExtKt.java:35)
       at android.view.View.performClick(View.java:7161)
       at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:3)
       at android.view.View.performClickInternal(View.java:7138)
       at android.view.View.access$3500(View.java:811)
       at android.view.View$PerformClick.run(View.java:27419)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7520)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by drchen** [comment] 2021-06-15 17:36
Can you show me what InputValidationExtKt.isBirthdayValid() is doing?

The crash can happen when InputValidationExtKt.isBirthdayValid() is called before MaterialDatePicker.onCreate() is called, which cause the NPE.

**Comment by green985** [comment] 2021-06-15 17:47
fun TextInputLayout.isBirthdayValid(datePicker: MaterialDatePicker<Long>?): Boolean {
    

    var text = this.editText?.text.toString()
    if (text.isNullOrEmpty() || datePicker == null || datePicker.selection == null) {
        this.setHintWithError(R.string.birthdate_required, true)
        return false
    }

    try {
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        val netDate = Date(datePicker.selection!!)
        sdf.format(netDate)
    } catch (e: Exception) {
        this.setHintWithError(R.string.birthdate_required, true)
        return false
    }
    this.hint = resources.getString(R.string.birthday)
    this.error = null
    return true
}

**Comment by green985** [comment] 2021-06-15 17:49
Actually isBirthdayValid called after close date picker dialog, this is a register operation fragment and after register button this control called.

**Closed** 2021-06-28 20:03 UTC
Labels: bug

**Comment by green985** [comment] 2021-06-28 22:09
Thanks for your great work. 
Have a nice day :)
