### ISSUE TITLE
App crashes on API 19 because of Androidx (verifyerror)

### ISSUE THREAD

**Issue by ashish2442** [material-components/material-components-android#950] opened 2020-01-28 01:06 UTC
When trying to open bottom sheet app crashes. Using 
version 1.1.0 of androidx.appcompat 
version 1.0.0 of com.google.android.material
 
This started happening after androidx is introduced.
Please suggest a work android or fix for it.

W/dalvikvm: VFY: invoke-direct <init> must be on current class or super
W/dalvikvm: VFY:  rejecting opcode 0x70 at 0x0000
W/dalvikvm: VFY:  rejected Landroidx/appcompat/app/AppCompatDialog;.<init> (Landroid/content/Context;ZLandroid/content/DialogInterface$OnCancelListener;)V
W/dalvikvm: Verifier rejected class Landroidx/appcompat/app/AppCompatDialog;

 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxxx PID: 3945
    java.lang.VerifyError: androidx/appcompat/app/AppCompatDialog
        at com.google.android.material.bottomsheet.BottomSheetDialogFragment.onCreateDialog(BottomSheetDialogFragment.java:32)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by matpag** [comment] 2020-01-28 17:24
Are you using `androidx.fragment:fragment:1.1.0`? (just to be sure it's not a bug in the Fragment library itself)

**Comment by ashish2442** [comment] 2020-01-30 02:40
@matpag 
I tried still its same issue. 
One thing that if I remove proguard then its working. But if proguard is enabled it always crashes.

I tried keeping class in proguard like below but its of no use.

-keep class androidx.appcompat.** { *; }
-keep class com.google.android.material.**{*;}

**Comment by cketcham** [comment] 2020-02-07 20:54
@ashish2442 I wasn't able to reproduce it. I'm guessing it has something to do with the proguard flags you are using? Could create a small sample that we can use to reproduce the bug?

**Comment by mitcho85** [comment] 2020-06-05 23:06
Bump

This is crashing for me on a 4.4 device when I try to invoke **androidx.appcompat**.AlertDialog but it doesn't crash if I change to **android.app**.AlertDialog

**Comment by leticiarossi** [comment] 2020-08-25 20:38
could someone provide a sample app with the issue? this may be something to do with the androidx migration instead of with the material library itself

**Comment by matpag** [comment] 2020-08-27 13:20
Maybe this is related https://issuetracker.google.com/issues/161403944
A bug affecting AGP 4.1.X used with `minifyEnabled true`

If this is the problem they fixed it in `AS 4.2 Canary 8` (need to update to AGP 4.2.0-alpha08 or manually upgrade R8 to the latest version)

**Comment by drchen** [comment] 2022-02-07 20:44
I'll close the issue due to there's no new updates to the issue and I tend to believe it's been fixed. 
(And it doesn't look like a Material library issue either.)

**Closed by drchen** 2022-02-07 20:44 UTC
