### ISSUE TITLE
[MaterialDatePicker] Crash in dark theme

### ISSUE THREAD

**Issue by AbdulazizRasulbek** [material-components/material-components-android#2360] opened 2021-09-06 07:52 UTC
**Description:** MaterialDatePicker and MaterialTimePicker not shown and app crashes when theme is dark on the phone. In Light theme everything is fine

**Expected behavior:** DatePicker dialog should be shown.

**Android API version:** Android 10 API 29

**Material Library version:** Material Android Library version 1.5.0-alpha02

**Device:** Google pixel 3 API 29 emulator and Huawei P30 Lite API 29  

**Logcat:**

android.view.InflateException: Binary XML file line #23 in uz.anorgroup.doonk:layout/mtrl_picker_dialog: Binary XML file line #26 in uz.anorgroup.doonk:layout/mtrl_picker_header_title_text: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #26 in uz.anorgroup.doonk:layout/mtrl_picker_header_title_text: Error inflating class TextView
    Caused by: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x7f08009c
        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1395)
        at android.content.res.Resources.loadColorStateList(Resources.java:1170)
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:678)
        at android.widget.TextView.readTextAppearance(TextView.java:4035)
        at android.widget.TextView.<init>(TextView.java:1104)
        at android.widget.TextView.<init>(TextView.java:1004)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:102)
        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:93)
        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:88)
        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:83)
        at com.google.android.material.theme.MaterialComponentsViewInflater.createTextView(MaterialComponentsViewInflater.java:61)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1563)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:244)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1071)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1007)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1243)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1241)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
        at com.google.android.material.datepicker.MaterialDatePicker.onCreateView(MaterialDatePicker.java:209)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2961)
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:504)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1797)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1715)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1658)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by drchen** [comment] 2021-09-16 16:42
Looks like a duplicate of #2370. Let's move the discussion to that issue.

**Closed by drchen** 2021-09-16 16:42 UTC
Labels: bug
