### ISSUE TITLE
[ExtendedFloatingActionButton] Shrink broken in android light mode

### ISSUE THREAD

**Issue by surechand** [material-components/material-components-android#2537] opened 2022-01-25 19:53 UTC
**Description:** ExtendedFloatingActionButton shrink works differently in light/dark mode in android. In dark mode it works correctly, but in light mode it is moved to the right side.

Dark mode:
![image](https://user-images.githubusercontent.com/43911358/151048675-739f5e97-e14a-47e9-885b-fe7e9a994a7f.png)

Light mode:
![image](https://user-images.githubusercontent.com/43911358/151048729-63b9e686-da3f-43ba-b5ef-dfd1526f4911.png)

The same thing happens when i remove the text from element

![image](https://user-images.githubusercontent.com/43911358/151049302-44874758-ba2e-4a7c-a173-c01771d5a29d.png)

**Source code:** 

<com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton
        android:id="@+id/refresh_button"
        android:layout_gravity="end|bottom"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:contentDescription="@string/refresh"
        app:icon="@drawable/ic_baseline_refresh_24"
        app:iconTint="@color/primaryColor"
        android:backgroundTint="@color/button_background_tint"
        android:textColor="@color/button_text_color"
        android:text="@string/refresh"
        android:layout_margin="16dp" />

**Material Library version:** Material Android Library version 1.5.0

**Comment by pekingme** [comment] 2022-02-01 01:40
@surechand, thanks for filing the bug. It's hard to imagine the size related behavior inconsistent between light/dark themes. I highly doubt this is related to the switching between light/dark themes. However, the code piece you provided is not enough for investigation. Could you provide a sample app for reproduce? TIA

**Comment by drchen** [comment] 2022-03-03 19:34
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-03-03 19:34 UTC
Labels: bug, Need more info, Widget: FloatingActionButton
