### ISSUE TITLE
[TextInputLayout] Some attributes doesn't work

### ISSUE THREAD

**Issue by H43RO** [material-components/material-components-android#1308] opened 2020-05-19 11:23 UTC
**Description:** Some attributes  of TextInputLayout doesn't work about 'error'.

I find issue about here attributes.
`app:boxStrokeErrorColor="@color/errorStroke"`
` app:errorIconTint="@color/errorIconTint"`

It dosen't work well.
Is there anything else I can do to use these attributes?

**Expected behavior:** I think it have to change Error icon color, and stroke color when error occured.

**Source code:** The code snippet which is causing this issue. Please consider attaching a minimal sample app that reproduces the issue.

**Android API version:** 28

**Material Library version:** 1.2.0-alpha06

**Device:** All device

**Comment by leticiarossi** [comment] 2020-05-21 18:22
Can you provide your source code and screenshots of your issue? What exactly is not working when you use those attributes?

**Comment by H43RO** [comment] 2020-05-25 01:41
> Can you provide your source code and screenshots of your issue? What exactly is not working when you use those attributes?

This is my source code.
<img width="638" alt="스크린샷 2020-05-25 오전 10 38 38" src="https://user-images.githubusercontent.com/30336663/82770588-0f669f00-9e74-11ea-931d-771ac8104915.png">

But ` app:boxStrokeErrorColor="@color/errorStroke`
and `app:errorIconTint="@color/errorIconTint`

 these attributes dosen't working like this ScreenShots
![Screenshot_1590370772](https://user-images.githubusercontent.com/30336663/82770664-43da5b00-9e74-11ea-8f88-5b87cdde5d34.png)

**Comment by gabrielemariotti** [comment] 2020-08-15 07:36
I am **not** able to reproduce the same issue with `1.2.0` and `1.3.0-alpha02`.
Everything works fine.

App theme:
```
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
  <!-- ...  -->
</style>
```
Layout:
```
   <com.google.android.material.textfield.TextInputLayout
       android:id="@+id/text"
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:layout_marginTop="16dp"
       android:layout_marginRight="4dp"
       app:boxBackgroundColor="#F6F6F6"
       app:boxStrokeErrorColor="@color/error_icon_tint"
       app:errorIconTint="@color/error_icon_tint"
       android:hint="Label">

     <com.google.android.material.textfield.TextInputEditText
         android:layout_width="match_parent"
         android:layout_height="match_parent"
         android:inputType="number"
         />
   </com.google.android.material.textfield.TextInputLayout>
```

error selector:
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/colorSecondary" android:state_enabled="false"/>
    <item android:color="@color/green500Dark"/>
</selector>
```

<img width="300" alt="Schermata 2020-08-15 alle 09 30 14" src="https://user-images.githubusercontent.com/2583078/90307853-b76f8f80-deda-11ea-8076-5a54aecbbc45.png">
<img width="611" alt="Schermata 2020-08-15 alle 09 30 24" src="https://user-images.githubusercontent.com/2583078/90307855-b9395300-deda-11ea-9e31-b4a7b22f87df.png">

Tried also with a color instead of a selector and it works.

**Comment by upseliseev** [comment] 2021-01-13 23:17
I'm running into a similar error as OP on 1.3.0-beta01. I'm setting the `boxStrokeErrorColor` through a style though.

**Comment by upseliseev** [comment] 2021-01-14 16:41
Just in case anyone else comes here in confusion or in case @H43RO didn't resolve their issue: 
make sure that your EditText doesn't have a background. Removing that resolved this issue for me

**Comment by dexcell** [comment] 2021-09-18 08:27
not working on `com.google.android.material:material:1.4.0`

**Comment by drchen** [comment] 2021-10-01 14:04
Hi @dexcell, can you provide more info since the issue is a bit old and we cannot really reproduce it on our end?

**Comment by drchen** [comment] 2021-11-02 20:15
I'll close the issue due to no further info available. Feel free to reopen it if this is still reproducible.

**Closed by drchen** 2021-11-02 20:15 UTC
Labels: bug, Need more info

**Comment by ham8821** [comment] 2021-11-21 20:37
boxStrokeErrorColor attribute not working on material 1.4.0 either
![Screen Shot 2021-11-22 at 9 33 56 AM](https://user-images.githubusercontent.com/48266431/142777986-402b9870-4730-453e-8134-d1695473cdca.png)
![Screen Shot 2021-11-22 at 9 36 50 AM](https://user-images.githubusercontent.com/48266431/142778094-23ffec8e-d3dc-4f57-ac38-3a84ea232282.png)

the bottom stroke color is not changing to its correct color.

**Comment by natansalda** [comment] 2022-02-13 10:30
boxStrokeErrorColor attribute not working on material 1.5.0 for me either. I have this in my styles:
```
    <style name="RegistrationInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="boxCornerRadiusBottomStart">10dp</item>
        <item name="boxCornerRadiusBottomEnd">10dp</item>
        <item name="boxCornerRadiusTopStart">10dp</item>
        <item name="boxCornerRadiusTopEnd">10dp</item>
        <item name="boxStrokeColor">@color/registration_input_color</item>
        <item name="boxStrokeErrorColor">@color/registration_input_error_color</item>
        <item name="hintTextColor">@color/registration_input_color</item>
    </style>
```

I would expect the outline to go red when error is displayed, but instead it stays the same color as usual:
<img width="299" alt="Screenshot 2022-02-13 at 11 28 12" src="https://user-images.githubusercontent.com/25266290/153748991-476ef355-ef6f-455f-8b73-63fa71d3cc29.png">

While what I would expect is this in error state:
<img width="299" alt="Screenshot 2022-02-13 at 11 29 37" src="https://user-images.githubusercontent.com/25266290/153749025-ba704cfa-e142-4b2b-ae05-058aeaea1ee1.png">

Maybe I am missing something?

**Comment by mosmb** [comment] 2023-04-14 09:41
Why has it been closed?
Same issue with `1.7.0`

**Comment by mosmb** [comment] 2023-04-15 06:51
I can't use Material3 in my project so I don't know

**Comment by drchen** [comment] 2023-04-17 15:51
Is it reproducible with the latest library version under your settings?

**Comment by sandyadikaram** [comment] 2025-01-30 07:04
Still the same with 1.12.0
