### ISSUE TITLE
[Popup Menu Option]

### ISSUE THREAD

**Issue by PartapSBimrah** [material-components/material-components-android#751] opened 2019-11-10 13:10 UTC
**Description:** I got an issue in the alpha version especially when we use the dark theme in an Android application. Please let me know and see the bug in the screenshot. Everywhere is black but only the popup menu shows some extra width around the menu. 

**Material Library version:** Material Android Library version currently am using here (    `implementation` 'com.google.android.material:material:1.2.0-alpha01'`)

**Device:** Samsung Galaxy J6 Infinity 

**ScreenShot:** 
![Screenshot_20191110-183124_Ai](https://user-images.githubusercontent.com/39325207/68544458-68477c00-03e9-11ea-8a47-174381351b35.jpg)

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by leticiarossi** [comment] 2019-11-11 16:34
Could you provide the source code/a sample app where the issue happens?

**Comment by KanwarpartapSinghBimrah** [comment] 2019-11-12 02:16
You can see the popup white color where the word is written `Settings` in the above screenshot. There is background white and black. Also, its height isn't less. Its height is more. Have any solution

**Source:**

`override fun onCreateOptionsMenu(menu: Menu): Boolean {
        val inflater: MenuInflater = menuInflater
        inflater.inflate(R.menu.main_menu_activity, menu)
        return true
    }
    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        return when (item.itemId) {
            R.id.settings -> {
                this.startActivity(Intent(this, SettingsActivity::class.java))
                return true
            }
            else -> super.onOptionsItemSelected(item)
        }
    }`

**Comment by hunterstich** [comment] 2019-11-12 21:52
Hey there. It would be great to get a complete, minimal sample app (including themes, styles, etc) that reproduces this issue so we can investigate where this is coming from.

**Comment by KanwarpartapSinghBimrah** [comment] 2019-11-13 01:08
@hunterstich Thanks for writing to me. Sure Everything I had complete write on the above message. Now I will be writing the theme or style code which is using for dark mode.

```
<style name="DarkModeTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="colorPrimary">#212121</item>
        <item name="colorPrimaryDark">#FC031113</item>
        <item name="colorAccent">#2196F3</item>
        <item name="backgroundColor">#F3020202</item>
        <item name="cardBackground">#FC1B1B1B</item>
        <item name="textColor">#ffffff</item>
        <item name="tintColor">#E9000000</item>
        <item name="buttonColor">#2196F3</item>
        <item name="viewColor">#3A3A3A</item>
        <item name="android:windowAnimationStyle">@style/WindowAnimationTransition</item>
        <item name="iconTint">#ffffff</item>
        <item name="android:itemBackground">#F2000000</item>
        <item name="android:textColor">#ffffff</item>
        <item name="popupMenuStyle">@style/Widget.MaterialComponents.PopupMenu</item>
        <item name="actionOverflowMenuStyle">@style/Widget.MaterialComponents.PopupMenu.Overflow</item>
    </style>

Other rest of the code I already mentioned above including the dependency any other let me know.

`implementation 'com.google.android.material:material:1.2.0-alpha01'`

Menu.xml code is 

`<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <item android:id="@+id/settings"
        android:title="@string/settings"
        app:showAsAction="never"/>
</menu>`
```

**Comment by iamAliRaza** [comment] 2019-11-22 18:35
Hy i am also facing exact same issue ... in my case library version is stable 
**implementation 'com.google.android.material:material:1.0.0'**

**Comment by leonardosibela** [comment] 2020-02-24 12:42
I'm also facing the same problem. In my case the  stable library version is
also 1.0.0

**Comment by UserGhost411** [comment] 2020-03-15 15:21
try using  
` <item name="popupMenuBackground">#F2000000</item>`
on your style

**Comment by sictiru** [comment] 2020-11-16 03:35
Same issue with material 1.2.1 and `popupMenuBackground` didn't work in this case

**Comment by wcshi** [comment] 2020-11-16 15:39
Could someone please confirm whether the bug is in the latest 1.3.x version of the lib? Thanks!

**Comment by PartapSBimrah** [comment] 2020-11-18 01:30
> try using
> ` <item name="popupMenuBackground">#F2000000</item>`
> on your style

I have tried then asking you

**Comment by drchen** [comment] 2021-11-05 21:10
Is this still reproducible with the latest library version? If so, can you please provide a minimal example app so we can reproduce the issue on our end?

**Comment by drchen** [comment] 2021-11-23 18:23
I'll close the issue for now due to no further info available. Feel free to reopen it if you have more details to provide. Thanks!

**Closed by drchen** 2021-11-23 18:23 UTC
Labels: bug, Need more info
