### ISSUE TITLE
[CollapsingToolbarLayout] Not centering when maxLines is defined

### ISSUE THREAD

**Issue by necronet** [material-components/material-components-android#2340] opened 2021-08-18 20:22 UTC
**Description:** 

When `maxLines` is set to a value higher than 1, and `expandedTitleGravity` is center, the `CollapsingToolbarLayout` does not center the text exactly. I'm not sure if this is the intended behaviour but I'd not expect `maxLines` to change the positioning of the text.

**Source code:** 

To reproduce use this layout:

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/hubContainerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="200dp"
        >

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:expandedTitleGravity="center"
            app:expandedTitleMarginStart="48dp"
            app:expandedTitleMarginEnd="64dp"
            app:title="Center title"
            app:maxLines="2"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin"/>

        </com.google.android.material.appbar.CollapsingToolbarLayout>


    </com.google.android.material.appbar.AppBarLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

![Capture d’écran 2021-08-18 à 14 20 15](https://user-images.githubusercontent.com/99554/129966615-906a7ea2-6a20-4a29-89c5-59d433171b4b.png)

**Android API version:** Android API 30

**Material Library version:** `com.google.android.material:material:1.3.0`

**Device:** One Plus 6T

**Comment by drchen** [comment] 2021-09-30 18:50
I think it's a duplicate of https://github.com/material-components/material-components-android/issues/1276. Closing this to better track the issue.

**Closed by drchen** 2021-09-30 18:50 UTC
Labels: bug
