### ISSUE TITLE
[ExposedDropdownMenu] Can not remove ripple effect correctly

### ISSUE THREAD

**Issue by MrBzik** [material-components/material-components-android#3354] opened 2023-04-19 15:03 UTC
Hi. I am using AutoCompleteTextView inside OutlinedBox.ExposedDropdownMenu like this : 

```
    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/textInputLayout"
style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginHorizontal="20dp"
        android:layout_marginTop="30dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tvTitle"
        app:prefixTextAppearance="@style/dialogItemText">

        <AutoCompleteTextView
            android:id="@+id/actv"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:backgroundTintMode="multiply"
            android:hint="Order by"
            android:inputType="none"
            android:textAppearance="@style/dialogItemText" />
```

Just spent some hours trying to remove ripple effect when I am clicking on widget (not dropdown menu items). 
Problem is when I remove ripple effect outline box it is being drawn over the hint text. 

I can remove ripple by passing backgroundTintMode and backgroundTint to AutoCompleteTextView in XML. And programatically (also by setting backgroundTintList). It always results in box outline crossing hint text. 

Also drop down arrow ripple effect fires double time, which looks not so good, but I dont see how to remove that either.

**Comment by drchen** [comment] 2023-04-19 17:05
I don't think there's a way to completely remove clicking ripples on `AutoCompleteTextView`. It's basically hard-coded in `TextInputLayout`. 

You can probably try to override `?attr/colorControlHighlight` to transparent and check how it works. But I guess it will only make the ripple lighter instead of removing it. 

Anyhow, removing ripples is a bad UX and not recommended by the Material design guidelines. I'll close this as working as intended.

**Closed by drchen** 2023-04-19 17:05 UTC
Labels: bug
