### ISSUE TITLE
[TextInputEditText] Not displaying text while typing, only  displayed after tapping anywhere in the screen

### ISSUE THREAD

**Issue by KousalyaRaj** [material-components/material-components-android#2058] opened 2021-02-11 09:09 UTC
I have two field. Username and Password. When typing Username no issues works fine. When typing password text is not displayed. Only displayed after tapping anywhere else in screen or tapping done in keypad.

 

`<com.google.android.material.textfield.TextInputLayout
            android:id="@+id/password_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/username_layout"
            android:layout_marginTop="10dp"
            android:layout_marginBottom="15dp"
            app:hintEnabled="false"
            app:passwordToggleEnabled="false"
            app:passwordToggleTint="@color/white">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/login_password_input"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@id/login_username_input"
                android:layout_weight="0.0"
                android:drawableEnd="@drawable/password"
                android:background="@drawable/round_bg"
                android:hint="@string/login_password_hint"
                android:imeActionLabel="@string/action_done"
                android:imeOptions="actionDone"
                android:inputType="textPassword"
                android:maxLines="1"
                android:nextFocusDown="@+id/submit_btn"
                android:paddingStart="10dp"
                android:paddingLeft="10dp"
                android:text=""
                android:textColor="#FFFFFF"
                android:textColorHint="#FFFFFF"
                android:textCursorDrawable="@null"
                tools:ignore="RtlSymmetry" />
        </com.google.android.material.textfield.TextInputLayout>
`
I am setting password eye icon programatically like below,
`passwordLayout.setEndIconMode(TextInputLayout.END_ICON_PASSWORD_TOGGLE);
                passwordLayout.setEndIconDrawable(GetDrawable.getDrawable("Show/Hide Password"));
                passwordLayout.setEndIconTintList(ColorStateList.valueOf(getResources().getColor(R.color.color_white)));`

Tested on library v1.3.1, Mi a2, Android Version 10

**Comment by yogeshchoudhary-gts** [comment] 2021-06-18 11:33
👍🏼

**Comment by drchen** [comment] 2021-11-04 18:16
Is this still reproducible with the latest library version?

**Comment by drchen** [comment] 2022-01-12 20:35
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.

**Closed by drchen** 2022-01-12 20:35 UTC
Labels: bug, Need more info
