### ISSUE TITLE
[MaterialContainerTransform] Shared Element Return Transtion now just blinks to the previous fragment

### ISSUE THREAD

**Issue by VincentJoshuaET** [material-components/material-components-android#1341] opened 2020-05-29 03:45 UTC
This all started to happen after the 1.2.0 beta update. The enter transition is still working properly.

```
sharedElementEnterTransition = MaterialContainerTransform().apply {
        drawingViewId = R.id.fragment
        scrimColor = Color.TRANSPARENT
        fadeMode = MaterialContainerTransform.FADE_MODE_OUT
        interpolator = FastOutSlowInInterpolator()
        duration = 500
    }
sharedElementReturn Transition = MaterialContainerTransform().apply {
        drawingViewId = R.id.fragment
        scrimColor = Color.TRANSPARENT
        fadeMode = MaterialContainerTransform.FADE_MODE_OUT
        interpolator = FastOutSlowInInterpolator()
        duration = 500
    }
```

**Comment by VincentJoshuaET** [comment] 2020-05-29 04:23
Video: https://imgur.com/a/YFGRtmR
The one that doesn't animated properly is using the 1.2.0-beta01 library

**Comment by dsn5ft** [comment] 2020-05-29 12:26
Hi @VincentJoshuaET, thanks for the report! Can you create a GitHub repo with a minimal sample app that reproduces the issue?

**Comment by hunterstich** [comment] 2020-05-29 16:38
Possibly related to #1073

**Comment by dsn5ft** [comment] 2020-06-23 17:50
@VincentJoshuaET we're currently looking at any issues that should be fixed for the next stable release. Can you provide any more info that can help reproduce this?

**Comment by VincentJoshuaET** [comment] 2020-06-23 17:53
> @VincentJoshuaET we're currently looking at any issues that should be fixed for the next stable release. Can you provide any more info that can help reproduce this?

I created a minimal sample app but there doesn't seem to be a problem 😕. Will just close this for now, thanks

**Closed** 2020-06-23 17:53 UTC

**Comment by dsn5ft** [comment] 2020-06-23 17:55
Hmm ok. In your actual app can you try using the `com.google.android.material.transition.platform` classes in the beta release to see if the issue is still there? And try disabling the shadow support that we added as another test? (`materialContainerTransform.setElevationShadowEnabled(false)`)

**Comment by VincentJoshuaET** [comment] 2020-06-24 05:59
I have tried that first suggestion before, no changes. Will try disabling shadows.

**Comment by AxelBlaz3** [comment] 2020-07-17 13:20
@VincentJoshuaET have you found a fix for your issue? I face the same with an `ImageView` wrapped by a `MaterialContainerTransform`.

**Comment by hunterstich** [comment] 2020-07-20 11:28
@AxelBlaz3 What's your setup for MaterialContainerTransform? Are you animating between Views? Fragments? Any chance you have a small sample that reproduces the issue?

**Comment by AxelBlaz3** [comment] 2020-07-20 11:33
@hunterstich sure! I'll share a sample code soon. Your help will be much appreciated! Thanks :)

**Comment by AxelBlaz3** [comment] 2020-07-21 04:28
@hunterstich 

1. **Item 2** to **Item 15** have that blinking issue I'm facing, You can see the blinking clearly when you're using a low end device.

2. While I'm reproducing the issue, I've somehow faced another weird issue. However it happens only with **Item 1** in the `RecyclerView`. 

Here's the sample repo: https://github.com/AxelBlaz3/BlinkIssue

**Comment by hunterstich** [comment] 2020-07-21 13:29
Thanks @AxelBlaz3!

For issue 2, this has been fixed (3c9096d45128f11f3a84dca9f650373ff196cdce) in 1.2.0-rc01 and will also be included in 1.3.0-alpha02 when it is release either this week or next.

I couldn't repro the blinking issue you described in issue 1. Is there a device/emulator setup that repros this?

**Comment by AxelBlaz3** [comment] 2020-07-22 16:11
@hunterstich okay, lemme share the project that has the bug. It's a simple Phone app(Contacts, Messaging, Dialer).

You can check the issue I'm facing when we **navigate from `ContactsFragment` to `ContactDetailFragment`

**Comment by AxelBlaz3** [comment] 2020-07-22 17:02
@hunterstich here you go: https://github.com/AxelBlaz3/Hello

**Also, manually allow permissions of Call logs, Sms, Contacts from App info in Settings. Sorry for the hassle**

**Comment by AxelBlaz3** [comment] 2020-07-24 15:54
@hunterstich I've updated the code with some crash fixes and migrated to Hilt (previously Dagger 2 was used)
