### ISSUE TITLE
[Bottom App Bar] The application wont compile due to errors in top edge treatment class.

### ISSUE THREAD

**Issue by Mr-Ramzan** [material-components/material-components-android#1011] opened 2020-02-12 08:31 UTC
**Description:** After Updating Plugins and libraries version this project won't compile and says Due to the usage of the third party Libraries

> **Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry.registerPublication(Ljava/lang/String;Lorg/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublication;)V'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
**

**Android API version:** Android X (29)

**Material Library version:** 1.2.0-alpha04

**Device:** Samsun Galaxy S 7 Edge (8 Oreo)

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

**Comment by leticiarossi** [comment] 2020-02-12 20:47
Hi, this looks like a duplicate of https://github.com/material-components/material-components-android/issues/464 can you try the solution offered in there?

**Comment by ymarian** [comment] 2020-07-08 19:04
https://github.com/material-components/material-components-android/commit/cb4c1edb219d7a49f759bf4a3f99fc1e92a34b76

**Closed by ymarian** 2020-07-08 19:04 UTC
Labels: bug
