### ISSUE TITLE
[DynamicColors] applyToActivityIfAvailable results in activy restarting in a loop when used together with applyOverrideConfiguration and Androidx Per-App Language on API 31/32

### ISSUE THREAD

**Issue by mtotschnig** [material-components/material-components-android#3422] opened 2023-05-23 19:29 UTC
**Description:** Given an activity that sets per-app language via Appcompat (https://developer.android.com/guide/topics/resources/app-languages#androidx-impl), and uses applyOverrideConfiguration in order to set a custom configuration (e.g. setting fontScale). If in addition you want to set a Content-based Dynamic Color, the activity is restarted in a loop. This happens on Android 12 only, since on Android 13 the framework per-app language support is used.

**Expected behavior:** It should be possible to configure an activity with a custom fontScale, a custom language and a content-based dynamic color.

Interestingly, combining content-based dynamic color with a custom language (without using applyOverrideConfiguration) works, and combining content-based dynamic color with applyOverrideConfiguration (without setting a custom language) works.

I have created a sample app that sets a content-based color. On first launch, no language and font-scale customization happens. Both can be activated via 2 buttons. As soon as both customizations are applied, app starts to enter a continuous loop of recreations.

**Source code:** https://github.com/mtotschnig/DynamicColorsExperiment/blob/master/app/src/main/java/com/example/myapplication/MainActivity.kt

**Minimal sample app repro:** https://github.com/mtotschnig/DynamicColorsExperiment

**Android API version:** 31/32

**Material Library version:** 1.10.0-alpha03

**Comment by pekingme** [comment] 2023-05-25 20:48
Moving `super.onCreate` after `DynamicColors.applyToActivityIfAvailable` fixes the issue. Please have a try and let me know if it persists.

**Comment by mtotschnig** [comment] 2023-05-25 21:01
Moving super.onCreate after DynamicColors.applyToActivityIfAvailable does prevent the restart loop. But: The content-based dynamic color is no longer applied, if applyOverrideConfiguration is used to set the font scale.
[Screen_recording_20230525_230105.webm](https://github.com/material-components/material-components-android/assets/1485456/2a0309e2-90f6-48cc-aad7-a6b8b20b314b)

**Comment by pekingme** [comment] 2023-05-30 17:11
Overriding `applyOverrideConfiguration` like this works for me. Not sure what's the cause. Worth more investigation in DynamicColors. Closing the issue for now.

```
  override fun applyOverrideConfiguration(overrideConfiguration: Configuration?) {
    overrideConfiguration?.let {
      val fontScale = it.fontScale
      it.setTo(baseContext.resources.configuration)
      it.fontScale = fontScale
    }
    super.applyOverrideConfiguration(overrideConfiguration)
  }
```

**Comment by mtotschnig** [comment] 2023-09-14 20:44
@pekingme The code you shared does not change the fontScale.

**Comment by marcuzge** [comment] 2023-09-19 00:07
Can you try syncing to the latest material release and move `super.onCreate` after `DynamicColors.applyToActivityIfAvailable`? I have tested your app locally with 1.11.0-alpha02 and it works without an issue.

**Comment by mtotschnig** [comment] 2023-09-19 07:41
@marcuzge Did you test on an API 31/32 device? With the changes you suggest, the dynamic color (green) is no longer applied, once I hit the "Increase font scale" button.

[3422.webm](https://github.com/material-components/material-components-android/assets/1485456/c1846c72-760e-49fe-96c6-89c3ae4f5e60)

**Comment by marcuzge** [comment] 2023-09-21 22:21
I see, have you tried using the recommended implementation of setting the app locale on Android 12 and if the problem still exist?

Implement using the AndroidX support library for Android 12 (API level 32) and earlier: https://developer.android.com/guide/topics/resources/app-languages#androidx-impl
Support Android 12 and lower: https://developer.android.com/guide/topics/resources/app-languages#android12-impl

**Comment by mtotschnig** [comment] 2023-09-22 09:07
The described problem is about using AndroidX per-app language:
https://github.com/mtotschnig/DynamicColorsExperiment/blob/780f97bdedfd7197abd31180e4b59bd0c66f3bde/app/src/main/java/com/example/myapplication/MainActivity.kt#L48-L50
I'll update the title to make this clear.

**Comment by marcuzge** [comment] 2023-09-25 21:38
I would highly recommend to not use AndroidX per-app language on Android 12,  as this is a known issue for app context to not have the correct resources described in https://issuetracker.google.com/issues/243457462

On android 12, you could achieve the same by providing a context with updated configs inside `attachBaseContext` similar to the code snippets below.
On android 13 and above, you can continue to use `AppCompatDelegate.setApplicationLocales` without any issue. 

```
    override fun attachBaseContext(newBase: Context?) {
        super.attachBaseContext(newBase?.let { getContextForConfigs(newBase) })
     }


   fun getContextForConfigs(context: Context): Context {
        val languageTag = PreferenceManager.getDefaultSharedPreferences(context).getString(PREF_APP_LANGUAGE_TAG, "")
        val locale = Locale.forLanguageTag(languageTag)
        Locale.setDefault(locale)

        val resources: Resources = context.resources
        val configuration: Configuration = resources.configuration
        configuration.setLocales(LocaleList(locale))
        
        PreferenceManager.getDefaultSharedPreferences(context).getFloat(KEY_FONT_SCALE, 0F).takeIf {
            it != 0F
        }?.let {
            configuration.fontScale = it
        }

        return context.createConfigurationContext(configuration)
    }
```

**Comment by marcuzge** [comment] 2023-09-27 17:40
Thanks for your suggestion. I will make a note and suggest you reaching out to appCompat and preferences if needed to investigate further. 

I am closing this bug as alternative implementation to apply dynamic colors along with font-size and per-app language has been provided on Android 12.

**Closed by marcuzge** 2023-09-27 17:40 UTC
Labels: bug, Feature: Color
