### ISSUE TITLE
[textfield.TextInputLayout] Password toggle icon can't align it's layout

### ISSUE THREAD

**Issue by akaratakan** [material-components/material-components-android#2342] opened 2021-08-20 12:43 UTC
**Description:** When hintEnable attribute set as false. Password toggle icon can not align to center.

**Expected behavior:** 
![image](https://user-images.githubusercontent.com/48197191/130234304-6895f6f4-4e1b-4f48-a74b-9388e8b46a91.png)

**Source code:** https://gist.github.com/akaratakan/cc590e4db49f06fd31442c390a0aa99c

**Android API version:** All API versions

**Material Library version:**1.4.0

**Device:** All device

**Comment by drchen** [comment] 2022-04-19 18:51
It looks like a duplicate of #1113. Let's keep tracking the issue there. : )

**Closed by drchen** 2022-04-19 18:51 UTC
Labels: bug, Widget: TextField
