### ISSUE TITLE
App Theme does not get applied to BottomSheetDialogFragment

### ISSUE THREAD

**Issue by beatbrot** [material-components/material-components-android#99] opened 2018-05-10 17:22 UTC
### Problem
The App Theme does not get appplied when using `BottomSheetDialogFragment`.

### Reproduction steps
- Like advised, I extended `BottomSheetDialogFragment` like so:
```
class LoginSheet : BottomSheetDialogFragment() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return inflater.inflate(R.layout.login_sheet, container, false)
    }
}
```

- Also, like advised, I use this code to show the Dialog:
```
    LoginSheet().showNow(fragmentManager, "LoginDialog")
```
- The BottomSheet shows up without the desired theme.
### Version number

 - 1.0.0-alpha1

### Operating system and device
- Android 8.1 (AOSP) on OnePlus One
### Related issues

**Comment by Bloody-Badboy** [comment] 2018-05-19 05:30
Use it like this to apply the AppTheme
```kotlin
 override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup?,
    savedInstanceState: Bundle?
  ): View? {
    val contextThemeWrapper = ContextThemeWrapper(activity, R.style.AppTheme) // your app theme here
    return inflater.cloneInContext(contextThemeWrapper).inflate(R.layout.login_sheet, container, false)
  }
```

**Comment by DSteve595** [comment] 2018-11-25 21:18
This is happening because the default `bottomSheetDialogTheme` attribute points to a style that isn't a ThemeOverlay, but rather a full theme that defines the default colors and such. This should be fixed in the library IMO.

Here's a somewhat clean workaround:
```xml
<style name="Theme.YourApp" parent="Theme.MaterialComponents.*something*">
  ...
  <item name="bottomSheetDialogTheme">@style/ThemeOverlay.YourApp.BottomSheetDialog</item>
  ...
</style>

<style name="ThemeOverlay.YourApp.BottomSheetDialog" parent="ThemeOverlay.MaterialComponents.Dialog">
  <item name="android:windowBackground">@android:color/transparent</item>
  <item name="android:windowAnimationStyle">@style/Animation.MaterialComponents.BottomSheetDialog</item>
  <item name="bottomSheetStyle">@style/Widget.MaterialComponents.BottomSheet.Modal</item>
</style>
```

**Comment by gaara87** [comment] 2018-12-21 00:10
https://github.com/material-components/material-components-android/blob/831ad7dde719ff450a840857a51234483e3ba2c6/lib/java/com/google/android/material/theme/res/values/themes_base.xml#L61 I see that in 1.1.0-alpha02 version, i'm assuming that would fix it?

**Comment by gaara87** [comment] 2018-12-21 00:39
I can confirm that this fixes the theming issue. @DSteve595 would you like me to submit a pull request on your behalf?

**Comment by DSteve595** [comment] 2018-12-22 17:55
A pull request would be great, but I'm not familiar enough with the structure of the styles.xml to be confident in doing it properly.

**Comment by ymarian** [comment] 2019-01-18 19:36
Please comment on the bug with any other updates.

**Closed by ymarian** 2019-01-18 19:36 UTC

**Comment by DSteve595** [comment] 2019-01-18 20:07
@ymarian Is this fixed? Or is the tracking being moved to https://issuetracker.google.com/issues/120073616?

**Comment by ymarian** [comment] 2019-01-18 20:13
@DSteve595 just the latter but it’s one of our priorities now. Hopefully syncing a fix soon. I can comment again here when that happens

**Comment by daniel-stoneuk** [comment] 2020-06-08 13:01
Has ThemeOverlay.MaterialComponents.BottomSheetDialog been removed since this issue?

**Comment by yamin8000** [comment] 2021-07-13 14:52
> 
> 
> Use it like this to apply the AppTheme
> 
> ```kotlin
>  override fun onCreateView(
>     inflater: LayoutInflater,
>     container: ViewGroup?,
>     savedInstanceState: Bundle?
>   ): View? {
>     val contextThemeWrapper = ContextThemeWrapper(activity, R.style.AppTheme) // your app theme here
>     return inflater.cloneInContext(contextThemeWrapper).inflate(R.layout.login_sheet, container, false)
>   }
> ```

How can I use this with view binding?

**Comment by subashz** [comment] 2021-10-05 07:44
> > Use it like this to apply the AppTheme
> > ```kotlin
> >  override fun onCreateView(
> >     inflater: LayoutInflater,
> >     container: ViewGroup?,
> >     savedInstanceState: Bundle?
> >   ): View? {
> >     val contextThemeWrapper = ContextThemeWrapper(activity, R.style.AppTheme) // your app theme here
> >     return inflater.cloneInContext(contextThemeWrapper).inflate(R.layout.login_sheet, container, false)
> >   }
> > ```
> 
> How can I use this with view binding?

        val contextThemeWrapper =
            ContextThemeWrapper(activity, R.style.Theme_MeroBazar) // your app theme here
        val view = inflater.cloneInContext(contextThemeWrapper)
            .inflate(R.layout.bs_edit_product, container, false)

        _binding = EditProductBinding.bind(view)

        return binding.root

**Comment by ashwinbhaskar** [comment] 2022-02-02 04:47
> Use it like this to apply the AppTheme
> 
> ```kotlin
>  override fun onCreateView(
>     inflater: LayoutInflater,
>     container: ViewGroup?,
>     savedInstanceState: Bundle?
>   ): View? {
>     val contextThemeWrapper = ContextThemeWrapper(activity, R.style.AppTheme) // your app theme here
>     return inflater.cloneInContext(contextThemeWrapper).inflate(R.layout.login_sheet, container, false)
>   }
> ```

@subashz @Bloody-Badboy this solution does not work for me. The theme doesn't change in darkmode. My `AppTheme` extends `Theme.AppCompat.DayNight`. I am using `BottomSheetDialogFragment` from `com.google.android.material.bottomsheet.BottomSheetDialogFragment`. 

These are my dependencies for appcompat and material
```
implementation 'androidx.appcompat:appcompat:1.4.1'
implementation 'com.google.android.material:material:1.6.0-alpha02'
```

Any idea as to where I could be going wrong?
